### ISSUE TITLE
Cannot get student API key

### ISSUE THREAD

**Issue by heliosgg** [Blockchair/Blockchair.Support#1001]
Hello, I have the same problem https://github.com/Blockchair/Blockchair.Support/issues/609

**Comment by daria-blockchair** [comment]
Please contact us at info@blockchair.com

**Comment by daria-blockchair** [comment]
Hi! The issue should've been fixed. Please try again to get a key on our [site](https://blockchair.com/student-pack) and let us know if you keep receiving the same error.

**Comment by heliosgg** [comment]
It works now. Thank you so much
