### ISSUE TITLE
Returns 500 while submitting form.

### ISSUE THREAD

**Issue by jkpatel1463** [Blockchair/Blockchair.Support#1002]
Hello there

Submitting information at form which is placed at bottom of the link is not working. Link is given below. It returns 500. Please take a look at attachments for error.

URL: https://blockchair.com/partnerships?subject=awesome#hi
![Screenshot 2022-10-21 at 8 51 48 AM](https://user-images.githubusercontent.com/1279950/197104107-17dc13f1-a4a9-48c7-a213-5c1b81b87056.png)

Hope it will help you to identify issues in blockchair.

Thank you.

**Comment by daria-blockchair** [comment]
It was a temporary technical issue that has already been fixed. We are sorry for the inconvenience.
