### ISSUE TITLE
Blockchar in

### ISSUE THREAD

**Issue by Liegeetukudoh** [Blockchair/Blockchair.Support#1009]
_please help me out _

**Comment by Liegeetukudoh** [comment]
I need advice on how to get back wallet

**Comment by daria-blockchair** [comment]
Hi!
Blockchair does not provide wallet services. We only display information regarding transactions that happened in blockchains. We do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
Thank you for understanding.
