### ISSUE TITLE
API Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by dhjw** [Blockchair/Blockchair.Support#101]
I was hoping to use the API to get an address balance in a browser extension, but if I'm not currently browsing blockchair.com I get this in console:

> Failed to load https://api.blockchair.com/bitcoin-cash/dashboards/address/xxx: The 'Access-Control-Allow-Origin' header has a value 'https://blockchair.com' that is not equal to the supplied origin. Origin 'chrome-extension://dnoepokpijbdefeceopfloblpcefdokn' is therefore not allowed access.

Any chance you can set Access-Control-Allow-Origin to * ?

**Comment by Har01d** [comment]
Hello, could you please drop us a line at <info@blockchair.com> about the extension you’re working on, maybe we’ll find some workaround (for example I guess we can simply add `chrome-extension://dnoepokpijbdefeceopfloblpcefdokn` to the whitelist, although I’m not sure if that id is static)
