### ISSUE TITLE
I need advice on how to get back wallet

### ISSUE THREAD

**Issue by Liegeetukudoh** [Blockchair/Blockchair.Support#1010]
I need advice on how to get back wallet 

_Originally posted by @Liegeetukudoh in https://github.com/Blockchair/Deleted-Issues/issues/552

**Comment by Liegeetukudoh** [comment]
We will publish any updates to our Privacy Policy at this page ([https://blockchair.com/privacy](https://blockchair.com/privacy)) and in the GitHub repository at [https://github.com/Blockchair/Blockchair.Support/blob/master/PRIVACY.md](https://github.com/Blockchair/Blockchair.Support/blob/master/PRIVACY.md) plus the link to the updated version will be available at the bottom of all our site pages.

**Comment by daria-blockchair** [comment]
Hello, 

As was mentioned in https://github.com/Blockchair/Deleted-Issues/issues/552, Blockchair does not provide wallet services. Unfortunately, we cannot help you to restore your wallet. Please contact your wallet support for further assistance. 

Thank you for understanding.
