### ISSUE TITLE
I didn't send this transaction

### ISSUE THREAD

**Issue by smilepro4evr** [Blockchair/Blockchair.Support#1011]
cbf94fd092a20d9edce3316bbfb44048f2df7d595d0a62cc0f6b9f70c6b6207c.  Someone has my backup phrase

**Comment by Ashleyburgos** [comment]
Access

**Comment by Ashleyburgos** [comment]
> cbf94fd092a20d9edce3316bbfb44048f2df7d595d0a62cc0f6b9f70c6b6207c. Someone has my backup phrase

Approve

**Comment by smilepro4evr** [comment]
what should i do every time i add more then a few dollars in any crypto it
all of a sudden gets transfered by it self to an address that ive never
seen before is there any way you guys could possiblyy reverse at least that
one unauthorized transaction for me

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
