### ISSUE TITLE
Where is my Bitcoin 

### ISSUE THREAD

**Issue by JimLongWong** [Blockchair/Blockchair.Support#1012]
Where is my Bitcoin! 1Es7bD5beAyo5f8yn5NhzpmpegC87273yS wallet I sent it to.

**Comment by EwilOwl** [comment]
Доброго времени суток господа! 
будьте так любезны, проинформируйте, сколько ещё транзакция будет висеть в воздухе? 
создал перевод между своими кошельками вчера в час ночи, время до завершения показывает одно и тоже (16 минут), а по факту прошло 23 часа. 

Кошелёк с которого выполнялся перевод;
13VKN7pCSDARgWmuFPK8Nmh5j8rzU3eusr

Кошелёк на который выполнялся перевод;
3DnYpcds5DcqjQhuTwH5MCgRFmB833zQ3e

Благодарю!

**Comment by DJANARSLANOV** [comment]
Здравствуйте не приходит биткойн прошло уже 48 часов 
Кошелек на который происходил перевод  3MMSroBdFQCEc89j18b1Qj8jWQdUsUGKf3

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.
 
Thank you for understanding.
