### ISSUE TITLE
non-payment

### ISSUE THREAD

**Issue by Mardic1975** [Blockchair/Blockchair.Support#1018]
250965c96657e10f3e1afdfd7b5c29ffd3d8fe4d905b2077f94fbe0cf52c883b Transaction number and coinloot-blockchair-faucetpay chain sent amount faucetpay litecoin : MRhHVbMQEAi5oe1DBaYXZH7VWQhypMjnZH account, please inform about the subject 
e-mail : ardic75@gmail.com

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
