### ISSUE TITLE
lost my crypto

### ISSUE THREAD

**Issue by Mxtroroo** [Blockchair/Blockchair.Support#1028]
i sent crypto and i never got it what happened to it? ive been waiting forever

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information.
 
Thank you for understanding.
