### ISSUE TITLE
Lost my balance 

### ISSUE THREAD

**Issue by Krevsus** [Blockchair/Blockchair.Support#1029]
bc1q3grh2vzrrdzux8qp70827zj09j8cznhptvxu7f

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
