### ISSUE TITLE
биткоин не дошел

### ISSUE THREAD

**Issue by vorhapok** [Blockchair/Blockchair.Support#1031]
приветствую, перевод так и не дошел вот хэш
 ceef3082f0935c64df20e4ab8274171a4fa2f013c3c0eeace3f5091147d71f88
сумма сделки 0.0099616БТД
время 
9 дек 2022 г., 10:22универсальное глобальное время
помогите пожалуйста

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
