### ISSUE TITLE
bitcoins aere not in my wallet yet did i do something wrong because im still learning how to build a wallet and cash out i didnt get any yt.

### ISSUE THREAD

**Issue by dustosohappy25** [Blockchair/Blockchair.Support#1032]

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
