### ISSUE TITLE
Multiple error screens

### ISSUE THREAD

**Issue by LabbyTheTechnician** [Blockchair/Blockchair.Support#1034]
Received a “Bad Gateway” error 502 when attempting to view litecoin transaction at:
[LTC transaction](https://blockchair.com/litecoin/transaction/39983472dd5f6550004348436ef79f75f8ed65ec4d461daddfe586a9a55a948d) 

Also, received error 500 after clicking on the “settings” button at the top of the screen under the main menu when navigating from the Blockchair home page

**Comment by Monseceaser** [comment]
Talk to LTC Support on the [Litecointalk live support](https://live-litecoin.online/) so that your issue can be looked into.

**Comment by daria-blockchair** [comment]
Hi! On 18 December there was a networking issue in our data center. It's already been fixed.  
We apologize for any inconvenience caused.
