### ISSUE TITLE
Need my door back 

### ISSUE THREAD

**Issue by Andrew1212oiuq** [Blockchair/Blockchair.Support#1036]
![6FC6A601-7918-4B08-9930-AC126A4FAA4B](https://user-images.githubusercontent.com/121130267/208756189-16be530f-8cff-4165-bade-0cb1d9ee356a.png)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
