### ISSUE TITLE
Bitcoin issue 

### ISSUE THREAD

**Issue by HackergirlNV88** [Blockchair/Blockchair.Support#1037]
I have yet to receive my top up. Transaction hash 5aa14c42d2ae4a02e942868bbb166e2c0dcd5d98e9cfa4f5f60766a78b385f98. Or can I get a update on what is going on please.

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
The transaction [5aa14c42d2ae4a02e942868bbb166e2c0dcd5d98e9cfa4f5f60766a78b385f98](https://blockchair.com/bitcoin/transaction/5aa14c42d2ae4a02e942868bbb166e2c0dcd5d98e9cfa4f5f60766a78b385f98) is confirmed. Please contact your wallet or exchange for more information.

Thank you for understanding.
