### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Dstrickla8** [Blockchair/Blockchair.Support#1039]
I submitted a transaction from crypto.com to bovada for .03 bitcoin...crypto said it went thru bovada is saying they never received it...I need help to be able to find it

**Comment by soddenf** [comment]
I didn't get all the money I have a screenshot I sent 28 dollars and got 4
![btc](https://user-images.githubusercontent.com/121657834/210039624-da9a1749-ab81-4b91-be8d-62551dfa8048.png)
![BTC2](https://user-images.githubusercontent.com/121657834/210039625-7ce16d82-6b2c-4654-b6a0-284b0e014473.png)

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
