### ISSUE TITLE
Can't tell how many confirmations?

### ISSUE THREAD

**Issue by festus1973** [Blockchair/Blockchair.Support#104]
Consider the following API call:

https://api.blockchair.com/bitcoin/outputs?q=recipient(bc1q74a2fq5phr4ktfdu35gexmkjvnys5hwhfr73uk)

There doesn't appear to be a way to determine how many confirmations have occurred for this output. Most block explorer APIs provide a field that contains a confirm count. 

Right now, as a workaround, I'm parsing the 'time' field of your result and calculating the number of minutes that have passed since then. From that, I can divide by 10, since each confirmation takes around 10 minutes, and obtain an approximation of how many confirmations have occurred. But this isn't particularly accurate.

Is there some field that I'm missing?

Best,

Festus

**Comment by Har01d** [comment]
Hello,

Unfortunately, right now there’s no field for the number of confirmations, so you first need to call `https://api.blockchair.com/bitcoin/` to get the `mempool_best_height` value (shows the best block height), and then subtract the transaction’s block height.

**Comment by Har01d** [comment]
Hey,

It the new API version there’s `context.state` field which contains the current best block height. To calculate the number of confirmations you can simply subtract `context.state` from the block id and add 1 (e.g. the `state` is 520000, the block number is 520000 — so there’s 1 confirmation).

The docs are available here: https://github.com/Blockchair/Blockchair.Support/blob/master/API.md
