### ISSUE TITLE
Не поступил платёж

### ISSUE THREAD

**Issue by Kris1990g** [Blockchair/Blockchair.Support#1046]
Не поступили деньги на кошелек. 

https://tyt.cash/hst_CZFLFAn5k53aqRk91qVDxEZ1wAYLe8zFw6
Почему и что делаеть??
![Screenshot_2023-01-15-08-42-30-427_com yandex browser](https://user-images.githubusercontent.com/122707137/212524910-bc1e7866-cbe9-4d28-aaec-850cda7206d5.jpg)
 Номер кошелька: bc1qz0qj90na8gf4mtggpdf08kmk8ezmretlkhppun

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.

Thank you for understanding.
