### ISSUE TITLE
Possible integration of a webhook??

### ISSUE THREAD

**Issue by code-wolf-byte** [Blockchair/Blockchair.Support#1048]
I am trying to create a program that uses a webhook to ping me whenever I receive funds in my wallet. Is there any way to setup a webhook using the API?

**Comment by daria-blockchair** [comment]
Hi, 
Unfortunately, we don’t offer websockets at this point. 
The closest we offer to websockets is the [State-changes endpoint](https://blockchair.com/api/docs#link_507). This endpoint returns you the balance changes per address in a specific block.
