### ISSUE TITLE
money not received

### ISSUE THREAD

**Issue by Krapalik227** [Blockchair/Blockchair.Support#1049]
c8c2968d57dcd8e79bda6c40c6d176b497173c27bbb2eebfeff7137ca730c1ef.
Help, more than two days have passed

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
