### ISSUE TITLE
Different values for BCH address balance 

### ISSUE THREAD

**Issue by savardiego** [Blockchair/Blockchair.Support#105]
Hi, there's something wrong with total received for BCH address:

At this URL the "total received" amount is: 0.01110000 BCH  --- WRONG
https://blockchair.com/search?q=qz6x7qem2e8z3s0vgul7vuxl9vwvt4nt2yy44eyrzk

While at this one, for the same address, the "total received" amount is 0.00370000 BCH  --- CORRECT
https://blockchair.com/bitcoin-cash/address/qz6x7qem2e8z3s0vgul7vuxl9vwvt4nt2yy44eyrzk

**Comment by dharma7777** [comment]
Sir me plz help.
Sir me withdraw a wrong wallet address.
So me bye mistake a Bitcoin cash wallet. Sir my address change possible
Bitcoin cash to Bitcoin .
Sir my amount blockchain show but my address wrong .
Sir my private Key not found and my transaction 60 after unconfirmed.
Sir plz my help.
Me wrong Bitcoin cash wallet addres------3DUMfv2SV4sNDEduZd6Kb9y9EB4Kayq7su
My wrong wallet transactionID--781a44ad578dc2eea19f898f3813ab9c94bbd629e3eed891848ca4e17a07aa60
