### ISSUE TITLE
Bitcoin Cash exchange transfer Needed 

### ISSUE THREAD

**Issue by Mirsahibul07** [Blockchair/Blockchair.Support#1056]
Hi, kindly advise and need your kind support urgently!

**Comment by Mirsahibul07** [comment]
Please advise about my funds and reply sooner

**Comment by Mirsahibul07** [comment]
Please advise about my funds and reply sooner!

**Comment by daria-blockchair** [comment]
Hi @Mirsahibul07, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
