### ISSUE TITLE
My ltc doesnt arrive my gamdom account

### ISSUE THREAD

**Issue by guneyink** [Blockchair/Blockchair.Support#1060]
Hey my ltc doesnt arrive my gamdom account please check this
 https://blockchair.com/tr/litecoin/transaction/8b74fbf3ba07f919d81796d48562fad73248286b02e16281dec7bf750a8f9450

**Comment by guneyink** [comment]
Hey

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
The transaction [8b74fbf3ba07f919d81796d48562fad73248286b02e16281dec7bf750a8f9450](https://blockchair.com/tr/litecoin/transaction/8b74fbf3ba07f919d81796d48562fad73248286b02e16281dec7bf750a8f9450) is confirmed. Please contact your wallet or exchange for more information.

Thank you for understanding.
