### ISSUE TITLE
LTC COIN

### ISSUE THREAD

**Issue by changyong8844** [Blockchair/Blockchair.Support#1062]
LTC 0.1 sand result TXID-c06d93ae255cb75c7ef8936a9463778d1adb0e80e6d32c09961e25596f4d335c   this  not checked to web

**Comment by daria-blockchair** [comment]
Hi, 
Unfortunately, there is no LTC transaction with a hash c06d93ae255cb75c7ef8936a9463778d1adb0e80e6d32c09961e25596f4d335c. Please contact your wallet or exchange for more information.
