### ISSUE TITLE
Get black a transaction to a wrong recipient

### ISSUE THREAD

**Issue by Cocosund** [Blockchair/Blockchair.Support#1064]
Yesterday I did a transaction but the recipient was wrong. Transaction id 06553efe5286220d25cafd9c022d899eb3515cb1c1c53d293530c1382fd37d6a

Is It possible to get It back to my account?
bc1q7d0q068enymm6evudtpxf6d6swagkafrl55l5p
Thank you

**Comment by BlackHatHacker1111** [comment]
I helped a lot of with this issue to recover there’s perfectly send me a friend request on telegram let me help you with yours my telegram is BlackHatHacker111

**Comment by daria-blockchair** [comment]
Hi,

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains.

Thank you for understanding.
