### ISSUE TITLE
How possible is it to trace funds sent to a wrong address?

### ISSUE THREAD

**Issue by WONDERSPLUG** [Blockchair/Blockchair.Support#1069]

**Comment by BlackHatHacker1111** [comment]
I helped a lot of with this issue to recover there’s perfectly send me a friend request on telegram let me help you with yours my telegram is BlackHatHacker111

**Comment by Henkzonfire** [comment]
Yes very possible message Blackhathacker111 on telegram he helped me with mine

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Thank you for understanding.
