### ISSUE TITLE
Pieniadze nie dotarly

### ISSUE THREAD

**Issue by PatryQ3254** [Blockchair/Blockchair.Support#1087]
when the money reaches the address bc1q0rvjh5p6rynv78lujquxl4kxldm43t4pwd38q9 I sent it almost 2 days ago and I'm still waiting for a refund or you would send it to this address

**Comment by PatryQ3254** [comment]
when the money reaches the address bc1q0rvjh5p6rynv78lujquxl4kxldm43t4pwd38q9 I sent it almost 2 days ago and I'm still waiting for a refund or you would send it to this address

**Comment by Macolc27** [comment]
Abilita piano
