### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by PatryQ3254** [Blockchair/Blockchair.Support#1089]
give me back my 1600 PLN  transaction bc1q0rvjh5p6rynv78lujquxl4kxldm43t4pwd38q9

**Comment by Leanid66** [comment]
Помогите пожалуйста вернуть мою транзакцию.b275b787af1844ec6ff11bdfcf4c023ccdc63134680cf797a8937dbdf0fc7022

**Comment by Macolc27** [comment]
> give me back my 1600 PLN  transaction bc1q0rvjh5p6rynv78lujquxl4kxldm43t4pwd38q9

**Comment by Macolc27** [comment]
Nessuno ha preso la tua transazione

**Comment by egor091191** [comment]
Наверняка меня 17 марта обманули мошенники и подсунули другой кошелек и я точно не проверив туда перевел бит!Я проверил через блокчейн там на том кошельке деньги до сих пор лежат!как мне их вернуть?

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. 

Thank you for understanding.
