### ISSUE TITLE
duda

### ISSUE THREAD

**Issue by didier1390** [Blockchair/Blockchair.Support#109]
no he podido entender como mis fondos de CEX.io vinieron a parar a *Blockchair*, si yo seguí los pasos indicados para que ellos llegaran a https://ito.kalatoken.io.

Explicaré desde el principio: yo ingrese a https://ito.kalatoken.io. para comprar bitcoin cash en https://cex.io y  luego retire los fondos y coloque la direccion de mi billetera (3NCgP2q8cTyNAfW67t8a4aTUqmpX9tZrqK ) pero llega el mensaje que la transacción fue recibida pero esta en estado pendiente y tienen un enlace que me direcciona hacia  https://live.blockcypher.com, y me dice que  "No se encontró ninguna transacción con el hash 6bc67634fb84d1b2ba70b72c8f5dc7f20201d7ae29fc80714ba4192ca06052af
(https://live.blockcypher.com/ltc/tx/6bc67634fb84d1b2ba70b72c8f5dc7f20201d7ae29fc80714ba4192ca06052af) para la primera compra  y  para la segundad me aparece el mismo mensaje  "No se encontró ninguna transacción con el hash aa132fae320cf649fca401ab736131028f7d1f9bb9f307535e5e049f2d9c9116".
( https://live.blockcypher.com/ltc/tx/aa132fae320cf649fca401ab736131028f7d1f9bb9f307535e5e049f2d9c9116)

Pero si consulto en la pagina de  https://cex.io/finance/transactions, aparece que la transacción fue exitosa y aparece un enlace que me direcciona hacia ustedes
1. https://blockchair.com/bitcoin-cash/transaction/aa132fae320cf649fca401ab736131028f7d1f9bb9f307535e5e049f2d9c9116
 
2. https://blockchair.com/bitcoin-cash/transaction/6bc67634fb84d1b2ba70b72c8f5dc7f20201d7ae29fc80714ba4192ca06052af
que corresponden a las  dos compras.

necesito que me expliquen que ocurrió y que puedo hacer

[Marco Alvarez.pdf](https://github.com/Blockchair/Blockchair.Support/files/1822306/Marco.Alvarez.pdf)

mis datos 
MARCO DIDIER ALVAREZ PATIÑO
CEDULA 15531390
EMAIL: didier1390@gmail.com 
celular 3113093000

**Comment by Har01d** [comment]
Hello, we provide support in English and Russian only. Please refer to our FAQ first: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
