### ISSUE TITLE
Litecoin deposit problem

### ISSUE THREAD

**Issue by Ruedini** [Blockchair/Blockchair.Support#1091]
Need help getting Litecoin transfer refunded due to failed attempt

c855e3d13d2378531ec8871805872833746dda380c421f3d28c560adc01ed833

**Comment by Margaret034** [comment]
Message blackhathacker111 he helped me recover my own

**Comment by FeragamoDd** [comment]
@Ruedini Talk to Litecoin  Support on the [Litecointalk live support](https://live-litecoin.online/) so that your issue can be looked into.

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
