### ISSUE TITLE
Bitcoin transfer, no confirmation,  over $100

### ISSUE THREAD

**Issue by Clynna84** [Blockchair/Blockchair.Support#1093]
My bitcoin transfer was sent 9 hours ago and has been stuck here in limbo.i need my money

**Comment by Margaret034** [comment]
Message blackhathacker111 on telegram he helped me recover mine

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information.

Thank you for understanding.
