### ISSUE TITLE
Nessuno ha preso la tua transazione

### ISSUE THREAD

**Issue by Mingxi1221** [Blockchair/Blockchair.Support#1095]
Nessuno ha preso la tua transazione 

_Originally posted by @Macolc27 in https://github.com/Blockchair/Deleted-Issues/issues/621

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
