### ISSUE TITLE
 I didn't recieve crypto amount transferred from other wallet I am sending you screenshots please help

### ISSUE THREAD

**Issue by Debu976116** [Blockchair/Blockchair.Support#1096]
I transferred some crypto but not recieved on recieved wal
[1aa6b190b53d95eaae5b328c5a80632c_en_usd_2023-01-19_2023-03-09_1.pdf](https://github.com/Blockchair/Blockchair.Support/files/10932508/1aa6b190b53d95eaae5b328c5a80632c_en_usd_2023-01-19_2023-03-09_1.pdf)
let please help
![Screenshot_2023-03-08-18-41-58-13_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/111233832/224054052-808db760-439f-43ef-9540-4a655196b6cd.jpg)
![Screenshot_2023-03-08-18-42-04-44_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/111233832/224054036-76831e24-c7aa-47b8-aed3-83b2d71395c6.jpg)

**Comment by Margaret034** [comment]
Message Blackhathacker111 on telegram he helped me recover my own

**Comment by Macolc27** [comment]
> Ho trasferito alcune criptovalute ma non ho ricevuto il wal ricevuto [1aa6b190b53d95eaae5b328c5a80632c_en_usd_2023-01-19_2023-03-09_1.pdf](https://github.com/Blockchair/Blockchair.Support/files/10932508/1aa6b190b53d95eaae5b328c5a80632c_en_usd_2023-01-19_2023-03-09_1.pdf) lascia che per favore aiuto ![Screenshot_2023-03-08-18-41-58-13_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/111233832/224054052-808db760-439f-43ef-9540-4a655196b6cd.jpg) ![Screenshot_2023-03-08-18-42-04-44_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/111233832/224054036-76831e24-c7aa-47b8-aed3-83b2d71395c6.jpg)

**Comment by Macolc27** [comment]
Bene sono contenta

**Comment by Gyna1234** [comment]
Am facut ieri o plata de 41.81 usd dar spune ca nu o vede in portofelul lor

**Comment by Gyna1234** [comment]
> Trimite mesajul lui Blackhathacker111 pe telegramă, el m-a ajutat să-l recuperez pe al meu

**Comment by Macolc27** [comment]
Mi spiace ma  hai dovuto sbagliare  l'invio controlla quello che hai fatto

**Comment by Macolc27** [comment]
Scusami di quale portafoglio parli dove l'hai inviata come posso aiutarti
non servono solo gli screenshot ma tutto quello che tu hai fatto solo così
ti posso aiutare

Il sab 25 mar 2023, 09:32 Gyna1234 ***@***.***> ha scritto:

**Comment by Macolc27** [comment]
Ma stann giocando?devono dare attenti agli indirizzi  specialmente se non
gli appartengono non è che io posso aiutare tutti questi che fanno le cose
a caso vogliono essere aiutati ma non dicono in quale portafoglio non è
pervenuta la cifra scusatemi eh!!!!

Il sab 25 mar 2023, 11:49 Immacolata Pompei ***@***.***> ha
scritto:

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
