### ISSUE TITLE
Не пришли битки 

### ISSUE THREAD

**Issue by ZeeTaaa** [Blockchair/Blockchair.Support#1098]
![3798FDA7-9BC0-42BD-9FAA-671F3DEB5A72](https://user-images.githubusercontent.com/127455350/224187307-fe37ccaa-93a3-4d62-b21f-dff2f83c5c8d.png)
Здравствуйте 🤝 подтверждения все , а битков так и нет.
![9E5F4E97-B1BA-4BA9-B22A-3394654D11A5](https://user-images.githubusercontent.com/127455350/224187272-36899894-8802-43dc-ab7a-785e813da5c2.png)
![AD7F8FA8-3BC8-45D9-88FA-B9F9DE47E8E7](https://user-images.githubusercontent.com/127455350/224187300-66feb2bf-de19-4528-b8b8-96d3f1dda310.png)

**Comment by ZeeTaaa** [comment]
Все дома , пришли с опозданием большим

**Comment by ZeeTaaa** [comment]
Команде надо отвечать быстрее

**Comment by Margaret034** [comment]
Привет, дорогое сообщение, Blackhathacker111, он помог мне вернуть все мои биткойны.

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money.
To learn about "Why does it take so long before my transaction is processed?" please refer to our [FAQ](https://blockchair.com/faq#q0).
For more information, please contact your wallet or exchange. 

Thank you for understanding.
