### ISSUE TITLE
Wrong address withdraw

### ISSUE THREAD

**Issue by dharma7777** [Blockchair/Blockchair.Support#110]
Sir me plz help.
Sir me withdraw a wrong wallet address.
So me bye mistake a Bitcoin cash wallet. Sir my address change possible
Bitcoin cash to Bitcoin .
Sir my amount blockchain show but my address wrong .
Sir my private Key not found and my transaction 60 after unconfirmed.
Sir plz my help.
Me wrong Bitcoin cash wallet addres------3DUMfv2SV4sNDEduZd6Kb9y9EB4Kayq7su
My wrong wallet transactionID--781a44ad578dc2eea19f898f3813ab9c94bbd629e3eed891848ca4e17a07aa60

**Comment by sergej200** [comment]
На ваше ресурсе есть blockchair.com куда почему то выводится криптовалюта админы молчам...подозрение в мошеничестве имеет место обратите внимание.....

**Comment by Har01d** [comment]
@dharma7777, please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md We can’t rollback transations.

**Comment by Har01d** [comment]
@sergej200, на Blockchair нельзя “вывести криптовалюту”, мы только показываем данные открытых блокчейнов Bitcoin и Bitcoin Cash. Прежде чем обвинять кого-то в мошенничестве, разберитесь как работают криптовалюты.

**Comment by sergej200** [comment]
Значит снимите с себя обвинения....я не против...вот смоьтрим сюда.******https://blockchair.com/bitcoin-cash/address/qrsmfanhjxnvan2tmw8rlc6z3zhu55vdsgj7eu7cw2****это криптовалюта с coinpot давайте поставим в этом деле точку я готов извенится перед вами....но криптовалюта моя чесно заработаная не выведена на кошелёк. а у вас она отображается....ищем виноватого...

**Comment by sergej200** [comment]
Так трансакции и небыло...почему у вас она отобраэается.....вот в чём проблема вы разберитесь как это произошло....криптовалюта на кошелёк не отправлена....но кудато пропала....но у вас она отображается....где же она ?   вот интересно....

**Comment by Har01d** [comment]
@sergej200, ещё раз — мы — блокчейн-обозреватель. Ваша “криптовалюта” ровно так же отображается на любом другом эксплорере: https://bch-insight.bitpay.com/address/qrsmfanhjxnvan2tmw8rlc6z3zhu55vdsgj7eu7cw2

**Comment by sergej200** [comment]
Тоже ещё раз.....ТРАНСАКЦИИ небыло....спросите у coinpot куда они перевели криптовалюту. И отображайте реальные трансакции. Могу скинуть скриншот EOBOT ничего не приходило. Мой кошелёк eobot.



30 марта 2018, 1:28:20, от "Nikita Zhavoronkov" < notifications@github.com >:


@sergej200, ещё раз — мы — блокчейн-обозреватель. Ваша “криптовалюта” ровно так же отображается на любом другом эксплорере: https://bch-insight.bitpay.com/address/qrsmfanhjxnvan2tmw8rlc6z3zhu55vdsgj7eu7cw2
- 
Вы получаете это, потому что вы были упомянуты. 
Ответьте на это письмо прямо, посмотрите на GitHub или отключите тему .

**Comment by sergej200** [comment]
Я на COINPOT нажимаю на вот это я отметил и попадаю к вам. Я о вас вообще не знал и ещё бы сто лет не знал. Но раз вы утверждаете, да ещё и перехожу к вам  с COINPOTA будьте добры....не пишите о трансакции или отвечайте за себя...стрелки не переводите на другие обозреватели. Coinpot делает переадресацию вот сюда (https://blockchair.com/bitcoin-cash/address/qrsmfanhjxnvan2tmw8rlc6z3zhu55vdsgj7eu7cw2) Что то тут не так... Coinpot отправляет к вам...а трансакции то небыло...



30 марта 2018, 1:28:20, от "Nikita Zhavoronkov" < notifications@github.com >:


@sergej200, ещё раз — мы — блокчейн-обозреватель. Ваша “криптовалюта” ровно так же отображается на любом другом эксплорере: https://bch-insight.bitpay.com/address/qrsmfanhjxnvan2tmw8rlc6z3zhu55vdsgj7eu7cw2
- 
Вы получаете это, потому что вы были упомянуты. 
Ответьте на это письмо прямо, посмотрите на GitHub или отключите тему .

**Comment by Har01d** [comment]
@sergej200, обратитесь в поддержку Coinpot.

**Comment by sergej200** [comment]
Обращался...пришла та ссылка на которую идёт переадресация с coinpot это ваш сайт. Они отмазались сказали что трансакция прошла....подтверждение тому опять же ваш сайт скриншоты я вам скидывал по моему что на кошелёк ничего не пришло. Вас подставляют.



30 марта 2018, 23:31:16, от "Nikita Zhavoronkov" < notifications@github.com >:


@sergej200, обратитесь в поддержку Coinpot.
- 
Вы получаете это, потому что вы были упомянуты. 
Ответьте на это письмо прямо, посмотрите на GitHub или отключите тему .
