### ISSUE TITLE
invito a ritirare da blochchain.com

### ISSUE THREAD

**Issue by lucpes65** [Blockchair/Blockchair.Support#1101]
Salve il 01/03/20223 mi arriva un invito a ritirare somme da questo indirizzo 17ktqv8zBURJC5MPfD6TkaXzxMZHoFPLtQ e mi dicono che non posso ricevere i soldi nel mio wallet binance perchè c'è un limite per ricevereli e dovrei versare dal 6 al 10 % del capitale che mi spetta che è indicativamente sui 18.000 euro circa. Vorrei sapere se  questo indirizzo wallet risulta a mio nome e se è una truffa? Mi date cortesemente una risposta precisa. Grazie.

**Comment by Macolc27** [comment]
Se hai il barcode , la chiave privata, e la frase passphrase, e roba tua non puoi sbagliare

**Comment by daria-blockchair** [comment]
Hi @lucpes65,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Generally, when somebody asks to send money to reveal a bigger amount is a scam. Please be aware, don't tell anyone your private key or seed phrase. For more information, please contact your wallet or exchange.

Thank you for understanding.
