### ISSUE TITLE
Scam 

### ISSUE THREAD

**Issue by annymo45** [Blockchair/Blockchair.Support#1103]
When blockchair had approved my money, it did not get to the right wallet. It said "sent", BUT nearly two days later I still haven't got anything. Please help me.

**Comment by Margaret034** [comment]
Message Blackhathacker111 on telegram he's the best and helped me got mine back

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
