### ISSUE TITLE
different kind of bitcoin wallet

### ISSUE THREAD

**Issue by barrosdangelis** [Blockchair/Blockchair.Support#111]
I´m facing a problem with a withdrawal, I set a different kind of bitcoin wallet, How can I fix it?

I used a wallet 1HisT1XSHqg98mrDa5TqSqiD1NvYysYsbw (btc) instead of a wallet (bch) to withdrawal

I appreciate your help

Leandro D'Angelis.'.

**Comment by AivaM** [comment]
Hello,
Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
