### ISSUE TITLE
deposit

### ISSUE THREAD

**Issue by jonlua01** [Blockchair/Blockchair.Support#1118]
hey i accidentally deposited money onto here and i cant seem to find it anywere i created annaccount but yet it doesnt seem ti show up

**Comment by Henkzonfire** [comment]
Same thing happened to me but thanks to blockchair support who helped me on telegram message them on telegram this their link https://t.me/blockchairsupport

**Comment by daria-blockchair** [comment]
Hi @jonlua01,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
