### ISSUE TITLE
Access to my bitcoin wallet

### ISSUE THREAD

**Issue by kassie2023** [Blockchair/Blockchair.Support#1119]
So I won in a casino and there was an option of form of payment one was bitcoin so they payed me but I can't access my wallet my phone got reset so now I have no access to my wallet I have the transaction ID and bitcoin address. But I don't have access to my bitcoin. Can someone please help me figure this out please I'm stuck

**Comment by 1384963** [comment]
> So I won in a casino and there was an option of form of payment one was bitcoin so they payed me but I can't access my wallet my phone got reset so now I have no access to my wallet I have the transaction ID and bitcoin address. But I don't have access to my bitcoin. Can someone please help me figure this out please I'm stuck

**Comment by daria-blockchair** [comment]
Hi @1384963,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
