### ISSUE TITLE
Urgent 

### ISSUE THREAD

**Issue by Brittany0519102** [Blockchair/Blockchair.Support#112]
Hello, 
          I need help, I accidentally sent BTC TO A BCH ADDRESS & now I see it at block chair

**Comment by Brittany0519102** [comment]
Thanks to anyone with any helpful feedback, I really appreciate it.

**Comment by AivaM** [comment]
Hello,
Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
