### ISSUE TITLE
Куда списали мои биткоины

### ISSUE THREAD

**Issue by ezamov1103** [Blockchair/Blockchair.Support#1121]
Куда ушли мои битки? Я никому не отправлял и мне они не приходили чё за х тут твориться

**Comment by daria-blockchair** [comment]
Hi @ezamov1103,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
