### ISSUE TITLE
Blockchair API using

### ISSUE THREAD

**Issue by AndranikHambartsumyan** [Blockchair/Blockchair.Support#1124]
How can i use Blockchair API for autamatic Dash transfers

**Comment by Henkzonfire** [comment]
Same thing happened to me but thanks to blockchair support who helped me on telegram message them on telegram this their link https://t.me/blockchairsupport

**Comment by daria-blockchair** [comment]
Hi @Taskkkiller, 
To learn more about the capabilities of our API, please refer to the [documentation](https://blockchair.com/api/docs).
