### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by Satoshingmx** [Blockchair/Blockchair.Support#1127]
As the creator  I am removing blockchair and reinstalling Blockchain private window open public source

**Comment by Ush121** [comment]
Have a transaction that I got scammed on can anyone help

**Comment by Ush121** [comment]
3KLQrQRBuK8jXzgDyj3yKG6T8GLZKCJdpk
Is the address that I sent the payment to but never delivered for fee paid to him for bitcoin. Was on February 4 at 7:28 am

**Comment by Jahzkanga** [comment]
> 3KLQrQRBuK8jXzgDyj3yKG6T8GLZKCJdpk Is the address that I sent the payment to but never delivered for fee paid to him for bitcoin. Was on February 4 at 7:28 am

Good day I got scammed too while trying to trade with this investor thanks to blackhathacker111 on telegram he helped me recover all my money

**Comment by daria-blockchair** [comment]
Hi @Ush121, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
