### ISSUE TITLE
ogbuikepromise111@gmail.com

### ISSUE THREAD

**Issue by king11111-O** [Blockchair/Blockchair.Support#1129]
I want my 0.01819773 Bitcoin back , I transfer from my Edge Wallet to my paxful wallet and I haven’t gotten the coin back for hours now.

**Comment by king11111-O** [comment]
How can I get my coin back in blockchair explorer

**Comment by king11111-O** [comment]
> I want my 0.01819773 Bitcoin back , I transfer from my Edge Wallet to my paxful wallet and I haven’t gotten the coin back for hours now.



> How can I get my coin back in blockchair explorer

**Comment by Henkzonfire** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi @king11111-O,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information.

Thank you for understanding.
