### ISSUE TITLE
Database dumps for Ethereum have stopped updating

### ISSUE THREAD

**Issue by syang-ng** [Blockchair/Blockchair.Support#1133]
It's possible that there could be a technical issue with the process of updating the database dumps for Ethereum.  We cannot find any new dumps after March 28th, 2023.

**Comment by daria-blockchair** [comment]
Hi @syang-ng, 
Thank you for pointing this out. 
We are aware of the issue and are already in the process of fixing it. Apologies for the inconvenience.
