### ISSUE TITLE
How to withdraw Bitcoins in my wallet account 

### ISSUE THREAD

**Issue by Alijaa700** [Blockchair/Blockchair.Support#1138]
Find the attached link: https://blockchair.com/bitcoin/address/bc1qmh576m4ldvk935p99yn068v56yp7xreqccse35?from=moonpay
When you press it, it shows you my wallet and BTC I hold in my wallet account. So how to withdraw those Bitcoins?
Thank you for responding to me.
Warm Regards,
Fernand

**Comment by daria-blockchair** [comment]
Hi @Alijaa700,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. 

Blockchain is a public distributed database of which anyone can make a copy. Your cryptocurrency transactions and address balance are also stored in such a database. However, your money and assets are not stored on Blockchair. Please contact your wallet or exchange for more information regarding your funds.

Thank you for understanding.
