### ISSUE TITLE
Why my account was suspended 

### ISSUE THREAD

**Issue by Chieflams90** [Blockchair/Blockchair.Support#1139]
Good day anyone 
Please I want to know the reason why my account got suspended because I still have a lot of coin inside and I can’t withdraw it out……… Have been having issues for the past 2 years now

**Comment by daria-blockchair** [comment]
Hi @Chieflams90,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
Thank you for understanding.
