### ISSUE TITLE
endereço biticoins cash

### ISSUE THREAD

**Issue by admir33** [Blockchair/Blockchair.Support#114]
Ola Boa Tarde , Mim Chamo Admir ... eu fiz uma transferencia da coinPot  para um Indereço de carteira.3NR6o1FYssTvrqCWsD6j9GbunRXunwp834 , ela foi dereçonada para https://blockchair.com/bitcoin-cash/address/pr34srfxp6g9llgljvntuwcjkwjy9qw9zvmnrkjfz3

Gostaria por Jentileza de uma orientação ...

**Comment by AivaM** [comment]
Hello,
Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
