### ISSUE TITLE
I am first time user and my ip address gets blocked for the first call

### ISSUE THREAD

**Issue by PeterCui1991** [Blockchair/Blockchair.Support#1147]
{
    "data": null,
    "context": {
        "code": 430,
        "error": "Your IP address is temporary blacklisted due to exceeding usage of API resources. Please apply for an API key by contacting us at info@blockchair.com",
        "market_price_usd": 28344,
        "cache": {
            "live": true,
            "duration": 60,
            "since": "2023-04-20 19:08:16",
            "until": "2023-04-20 19:09:16",
            "time": null
        },
        "api": {
            "version": "2.0.95-ie",
            "last_major_update": "2022-11-07 02:00:00",
            "next_major_update": null,
            "documentation": "https://blockchair.com/api/docs",
            "notice": "Please note that on November 7th, 2022 public support for the following blockchains was dropped: EOS, Bitcoin SV"
        },
        "servers": "API4",
        "time": null,
        "render_time": 0.0014319419860839844,
        "full_time": 0.0014319419860839844,
        "request_cost": 1
    }
}

**Comment by daria-blockchair** [comment]
Hi @PeterCui1991! 

We offer free access to our API for several days with a limit of 1,000 calls/day. After a trial period, we recommend applying an API key. Also, our Dashboard endpoints are not available without the key. 
You are welcome to purchase an API key on [this page](https://blockchair.com/api/plans): blockchair.com/api/plans
If you require further assistance, please contact us at info@blockchair.com

**Comment by mhm1likae** [comment]
Hi
