### ISSUE TITLE
Where can I see Mempool size?

### ISSUE THREAD

**Issue by buyx** [Blockchair/Blockchair.Support#115]
Mempool is heating up on BTC, but couldn's see info about Mempool size. Please direct me to that info!

**Comment by Har01d** [comment]
Hello,

You can find it on the front page: https://blockchair.com

**Comment by buyx** [comment]
Ok, Thank you.

Request: Could you provide size of Mempool in Mbytes. That is more comparable to what blockchain.info has for BTC.
Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Har01d** [comment]
Now you can see the mempool size on coin homepages:

https://blockchair.com/bitcoin
https://blockchair.com/bitcoin-cash
https://blockchair.com/ethereum
https://blockchair.com/litecoin

Thanks for the request!

**Comment by buyx** [comment]
Great, thanks!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
