### ISSUE TITLE
Куда делись деньги?

### ISSUE THREAD

**Issue by Sergey19812006** [Blockchair/Blockchair.Support#1151]
Здрасте на сумму 4201рубль сделал обмен на биткоины уже три дня назад куда и почемунепришли  или куда делись

**Comment by GarettBill** [comment]
То же самое случилось со мной, но благодаря Blackhathacker111, который помог мне отправить ему сообщение в телеграмме, его имя пользователя в телеграмме https://t.me/Blackhathacker111.

**Comment by daria-blockchair** [comment]
Hi @Sergey19812006, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.

Thank you for understanding.
