### ISSUE TITLE
Token values & retrieval help 

### ISSUE THREAD

**Issue by tiffanyhowser** [Blockchair/Blockchair.Support#1154]
https://github.com/orgs/community/discussions/52872

**Comment by Deadliestrope** [comment]
I belive i was scamad I have screen shots of my issues

**Comment by Deadliestrope** [comment]
Is there any way to retrieve my funds

**Comment by daria-blockchair** [comment]
Hi @Deadliestrope, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
