### ISSUE TITLE
Balance is lower than amount transferred in

### ISSUE THREAD

**Issue by 0x2f1f95edd** [Blockchair/Blockchair.Support#1156]
![IMG_0035](https://user-images.githubusercontent.com/131832799/234441008-05f56c23-0384-422e-b1be-5ef55761b54c.png)

My why 21.00 balance, yet 21.04 txin. Why my ₿ do such?

causing unknown, cashinapp is being the sent of txo.

**Comment by George43566** [comment]
I can help you rectify it . But you have to deposit 50 to fixed it

**Comment by GarettBill** [comment]
> ![IMG_0035](https://user-images.githubusercontent.com/131832799/234441008-05f56c23-0384-422e-b1be-5ef55761b54c.png)
> 
> My why 21.00 balance, yet 21.04 txin. Why my ₿ do such?
> 
> causing unknown, cashinapp is being the sent of txo.

Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by George43566** [comment]
I can help you solved this.  Deposit first so I can handle it before you
send your address ID

**Comment by George43566** [comment]
This is the address.  Deposit here so I fixed it .

bc1q4s7x87r7ewr6p2rqnaezynyfkhf5t5c83qy5pl

**Comment by George43566** [comment]
The 50 is not complete.  Make it complete so I can handle it . What I  saw
was 43 . Please complete it so I can fixed your account

**Comment by daria-blockchair** [comment]
Hi @0x2f1f95edd,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
