### ISSUE TITLE
Avalanche Transaction Hash (Txhash) Details | SnowTrace
Owner:chais fitzwater=
chaisfitzwater@gmail.com

### ISSUE THREAD

**Issue by ETCorps** [Blockchair/Blockchair.Support#1158]
"0x9fbf10fc0000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000002b322653ae998d01fc721cbc2371204f3d77c2da0000000000000000000000000000000000000000000000000000000011d51af50000000000000000000000000000000000000000000000000000000011be479f000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000142b322653ae998d01fc721cbc2371204f3d77c2da0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
 https://snowtrace.io/tx/0xb716f3a9c6aadcd174ffa1175e2d5a5254c4c9ec2bc2bb3da2dc5be26a40a6ee#:~:text=0x9fbf10fc0000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000002b322653ae998d01fc721cbc2371204f3d77c2da0000000000000000000000000000000000000000000000000000000011d51af50000000000000000000000000000000000000000000000000000000011be479f000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000142b322653ae998d01fc721cbc2371204f3d77c2da0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by mhm1likae** [comment]
Hi what mean this
