### ISSUE TITLE
transaferencia

### ISSUE THREAD

**Issue by danielitalo** [Blockchair/Blockchair.Support#116]
boa noite 
gostaria de saber com quantos dias e devolvido um valor vindo direto da blockchair?
e gostaria de saber porque a transferência do pedido: não chegou em minha carteira de devolução. 
serei grato por vossa atenção.

Informações gerais
--
Tipo de endereço | pubkeyhash
Formato de endereço legado | 1AQJQESjBiYVqpP55h9f1SRMAkTjkubKxh
Formato de endereço de caixa | qpnjzwtn4fxgk04tm9ptxe4e3t5cdczza5yg9tfxxn
Formato de endereço monetário com prefixo | bitcoincash: qpnjzwtn4fxgk04tm9ptxe4e3t5cdczza5yg9tfxxn
Roteiro | ?
Script [bin] | v�g!9s�L�>�B�f�B투
Primeiro visto recebendo  gastar | 2018-04-18 10:59 |  
Visto pela última vez recebendo  gastar | 2018-04-18 10:59 |  
Total recebido | 0. 00031184 BCH* | 0. 24 USD t
Total gasto | 0. 00000000 BCH* | 0. 00 USD t
Total não gasto (saldo) | 0. 00031184 BCH* | 0. 35 USD hoje

**Comment by AivaM** [comment]
Hello,
 
Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master…
 
—
 
Blockchair Support
