### ISSUE TITLE
Transaction wallet not in use anymore

### ISSUE THREAD

**Issue by Live-Long34** [Blockchair/Blockchair.Support#1160]
I have deposited money towards an wallet which is not anymore used. Although I notice that the network shows that the money has been accepted, I am not sure whether it would be sent back after 30 days as it is not anymore in use? Would it be possible to request that the money is sent back towards me? Not sure whether it would be a good idea to share the wallet here but if asked for I will.

**Comment by George43566** [comment]
Okay.  Send on this wallet address so I help you out .
bc1qgtwp38q5zhdlmf022my52rla8zzuqgjfc4t6zn

**Comment by Live-Long34** [comment]
Would it be alright if I just sent the wallet adress here?

**Comment by George43566** [comment]
Yes it will be alright.  Use the address and let me know so I can start the
process

**Comment by Live-Long34** [comment]
This is the adress that I have sent it to: bc1qdcps8ts9k5m47jsfzcvr3jv6tlfhnsxac6njrq

And this is my adress:
bc1qngx29p472mkpka655j4hpd0cfr8rgtk9u9rjl3

**Comment by GarettBill** [comment]
> I have deposited money towards an wallet which is not anymore used. Although I notice that the network shows that the money has been accepted, I am not sure whether it would be sent back after 30 days as it is not anymore in use? Would it be possible to request that the money is sent back towards me? Not sure whether it would be a good idea to share the wallet here but if asked for I will.

Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by George43566** [comment]
It will be possible because I will help you out . But you have to deposit
first then send your address ID

**Comment by daria-blockchair** [comment]
Hi @Live-Long34!

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.

**Comment by Live-Long34** [comment]
First of all, @George43566 @GarettBill thank you very mucho for offering me help ❤️. I am first going to try through the methods that are being suggested by blockchair and contact the support of my wallet (while probably knowing the outcome 😉😮‍💨). I might hopefully get my money back after 30 days, cause after contracting the previous owners, they mentioned thst it is not in use anymore. If not I hope to take you upon the offer given after that probably, if you are still open for that ofcourse. My reasons for not upholding and respecting these boundaries created for us is that 1) having the money in a wallet not anymore used doesn't really benefits us at all, 2) it is probably more unsustainable regarding energy use and 3) keeps the btc price unnecessarily higher while taking away potential buyers from obtaining BTC as there is a maximum amount of BTC that can be obtained.

I do want to thank and appreciate that blockchair doesn't sensor comments given previously but does flag them. This is something more platforms really should use more often. Being censored or not seeing censored information can have negative impact when abused by authorities and by flaging and not censoring people still are able to make their choices and see things more as they are. Thank you very much for upholding these boundaries in a very beautiful and righteous way. 

PS: Before I forget @George43566 @GarettBill if hacking is something fun you like to do and want to take this as a carrier path, there is something called ethical hackers even when dealing with wallets. I know for sure if you google around you probably find some amazing offers. They can deal with different kinds of criminals or search for different holes in different organizations programs etc... Maybe something to think about if you want to go more legal😅
