### ISSUE TITLE
Обмен 

### ISSUE THREAD

**Issue by Shoma77** [Blockchair/Blockchair.Support#1161]
Прошло больше 48 часов я не получил средства что делать?

**Comment by George43566** [comment]
Send 200 in this wallet so I rectify it for you .
Отправьте 200 в этот кошелек, чтобы я исправил это для вас.
Address  bc1qgtwp38q5zhdlmf022my52rla8zzuqgjfc4t6zn

**Comment by GarettBill** [comment]
То же самое случилось со мной, но благодаря Blackhathacker111, который помог мне отправить ему сообщение в телеграмме, его имя пользователя в телеграмме https://t.me/Blackhathacker111

**Comment by George43566** [comment]
Я решу это, все, что вам нужно сделать, это сначала внести 200, чтобы я мог
это исправить. затем вы присылаете мне свой идентификатор адреса. Спасибо

это адрес, по которому вы будете вносить

bc1q4s7x87r7ewr6p2rqnaezynyfkhf5t5c83qy5pl

**Comment by George43566** [comment]
I have checked it out , deposit now so I can solve it . Am here to support
you . Thank you

**Comment by George43566** [comment]
Я проверил это, внесите депозит сейчас, чтобы я мог решить эту проблему. Я
здесь, чтобы поддержать вас. Спасибо

**Comment by daria-blockchair** [comment]
Hi @Shoma77! Please be aware of scammers.

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions. Unfortunately, we can not speed up the transaction confirmation.

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee. If your transaction fee is low, it might take some time before the transaction is included in a block.
Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
