### ISSUE TITLE
My Ltc was spent?

### ISSUE THREAD

**Issue by 369Cfi369** [Blockchair/Blockchair.Support#1163]
Hi im not sure what happend but it seems   like someone has used my ltc. Just cant find it. Your blockchair app says it was spent but it was not me. Can someone please help me to see what happened. Thank you

**Comment by George43566** [comment]
Am here to help you.  All you need to do is to deposit 150 so I can fixed
it for you.  You have some errors on it so it can't work . Deposit it to
this address so I help you out .

bc1q4s7x87r7ewr6p2rqnaezynyfkhf5t5c83qy5pl

**Comment by GarettBill** [comment]
> Hi im not sure what happend but it seems like someone has used my ltc. Just cant find it. Your blockchair app says it was spent but it was not me. Can someone please help me to see what happened. Thank you

Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi @George43566 and @369Cfi369! Please be aware of scammers. 
Once a transaction is included in a block, it is not possible to reverse the transaction.
Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains. No one can.
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

**Comment by George43566** [comment]
Am here to solve it. All you need to do is to deposit 100 so I can fixed it
and secure it  . I need your ID address  to fixed it once you deposit
Here is the address

bc1q4s7x87r7ewr6p2rqnaezynyfkhf5t5c83qy5pl
