### ISSUE TITLE
Etcbi.inc/dhacm

### ISSUE THREAD

**Issue by ETCorps** [Blockchair/Blockchair.Support#1164]
Not possible to read any address balance
Always showing Errors1.

Error Details
{
"error": null,
"response": {
"statusCode": 430,
"body": "{"data":null,"context":{"code":430,"error":"Your IP address is temporary blacklisted due to exceeding usage of API resources. Please apply for an API key by contacting us at info@blockchair.com","cache":{"live":true,"duration":30,"since":"2019-11-02 11:06:52","until":"2019-11-02 11:07:22","time":null},"api":{"version":"2.0.39","last_major_update":"2019-07-19 18:07:19","next_major_update":null,"tested_features":"omni-v.a1,whc-v.a1,aggregate-v.b5,xpub-v.b5,ripple-v.a1,ethgraph-v.a1,erc_20-v.a1","documentation":"https:\/\/github.com\/Blockchair\/Blockchair.Support\/blob\/master\/API.md","notice":"Beginning July 19th, 2019 all applications using Blockchair API on a constant basis should apply for an API key (mailto:info@blockchair.com)"}}}",
"headers": {
"server": "nginx",
"content-type": "application/json",
"transfer-encoding": "chunked",
"connection": "close",
"cache-control": "no-cache, private",
"date": "Sat, 02 Nov 2019 11:06:52 GMT",
"x-xss-protection": "1; mode=block",
"access-control-allow-origin": "*",
"access-control-allow-methods": "GET,POST",
"access-control-allow-credentials": "true",
"access-control-allow-headers": "Origin, Content-Type, X-Auth-Token",
"referrer-policy": "strict-origin",
"feature-policy": "geolocation none; midi none; notifications none; push none; sync-xhr none; microphone none; camera none; magnetometer none; gyroscope none; speaker self; vibrate none; fullscreen self; payment none;"
},
"request": {
"uri": {
"protocol": "https:",
"slashes": true,
"auth": null,
"host": "api.blockchair.com",
"port": 443,
"hostname": "api.blockchair.com",
"hash": null,
"search": "?offset=0",
"query": "offset=0",
"pathname": "/bitcoin/dashboards/address//",
"path": "/bitcoin/dashboards/address//?offset=0",
"href": "https://api.blockchair.com/bitcoin/dashboards/address/1a/?offset=0"
},
"method": "GET",
"headers": {
"User-Agent": "request"
}
}
},
"body": "{"data":null,"context":{"code":430,"error":"Your IP address is temporary blacklisted due to exceeding usage of API resources. Please apply for an API key by contacting us at info@blockchair.com","cache":{"live":true,"duration":30,"since":"2019-11-02 11:06:52","until":"2019-11-02 11:07:22","time":null},"api":{"version":"2.0.39","last_major_update":"2019-07-19 18:07:19","next_major_update":null,"tested_features":"omni-v.a1,whc-v.a1,aggregate-v.b5,xpub-v.b5,ripple-v.a1,ethgraph-v.a1,erc_20-v.a1","documentation":"https:\/\/github.com\/Blockchair\/Blockchair.Support\/blob\/master\/API.md","notice":"Beginning July 19th, 2019 all applications using Blockchair API on a constant basis should apply for an API key (mailto:info@blockchair.com)"}}}"
}

**Comment by mhm1likae** [comment]
Hi

**Comment by daria-blockchair** [comment]
Hi @ETCorps, 

Most probably your IP address was blacklisted due to exceeding the limit of a free trial period of API. We offer free access for several days with a daily limit of 1,000 calls. After a trial period, we recommend applying an API key. 

You can purchase an API key on [this page](https://blockchair.com/api/plans). 

To students, we provide keys for free through the GitHub Student Developer Pack or on our [website](https://blockchair.com/student-pack).

If you have further questions, please contact us at info@blockchair.com.
