### ISSUE TITLE
Transection didn't process at all after 1 day passed 

### ISSUE THREAD

**Issue by Ts00695628** [Blockchair/Blockchair.Support#1165]
fdeafc533eb8308cabce65b2806c32342e83e94243cdcd0eb26985cafc43044b TX ID

https://blockchair.com/bitcoin/transaction/fdeafc533eb8308cabce65b2806c32342e83e94243cdcd0eb26985cafc43044b

Why it took so long to complete. Never happen to me before and this time it's take very long.

**Comment by Blockchainexpert44** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi @Ts00695628, 

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
