### ISSUE TITLE
Unable to Sort USDT Transactions by Value or Search for Specific Transaction Amounts

### ISSUE THREAD

**Issue by BHK-Industry** [Blockchair/Blockchair.Support#1166]
Dear Blockchair Support Team,

I am writing this support ticket to report an issue I'm experiencing while using your platform. Specifically, I'm having trouble sorting global USDT transactions by value and looking for specific transaction amounts.

I've been using your platform to keep track of my USDT transactions, and it has been incredibly useful so far. However, when I tried to sort my transactions by value or look for a specific transaction amount, I couldn't find any option to do so.

I've tried using the search bar, but it only searches for specific addresses or transaction hashes. I've also tried using the "sort by" option, but it only allows me to sort by date, block height, fee, and size.

Could you please assist me with this issue? I need to be able to sort my transactions by value, so I can easily identify large transactions and track my account balance. Additionally, I need to be able to look for specific transaction amounts to reconcile my account with my records.

I would appreciate any help you could provide in resolving this issue as soon as possible. If you need any further information from me, please do not hesitate to ask.

Thank you for your assistance.

Best regards,

Bjorn

**Comment by Blockchainexpert44** [comment]
I had desame issue blackhathacker111 helped me on it immediately message him on telegram https://t.me/Blackhathacker111

**Comment by Margaret034** [comment]
For real blackhat is good he helped me with this same issue here's his telegram link https://t.me/Blackhathacker111

**Comment by mhm1likae** [comment]
Hi

**Comment by BHK-Industry** [comment]
> Hi

Hello!

**Comment by mhm1likae** [comment]
Hi

**Comment by daria-blockchair** [comment]
Hi @BHK-Industry, 

Glad to tell you that the issue has been fixed. Now you can sort USDT transactions by value https://blockchair.com/ethereum/erc-20/transactions?q=token_address(0xdac17f958d2ee523a2206206994597c13d831ec7)
