### ISSUE TITLE
QR Code on Website

### ISSUE THREAD

**Issue by 1mbtxn** [Blockchair/Blockchair.Support#117]
You need to add a QR code feature to the website.  Literally impractical to make BCH payments without an easy way to display QR codes.  Please add this ASAP!

**Comment by Har01d** [comment]
Now Blockchair has QR codes for every blockchain we support: Bitcoin, Bitcoin Cash, Ethereum, and Litecoin. Check out an example: https://blockchair.com/bitcoin-cash/address/qp3wjpa3tjlj042z2wv7hahsldgwhwy0rq9sywjpyy (available on the mobile version as well).
