### ISSUE TITLE
Btc transaction sent with low fee (by mistake, i'm new)

### ISSUE THREAD

**Issue by jweik1984** [Blockchair/Blockchair.Support#1170]
I started a transaction from my coinbase sending BTC out. The first transaction was almost 2 days ago and it is still pending because the fee is low. So I tried another 1 and I assume the fee is to low still because it says 23 hours in que. How do I up the fees for both of these sent transactions so my btc isn't just pending?

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi @jweik1984!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block more quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
