### ISSUE TITLE
МОШЕННИК   Сотрудники github кто то может мне помочь в этом недоразумений 

### ISSUE THREAD

**Issue by Shoma77** [Blockchair/Blockchair.Support#1172]
![Screenshot_2023-05-04-08-58-33-551_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236110937-8aab0c87-fc00-4cac-8054-d6c1cb7d8a11.jpg)
![Screenshot_2023-05-04-08-58-30-794_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236110946-48d00327-0eb2-4238-b9de-1f14aaf052a6.jpg)
![Screenshot_2023-05-04-08-58-27-217_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236110953-0f97bcf0-7d95-48ac-824d-7d3a43b4120d.jpg)
![Screenshot_2023-05-04-08-48-02-282_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236110969-0982c0b1-15d5-4345-a6cb-7c8aeb33368e.jpg)
![Screenshot_2023-05-03-20-30-21-200_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236110999-49628754-bfe2-4e87-ab49-daccbb4c0d8d.jpg)
![Screenshot_2023-05-03-20-30-08-531_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111009-898eeea9-2507-434d-8731-18af50763c86.jpg)
![Screenshot_2023-05-03-20-30-01-561_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111021-a87388b0-b67d-4268-bc75-502a9b02fd82.jpg)
![Screenshot_2023-05-03-20-29-58-319_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111033-48b0387a-84dd-4b10-a3f0-d0f59b0f7875.jpg)
![Screenshot_2023-05-03-20-29-55-571_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111054-b55394c8-73e4-48a2-b2c8-d7c9ec05dbef.jpg)
![Screenshot_2023-05-03-20-29-52-504_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111067-94c20a58-ee2f-471e-82c1-015d41de7e29.jpg)
![Screenshot_2023-05-03-20-29-45-890_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111086-ec3aed77-09e9-4bed-b58f-223f735b5f8d.jpg)
![Screenshot_2023-05-03-20-29-17-096_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111103-2455bed6-b1fc-4da2-98f5-aac665795a97.jpg)
![Screenshot_2023-05-03-20-28-50-587_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111108-e47876b4-58ff-424c-920e-acab0a1afacc.jpg)
![Screenshot_2023-05-03-20-28-45-609_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111111-058ed838-d0a7-4b2f-bbdc-ee5a2c851dec.jpg)
![Screenshot_2023-05-02-22-21-45-203_com akwhatsapp](https://user-images.githubusercontent.com/131845934/236111125-d1dbc331-8d13-4237-8569-476989d5802f.jpg)

**Comment by Shoma77** [comment]
Вымогательства какой то помогите

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Yessika224** [comment]
То же самое случилось со мной, но благодаря Blackhathacker111, который помог мне отправить ему сообщение в телеграмме, его имя пользователя в телеграмме https://t.me/Blackhathacker111.

**Comment by daria-blockchair** [comment]
Hi @Shoma77,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Paying extra funds to ‘release’ other funds sounds like a classic scam. Please beware of scammers and make sure that you only speak through the official channels of your wallet of exchange.
If you suspect fraud you can contact local authorities.

Thank you for understanding.
