### ISSUE TITLE
Application terms and conditions to the users 

### ISSUE THREAD

**Issue by SlattPp** [Blockchair/Blockchair.Support#1175]
Do have your swap price lowered, I tried swapping a $50, then was showed a new amount for the swap, $202, this is nuts and I have no joy to see this happening, I don't get it with your partnership with the third party, seems they are not having to be reasonable with their thinking these days

**Comment by daria-blockchair** [comment]
Hello @SlattPp,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet or other financial services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
