### ISSUE TITLE
Withdrawal process 

### ISSUE THREAD

**Issue by Trylan123** [Blockchair/Blockchair.Support#1176]
Hi here is my wallet id 2K2764NV2 it is a paper wallet and i want to import it and process the withdrawal. I  have made payments for it already more than what it was asking. I wi attached thw receipt and i need yo knoq how to complete the peocess. Please guide me photos and videos with step by step process should of be a big help. Thanks

Payment. 39wTXBHs5XivvZHpFyYg2baoDZPzB8mCBE

Wallet: 

bc1qfzmx32wjytknp6he5zftx5uxe6zaq005vq7r79

+d00dfa7f7efc4bc818b9e94806003cbdce5fac486c7f6ae159b2c815b0567d41

**Comment by Yessika224** [comment]
Message blackhathacker111 on telegram he’ll help you

**Comment by Victoriahidalgoestafadora** [comment]
> Envía un mensaje a blackhathacker111 en Telegram, él te ayudará.  . He must want money in exchange because he didn't help me at all... please don't make false propaganda for him
