### ISSUE TITLE
Bitcoin not paid out

### ISSUE THREAD

**Issue by BeautifulLover86** [Blockchair/Blockchair.Support#1177]
I did a withdrawal through Bitcoin for $33. My withdrawal was approved but my Bitcoin was not paid out. Please help me. I'm uploading screenshots if I'm able to. 
![Screenshot_2023-05-07-08-44-28](https://user-images.githubusercontent.com/132829490/236681806-79ea9785-cb94-4a90-86d1-9594971f8fe1.png)
![Screenshot_2023-05-07-08-44-40](https://user-images.githubusercontent.com/132829490/236681817-878bf82c-b62a-4c5f-a12d-6f654a5c7d38.png)
![Screenshot_2023-05-07-08-44-53](https://user-images.githubusercontent.com/132829490/236681824-31469560-5d60-4489-99bb-bee6b148aa60.png)
![Screenshot_2023-05-07-08-45-26](https://user-images.githubusercontent.com/132829490/236681836-24196b68-b558-4926-bc62-2f090d70a9bb.png)
![Screenshot_2023-05-07-08-57-19](https://user-images.githubusercontent.com/132829490/236682062-4121e955-9ca1-4e9e-a544-189016d0d473.png)
I added my Bitcoin address that I entered. The withdrawal confirmation from which I withdrew and your records stating there is no such transaction

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Victoriahidalgoestafadora** [comment]
> Me pasó lo mismo, pero gracias a Blackhathacker111 que me ayudó a enviarle un mensaje en Telegram, su nombre de usuario de Telegram es https://t.me/Blackhathacker111
   Estás en todos lados...  Responde

**Comment by Victoriahidalgoestafadora** [comment]
> Me pasó lo mismo, pero gracias a Blackhathacker111 que me ayudó a enviarle un mensaje en Telegram, su nombre de usuario de Telegram es https://t.me/Blackhathacker111

No hagas más publicaciones si la otra persona no ayuda

**Comment by moccaiii** [comment]
Jeg aner ikke hvordan , men jeg prøver å finne appen til din side uten hell , hva heter den ? Jeg skrev BTC i app store men ikke treff !

**Comment by daria-blockchair** [comment]
Hi @BeautifulLover86,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
