### ISSUE TITLE
Goods not received 

### ISSUE THREAD

**Issue by Roysweetness** [Blockchair/Blockchair.Support#1178]
ae202cee2072d1b676656376bf1843af1cb06c606e1405b3b68a937e1ec30c75

**Comment by Victoriahidalgoestafadora** [comment]
M8robjFAmExzwjN2WZfr8Y1jhghSmJ3f2N

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Victoriahidalgoestafadora** [comment]
Quien ese ese blak.   El me puede ayudar a  recuperar mis litecoin robados ??

**Comment by Victoriahidalgoestafadora** [comment]
> Me pasó lo mismo, pero gracias a Blackhathacker111 que me ayudó a enviarle un mensaje en Telegram, su nombre de usuario de Telegram es https://t.me/Blackhathacker111

A qué te refieres?

**Comment by Victoriahidalgoestafadora** [comment]
> Me pasó lo mismo, pero gracias a Blackhathacker111 que me ayudó a enviarle un mensaje en Telegram, su nombre de usuario de Telegram es https://t.me/Blackhathacker111

Le escribí y no puede ayudar en nada ...deberías dejar de hacer publicidad falsa.

**Comment by daria-blockchair** [comment]
Hi @Victoriahidalgoestafadora, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
