### ISSUE TITLE
I want my 68$ dollars back, please 

### ISSUE THREAD

**Issue by Victoria3344** [Blockchair/Blockchair.Support#1179]
Hi you've been send me 100 email that I have to pay 68$for the exgenge from bitcoin to dolari and I have to pay 68$ which I did, for to be able to get a transfer of 8.533.00.and it's already 2 weeks and nothing happen. So please can at least have my 68 dolars back please, if you hade any heart. If I've been ok with money, I would never did anything like that.  So please be kind don't be gready person, one day we all will pay for this scams.

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi @Victoria3344,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

Paying extra funds to ‘release’ other funds sounds like a classic scam. Please beware of scammers and make sure that you only speak through the official channels of your wallet of exchange.
If you suspect fraud you can contact local authorities.

Thank you for understanding.
