### ISSUE TITLE
Owen23

### ISSUE THREAD

**Issue by owen239** [Blockchair/Blockchair.Support#118]
i sent funds to this account on my blockchain account 1DefP1gRHMnPp8Y2P2xdcNTQKq1Jsh7RfT and after sending it  dont know how it automatically send to another address i dont know this is the address the money was sent to qz9vpuqx8tjeu86cws2ldjelfz7f25d9tucf3u358l  please i need my money back

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
