### ISSUE TITLE
Still pending

### ISSUE THREAD

**Issue by raeychill88** [Blockchair/Blockchair.Support#1182]
I've contacted cash app, I've contacted bitstarz. Neither one can give me an answer, it typically only takes mins to receive my funds. This has been pending since Saturday. 
![Screenshot_20230507-133318~2](https://user-images.githubusercontent.com/132975757/236996472-52cc64f3-254e-4ede-ac4a-c515ca0137bd.png)

**Comment by raeychill88** [comment]
![Uploading Screenshot_20230508-214749.png…]()

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi @raeychill88, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block more quickly.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

Thank you for understanding.
