### ISSUE TITLE
Зависшая транзакция

### ISSUE THREAD

**Issue by Druid62r** [Blockchair/Blockchair.Support#1183]
Добрый день.07.05.2023, 12:45:36 отправил с WebMoney транзакцию которая зависла и до сегодня не получила подтверждений. Насколько я понял проблема в слишком малом размере комиссионных. В технической поддержке WebMoney сказали что комиссия была назначена верно (по их мнению) Прошу Вашей помощи в решении данной проблемы. Возможно ли увеличение комиссии майнерам на данном этапе? Рассмотрите возможные варианты.Эти средства крайне важны для меня
[BTC.pdf](https://github.com/Blockchair/Blockchair.Support/files/11439861/BTC.pdf)
[Транзакция.pdf](https://github.com/Blockchair/Blockchair.Support/files/11439864/default.pdf)

**Comment by Yessika224** [comment]
То же самое случилось со мной, но благодаря Blackhathacker111, который помог мне отправить ему сообщение в телеграмме, его имя пользователя в телеграмме https://t.me/Blackhathacker111

**Comment by Druid62r** [comment]
Благодарю за информацию.Если это не секрет во сколько обошлось решение
проблемы?

ср, 10 мая 2023 г., 13:10 Yessika224 ***@***.***>:

**Comment by Yessika224** [comment]
> Благодарю за информацию.Если это не секрет во сколько обошлось решение проблемы?

Пожалуйста, он действительно помог мне сделать это, он лучший

**Comment by Cryptolord123** [comment]
> Добрый день.07.05.2023, 12:45:36 отправил с WebMoney транзакцию которая зависла и до сегодня не получила подтверждений. Насколько я понял проблема в слишком малом размере комиссионных. В технической поддержке WebMoney сказали что комиссия была назначена верно (по их мнению) Прошу Вашей помощи в решении данной проблемы. Возможно ли увеличение комиссии майнерам на данном этапе? Рассмотрите возможные варианты.Эти средства крайне важны для меня
> [BTC.pdf](https://github.com/Blockchair/Blockchair.Support/files/11439861/BTC.pdf)
> [Транзакция.pdf](https://github.com/Blockchair/Blockchair.Support/files/11439864/default.pdf)

Здравствуйте, добрый день, слава богу, я отвечаю на вашу жалобу, это случилось со многими моими учениками, но я помог им решить ее очень быстро, напишите мне в WhatsApp +2349072788076, чтобы я помог вам сделать это немедленно.

**Comment by daria-blockchair** [comment]
Hi @Druid62r, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block more quickly.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

Thank you for understanding.
