### ISSUE TITLE
Recieving

### ISSUE THREAD

**Issue by Levene09** [Blockchair/Blockchair.Support#1189]
Have not uet revieved bitcoin i sent to my account in over 2weeks

**Comment by Cryptolord123** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi @Levene09,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
