### ISSUE TITLE
not recieved bitcoins

### ISSUE THREAD

**Issue by strubes18** [Blockchair/Blockchair.Support#1190]
why has my transaction been confirmed

You received some Bitcoin
Address
3B78bLaUwnx92HwSzFhvXNtNXbK55XvXee
To
Everyday Bitcoin
Amount
0.00101359 BTC
TXID
af0ed5c0137676b796ec4afdbb2ae6289cfe53d3264321c22f32af1c18214071
Status
Pending 0/3
Date
May 05, 2023 10:59

**Comment by Cryptolord123** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by strubes18** [comment]
did you have to pay a fee

**Comment by Cryptolord123** [comment]
> did you have to pay a fee

Yes just a little for fee do that

**Comment by Ush121** [comment]
I've got a transaction that never went through after paying g fee to minor can anyone help

**Comment by Cryptolord123** [comment]
> I've got a transaction that never went through after paying g fee to minor can anyone help

Message him immediately for that https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block more quickly.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Thank you for understanding.
