### ISSUE TITLE
I lost my funds after doing a swap

### ISSUE THREAD

**Issue by Yuliannycvg** [Blockchair/Blockchair.Support#1191]
Good afternoon, I made a BITCOIN to ETH swap and my funds disappeared, more than 24 hours have passed and I don't get any response from trustwallet

**Comment by Cryptolord123** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Ush121** [comment]
3KLQrQRBuK8jXzgDyj3yKG6T8GLZKCJdpk 
How can you contact someone by there address I paid
 this minor and he never delivered

**Comment by daria-blockchair** [comment]
Hi @Yuliannycvg,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
