### ISSUE TITLE
Desperate 

### ISSUE THREAD

**Issue by Lordvalitile** [Blockchair/Blockchair.Support#1197]
I have been waiting for 3days. I desperately need that to clear asap Like I'm not taking my kid to school cause I. Don't have gas need Please help.

**Comment by daria-blockchair** [comment]
Hi @Lordvalitile, 

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
