### ISSUE TITLE
BlockChair is stuck on an abandoned fork of the Dash blockchain

### ISSUE THREAD

**Issue by LucasBrinkers** [Blockchair/Blockchair.Support#1198]
The Dash blockchain was temporary halted today and BlockChair seems to be on a dead fork: https://blockchair.com/nl/dash/block/1874880
Please update Dash to the latest version https://github.com/dashpay/dash/releases/tag/v19.1.0
And you probably want to reindex afterwards.
Check the Dash discord for more info: https://discord.com/channels/484546513507188745/484546513935269918/1110307304299053117

**Comment by LucasBrinkers** [comment]
The Dash blockchain was temporary halted today and BlockChair seems to be on a dead fork: https://blockchair.com/nl/dash/block/1874880
Please update Dash to the latest version https://github.com/dashpay/dash/releases/tag/v19.1.0
And you probably want to reindex afterwards.
Check the Dash discord for more info: https://discord.com/channels/484546513507188745/484546513935269918/1110307304299053117

**Comment by LucasBrinkers** [comment]
Looking good now!

**Comment by Har01d** [comment]
There was an issue with v.19.1.0: https://github.com/dashpay/dash/issues/5383#issuecomment-1557751535
