### ISSUE TITLE
Block export does not contain last block

### ISSUE THREAD

**Issue by robvanbentem** [Blockchair/Blockchair.Support#12]
When using the exporting function the generated file does not contain the latest block (at least not for BCH blocks, haven't checked BTC).

How to reproduce: create a filter with block height >= ${recent block}, click export and compare results.

![2017-08-11-133141_660x238_scrot](https://user-images.githubusercontent.com/940570/29211463-8799b424-7e99-11e7-99fd-4f5d4ecede81.png)
![2017-08-11-133153_617x105_scrot](https://user-images.githubusercontent.com/940570/29211464-87d642e0-7e99-11e7-8431-8ccec2ae6bf5.png)

**Comment by Har01d** [comment]
Thanks, fixed!

By the way, if it’s possible to mention Blockchair as the data source on the fork.lol website that would be great! :)

**Comment by robvanbentem** [comment]
> By the way, if it’s possible to mention Blockchair as the data source on the fork.lol website that would be great! :)

Oh my... I ashamed you even had to ask that. You're mentioned now!

Thanks!

**Comment by Har01d** [comment]
No worries! Thank you :)
