### ISSUE TITLE
Bitcoin cash issue

### ISSUE THREAD

**Issue by CryptoNaj** [Blockchair/Blockchair.Support#120]
I've sent bch from coinbase to another coinbase account and it has completed but has not showed up yet. The address is  pzpjcwmjds3fq76dfeq6hsxr9ulaw54nwc7ktp3cwr. PLEASE HELP !!!! THANK YOU

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
