### ISSUE TITLE
Recieve end of bitcoin!!!

### ISSUE THREAD

**Issue by CMSal2299** [Blockchair/Blockchair.Support#1200]
I recieved funds on 4-12-2023, it showed on my exchange, for three hours then disappered, I contacted support and they began there troubleshooting but still today a month plus and they still can’t figure out why funds do not want to reappear on the exchange wallet, in my in vestigating there are two issues:1- there was a exchange app That was later updated to a updated version, I had used the other 6 months prior with no problem, I then used the new updated app version but when I requested a recieve Address it put out the same identical address from 6 months prior, my funds are still on the blockchain as unspent funds, but exchange support has been scratching there heads for a month and all I get is there still working on the issue, I was able to trace back and put together the wallet I’d, that corresponds with the address but it seems that my initial bitcoin wallet address spit this address out and then another bitcoin wallet (new app)upgrade spit out the same address, so it seems to me that two addresses and two set of recovery phrases, can anybody please help me with some info

**Comment by BestSoftwareenginee** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111
