### ISSUE TITLE
Hurry the f up

### ISSUE THREAD

**Issue by Xyang213** [Blockchair/Blockchair.Support#1205]
All this technology and you guys still can't make this by pass faster.

**Comment by DrrDino** [comment]
What’s your issue??

**Comment by daria-blockchair** [comment]
Hi @Xyang213, 

At Blockchair we don't process transactions, we just show the information stored on blockchains. 
If you have been waiting for a long time for your transaction to be processed, please refer to [this article](https://blockchair.com/faq#q0) from our FAQ and contact your wallet or exchange for further assistance. 

Thank you for understanding.
