### ISSUE TITLE
help on soft limits on API. Please i need a response so i can relay to my company

### ISSUE THREAD

**Issue by script-2000** [Blockchair/Blockchair.Support#1207]
Am part of a team working on an App which needs to make transactions on the server side. The problem is with the  soft limit of 5 requests per second on api post calls , how will more than 2000 users be able to use the app since we are expecting more than 2000 users when the app is launch . Is there a way to whitelist our server ip from the soft limit or increase the soft limit for us ?

**Comment by DrrDino** [comment]
Yes message blackhathacker111 on telegram he helped me do mine  https://t.me/Blackhathacker111

**Comment by script-2000** [comment]
> Yes message blackhathacker111 on telegram he helped me do mine https://t.me/Blackhathacker111

am not going to do that . also am waiting for the proper customer service and not you

**Comment by daria-blockchair** [comment]
Hi @script-neutron,

Thank you for reaching out. 

This limit is applied only if we experience a very high load on our servers, and it's turned on and off manually by our admins. In case you hit this limit, an error 435 will be returned.

Please contact us at info@blockchair.com. We'll be glad to provide you with more information and find the best solution for your needs.
