### ISSUE TITLE
Victim of scam 

### ISSUE THREAD

**Issue by Jacquielh157** [Blockchair/Blockchair.Support#121]
I sent my bitcoin cash to Someone for services. I was a victim of scam. I did not receive anything. I need to cancel my payment and refund my bitcoin cash.

**Comment by AivaM** [comment]
Hello,
 
Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
 
—
 
Blockchair Support

**Comment by Jacquielh157** [comment]
This link doesn’t send me to any supposed page. I emailed support and they sent me here to this page. I will need to get in contact with someone who can help me resolve this issue

**Comment by Jacquielh157** [comment]
I tried again and it Sent me back to the same link.
