### ISSUE TITLE
bc1qzdpl8tu48lhwjpypy0kyzludh95j6kcx05w843

### ISSUE THREAD

**Issue by krasiva711** [Blockchair/Blockchair.Support#1211]
![Uploading _ad8278df-c74b-45a5-894c-c8cc6d42b7a5.jpg…]()
              bc1qzdpl8tu48lhwjpypy0kyzludh95j6kcx05w843

_Originally posted by @krasiva711 in https://github.com/Blockchair/Blockchair.Support/issues/1192#issuecomment-1553890936_

**Comment by Bossgame94** [comment]
It's still pending on the Blockchain

**Comment by wils81ouwehand** [comment]
bnb1fnd0k5l4p3ck2j9x9dp36chk059w977pszdgdz

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
