### ISSUE TITLE
Bitcoin cash sent to bitcoin wallet 

### ISSUE THREAD

**Issue by Humble7373** [Blockchair/Blockchair.Support#122]
Please I mistakenly sent bitcoin cash to a bitcoin wallet and now the bitcoin cash is stuck. I need help to reverse it back to my wallet 

53c48c2d-216b-41e1-b684-453efa8ad147

**Comment by csorila2k17** [comment]
Hi, I mistakenly sent bitcoin cash to a bitcoin wallet with btc address 3M77LC1qgTfFam4mJ4i8CegM56z5wGr5Ye no showing as legacy address and it generates a cash address format. I sent it from my blockchain wallet c805e67b-55d8-4ea5-95fb-b1fae03cd1f6. please help me.

**Comment by AivaM** [comment]
Hello,
 
Please refer to our FAQ regarding this issue: 
https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
 
—
 
Blockchair Support
