### ISSUE TITLE
Time (date) filter not working

### ISSUE THREAD

**Issue by orcaclub** [Blockchair/Blockchair.Support#1220]
I am trying to filter outputs at https://blockchair.com/bitcoin/outputs - by selecting a filter 'time' - set a date and nothings happens. 
Seems like the filter does not send the right argument into the URL.
<img width="847" alt="Screenshot 2023-06-29 at 20 24 51" src="https://github.com/Blockchair/Blockchair.Support/assets/5121841/a8fd78c8-e179-4711-88bc-23c4878443be">

**Comment by daria-blockchair** [comment]
Hi @orcaclub, 

Thank you for reporting the issue. It has been fixed.
