### ISSUE TITLE
MY BITCOIN TRANSFEE WAS NEVER RECEIVED 

### ISSUE THREAD

**Issue by Ezeees** [Blockchair/Blockchair.Support#1224]
I never received my bitcoin to my wallet what is going on its the correct address and everything 1c22c4c1e5f66969604469b9c4f5e6314f8fde41ed885c16a1e632b339975690

**Comment by HenryEnrique** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
Hi @,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
