### ISSUE TITLE
Transaction issue

### ISSUE THREAD

**Issue by Painisinsane** [Blockchair/Blockchair.Support#1226]
Went to buy tokens and it shows That it was confirmed but no tokens anywhere .. even messaged dogetti to fix the issue and nothing has been done

**Comment by HenryEnrique** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
Hi @Painisinsane,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
