### ISSUE TITLE
help with xmr/btc that was sent to wrong address and never received 

### ISSUE THREAD

**Issue by drankman123** [Blockchair/Blockchair.Support#1230]
hi i accidently sent my xmr to the wrong address if anyone can please help it would be really helpfu! i converted to btc to xmr.  btc was purchased on the 16th of june  and converted on the 19th of june and the xmr was lost xmr on the 19th after i sent it. 

https://blockchair.com/bitcoin/transaction/485d59f8a0b2e9da9445e64c7a5b451333dc2232d2117efb0f42b444ce14747e

xmr was sent to this by accident,

871wLL2nqQT3vBGuAn7g6eRQgtzr2aVCsNZB8zy7fvGANAXM2WSqobHBx5r9EWiAR7YNejjSqZTs19SuqAEapTW88sYTfmA 

https://www.exploremonero.com/transaction/fa47c35594130e2e213676c6572209a7a30e7c44d61a813313a18a36efd82684

any help would be greatly appreciated and if someone can help me get it back i will happily send you some btc or xmr!

**Comment by HenryEnrique** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Lyalya33** [comment]
Столкнулась почти с такой же проблемой, ток у меня заменился адрес, скам в общем. Пытаюсь заменить адрес получателя на свой. У вас что нибудь вышло?

**Comment by daria-blockchair** [comment]
Hi @drankman123, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
