### ISSUE TITLE
How do I know trace the reciever name or company name of the funds reciever ?

### ISSUE THREAD

**Issue by greknar2** [Blockchair/Blockchair.Support#1237]
I have sent bitcoin to 
"
![image](https://github.com/Blockchair/Blockchair.Support/assets/85964924/c4f951fb-8a01-4647-a038-8afffd39a1bd)
"

which company is this ?

**Comment by OkponkoXchange** [comment]
https://github.com/Blockchair/Blockchair.Support/issues/1237#issuecomment-1657083782 #467 @OkponkoXchange #
Duplicate of #

**Comment by daria-blockchair** [comment]
Hi @OkponkoXchange, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. We also don't have any information regarding the owners of the addresses or on which platform that address was registered. 

Please get in touch with your wallet or exchange for more information.

Thank you for understanding.
