### ISSUE TITLE
I need help to recover my Bitcoin from a wallet I sent wrong

### ISSUE THREAD

**Issue by Hbutt146l** [Blockchair/Blockchair.Support#1239]
Please help me... I need instructions and guidance for recovery of my Bitcoin from a mistake.

**Comment by Mmiriewilo** [comment]
A pending transaction

**Comment by Mindaugas723** [comment]
bc1qqk4d8mjxst3t9x93c8nhe4s7dl8lc6ky7uf7c8 per klaida jie buvo pervesti cia o turejo patekti i Revolt

**Comment by Mindaugas723** [comment]
kaip persivesti i Revolt saskaita

**Comment by Mindaugas723** [comment]
30fea21029aa72a0fe15b4c5cfda95fc2f01032ef713be9baaadbf21332f3e8d susigrazinti kurie per klaida buvo pervesti cia

**Comment by TechGirl8778** [comment]
> A pending transaction

I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by TechGirl8778** [comment]
> Please help me... I need instructions and guidance for recovery of my Bitcoin from a mistake.

I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Hopefully123** [comment]
Please help me... I need instructions and guidance for recovery of my Bitcoin from a mistake.

**Comment by TechGirl8778** [comment]
> Please help me... I need instructions and guidance for recovery of my Bitcoin from a mistake.


I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
Hi @Hopefully123, @Hbutt146l, 

We are sorry to hear about your case. Unfortunately, we are not able to help get your funds back. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains.
