### ISSUE TITLE
Transactions quantity and list of BCH aren't resetted with every block

### ISSUE THREAD

**Issue by MalkavianBilbao** [Blockchair/Blockchair.Support#124]
Seems that the BCH transactions mempool aren't resetted when a new block is mined so it shows a lot of them pending...

**Comment by AllenChong** [comment]
issue

**Comment by Har01d** [comment]
Hello,

I don't think there's an issue — stress test transactions don't get included in blocks due to too low fees, so they stay in the mempool until they get evicted (if I remember correctly, the default lifespan is 72 hours).

**Comment by MalkavianBilbao** [comment]
I don't more than 45,000 pending transactions now here,  altough maybe Johoe's node discard automatically too low fee ones.
https://jochen-hoenicke.de/queue/#3,24h
