### ISSUE TITLE
bc1q4cflgv5tgk8set7wnq95fy0qr479r0yrmg7usr

### ISSUE THREAD

**Issue by Mindaugas723** [Blockchair/Blockchair.Support#1240]
kaip persivesti savo pinigus kurie buvo perklaida ne ten pervesti #467  bitcyti

**Comment by TechGirl8778** [comment]
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
Hi @Mindaugas723, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.

Thank you for understanding.
