### ISSUE TITLE
30fea21029aa72a0fe15b4c5cfda95fc2f01032ef713be9baaadbf21332f3e8d

### ISSUE THREAD

**Issue by Mindaugas723** [Blockchair/Blockchair.Support#1241]
30fea21029aa72a0fe15b4c5cfda95fc2f01032ef713be9baaadbf21332f3e8d per klaida buvo pervesti pinigai kaip juos sugrazinti i Revolt21 saskaita

**Comment by daria-blockchair** [comment]
Hi @Mindaugas723, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.

Thank you for understanding.
