### ISSUE TITLE
Billetera bloqueada

### ISSUE THREAD

**Issue by Jonat2223** [Blockchair/Blockchair.Support#1242]
No puedo acceder a
Mi billetera me podrían ayudar Bch es  esta pqrkrn8xgvmd7qg8zkh729690rrzwnljfy32gqmkwj

**Comment by Jonat2223** [comment]
Necesito recuperar mis bch

**Comment by TechGirl8778** [comment]
Perdí muchas monedas en un caso de estafa como este gracias al mejor hacker del mundo que me ayudó a recuperar todos mis fondos, envíele un mensaje en Telegram, su nombre de usuario de Telegram es https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
Hi @Jonat2223, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.

Thank you for understanding.
