### ISSUE TITLE
Wrong lobstr Stella wallet 

### ISSUE THREAD

**Issue by Staz22** [Blockchair/Blockchair.Support#1243]
Greetings, I made a mistake sending coin to the wrong wallet address. Can I be refunded back to my wallet.

Sender wallet: GAFF7NOIC6OFWMSQRC4KHBRJTX5VHG3TBRP4G5Q2JF6YOUO7ZU4RPHUU

Receiver wallet:
GDTHJZKRPPH7S3X3ZNIVVBJQMSML3YE4CSFQ57AACLHTFE6UTR27FBKO

Memo: Gary Eggleston

**Comment by TechGirl8778** [comment]
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
Hi @Staz22, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains. No one can.

Thank you for understanding.
