### ISSUE TITLE
Bitcoin taken longer that two days to confirm

### ISSUE THREAD

**Issue by g3386716** [Blockchair/Blockchair.Support#1247]
Yes I need to get my transaction confirmed ASAP, it is known that Bitcoin by terms and conditions or currency law cannot take longer than 24 hours to transfer as it is considered withholding money which there for is stealing, 

This is the transaction hash for the transaction. 

bb676127ce6bf083e5dbe6c1240ccc3ca3eecfef1886fca7e19b31001615e7b4

**Comment by daria-blockchair** [comment]
Hi @g3386716, 

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

If you have been waiting a long time for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
