### ISSUE TITLE
is xtz still supported ?

### ISSUE THREAD

**Issue by rootmout** [Blockchair/Blockchair.Support#1249]
Hi,

Maybe I missed a blogpost that give the info, anyway, I can see that your documentation provide endpoint information for Tezos 

> Tezos-like blockchain stats
> Endpoint:
> https://api.blockchair.com/tezos/stats

https://blockchair.com/api/docs#link_M1

but when I query the URL I got a `Sorry, the page you are looking for could not be found.` error message.

**Comment by daria-blockchair** [comment]
Hi, 

Unfortunately, we no longer support Tezos.
