### ISSUE TITLE
API Call Result Count

### ISSUE THREAD

**Issue by MichaelJamesHofer** [Blockchair/Blockchair.Support#125]
Am I missing something or do the API call's only return the first 10 results? Is there a way to change this?

**Comment by Har01d** [comment]
Right now you can use the export feature, or use deprecated `next` and `next_sort` options (see https://github.com/Blockchair/Blockchair.Support/blob/master/API.md).

We’ve also finished the development of our new API, which includes simple `offset` parameter which allows easy pagination, will be in production soon, English documentation is on the way.

**Comment by Har01d** [comment]
The new version of our API has a very easy way to paginate. Please check out the documentation: https://github.com/Blockchair/Blockchair.Support/blob/master/API.md (use `offset`).
