### ISSUE TITLE
Pending payment 

### ISSUE THREAD

**Issue by Meiehz** [Blockchair/Blockchair.Support#1256]
My bitcoin payment has been pending for 48 hours

**Comment by Princeprince559** [comment]
@Meiehz 
my apologies for the inconvenience... are still having trouble with the system??? and what steps did you take to purchase the bitcoin???

> My bitcoin payment has been pending for 48 hours

please let me know at your earliest convenience. thank you and have a good one!!!

**Comment by Meiehz** [comment]
I won money on bovada then used bitcoin to get it to my cash appSent from my iPhoneOn Sep 6, 2023, at 1:37 AM, Princeprince559 ***@***.***> wrote:﻿
@Meiehz
my apologies for the inconvenience... are still having trouble with the system??? and what steps did you take to purchase the bitcoin???

My bitcoin payment has been pending for 48 hours

please let me know at your earliest convenience. thank you and have a good one!!!

**Comment by daria-blockchair** [comment]
Hi @Meiehz, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.

Thank you for understanding.
