### ISSUE TITLE
Yanlis bir adrese usdt gonderimi yaptim.bu adresin kime ait oldugunu ve nasıl iletisime gececegim

### ISSUE THREAD

**Issue by Candan166** [Blockchair/Blockchair.Support#1257]
![Screenshot_20230906-093213_Chrome](https://github.com/Blockchair/Blockchair.Support/assets/144211203/a0f8d7de-7c1c-4966-b595-935ae73c4408)
 

Bu adrese nasıl ulaşabilirim  ?

**Comment by daria-blockchair** [comment]
Hi @Candan166, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately.
Also, we don't have any information about the owners of the addresses or on which platform the address was registered.

For more information, please get in touch with your wallet or exchange.

Thank you for understanding.
