### ISSUE TITLE
Paid taxes and fees completely almost three weeks ago

### ISSUE THREAD

**Issue by trashchick** [Blockchair/Blockchair.Support#1259]
All taxes and fees have been paid. Been paid for about 3 weeks. The funds still haven't been released. Is there any way to expedite the release of the funds? For Bitcoin

**Comment by Stargazerr1** [comment]
> All taxes and fees have been paid. Been paid for about 3 weeks. The funds still haven't been released. Is there any way to expedite the release of the funds? For Bitcoin

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
Hi @trashchick, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.

Thank you for understanding.
