### ISSUE TITLE
BTC Congestion

### ISSUE THREAD

**Issue by btcethcardano** [Blockchair/Blockchair.Support#1260]
Is there a BTC congestion issue that has restricted my funds for almost a week?

**Comment by Stargazerr1** [comment]
> Is there a BTC congestion issue that has restricted my funds for almost a week?

Yes message this hacker he helped me recovered my funds I had same issue or else you lose it for life https://t.me/Blackhathacker110

**Comment by Macdave02** [comment]
I’m having errors sending btc

**Comment by Macdave02** [comment]
I’m having issues

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
