### ISSUE TITLE
Delay in transaction 

### ISSUE THREAD

**Issue by Boluwatifeiyanu12** [Blockchair/Blockchair.Support#1261]
I have made a transaction since more than 14hours and the transaction is still not completed yet. Pls kindly attend with urgency.

**Comment by Pooch8920** [comment]
I have a transaction that's been processing for 2 days.
559fe37e390c296b5b5a25ab0777c4d4aed97fcc5b9b65bfa7fc29767216f11f

**Comment by pkerins79** [comment]
Over 48 hours of unconfirmed transactions
30b05eab94c0c30572b85ed139c34ef9bdd189f2a7f9a695d583002e0a0bb3e4

**Comment by Pooch8920** [comment]
Yes

**Comment by The-Jel** [comment]
Has your transaction been completed yet?

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
