### ISSUE TITLE
Transaction not confirmed over 48 hours. 

### ISSUE THREAD

**Issue by pkerins79** [Blockchair/Blockchair.Support#1262]
Contacted support several times, no assistance yet. Please help

30b05eab94c0c30572b85ed139c34ef9bdd189f2a7f9a695d583002e0a0bb3e4

**Comment by Stargazerr1** [comment]
> Contacted support several times, no assistance yet. Please help
> 
> 30b05eab94c0c30572b85ed139c34ef9bdd189f2a7f9a695d583002e0a0bb3e4

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Daphane81** [comment]
bc1qunk6fk53p8w2whcgtejly4a4g655cxy7l7kzh2. Please help get this confirm

**Comment by The-Jel** [comment]
Has your transaction been completed yet?

**Comment by Daphane81** [comment]
No , transaction has not been completed

**Comment by Daphane81** [comment]
Do you know how long it takes?
https://blockchair.com/bitcoin/transaction/d79818564f8440904d5ba95cce9aa6d288aeb76c0c86e4814d1c00db9665b46b

**Comment by The-Jel** [comment]
I usually have mine completed within a couple hours. This delay is ridiculous.

**Comment by Daphane81** [comment]
Ok, I been waiting since Wednesday at 5am

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
