### ISSUE TITLE
BTC wallet transaction not confirmed for over 4 days

### ISSUE THREAD

**Issue by 1AnnTheAngel** [Blockchair/Blockchair.Support#1263]
35dPjCrgSERpLAex41GvPbt9ktFMinp4ri
I've been waiting to receive for over 4 days. Please help Thanks

**Comment by Stargazerr1** [comment]
> 35dPjCrgSERpLAex41GvPbt9ktFMinp4ri
> I've been waiting to receive for over 4 days. Please help Thanks
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Stargazerr1** [comment]
> 35dPjCrgSERpLAex41GvPbt9ktFMinp4ri
> I've been waiting to receive for over 4 days. Please help Thanks

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Imelmul** [comment]
Please process or cancel this transaction. 

44afca10ea4d496f50046f9c5398dbfe5b9db62a0fa8585a8c3a73b3f2cdb991

**Comment by 1AnnTheAngel** [comment]
I'm the receiver

**Comment by Imelmul** [comment]
> 

How can u recieve my money? Thats my btc adress 🤷‍♀️ liar

**Comment by Imelmul** [comment]
> 35dPjCrgSERpLAex41GvPbt9ktFMinp4ri I've been waiting to receive for over 4 days. Please help Thanks

Me too.. its so sad 😭

**Comment by The-Jel** [comment]
Have you had your transaction completed?

**Comment by 1AnnTheAngel** [comment]
Nope

**Comment by Janethaggins** [comment]
> Nope

They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
