### ISSUE TITLE
BTC wallet transaction not confirmed for over 5 days

### ISSUE THREAD

**Issue by Alex420742** [Blockchair/Blockchair.Support#1264]
wish to inform you that transaction number : 2b8b1bb7e1f2475af3d8cd788cd6277c68cf515a72e0d9babab3ef43cfe35a7c  has been pending for 5 days and remains invalid. I await a prompt resolution.

Sincerely,

**Comment by Stargazerr1** [comment]
> wish to inform you that transaction number : 2b8b1bb7e1f2475af3d8cd788cd6277c68cf515a72e0d9babab3ef43cfe35a7c has been pending for 5 days and remains invalid. I await a prompt resolution.
> 
> Sincerely,

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Daphane81** [comment]
d79818564f8440904d5ba95cce9aa6d288aeb76c0c86e4814d1c00db9665b46b. Has been pending for over 5 days

**Comment by The-Jel** [comment]
Has your transaction been completed?

**Comment by Alex420742** [comment]
> Has your transaction been completed?

No

**Comment by Daphane81** [comment]
No

**Comment by Daphane81** [comment]
> Has your transaction been completed?

No

**Comment by Daphane81** [comment]
> Has your transaction been completed?

No

**Comment by Janethaggins** [comment]
> wish to inform you that transaction number : 2b8b1bb7e1f2475af3d8cd788cd6277c68cf515a72e0d9babab3ef43cfe35a7c has been pending for 5 days and remains invalid. I await a prompt resolution.
> 
> Sincerely,

They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by Janethaggins** [comment]
> > Has your transaction been completed?
> 
> No

They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by The-Jel** [comment]
Warning!

Beware of scammers! No one can reverse your transaction and only YOU have the power to speed up your transaction. Don’t fall for scammers impersonating members of Blockchair! We will never ask for your private keys, seed phrase or mnemonic phrase.

We will not write to you first, be that in a private message on Telegram or other social media, and we do not provide support for individual requests which are unrelated to Blockchair’s products and services.

**Comment by Janethaggins** [comment]
> Warning!
> 
> Beware of scammers! No one can reverse your transaction and only YOU have the power to speed up your transaction. Don’t fall for scammers impersonating members of Blockchair! We will never ask for your private keys, seed phrase or mnemonic phrase.
> 
> We will not write to you first, be that in a private message on Telegram or other social media, and we do not provide support for individual requests which are unrelated to Blockchair’s products and services.

Lol says who’s looking for help too
