### ISSUE TITLE
My Bitcoin Transaction has been stuck on the block chain for 5 days

### ISSUE THREAD

**Issue by JustinTneedshelp** [Blockchair/Blockchair.Support#1266]
Please help me can you either cancel this transaction or push it threw 374pC7SwvuerTwb9VSp9ckaT3SVVauRiPD (this was the address)

**Comment by The-Jel** [comment]
Have you heard anything? Has your transaction been completed?

**Comment by JustinTneedshelp** [comment]
Nothing we can do but wait It’s a problem with the blockchain out of our
control

**Comment by Janethaggins** [comment]
> Please help me can you either cancel this transaction or push it threw 374pC7SwvuerTwb9VSp9ckaT3SVVauRiPD (this was the address)

They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
