### ISSUE TITLE
Is anyone else scared that we may never see our transactions completed?

### ISSUE THREAD

**Issue by The-Jel** [Blockchair/Blockchair.Support#1269]
I have been waiting over 5 days. No one has responded to my questions or requests. When will my transaction be complete? I feel like no one is listening to me or these others experiencing the same trouble. 
Hash: 
8782467ad205cbf5a8a3292f0ded19a69bb991d47dbb1cd6e50bdc0e7c19200e

**Comment by Breezy079** [comment]
I’ve been waiting 7 days now I’m yet to see my transaction completed
Hash; ef33d13e4521b750ff70ed1498a2a244ab3f787ebf32933f841bf0298c6c6e39

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
