### ISSUE TITLE
Search Outputs from Known Sending Address

### ISSUE THREAD

**Issue by NoWay426** [Blockchair/Blockchair.Support#127]
There is a way to search for outputs by recipient address, but no way to search for outputs from a sending address. I'm looking for a single output - I know the satoshi value and possible sending addresses - cannot figure out a way to do this.

Perhaps what I'm looking for is a way to search inputs from a known sending address?

**Comment by Har01d** [comment]
Basically we treat inputs simply as spent outputs (so there’s no separate table for inputs, the outputs table is updated each time an input gets spent), so you can query like this: `https://blockchair.com/bitcoin/outputs?q=is_spent(1),recipient([addr])` to find inputs.
