### ISSUE TITLE
Is it better to have a higher or lower queue number? Which way gets you closer to confirmation?

### ISSUE THREAD

**Issue by The-Jel** [Blockchair/Blockchair.Support#1271]
Is it better to have a higher or lower queue number? Which way gets you closer to confirmation?

**Comment by Breezy079** [comment]
Lower queue numbers

**Comment by Janethaggins** [comment]
They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by Breezy079** [comment]
Thanks but I think I’ll wait until my transaction is completed
