### ISSUE TITLE
What the F***!!! When will I have my funds???

### ISSUE THREAD

**Issue by The-Jel** [Blockchair/Blockchair.Support#1274]
I’m going on 7-days and I’m still no further up in queue than 15,000. Will I ever get my transaction settled?!?!?!!!!!

**Comment by The-Jel** [comment]
8782467ad205cbf5a8a3292f0ded19a69bb991d47dbb1cd6e50bdc0e7c19200e

**Comment by The-Jel** [comment]
Please complete my transaction. PLEASE!!!!!!  N

**Comment by The-Jel** [comment]
Come on!!! My queue is going backwards!!!
Please! Someone just complete my transaction. 
7-days! This is RIDICULOUS!!!
My Bitcoin value is LOSING VALUE!!!

**Comment by Janethaggins** [comment]
> Come on!!! My queue is going backwards!!!
> Please! Someone just complete my transaction.
> 7-days! This is RIDICULOUS!!!
> My Bitcoin value is LOSING VALUE!!!

They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by The-Jel** [comment]
Nice try Scammer.

**Comment by Janethaggins** [comment]
> Nice try Scammer.

Your lost not mine MF

**Comment by The-Jel** [comment]
Whatever, Dude.

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
