### ISSUE TITLE
My bitcoin

### ISSUE THREAD

**Issue by Luczek10** [Blockchair/Blockchair.Support#1278]
Still waiting for my bitcoin. Its been 1 week and a couple days and no sign of it

**Comment by daria-blockchair** [comment]
> Still waiting for my bitcoin. Its been 1 week and a couple days and no sign of it

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
