### ISSUE TITLE
Money I sent from my bitcoin wallet isn’t showing up to the address I sent it to. 

### ISSUE THREAD

**Issue by bigjerryy** [Blockchair/Blockchair.Support#128]
I sent money yesterday to an address and it’s showing that it hasn’t processed on the website the address is from. How long does it typically take for my money to reach its destination? Blockchair has said that it’s spent which old what that means. Please tell me I didn’t lose my money!!!!!!

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue:
https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
