### ISSUE TITLE
btc exchange

### ISSUE THREAD

**Issue by dddaaasss15** [Blockchair/Blockchair.Support#1280]
Hello, during the exchange I specified the wrong BTC wallet and the funds arrived at a different address, what can I do?

**Comment by Doncharless** [comment]
> Hello, during the exchange I specified the wrong BTC wallet and the funds arrived at a different address, what can I do?

The best hacker who helped me with that I will advise message him on telegram
https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
> Hello, during the exchange I specified the wrong BTC wallet and the funds arrived at a different address, what can I do?

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains. No one can.
