### ISSUE TITLE
BTC is not pay

### ISSUE THREAD

**Issue by lego161rus** [Blockchair/Blockchair.Support#1284]
The correct wallet address is specified, but the BTC has not yet arrived. What to do and why did this happen?

**Comment by Doncharless** [comment]
> The correct wallet address is specified, but the BTC has not yet arrived. What to do and why did this happen?

The best hacker who helped me with that I will advise message him on telegram
https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
