### ISSUE TITLE
Add coingeek.com to guessed miners

### ISSUE THREAD

**Issue by joechin13** [Blockchair/Blockchair.Support#129]
Please add coingeek.com to guessed miners. They are the largest BCH miner with consistently over 20% of the hash power. The blocked mined by them can be identified in the coinbase text "coingeek.com". Thanks.

**Comment by Har01d** [comment]
Hello,

Thanks for the request! Please check this out — https://blockchair.com/bitcoin-cash/blocks?q=guessed_miner(CoinGeek)#

**Comment by joechin13** [comment]
Looks great! Thanks!
