### ISSUE TITLE
Delay transaction 

### ISSUE THREAD

**Issue by Pappj67** [Blockchair/Blockchair.Support#1297]
Please can someone help me I am having delay in confirmation 
It’s day 19 and my coin still ain’t be confirmed 
4da781d6ffd91850d2445589585d2ad12245d1b1d61da38afc34afc046009531

**Comment by Pappj67** [comment]
Please can someone help me I am having delay in confirmation
It’s day 19 and my coin still ain’t be confirmed
4da781d6ffd91850d2445589585d2ad12245d1b1d61da38afc34afc046009531

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
