### ISSUE TITLE
Return bitcoin

### ISSUE THREAD

**Issue by Emizinwilson1** [Blockchair/Blockchair.Support#1298]
Please I need the bitcoin sent to this wallet address returned back to the previous sender

**Comment by Marfarita** [comment]
Proszę, aby bitcoin wysłany na ten adres portfela został zwrócony poprzedniemu nadawcy

**Comment by Marfarita** [comment]
> Proszę, aby bitcoin został znaleziony na ten adres portfela został zwrócony poprzedniemu nadawcy

**Comment by Marfarita** [comment]
Z mojego portfela i za moje pieniądze- NIGDY WIĘCEJ!! +

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
