### ISSUE TITLE
My transaction has been on queue for 19 days now and no one is even letting me know what’s going on just approve my transaction please

### ISSUE THREAD

**Issue by Breezy079** [Blockchair/Blockchair.Support#1299]
Please approve my transaction

**Comment by mail731212** [comment]
[]()

**Comment by mail731212** [comment]
@mail731212

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq/why) section and get in touch with your wallet or exchange for more information.
Thank you for understanding.
