### ISSUE TITLE
Что за бред

### ISSUE THREAD

**Issue by Serega161161** [Blockchair/Blockchair.Support#1300]
Верните деньги обратно на кошелёк отмените или уже одобрите транзакцию сколько можно ждать, что за безпредел

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
