### ISSUE TITLE
Верните деньги или одобрите транзакцию что за безпредел такой??? 

### ISSUE THREAD

**Issue by Serega161161** [Blockchair/Blockchair.Support#1301]

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in contact with your wallet or exchange for more information.
Thank you for understanding.
