### ISSUE TITLE
Reverse my transaction 

### ISSUE THREAD

**Issue by ashokkarri** [Blockchair/Blockchair.Support#1302]
Transaction ID:
https://blockchair.com/bitcoin/transaction/5198157579094acc2a987d2ed18c68dd2d3613525e317cc9b345c839c2a54655
3Pid1xBUSptx4221C1VN7u4ztbZDRTVMhZ
Wallet
askkarri@gmail.com

**Comment by daria-blockchair** [comment]
> Transaction ID: https://blockchair.com/bitcoin/transaction/5198157579094acc2a987d2ed18c68dd2d3613525e317cc9b345c839c2a54655 3Pid1xBUSptx4221C1VN7u4ztbZDRTVMhZ Wallet [askkarri@gmail.com](mailto:askkarri@gmail.com)

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains.
