### ISSUE TITLE
bc1qq2jrg2c6ye660xeyrvnkayluw6cqktr36wsqjr

### ISSUE THREAD

**Issue by Marfarita** [Blockchair/Blockchair.Support#1305]
Syki

**Comment by daria-blockchair** [comment]
> Syki

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
