### ISSUE TITLE
Bitcoin 

### ISSUE THREAD

**Issue by RazzyDM847** [Blockchair/Blockchair.Support#1309]
My coins moved out 

bc1qeugt5dl5nddv0hpq8e50gdyk5saddrze3ll0a6

**Comment by daria-blockchair** [comment]
> My coins moved out
> 
> bc1qeugt5dl5nddv0hpq8e50gdyk5saddrze3ll0a6

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
