### ISSUE TITLE
i didn't receive my bch in my wallet!

### ISSUE THREAD

**Issue by Justinyaa** [Blockchair/Blockchair.Support#1310]
it says confirmed on my address nut the platform said they dont see it .. if anyone can tell me why ? or if someone can figure it out ill pay

**Comment by Gavehenry12** [comment]
> it says confirmed on my address nut the platform said they dont see it .. if anyone can tell me why ? or if someone can figure it out ill pay

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
> it says confirmed on my address nut the platform said they dont see it .. if anyone can tell me why ? or if someone can figure it out ill pay

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. 
Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
