### ISSUE TITLE
Did not receive bits

### ISSUE THREAD

**Issue by Wsltr** [Blockchair/Blockchair.Support#1311]
99fb19b0b606750d1488896ca224bc27a28bcfd44da2d3951589a95bd4f64669 transaction hash
Please, help me!

**Comment by Wsltr** [comment]
Проблема с поступлением средств. Подтверждено, но в кошельке нет их

**Comment by Gavehenry12** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
> Проблема с поступлением средств. Подтверждено, но в кошельке нет их

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
