### ISSUE TITLE
Bitcoin transaction is 0.00

### ISSUE THREAD

**Issue by Megstalean33** [Blockchair/Blockchair.Support#1312]
My bitcon transaction is 0.00 when it's supposed to be $30.00. USD. Does that mean it has been rejected?

**Comment by daria-blockchair** [comment]
> My bitcon transaction is 0.00 when it's supposed to be $30.00. USD. Does that mean it has been rejected?

You can check the details of your transaction by searching its hash on [blockchair.com](https://blockchair.com/).
For more information, please get in touch with your wallet or exchange.

Blockchair does not provide wallet services, does not process transactions, and does not store your money.

Thank you for understanding.
