### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by Evaaabricot** [Blockchair/Blockchair.Support#1319]
Hi, I didn’t got any check ID of those cryptos. Can I have a refund on them. I’ve also contacted the Mercuryo’s service and they redirected me to you to have them back.

**Comment by daria-blockchair** [comment]
> Hi, I didn’t got any check ID of those cryptos. Can I have a refund on them. I’ve also contacted the Mercuryo’s service and they redirected me to you to have them back.

Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
