### ISSUE TITLE
Bitcoin.com whitepaper hash gives HTTP 301 error

### ISSUE THREAD

**Issue by maff1989** [Blockchair/Blockchair.Support#132]
The whitepaper link for Bitcoin.com linked at `https://blockchair.com/bitcoin/whitepaper` gives a `301` status code and `Unknown` hash.

The link to the Bitcoin.com whitepaper at the above blockchair link needs to be updated to the URL `https://www.bitcoin.com/bitcoin.pdf` in order to resolve this issue

**Comment by Har01d** [comment]
Hello,

Yes, thank you for noticing, this has already been fixed on our new front-end we’re going to make public around September 1st.

<img width="1157" alt="" src="https://user-images.githubusercontent.com/14060856/44380567-be927b80-a514-11e8-987f-a17a360fe329.png">

**Comment by Har01d** [comment]
Fixed: https://blockchair.com/bitcoin/whitepaper
