### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by Ashaft32** [Blockchair/Blockchair.Support#1322]
I did mempool blockchain and I didn't have an api I don't know what to do to collect my rewards

**Comment by Gavehenry12** [comment]
They will never reply you on here and they can’t do anything,a hacker helped me and he did it well message him on telegram https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
> I did mempool blockchain and I didn't have an api I don't know what to do to collect my rewards

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
