### ISSUE TITLE
Btc

### ISSUE THREAD

**Issue by Ceasear2023** [Blockchair/Blockchair.Support#1324]
My recipent have not yet received payment .

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact the support of the receiving wallet or exchange for more information and to find out when the funds will be credited to the account.

Thank you for understanding.

**Comment by daria-blockchair** [comment]
> My recipent have not yet received payment .

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact the support of the receiving wallet or exchange for more information and to find out when the funds will be credited to the account.

Thank you for understanding.
