### ISSUE TITLE
Date formats on Wallet Statement are inconsistent

### ISSUE THREAD

**Issue by jorng** [Blockchair/Blockchair.Support#1328]
When generating a Wallet Statement, the headings (`STATEMENT PERIOD`, `HISTORY OF TRANSACTIONS`) and date summary (at the top) show dates as `DD/MM/YYYY`, but under transactions, date/times are shown in ISO format as `YYYY-MM-DD`.  For consistency, and internationalization, the dates should be kept consistent, and always use `YYYY-MM-DD`, so as to avoid any ambiguity by using an international standard.

**Comment by daria-blockchair** [comment]
> When generating a Wallet Statement, the headings (`STATEMENT PERIOD`, `HISTORY OF TRANSACTIONS`) and date summary (at the top) show dates as `DD/MM/YYYY`, but under transactions, date/times are shown in ISO format as `YYYY-MM-DD`. For consistency, and internationalization, the dates should be kept consistent, and always use `YYYY-MM-DD`, so as to avoid any ambiguity by using an international standard.

This has been fixed. 
Thank you for noticing and reporting the issue.

**Comment by jorng** [comment]
Verified. Looks good; thanks!
