### ISSUE TITLE
Missing XRP Transactions

### ISSUE THREAD

**Issue by chrisjquinn** [Blockchair/Blockchair.Support#1329]
Looking into a few XRP transactions on blockchair vs public explorers is yielding different results. Here are a few hashes for examples:

`9336FF36E54184BA49BFD7154117E2192B4E5E1639038254E7C1ECC76087F568`
`2A5DEE661D8EBC9442E45F9D03D37BA30A144F34F22675D5F81FC3805913EFA3`
`F9F8778E8542E832382B123188CB5BE58CC51F94EA4A391C4956F57B1F0EC00A`

Using the UI on blockchair gives the result:
**"Oops! We couldn`t find “2A5DEE661D8EBC9442E45F9D03D37BA30A144F34F22675D5F81FC3805913EFA3” among the information stored on blockchains.
Recheck the phrase and try again."**

And an API response of:
```json
{
    "data": null,
    "context": {
        "code": 404,
        "source": "D",
        "results": 0,
        "error": "We don't have info for this transaction",
        "market_price_usd": 0.488001,
        "cache": {
            "live": true,
            "duration": 120,
            "since": "2023-10-11 10:53:39",
            "until": "2023-10-11 10:55:39",
            "time": null
        },
        "api": {
            "version": "2.0.95-ie",
            "last_major_update": "2022-11-07 02:00:00",
            "next_major_update": null,
            "documentation": "https://blockchair.com/api/docs",
            "notice": "Please note that on November 7th, 2022 public support for the following blockchains was dropped: EOS, Bitcoin SV"
        },
        "servers": "API4,XRP4",
        "time": 0.000659942626953125,
        "render_time": 0.007887125015258789,
        "full_time": 0.008547067642211914,
        "request_cost": 1
    }
}
```

Taking the same hashes and trying some other explorer, say [XRPScan](https://xrpscan.com/) gives details on these transactions. This is to flag a data issue, and I can try to inspect more for a pattern

**Comment by Har01d** [comment]
Right now Blockchair runs on a non-archive node, so we don't have a full history for XRPL. We're in process of upgrading to a new engine which will support larger time frames by not pruning the data (see https://blockchair.com/xrp-ledger instead of https://blockchair.com/ripple).
