### ISSUE TITLE
What time zone of dates?

### ISSUE THREAD

**Issue by xorcare** [Blockchair/Blockchair.Support#133]
What is the time zone for these dates and for others?

> address.first_seen_receiving - timestamp when the first time this address received bitcoins
address.last_seen_receiving - timestamp when the last time this address received bitcoins
address.first_seen_spending - timestamp when the first time this address sent bitcoins
address.last_seen_spending - timestamp when the last time this address sent bitcoins

**Comment by Har01d** [comment]
Hello,

All timestamps are in UTC. We’ll update the documentation to mention that for `dashboard` calls.

**Comment by xorcare** [comment]
Thanks for the clarification!
