### ISSUE TITLE
in the application you robbed me of PLN 35,000, I'm taking back what's mine because I have your wallet address in my transaction history!!

### ISSUE THREAD

**Issue by Cardi411** [Blockchair/Blockchair.Support#1330]
I did not approve this, a spammer got access to Mt blockchain wallet and hacked this email and my github account 

             in the application you robbed me of PLN 35,000, I'm taking back what's mine because I have your wallet address in my transaction history!!

￼

_Originally posted by @Marfarita in https://github.com/Blockchair/ton-deploy/issues/6#issuecomment-1751699965_

**Comment by Cardi411** [comment]
Did not authorize this

**Comment by daria-blockchair** [comment]
> I did not approve this, a spammer got access to Mt blockchain wallet and hacked this email and my github account
> 
> ```
>          in the application you robbed me of PLN 35,000, I'm taking back what's mine because I have your wallet address in my transaction history!!
> ```
> 
> ￼
> 
> _Originally posted by @Marfarita in [Blockchair/ton-deploy#6 (comment)](https://github.com/Blockchair/ton-deploy/issues/6#issuecomment-1751699965)_

Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
