### ISSUE TITLE
Add Gem Wallet as featured wallet on about page

### ISSUE THREAD

**Issue by gemcoder21** [Blockchair/Blockchair.Support#1331]
We use Blockchair as primary blockchain explorer for chains like bitcoin, doge coin and few others, it would be great to be listed on about page featuring us (https://blockchair.com/about).

Gem Wallet available on both iOS and Android platform, link listed on the website gemwallet.com. 

For logos please any from this page: https://gemwallet.com/presskit/

**Comment by daria-blockchair** [comment]
> We use Blockchair as primary blockchain explorer for chains like bitcoin, doge coin and few others, it would be great to be listed on about page featuring us (https://blockchair.com/about).
> 
> Gem Wallet available on both iOS and Android platform, link listed on the website gemwallet.com.
> 
> For logos please any from this page: https://gemwallet.com/presskit/

Hi! Thank you for reaching out. Please contact us at info@blockchair.com to further discuss this matter
