### ISSUE TITLE
Still no confirmations after using the bit accelerator…

### ISSUE THREAD

**Issue by alleycat293** [Blockchair/Blockchair.Support#1332]
Still no confirmations after using the bit accelerator…

_Originally posted by @alleycat293 in https://github.com/Blockchair/Deleted-Issues/issues/706#issuecomment-1722320850_

**Comment by nimrodotsile** [comment]
I don't know what to say about what you are saying, I don't have any of your money so please don't make me feel bad I'm so sorry for what you're talking about.

**Comment by daria-blockchair** [comment]
> I won't sign anything!!!! Because formally you are guilty of a crime and formally you will have me in your grasp - for the money you return to me I will have to buy you cryptocurrencies that I bought with my money and you think they belong to you, so you won't give me anything back because you will still have profits for the sale and for buying new ones, if I signed these documents, I would be giving myself a death sentence!!! People, you are corrupt, benefit from people's harm!!!! Remember, karma will catch up with you, when asked why you are in such a bad situation, when that time comes, remember about me, what you did to me and what you wanted to do to me consciously and with full premeditation. Karma is a female dog, she doesn't need an address to hold you accountable for every wrong!!

Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
