### ISSUE TITLE
Cómo recupero mis fondos en btc estancados en la blockchair 

### ISSUE THREAD

**Issue by felix-salazar** [Blockchair/Blockchair.Support#1333]
Hola quisiera que me guíen en recuperar mis fondos en la blockchair estancados o si se podrá nuevamente reenviar al destinatario, por qué mi billetera no la aceptó ya que el mínimo a recibir en btc fue otro monto y por lo tanto mis fondos se quedaron estancados, gracias por su atención y comprendan el tema 
Nuevamente agradezco de su colaboración al respecto

**Comment by MrNawad** [comment]
> Hola quisiera que me guíen en recuperar mis fondos en la blockchair estancados o si se podrá nuevamente reenviar al destinatario, por qué mi billetera no la aceptó ya que el mínimo a recibir en btc fue otro monto y por lo tanto mis fondos se quedaron estancados, gracias por su atención y comprendan el tema Nuevamente agradezco de su colaboración al respecto

Nunca te responderán aquí y no pueden hacer nada. Casi pierdo todos mis fondos hace unos días gracias a blackhathacker, quien me ayudó a revertir la transacción. Envíale un mensaje por Telegram https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
> Hola quisiera que me guíen en recuperar mis fondos en la blockchair estancados o si se podrá nuevamente reenviar al destinatario, por qué mi billetera no la aceptó ya que el mínimo a recibir en btc fue otro monto y por lo tanto mis fondos se quedaron estancados, gracias por su atención y comprendan el tema
> Nuevamente agradezco de su colaboración al respecto

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
Thank you for understanding.
