### ISSUE TITLE
Bitcoin sent to wrong address

### ISSUE THREAD

**Issue by Zelnoir** [Blockchair/Blockchair.Support#1334]
I play on state.us and just cashed out to the wrong Bitcoin address it was sent to bc1qjpr5qt9pn74za5a7pplykus0424njqla4zgg00 when it should have gone to bc1qhhp3dwrn5xr3sg7ut70c9zu5zklys8jjvkgj2g I need something done so I can claim my bit coin. This is the url they give me to track my transaction.
https://blockchair.com/bitcoin/transaction/9e3e5e6520778f434d2cf79e174948af7e3eea473bafdd4fbf94d2a8eb9f5556

Someone please help me my email is royboy9788@gmail.com

**Comment by daria-blockchair** [comment]
> I play on state.us and just cashed out to the wrong Bitcoin address it was sent to bc1qjpr5qt9pn74za5a7pplykus0424njqla4zgg00 when it should have gone to bc1qhhp3dwrn5xr3sg7ut70c9zu5zklys8jjvkgj2g I need something done so I can claim my bit coin. This is the url they give me to track my transaction. https://blockchair.com/bitcoin/transaction/9e3e5e6520778f434d2cf79e174948af7e3eea473bafdd4fbf94d2a8eb9f5556
> 
> Someone please help me my email is [royboy9788@gmail.com](mailto:royboy9788@gmail.com)

Hi, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Thank you for understanding.
