### ISSUE TITLE
Bitcoin issues 

### ISSUE THREAD

**Issue by potter2597** [Blockchair/Blockchair.Support#1335]
Please mistakenly send BCH to Bitcoin wallet please help

**Comment by daria-blockchair** [comment]
> Please mistakenly send BCH to Bitcoin wallet please help
Hi, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Thank you for understanding.
