### ISSUE TITLE
Failed swap & funds doesn't revert 

### ISSUE THREAD

**Issue by Sub7iam** [Blockchair/Blockchair.Support#1336]
Hello 

4 days ago i swaped doge to ltc after 45 minutes swap goes fail but my doges doesn't back to wallet , i try to contact and report trust wallet support team but they didn't answer me after 3 days.
Transaction hash goes to error 404 and i cant see transaction in blockchair.
would you mind telling me what iv to do please

Hash: 
https://blockchair.com/dogecoin/transaction/0f48bb5bcee306982ccc65cc720deaa3ae2eaf7ebdd048d5ccf66384f7f25b90?from=trustwallet

Regards

![AB70C34B-220F-4C41-94BB-0880F72F1432](https://github.com/Blockchair/Blockchair.Support/assets/148655615/14404740-e588-41ba-b0e7-05d94ed9272f)
![0BFBE7BF-70A5-43A1-BCF0-1D67131199C8](https://github.com/Blockchair/Blockchair.Support/assets/148655615/cafb3e80-1c55-4183-9dc7-a46dc7903951)
![F7478F37-43BC-47A0-AB8D-B8B3B6F43413](https://github.com/Blockchair/Blockchair.Support/assets/148655615/a63d1e71-9f02-43db-a4d8-3e7b36f4da0e)

**Comment by MrNawad** [comment]
> Hello
> 
> 4 days ago i swaped doge to ltc after 45 minutes swap goes fail but my doges doesn't back to wallet , i try to contact and report trust wallet support team but they didn't answer me after 3 days. Transaction hash goes to error 404 and i cant see transaction in blockchair. would you mind telling me what iv to do please
> 
> Hash: https://blockchair.com/dogecoin/transaction/0f48bb5bcee306982ccc65cc720deaa3ae2eaf7ebdd048d5ccf66384f7f25b90?from=trustwallet
> 
> Regards
> 
> ![AB70C34B-220F-4C41-94BB-0880F72F1432](https://user-images.githubusercontent.com/148655615/277132236-14404740-e588-41ba-b0e7-05d94ed9272f.png) ![0BFBE7BF-70A5-43A1-BCF0-1D67131199C8](https://user-images.githubusercontent.com/148655615/277132238-cafb3e80-1c55-4183-9dc7-a46dc7903951.png) ![F7478F37-43BC-47A0-AB8D-B8B3B6F43413](https://user-images.githubusercontent.com/148655615/277132241-a63d1e71-9f02-43db-a4d8-3e7b36f4da0e.png)

Believe me or not only a fellow hacker can help you get this back same thing happened to me I lost almost 7btc but thanks to blackhathacker he helped me recover them message his telegram https://t.me/Blackhathacker110

**Comment by Sub7iam** [comment]
😅

**Comment by daria-blockchair** [comment]
Hi @Sub7iam, 
Unfortunately, we are not able to help get your funds back. Please reach out to your wallet for further assistance.
