### ISSUE TITLE
My deposits are pending or what?

### ISSUE THREAD

**Issue by mbarkimed** [Blockchair/Blockchair.Support#1339]
Hello, I made 3 deposits on the “100 Dog” website at a value of 30 Dog for each deposit, but I was surprised that 2 deposits did not enter my account on the site. I also noticed that the two deposits were moved to your site “Blockshare” under the title
https://blockchair.com/dogecoin/transaction/80a6f5d70f1843c080b4cff0a81a0a608d2147d305978b9f004ba3ea2a2b8255
https://blockchair.com/dogecoin/transaction/158bb1755a9c3c9bdc620ebab1192c3436161c7a03a9a151e3491a15b7bb941a
https://blockchair.com/dogecoin/transaction/78fcab4ead75622e7b996f9feb73f56e45551b90b8d96408bcacce3c9ec93e55
  I do not know what exactly happened, knowing that the “100 Dog” website was the one that gave me these addresses, and where the withdrawal from my “Foast Pay” wallet was proven, so I ask you to complete the deposit process for the benefit of the “100 Dog” website or recover it.
Thanks

**Comment by daria-blockchair** [comment]
> Hello, I made 3 deposits on the “100 Dog” website at a value of 30 Dog for each deposit, but I was surprised that 2 deposits did not enter my account on the site. I also noticed that the two deposits were moved to your site “Blockshare” under the title https://blockchair.com/dogecoin/transaction/80a6f5d70f1843c080b4cff0a81a0a608d2147d305978b9f004ba3ea2a2b8255 https://blockchair.com/dogecoin/transaction/158bb1755a9c3c9bdc620ebab1192c3436161c7a03a9a151e3491a15b7bb941a https://blockchair.com/dogecoin/transaction/78fcab4ead75622e7b996f9feb73f56e45551b90b8d96408bcacce3c9ec93e55 I do not know what exactly happened, knowing that the “100 Dog” website was the one that gave me these addresses, and where the withdrawal from my “Foast Pay” wallet was proven, so I ask you to complete the deposit process for the benefit of the “100 Dog” website or recover it. Thanks

Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
