### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hrast83** [Blockchair/Blockchair.Support#1341]
How to acces my account? https://blockchair.com/

**Comment by daria-blockchair** [comment]
> How to acces my account? https://blockchair.com/

Hi, 

At Blockchair we provide insight into data that is stored in blockchains. You can see the information about your transaction or address on our website. However, your money and assets are not stored on Blockchair. We do not provide wallet services and do not process transactions.
For more information about your account, please contact your wallet or exchange. 

Thank you for understanding.
