### ISSUE TITLE
Stellar account transactions pagination

### ISSUE THREAD

**Issue by azizfcb** [Blockchair/Blockchair.Support#1346]
Hi, I'm using this endpoint `/raw/account/{STELLAR_WALLET}/transactions=true&trades=true&operations=true&payments=true` to query for transactions. It seems that the limit is 200 items per type (trade, payment etc) and there's no way to query past this (using some sort of cursor, offset or a date timestamp...)

Could you please check this and get back to me. Thanks

**Comment by Har01d** [comment]
At the moment, we don't provide full historical data for Stellar. We're looking into if it's possible to have more history with the new engine we'll be using for Stellar (https://github.com/3xplcom/Core/pull/61). Thanks!
