### ISSUE TITLE
Btc

### ISSUE THREAD

**Issue by Polo1212** [Blockchair/Blockchair.Support#1348]
3AMTPfqALk1DTaeh8UusYZ2UQgzB1QU1RS

**Comment by Polo1212** [comment]
Need to get this balance to my other account

**Comment by daria-blockchair** [comment]
> Need to get this balance to my other account

Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money.

Please contact the support of your wallet or exchange for more information and further assistance.

Thank you for understanding.
