### ISSUE TITLE
BTC  72hrs still not get confirm

### ISSUE THREAD

**Issue by krysthn** [Blockchair/Blockchair.Support#1350]
Any suggestion or option  to do to get my transaction get confirm...

**Comment by Kjamess** [comment]
> Any suggestion or option to do to get my transaction get confirm...

They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
> Any suggestion or option to do to get my transaction get confirm...

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee. You can contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

For more information about why your transaction is being processed slowly and what you can do to speed up your transaction, please refer to the [FAQ](https://blockchair.com/faq/why):https://blockchair.com/faq/why.

For further assistance, please contact your wallet or exchange.
