### ISSUE TITLE
poyraz can

### ISSUE THREAD

**Issue by poyrazcan36** [Blockchair/Blockchair.Support#1352]
2023-11-03 09:50:20
2764
Dogecoin
0
14.1 DOGE
Paid
[DMv9M1M9ER3aMZP7TeR2VSKmDz89LA...](https://blockchair.com/dogecoin/address/DMv9M1M9ER3aMZP7TeR2VSKmDz89LAQieq)

The amount in question has not been deposited to me, I would appreciate it if you could check it. money deposited by coin payu

my doge account

DMv9M1M9ER3aMZP7TeR2VSKmDz89LAQieq

**Comment by poyrazcan36** [comment]
ne zaman düzelecek

**Comment by poyrazcan36** [comment]
2023-11-03 09:50:20
2764
dogecoin
0
14.1 DOGE
Paid
DMv9M1M9ER3aMZP7TeR2VSKmDz89LA...

The amount in question was not deposited to me, I would appreciate it if you could check it. money deposited with coin payu

my doge account

DMv9M1M9ER3aMZP7TeR2VSKmDz89LAQieq

**Comment by daria-blockchair** [comment]
> ne zaman düzelecek

Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
