### ISSUE TITLE
I paid my admin fees 

### ISSUE THREAD

**Issue by AngelaLove4** [Blockchair/Blockchair.Support#1353]
I paid my admin fees for 177 bitcoin, and I still have not received my withdrawal.

**Comment by daria-blockchair** [comment]
> I paid my admin fees for 177 bitcoin, and I still have not received my withdrawal.

Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
