### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by EgorGlebov** [Blockchair/Blockchair.Support#1357]
https://blockchair.com/bitcoin/transaction/f2607285942132b20a3ec04227b50ccc5f1d7d1cca0b7f3909067318cc17883a

https://www.blockchain.com/ru/explorer/transactions/btc/f2607285942132b20a3ec04227b50ccc5f1d7d1cca0b7f3909067318cc17883a

Hello. Can you please help me with this question? The transaction is not visible to you, but is displayed on the blockchain.com website. What could be the error and on what basis do you display transactions?

**Comment by iruga55** [comment]
same problem with me

**Comment by leodanys81** [comment]
No

**Comment by Har01d** [comment]
Hello, we don't store transactions which didn't get into a block forever. This particular transaction hasn't got into a block.
