### ISSUE TITLE
Transaction issues 

### ISSUE THREAD

**Issue by SlimShady26** [Blockchair/Blockchair.Support#1358]
Good morning sir/ma'am.
I made transaction on 13th/14th to my wallet address ($70) and till now is yet to appear on my wallet balance, please sir / ma'am what could be the problem. (wallet address : bc1qv9z5gtna4p59ydsf6p7qe7f53zygfuen9vkvvu).
Thanks.

**Comment by emmycs** [comment]
I made a transaction on 11th to my wallet address ($374) and it’s still on pending since then please can you help me sort it out as the money is my school fees 
Address: bc1q8cgwwzzjx0lgsv4m397t7x7tkvx05jzca2h5me

**Comment by daria-blockchair** [comment]
Hi, 

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee. (You can find the detailed information [here]( https://blockchair.com/faq/why))

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed.

To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block faster.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
