### ISSUE TITLE
Биткоины не пришли на счёт в течении трёх дней!

### ISSUE THREAD

**Issue by Diman007-ctrl** [Blockchair/Blockchair.Support#1359]
Добрый день! Три дня назад отправил биткоины до сих пор не пришли. Три дня это очень долго. Помогите пожалуйста мне в решении этого вопроса!!! Подтвердите пожалуйста транзакцию!!!
Ссылка для отслеживания транзакции : https://sochain.com/tx/BTC/ed8e927e142c8c437f761af909721305b717d064641be70b1619cba10308080e

Получаете: 0.000844 Bitcoin BTC , На счет: bc1qfnma6nhj5xs4ep7s4exrjkcv2muhwrup2yzu2q

**Comment by daria-blockchair** [comment]
> ed8e927e142c8c437f761af909721305b717d064641be70b1619cba10308080e

It appear that the transaction is confirmed:
https://blockchair.com/bitcoin/transaction/ed8e927e142c8c437f761af909721305b717d064641be70b1619cba10308080e

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee. (More detailed information can be found [here](https://blockchair.com/faq/why))

To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
