### ISSUE TITLE
Transaction issue 

### ISSUE THREAD

**Issue by jashley83** [Blockchair/Blockchair.Support#1360]
I sent $250 from one Bitcoin address to another 10 days ago on 11/08, it is still unconfirmed. Can someone please advise on what to do. I needed the $ 9 days ago now. Everything I do does nothing to move it along and I'm tired of hearing be patient, thought this was the future of monetary transacting. It feels more like it's the one on it's way out. I think this will be my last time using crypto. Any help would be greatly appreciated. Thank you

**Comment by daria-blockchair** [comment]
> I sent $250 from one Bitcoin address to another 10 days ago on 11/08, it is still unconfirmed. Can someone please advise on what to do. I needed the $ 9 days ago now. Everything I do does nothing to move it along and I'm tired of hearing be patient, thought this was the future of monetary transacting. It feels more like it's the one on it's way out. I think this will be my last time using crypto. Any help would be greatly appreciated. Thank you

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed.

To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
Please find more information [here](https://blockchair.com/faq/why): https://blockchair.com/faq/why
