### ISSUE TITLE
چرا

### ISSUE THREAD

**Issue by mojmoj204** [Blockchair/Blockchair.Support#1361]
من میخواهم در مورد کارمزد تراکنش بیت کوین شکایت کنم

**Comment by mojmoj204** [comment]
Hello, I made a transaction in the Konomi wallet, which showed me the fee amount of 6 dollars when the fee was displayed, but after it was sent, the transaction fee was deducted from me in the amount of 50 dollars. And this is the second time that this problem has happened to me and I am complaining about this transaction and the amount of the fee

**Comment by daria-blockchair** [comment]
> من میخواهم در مورد کارمزد تراکنش بیت کوین شکایت کنم

Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 

Please contact the support of your wallet for more information and to discuss the issue. 

Thank you for understanding.
