### ISSUE TITLE
BTC to Dogecoin atomic wallet exchange: no dogecoin received in gui

### ISSUE THREAD

**Issue by charliebluehawk** [Blockchair/Blockchair.Support#1362]
Using atomic wallet, I exchanged US$ 1,100 btc for dogecoin.
The btc went out.
The dogecoin never arrived.
The hash says that I received the dogecoin.
The support at atomic wallet are useless.
The dogecoin never appeared in the GUI of atomic wallet.
Hash:
https://dogecoin.atomicwallet.io/tx/94b9074edafda35c4b5f35697beaf36bb655747fba426337e241a2f01fcc7254
Any help in tracking down these missing dogecoin would be appreciated.

**Comment by daria-blockchair** [comment]
> Any help in tracking down these missing dogecoin would be appreciated.

We're sorry to hear that you're experiencing issues.

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately.

Based on the blockchain data, it appears that the transaction you provided was successfully confirmed and included in block 4957239: https://blockchair.com/dogecoin/transaction/94b9074edafda35c4b5f35697beaf36bb655747fba426337e241a2f01fcc7254

If you're experiencing issues with Atomic Wallet not displaying the received Dogecoin, we would recommend reaching out to the support team of Atomic Wallet for further assistance. They should be able to investigate the issue and help you track down your missing Dogecoin.

Thank you for understanding.
