### ISSUE TITLE
My Bitcoin was transferred from Cwallet to this wallet bc1qg65ef6u054weqjz8nzwdrkqmrhmsks0vfttmtn how can recover it

### ISSUE THREAD

**Issue by barbaraerb63** [Blockchair/Blockchair.Support#1363]

**Comment by daria-blockchair** [comment]
> _No description provided._

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains and, unfortunately, are not able to help get your money back.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
