### ISSUE TITLE
Recognize "Northern Bitcoin" BCH blocks from Coinbase

### ISSUE THREAD

**Issue by alican** [Blockchair/Blockchair.Support#137]
Hi, 
our new pool is started and we have already 2% market share and more in the next week.
We're using Blockchair daily and will be happy when our pool is recognize properly. We are including in all our blocks the string /Northern Bitcoin/ in the Coinbase.

**Comment by Har01d** [comment]
Hello,

Thanks for the request and sorry about the wait, adding a new pool requires manual repopulating of one of our databases. We've made some amendments to our engine to make this process faster in the future.

https://blockchair.com/bitcoin-cash/blocks?q=guessed_miner(Northern%20Bitcoin)#

Thanks for using Blockchair!
