### ISSUE TITLE
Fraude com o meu dinheiro CRIPTMOEDA my e-mail is mt-vitaminar@hotmail.com

### ISSUE THREAD

**Issue by DrAuto73** [Blockchair/Blockchair.Support#1372]
bc1qk6kvx96vafhrtl9fg2qvt0racg8tmtz6spjm56 e esta carteira bc1qws8yeyfxzykuq7tevwwxezyv3ad99emlyy9uls sao minhas naoconsigo ter acessoaelas e alguem ANDA desiar dinherio da carteira tive que colocar mais 22.500€ de cauçãoe tambem naosei delesagradeçoqueme deolam omeudinheiroquenototal 91.700.€que possocomproar 
[Agreement2.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642689/Agreement2.pdf)
[AML Explanationpdf.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642690/AML.Explanationpdf.pdf)
[Comprovativo_TransferenciaIBAN (1).pdf](https://github.com/Blockchair/Blockchair.Support/files/13642691/Comprovativo_TransferenciaIBAN.1.pdf)
[Comprovativo_TransferenciaIBAN (2).pdf](https://github.com/Blockchair/Blockchair.Support/files/13642692/Comprovativo_TransferenciaIBAN.2.pdf)
[Comprovativo_TransferenciaIBAN (3).pdf](https://github.com/Blockchair/Blockchair.Support/files/13642693/Comprovativo_TransferenciaIBAN.3.pdf)
[Comprovativo_TransferenciaIBAN (4).pdf](https://github.com/Blockchair/Blockchair.Support/files/13642694/Comprovativo_TransferenciaIBAN.4.pdf)
[Comprovativo_TransferenciaIBAN.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642695/Comprovativo_TransferenciaIBAN.pdf)
[Conversion Bill,Luis Marques1610.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642696/Conversion.Bill.Luis.Marques1610.pdf)
[Conversion Bill,Luis MarquesDone2.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642697/Conversion.Bill.Luis.MarquesDone2.pdf)
[Scan_david.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642698/Scan_david.pdf)
[Tax document Luis Marques.. (1).pdf](https://github.com/Blockchair/Blockchair.Support/files/13642699/Tax.document.Luis.Marques.1.pdf)
[Tax document Luis Marques..2.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642700/Tax.document.Luis.Marques.2.pdf)
[Tax document Luis Marques2.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642701/Tax.document.Luis.Marques2.pdf)
![Trading asset records](https://github.com/Blockchair/Blockchair.Support/assets/152528430/a5729e8a-187d-4db1-8b3b-26a19fc6f14f)
[wallet statement! (1)2.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642702/wallet.statement.1.2.pdf)
[wallet statement! (2).pdf](https://github.com/Blockchair/Blockchair.Support/files/13642703/wallet.statement.2.pdf)
[wallet statement!.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642704/wallet.statement.pdf)
![WhatsApp Image 2023-10-26 at 17 48 38](https://github.com/Blockchair/Blockchair.Support/assets/152528430/5a3faef4-7327-4dc5-891a-d6f646f27538)
![WhatsApp Image 2023-10-30 at 16 29 45](https://github.com/Blockchair/Blockchair.Support/assets/152528430/2a61dcaa-7d91-4fcc-9636-224cccd8aea5)
![WhatsApp Image 2023-10-31 at 10 18 55 (1)](https://github.com/Blockchair/Blockchair.Support/assets/152528430/0d15aca1-4851-4602-b467-17bf76c6ba53)
![WhatsApp Image 2023-10-31 at 10 18 55](https://github.com/Blockchair/Blockchair.Support/assets/152528430/7ad9755b-6add-47c2-a60d-6100585baea9)
![WhatsApp Image 2023-10-31 at 13 20 55](https://github.com/Blockchair/Blockchair.Support/assets/152528430/18885087-a8e0-421e-8d3f-bd7dd037ee8e)
[Wire Pending Luis Marques1610.pdf](https://github.com/Blockchair/Blockchair.Support/files/13642705/Wire.Pending.Luis.Marques1610.pdf)
 E aqui esta todo dinheiroque transferi naonao o consigoterde olta pela burlaque esse senhor fez DAVID A GEORGE agradeço que bloquei a carteira para que esse dinheiro me seja devolido ,mais informoque interpool e policia judiciaria portugusa esta omoaso nas maos . aguradouma resposta vossa  obrigado Luis Miguel Braga Marques

**Comment by daria-blockchair** [comment]
Dear @DrAuto73, 

We are sorry to hear that you've been scammed. Unfortunately, we are not able to help you. 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. 

Thank you for understanding.
