### ISSUE TITLE
My BTC send has been in pending for more then 15 hours.   My btc has fresher since funds were sent and too it off it mentions my privacy is low, but that wouldn't effect right?  I need costumer support please

### ISSUE THREAD

**Issue by Savages101** [Blockchair/Blockchair.Support#1373]

**Comment by daria-blockchair** [comment]
> _No description provided._

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, and sometimes several days.

We understand that this is annoying, but Blockchair does not process transactions, so we cannot help you speed up your transaction. You should contact your wallet or exchange to receive information about how to increase your transaction fee.
