### ISSUE TITLE
WHERE IS MY WITHDRAWAL FROM MY GAME I WON

### ISSUE THREAD

**Issue by Arich9696** [Blockchair/Blockchair.Support#1374]
So on 12/13/2023 I withdrew 100 dollars from my gambling website ignitioncasino which I always do and always withdraw it the same way nothing different and it hahakkt arrives to my trust wallet within 2 hours at most 3 hours it has been going on 2 days (48 hours est) anything  at 5 am tonight est and I haven’t revert any of the 100 US dollar at all I do not know what is going on I check on the blockchair and it says I have 0 of 6 confirmation and I should raise my transaction fee which I don’t know how to seeing that I never had to do it before I just click the withdrawal button on my website I copy the trust wallet bitcoin address and it does it all by itself except this time and I am starting to get aggravated with this I contacted ignition casino. They said they cannot do nothing about it saying that it is already pending on the block chair to contact you guys so here I am. I want my hundred US dollars. This is ridiculous. I want it I want it it’s mine. I was going to get my wives Christmas present order it and it would’ve been here December 24 with the money things that I unemployed and this is helping me a lot but can’t do that now cause I’m gonna be here till the 26th so this is causing major inconvenience in my life where is my money ?.

**Comment by willthabeast** [comment]
I have the same problem rite now I'm goin in 28 hours with the confirmations after I was forced to do a reversal on my deposit.. unfortunately I did the original transfer thru cash app and I was warned after I did it that to never do it thru Cash app.. thanks everyone but you all was an hr late.. now my 101 dollers is s just sitting there.. I need that money but it says that if I have the arf enabled I can simply restart my re VC srsal with a erd party wallet.. well the option in mine says it's not enabled.. and it says itlf it's not enabled then im better roff just waiting on it to get kicked off the "merpal "I guess the merpal is sone sort of graveyard of untouched transactions that's where they go when the fee is to small and no body ehabrs to touch it .. is there anyone out there that can give me any kinda reassurance about my money.. or an I gonna get robbed by blockchain.. help

**Comment by Arich9696** [comment]
I am still waiting on mine 0 confirmation

**Comment by Arich9696** [comment]
3 days

**Comment by Arich9696** [comment]
Just received mine

**Comment by willthabeast** [comment]
Really . U got yours ?

**Comment by daria-blockchair** [comment]
Hello,

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

Thank you for understanding.
