### ISSUE TITLE
Delayed transaction for over 15 hours

### ISSUE THREAD

**Issue by Fatality079** [Blockchair/Blockchair.Support#1376]
Please approve my transaction it has a decent processing fee 
I really need it

**Comment by daria-blockchair** [comment]
@Fatality079 Hello,

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

Thank you for understanding.
