### ISSUE TITLE
Failing to email Support

### ISSUE THREAD

**Issue by Yareaj** [Blockchair/Blockchair.Support#1378]
I've been trying to contact support at info@blockchair.com however my email is being rejected for potential spam, which I believe there's no reason for given that I'm just trying to recover a lost API key.

Is there any other contact method I can use then?

**Comment by Gracefuly** [comment]
They won’t reply you on here same thing happened to me Blackhathacker110 on telegram helped me https://t.me/Blackhathacker110

**Comment by Har01d** [comment]
Hi @Yareaj,

You can contact us via Telegram: https://t.me/blockchair or try another mail server.

Thanks!

**Comment by Yareaj** [comment]
Thanks, I was able to contact using a different server :D
