### ISSUE TITLE
Why is my transaction is not confirmed

### ISSUE THREAD

**Issue by Johnsuton1** [Blockchair/Blockchair.Support#1379]
It has been sitting there for four days now and I want to know why? And why don't I see it saying pending where im supposed to be receiving it at but it's saying waiting confirmation here?
![Screenshot_20231215-024822](https://github.com/Blockchair/Blockchair.Support/assets/153977747/e23d12b3-8844-4700-8410-92d7078e714e)
![Screenshot_20231216-015459](https://github.com/Blockchair/Blockchair.Support/assets/153977747/fe014549-bf2e-489d-95fe-7e583041cc05)
![Screenshot_20231216-015530](https://github.com/Blockchair/Blockchair.Support/assets/153977747/27c0f4bd-c601-493e-af7e-6b0c98ed7ea4)

**Comment by zhhz40** [comment]
I have the same issue

**Comment by Gracefuly** [comment]
> It has been sitting there for four days now and I want to know why? And why don't I see it saying pending where im supposed to be receiving it at but it's saying waiting confirmation here?
> ![Screenshot_20231215-024822](https://private-user-images.githubusercontent.com/153977747/290977737-e23d12b3-8844-4700-8410-92d7078e714e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjUyMzIsIm5iZiI6MTcwMjg2NDkzMiwicGF0aCI6Ii8xNTM5Nzc3NDcvMjkwOTc3NzM3LWUyM2QxMmIzLTg4NDQtNDcwMC04NDEwLTkyZDcwNzhlNzE0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwMjAyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGEwYTZiMWIzYjliZjg0MWY2NmQ5NmNmMTQ2ZTUxM2I5OTI5ZTIzYjYxZTI3MTZlMzlkYzQ4ZDZjMTZjNjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oawOSl7hoOq0AVaY6iNZhTgZtIhedzSiD1ysbhCKff0)
> ![Screenshot_20231216-015459](https://private-user-images.githubusercontent.com/153977747/290978005-fe014549-bf2e-489d-95fe-7e583041cc05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjUyMzIsIm5iZiI6MTcwMjg2NDkzMiwicGF0aCI6Ii8xNTM5Nzc3NDcvMjkwOTc4MDA1LWZlMDE0NTQ5LWJmMmUtNDg5ZC05NWZlLTdlNTgzMDQxY2MwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwMjAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDc4OTMwY2FmNjM0ZDk0ODNjZDZjNjA2YjAxZjBhMmRjMGQ2MzI3NGNiZDEyN2I0ODVmODk3OWVkYWM0N2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6nXA9FK6THbU9Xv9sSvo9Tt71gLAA00an49siao38F4)
> ![Screenshot_20231216-015530](https://private-user-images.githubusercontent.com/153977747/290978017-27c0f4bd-c601-493e-af7e-6b0c98ed7ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjUyMzIsIm5iZiI6MTcwMjg2NDkzMiwicGF0aCI6Ii8xNTM5Nzc3NDcvMjkwOTc4MDE3LTI3YzBmNGJkLWM2MDEtNDkzZS1hZjdlLTZiMGM5OGVkN2VhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwMjAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDRhZWQ5MjE1YjViYWI5ZTk1NjNjNWQxNTdiZTcyNDFkMTcxOGZmMzhkNjJhY2Y4ODJmY2RiNGU3NGIzYmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZpKHL4IcJkPewqwEHYX8ntf_hwuSOBO0DrihHhPJSX0)

They won’t reply you on here same thing happened to me Blackhathacker110 on telegram helped me https://t.me/Blackhathacker110

**Comment by scott3691** [comment]
It’s been over a week and I won $380 using stake.us app and I sent bitcoin to cash app and it got rejected and I was told to reverse the payment and I did and nothing has happened I contacted cash app and they said it went through on there end but now it’s stuck in blockchain I would like to know when I’m going to receive my money I play 3-4 times a week and I win couple hundred every time I play and I never had any issues what will it take to resolve this the address is bbf6fae7abd3f0530f49092a376b3816579172a557e14606a8bb89885746c64e and  my email is scottcollamore3691@gmail.com I would appreciate it if this gets taken care of asap I have Xmas to deal with and I got 5 kids and a grand son would be very helpful to get that money I won fair and square

**Comment by daria-blockchair** [comment]
@Johnsuton1 Hello,

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

Thank you for understanding.
