### ISSUE TITLE
Still holding my transaction in 0-6 confirmed.. 4th day 101 bucks

### ISSUE THREAD

**Issue by willthabeast** [Blockchair/Blockchair.Support#1380]
4th day now holding 101.00 bucks from my kids Christmas 4 days.. this is insane.. someone please help me out .. I am a single father of to ruda ass teenagers that think if they don't get a certain thing under the tree that the world will literally stop spinning and they will pass away.. HELP ME PLZ PEOPLE

**Comment by daria-blockchair** [comment]
@willthabeast Hello,

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

Thank you for understanding.
