### ISSUE TITLE
Not one confirmation in almost 7 days what the heck

### ISSUE THREAD

**Issue by pogqueen68** [Blockchair/Blockchair.Support#1385]
I really like to know what is going on and why my Bitcoin is not getting confirmed

**Comment by Thebeast44** [comment]
Donot chek

**Comment by daria-blockchair** [comment]
> I really like to know what is going on and why my Bitcoin is not getting confirmed

Hello,

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

Thank you for understanding.
