### ISSUE TITLE
Confirmation en attente

### ISSUE THREAD

**Issue by Gigatony71** [Blockchair/Blockchair.Support#1386]
Bonjour, j'ai fais un transfert et il me dis qu'il manque 1 confirmation je ne sais pas ce que c'est pouvez-vous m'expliquer merci.

**Comment by Thebeast44** [comment]
Uyu

**Comment by daria-blockchair** [comment]
> Bonjour, j'ai fais un transfert et il me dis qu'il manque 1 confirmation je ne sais pas ce que c'est pouvez-vous m'expliquer merci.

Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
