### ISSUE TITLE
Transfer stuck for 2 weeks

### ISSUE THREAD

**Issue by Lomaloma24** [Blockchair/Blockchair.Support#1388]
I need help with a transfer

**Comment by daria-blockchair** [comment]
Hi @Lomaloma24, 

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee. Some wallets support functionality to increase the transaction fee. Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
