### ISSUE TITLE
Cancel transaction 

### ISSUE THREAD

**Issue by Jaemax1** [Blockchair/Blockchair.Support#1400]
I want to cancel my transaction and send to another wallet 41edaa5901d112216083edc935b268f0faffa0020ce6661e082e5f2b81e01a04

**Comment by Vanciugach** [comment]
?ù

**Comment by Daur1928** [comment]
I want to cancel my transaction and send to another wallet

**Comment by Jaemax1** [comment]
Yes I want to cancel my transaction
