### ISSUE TITLE
ccd9615efa1f28e14eadedaab05cdba191d58efdeccaf599b05aa7a4516815d4

### ISSUE THREAD

**Issue by 3bendi** [Blockchair/Blockchair.Support#1401]

**Comment by daria-blockchair** [comment]
The transaction is confirmed: https://blockchair.com/litecoin/transaction/ccd9615efa1f28e14eadedaab05cdba191d58efdeccaf599b05aa7a4516815d4

For more information please contact your wallet or exchange.
