### ISSUE TITLE
Somebody please help me with this transaction 

### ISSUE THREAD

**Issue by BRHODESMANE** [Blockchair/Blockchair.Support#1402]
047f25eacf03ebd2701548def8c73f0841b7642792617b02b73b6e6d1b96e71f

**Comment by BRHODESMANE** [comment]
047f25eacf03ebd2701548def8c73f0841b7642792617b02b73b6e6d1b96e71f

**Comment by BRHODESMANE** [comment]
[047f25eacf03ebd2701548def8c73f0841b7642792617b02b73b6e6d1b96e71f.pdf](https://github.com/Blockchair/Blockchair.Support/files/13933786/047f25eacf03ebd2701548def8c73f0841b7642792617b02b73b6e6d1b96e71f.pdf)
[bc1qsyqfz77006pwv7g3e2mf04w5u4qmqsufzx04qy_en_usd_2023-11-29_2024-01-09_1.pdf](https://github.com/Blockchair/Blockchair.Support/files/13933787/bc1qsyqfz77006pwv7g3e2mf04w5u4qmqsufzx04qy_en_usd_2023-11-29_2024-01-09_1.pdf)

**Comment by Nolandf** [comment]
Contact the support team

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
