### ISSUE TITLE
Issue with a TX showing "script" 

### ISSUE THREAD

**Issue by DunningKrugR** [Blockchair/Blockchair.Support#1404]
https://blockchair.com/bitcoin/transaction/d5fbae522182d8e3db968ffcda4fd1fa54bfac718280ad67408e52860b1fefbdÍ
<img width="1016" alt="Screenshot 2024-01-19 at 3 40 24 PM" src="https://github.com/Blockchair/Blockchair.Support/assets/82776982/11ff5743-c9ec-4db1-aafc-0486d280d8fe">

The TX is showing "script" and not showing correct data. 

Same TX on mempool: https://mempool.space/tx/d5fbae522182d8e3db968ffcda4fd1fa54bfac718280ad67408e52860b1fefbd

**Comment by Har01d** [comment]
This transaction actually comes from 3xpl, not from Blockchair as we're currently using 3xpl for transactions which are not present on Blockchair's mempool. Most probably this bug is due to different node versions, we'll look into it.

**Comment by Har01d** [comment]
This has been fixed a while back, thanks for noticing!
