### ISSUE TITLE
Bitcoin transactions still pending after 8 days 

### ISSUE THREAD

**Issue by baileysavage21** [Blockchair/Blockchair.Support#1409]
Someone please help have been waiting on this transaction for over a week now made this transaction last Friday it keeps getting confirmed every morning these last few days then 5 mins later it’s unconfirmed again I even have screen shots of the confirmation please help. 
5aaab558c0812f94fb79b49253cb09e7590d84e39159abefeb21a70e4a1b13c1

**Comment by daria-blockchair** [comment]
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
