### ISSUE TITLE
hi , i forget the api key with pay-as-you-go plan. can you send me another email

### ISSUE THREAD

**Issue by JackWoodN** [Blockchair/Blockchair.Support#1419]
i dont save the api key. when i visit the https://transactions.sendowl.com/orders/137171335/download/1a8a7d5225965fc2665bd742c04607e1 , i found i cant download it that can only download once. can you send me again.

my order id  : 0137171335 

Thanks for ordering from us. This email confirms your order of the following items:

[Blockchair.com](http://blockchair.com/) API key (pay-as-you-go plan): $10 for 10.000 requests, valid for 365 days x 1

Your Order ID is 0137171335 and your payment has now cleared. A receipt has been emailed to you separately.

You can download your digital products from https://transactions.sendowl.com/orders/137171335/download/1a8a7d5225965fc2665bd742c04607e1  In order to use some of the products in this order you will require the following license keys:

**Comment by Har01d** [comment]
Hello, we'll send you an e-mail. Thanks! Please feel free to reopen this issue in case there are other problems.

**Comment by JackWoodN** [comment]
> Hello, we'll send you an e-mail. Thanks! Please feel free to reopen this issue in case there are other problems.

hi，i dont receive e-mail, did you had send an e-mail? .

**Comment by daria-blockchair** [comment]
> > Hello, we'll send you an e-mail. Thanks! Please feel free to reopen this issue in case there are other problems.
> 
> hi，i dont receive e-mail, did you had send an e-mail? .

Hi, yes, we've sent you an email with the activation password to the address from which you've made the payment.
