### ISSUE TITLE
hi，i dont receive e-mail about api key,  did you had send an e-mail? .

### ISSUE THREAD

**Issue by JackWoodN** [Blockchair/Blockchair.Support#1422]
Hello, we'll send you an e-mail. Thanks! Please feel free to reopen this issue in case there are other problems.

_Originally posted by @Har01d in https://github.com/Blockchair/Blockchair.Support/issues/1419#issuecomment-1944463507_

**Comment by daria-blockchair** [comment]
Hi! We've emailed you the activation password to the address from which you made the payment.
If you haven't received it, please check your spam. If you can't find an email, please email us at info@blockchair.com
