### ISSUE TITLE
Wallet issues with withdrawing 

### ISSUE THREAD

**Issue by Keenakkt** [Blockchair/Blockchair.Support#1441]
I had put multiple pieces of bitcon from a game I won alot of money. Now, I can't get it out of the wallet. It keeps saying send my crypto. Is thus just the fee for handling? If not, how can I retrieve this money to my bank account?
![Screenshot_20240310_123854_MoonPay](https://github.com/Blockchair/Blockchair.Support/assets/163031003/f980981d-1bfe-4541-803b-6371f0e5886e)
![Screenshot_20240310_123823_MoonPay](https://github.com/Blockchair/Blockchair.Support/assets/163031003/53d1bc29-e631-4697-bda2-a82375f36965)
![Screenshot_20240310_123813_MoonPay](https://github.com/Blockchair/Blockchair.Support/assets/163031003/723fb1d4-6a09-4859-b327-442260fcd78b)
![Screenshot_20240310_140027_Chrome](https://github.com/Blockchair/Blockchair.Support/assets/163031003/f4576378-445e-43bb-8378-9ae90b9d9c6e)
![Screenshot_20240310_140032_Chrome](https://github.com/Blockchair/Blockchair.Support/assets/163031003/bf95d384-29d0-401e-9a7d-19e84a59831e)

**Comment by daria-blockchair** [comment]
Hi @Keenakkt, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
