### ISSUE TITLE
Btc has been Pending for a week

### ISSUE THREAD

**Issue by justinc9** [Blockchair/Blockchair.Support#1442]
My bitcoin has been pending gor a week i need help asap please

**Comment by daria-blockchair** [comment]
> My bitcoin has been pending gor a week i need help asap please

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
