### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by Kidd0328** [Blockchair/Blockchair.Support#1443]
You guys have been harassing me for over two years about some stupid scam BTC mining scam and I have had enough of it. You have sent me harassing emails dozens of them. I want you to leave me alone or I am going to sue your asses off. Leave me alone!  This is the website they come from

 https://mining-patner-club.pro/

Stop scamming ppl!

**Comment by daria-blockchair** [comment]
> You guys have been harassing me for over two years about some stupid scam BTC mining scam and I have had enough of it. You have sent me harassing emails dozens of them. I want you to leave me alone or I am going to sue your asses off. Leave me alone! This is the website they come from
> 
> https://mining-patner-club.pro/
> 
> Stop scamming ppl!

Hi, 
Blockchair is a block explorer and we do not offer mining services. 
Thank you for understanding.
