### ISSUE TITLE
Lost Money

### ISSUE THREAD

**Issue by uryeahn** [Blockchair/Blockchair.Support#1446]
Hello there. I wanted to deposit LTC to my wallet in rollercoin.com several days ago, but I believe I tapped the address generate button on my phone and my PC without refreshing the one I did after and it led to a total different address popping up. I didn't receive it and I also hadn't send the minimum required and thought to myself, maybe I can have it and the one before through if I send the least minimum required to the same previous one again this time. It turned out to be pointless. I was wondering if I could ask for help to have it back, since Rollercoin informed me that I should reach the network support out. Down bellow here you can see the links of the details of the transaction. And I provided the two different screenshots of the generated address above all the description. I would provide any further information you'd like to ask.

https://blockchair.com/litecoin/transaction/85849c91590f4304a200c9ec9d8af79ff64a32b07202865273832904ccc12593

https://blockchair.com/litecoin/transaction/4de4258b9f91434b54d705bf94a9ef6cafaa7f7f83f80cf2666660e660f61b7c

![photo_2024-02-28_14-15-34](https://github.com/Blockchair/Blockchair.Support/assets/43124600/7bbc8d00-4385-490c-9a7f-8eb322366e8c)

![Screenshot 2024-03-03 024057](https://github.com/Blockchair/Blockchair.Support/assets/43124600/2b50d30a-fbee-42e7-a198-cc1cf4797d01)

**Comment by PASS989** [comment]
我不太清楚您的意思
我是TAIWIN人

uryeahn ***@***.***> 於 2024年3月15日 週五 12:47 寫道：

**Comment by uryeahn** [comment]
> uryeahn ***@***.***> 於 2024年3月15日 週五 12:47 寫道：

Hello fellow Taiwanese. Try copy and past it in a translator and try to see if you could help please, because I don't know how to speak Taiwanese. 

So.. Is this how I apply to get support? I mean just leaving a post here about my problem? Cause I haven't yet got any answers.

So.. to be brief, I got two different deposit address in a website and I sent to the old one and it resulted in not having my balance accrued. I reached out to them and they told me that I should contact the support of the currency's network . I went straight to the transaction tracking page and found support section. They suggested that I leave a post here and I did so.

**Comment by daria-blockchair** [comment]
> Hello there. I wanted to deposit LTC to my wallet in rollercoin.com several days ago, but I believe I tapped the address generate button on my phone and my PC without refreshing the one I did after and it led to a total different address popping up. I didn't receive it and I also hadn't send the minimum required and thought to myself, maybe I can have it and the one before through if I send the least minimum required to the same previous one again this time. It turned out to be pointless. I was wondering if I could ask for help to have it back, since Rollercoin informed me that I should reach the network support out. Down bellow here you can see the links of the details of the transaction. And I provided the two different screenshots of the generated address above all the description. I would provide any further information you'd like to ask.
> 
> https://blockchair.com/litecoin/transaction/85849c91590f4304a200c9ec9d8af79ff64a32b07202865273832904ccc12593
> 
> https://blockchair.com/litecoin/transaction/4de4258b9f91434b54d705bf94a9ef6cafaa7f7f83f80cf2666660e660f61b7c
> 
> ![photo_2024-02-28_14-15-34](https://private-user-images.githubusercontent.com/43124600/313065750-7bbc8d00-4385-490c-9a7f-8eb322366e8c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDU4NzIsIm5iZiI6MTcxMTc0NTU3MiwicGF0aCI6Ii80MzEyNDYwMC8zMTMwNjU3NTAtN2JiYzhkMDAtNDM4NS00OTBjLTlhN2YtOGViMzIyMzY2ZThjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDIwNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMzI5NThkZWMwNjUzZjA2Zjc0MGMwOGY5YjQ2OTM0OTU3NmJkNDVmNjdhZDAzOTg1MGVlYWNkY2ZlMjA2ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fJcZ0OGJL18kYvjJafOrDau9eGBSjW4kULZDniABdJo)
> 
> ![Screenshot 2024-03-03 024057](https://private-user-images.githubusercontent.com/43124600/313065756-2b50d30a-fbee-42e7-a198-cc1cf4797d01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDU4NzIsIm5iZiI6MTcxMTc0NTU3MiwicGF0aCI6Ii80MzEyNDYwMC8zMTMwNjU3NTYtMmI1MGQzMGEtZmJlZS00MmU3LWExOTgtY2MxY2Y0Nzk3ZDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDIwNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNjFlNjcxMTVmZTI3N2RiNDU0MDM1MzQwZGVjNzc0ZjE5YjUyZTFiNjhlNTE1NjY5NTBiOTllYzZjNWVhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O5WFYT1pAzI3TBNOmkyB3RToOzNNgv4KaQlNW9mwGa0)

Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
