### ISSUE TITLE
0x23c07461c7b0c93f550b617230c0ff3313271c2c.     0x0598bef845934d83463ceadd8c86f0801e2ee058

### ISSUE THREAD

**Issue by soho1111** [Blockchair/Blockchair.Support#1447]
This is the token contract and initiator contract of usdc rewards that are to come to me
Please advise 🙏 
The initiator contract is 0x23c07461c7b0c93f550b617230c0ff3313271c2c
And the token contract is 0x0598bef845934d83463ceadd8c86f0801e2ee058
I cannot redeem my rewards on usdrewards.org it doesn't exist anymore 
Thanks again 
William Tarr 
Soho1111wt@gmail.com

**Comment by daria-blockchair** [comment]
Hi @soho1111, 
Blockchair does not process transactions and does not store your funds. Unfortunately, we cannot assist you on this matter
