### ISSUE TITLE
Please show Bitcoin SV on the pie chart of BCH node implementations

### ISSUE THREAD

**Issue by joechin13** [Blockchair/Blockchair.Support#145]
On https://blockchair.com/bitcoin-cash/nodes please show Bitcoin SV on the pie chart of BCH node implementations. There are now 136+ Bitcoin SV nodes so it is becoming a significant implementation. That number will increase in advance of the 15th November hard fork, so it will be interesting to track the increase in adoption. Thanks.

**Comment by Har01d** [comment]
Hey,

Thanks for the request.

We’ll be revamping https://blockchair.com/bitcoin-cash/nodes in the near future to create a separate page for Bitcoin SV.

**Comment by Har01d** [comment]
Closed as we now have a separate SV node list: https://blockchair.com/bitcoin-sv/nodes (added a long time ago in API v.2.0.17)
