### ISSUE TITLE
Transferred 0x97a26CFFf69C06F6cABB5A6742de74D6cFa4CA133 but not yet received 

### ISSUE THREAD

**Issue by jrcjr1965** [Blockchair/Blockchair.Support#1451]
I sent $189 to the wallet address above. I am being told that it was not received. But it has been confirmed and completed on the blockchair. How do I investigate further that it was received? The recipient is telling me that the wallet address that I sent it to is having a problem receiving cryptocurrency. Yet they said it was confirmed, but nothing is going into the wallet. Is that possible?

**Comment by daria-blockchair** [comment]
> I sent $189 to the wallet address above. I am being told that it was not received. But it has been confirmed and completed on the blockchair. How do I investigate further that it was received? The recipient is telling me that the wallet address that I sent it to is having a problem receiving cryptocurrency. Yet they said it was confirmed, but nothing is going into the wallet. Is that possible?

Please double-check if you've sent a transaction to the correct address. 
You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/).

Unfortunately, there is nothing we can do to revert the transaction if it was sent to the wrong address and we can not help get your money back. 

Thank you for understanding.
