### ISSUE TITLE
Currency switch for wallet statement not working

### ISSUE THREAD

**Issue by pingec** [Blockchair/Blockchair.Support#1464]
Hello,

I've noticed that when I try to generate a wallet pdf statement, the currency setting is not taken into account anymore. For example I set the currency in the top right corner to EUR but the generated pdf statement is for USD. Same for GBP. This used to work before as I have generated statements in EUR.

Is this perhaps a bug or is there another way to get a statement in EUR ?

Thanks

**Comment by daria-blockchair** [comment]
Hi @pingec, 

I'm glad to tell you that the issue has been resolved. 

Now you can change fiat currency in the site's settings. Also, wallet statements can be generated in various fiat currencies.

**Comment by pingec** [comment]
It works great! Thank you!

**Comment by pingec** [comment]
It works great now! Thank you!
