### ISSUE TITLE
wallet :3KidEc61xmxraQJnNBuzBXxowotMASUJs5

### ISSUE THREAD

**Issue by Wsmiy** [Blockchair/Blockchair.Support#1470]
In explorer i seen  ‎0.04998665 BTC in my wallet but not available in my account

**Comment by daria-blockchair** [comment]
Hi @Wsmiy,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
