### ISSUE TITLE
BCH to nowhere

### ISSUE THREAD

**Issue by renaembell** [Blockchair/Blockchair.Support#1475]
I sent a BCH transaction from one of my wallets to another, and it never arrived. How do I know this? I am the owner of both wallets. The transaction looks super sketchy, since the hash shows a different wallet address it was sent to, and not the one that the transaction receipt does.

<html><body>

Recipient’s address | 37sn4nqa59CphQHjHfq3ssrmVaKiHUSF7X
-- | --

</body>
</html>
is where the transaction was going. Instead, it went to 
pppanse24u2w6enjflvvmccpmdxywzqzyy9mxrxajl

It has been a year now of trying to get the two companies to work together to see what the hell actually happened, rather than pointing at each other and saying "Not it". How can this be resolved?

**Comment by daria-blockchair** [comment]
Hi @renaembell,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
