### ISSUE TITLE
Refferal and invite problum

### ISSUE THREAD

**Issue by Manojdk45** [Blockchair/Blockchair.Support#1493]
Sir I want to invite my friends but I don't now the process it's not shown invite who submit my I'd for refference please teach me how to do that thank you

**Comment by daria-blockchair** [comment]
Hi @Manojdk45! While we don't currently offer a referral program for individuals, you're more than welcome to share a link to our website with your friends: https://blockchair.com/
They can explore data from 43 blockchains and take advantage of our various other services, all free of charge!

If you are a business, please take a look at this page: https://blockchair.com/partnerships
