### ISSUE TITLE
Bitcoin Mempool Transactions missing

### ISSUE THREAD

**Issue by clemtaylor** [Blockchair/Blockchair.Support#15]
My node running Satoshi:0.14.2 currently (block height 480326) shows 9889 transactions in the mempool, but https://blockchair.com/bitcoin/mempool/transactions only shows 7206.

I'm not sure what filter rules you are using, but I would assume it should be the same as bitcoin core out of the box.

(It looks like you have an age limit of about 2 days, but with the current state of the mempool transactions are getting stuck in the mempool for much longer then that)

**Comment by Har01d** [comment]
Thanks for reporting!

That’s not an age limit, it’s just we restarted our Bitcoin node two days ago. Currently the node sees the same number of transactions in the mempool as our main database.

I guess the difference in numbers comes from the fact that some older and/or low fee transactions are stopped from being relayed at some point.

**Comment by clemtaylor** [comment]
I have a 3 transactions in the mempool (generated @ height 479917), that do not show up blockchair, but show up on blockchain.info. My node is fairly well connected and has re-transmitting the transactions since I created them (with way too low of a fee).

Could you be filtering out old mempool transactions based on locktime? I noticed my transactions do have locktime set to 479917?

**Comment by Har01d** [comment]
No, we are not filtering transactions in any way. It also doesn’t seem like the problem is with locktime: https://blockchair.com/bitcoin/mempool/transactions?q=block_id(-1),lock_time(1..)#

Maybe the problem is that we are running Satoshi:0.12.1. We’ll investigate the issue further.

**Comment by Har01d** [comment]
While introducing support for SegWit we’ve upgraded our Bitcoin node, so I hope it should now see more transactions.

In the future we’ll be using multiple nodes to collect as many mempool transactions as possible.

**Comment by julee123** [comment]
Hello please help me regarding my coinpot withrawal to my coins.ph i didn't receive my withrawal ang when i click th transaction from coinpot it is automatically going to blockchair. Please help me

**Comment by Har01d** [comment]
@julee123, please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
