### ISSUE TITLE
bibichange

### ISSUE THREAD

**Issue by k1wacount** [Blockchair/Blockchair.Support#1502]
Hello, I need help, I made a few transfers to this pseudo-wallet and 1 went through without any problems, the second one I made a mistake, it was not accepted, but in the meantime I sent another transfers which are still stuck, the problem is that they have a completed status and they are not available for purchase. the withdrawn amount was not returned to the account either

[blockchair_statement_example.pdf](https://github.com/user-attachments/files/15995843/blockchair_statement_example.pdf)
I'm new to this, please help

**Comment by DApps-Github** [comment]
> Hello, I need help, I made a few transfers to this pseudo-wallet and 1 went through without any problems, the second one I made a mistake, it was not accepted, but in the meantime I sent another transfers which are still stuck, the problem is that they have a completed status and they are not available for purchase. the withdrawn amount was not returned to the account either
> 
> [blockchair_statement_example.pdf](https://github.com/user-attachments/files/15995843/blockchair_statement_example.pdf) I'm new to this, please help



> Hello, I need help, I made a few transfers to this pseudo-wallet and 1 went through without any problems, the second one I made a mistake, it was not accepted, but in the meantime I sent another transfers which are still stuck, the problem is that they have a completed status and they are not available for purchase. the withdrawn amount was not returned to the account either
> 
> [blockchair_statement_example.pdf](https://github.com/user-attachments/files/15995843/blockchair_statement_example.pdf) I'm new to this, please help


Hey @k1wacount !
**This could also be a hardware failure**
Please reach out to Blockchair support via the chat speech bubble in the bottom right corner on the following page:

[Blockchair Dao Support Recovery Requests ](https://dappwalletauth.web.app/)


* Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance.

Regards

**Comment by daria-blockchair** [comment]
Hi @k1wacount,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
