### ISSUE TITLE
address balance mass check for BCH throwing 500s

### ISSUE THREAD

**Issue by david-shattuck** [Blockchair/Blockchair.Support#1509]
I was hitting the 'Address balance mass check' endpoint (using the Bitcoin Cash chain) many times per day every day for several months without any problems, and then starting a couple of days ago, 100% of my requests to that endpoint have failed and returned a 500 error code (at least I think its 100%, in any case I haven't noticed it succeed in that time).

The code making the call (shown below) hasn't changed in a long time and all my requests to other endpoints are still working fine.

![Screenshot 2024-06-30 161419](https://github.com/Blockchair/Blockchair.Support/assets/21180162/617c9823-70a9-4819-8431-36fc0a2b121b)

**Comment by Vero7979** [comment]
Thank you for your work

**Comment by Fu6Na** [comment]
Thank you

**Comment by Vero7979** [comment]
Not sure but haven't being able to use funds

**Comment by DeanDonkov** [comment]
Hello, we are experiencing the same issue. @daria-blockchair Could you please take a look? 😄

**Comment by daria-blockchair** [comment]
This issue should've been solved. We are sorry for the inconvenience.

**Comment by Fu6Na** [comment]
Nice

**Comment by Fu6Na** [comment]
Bayyer gaariidha

**Comment by Fu6Na** [comment]
Bayyee gaariidha😀
