### ISSUE TITLE
Quero receber o meu investimento.

### ISSUE THREAD

**Issue by 02091945** [Blockchair/Blockchair.Support#1514]
Quero pedir o meu investimento, como devo fazer???

**Comment by 02091945** [comment]
Como posso pedir o meu investimento

**Comment by TonkeilEth-Mod** [comment]
@02091945 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by daria-blockchair** [comment]
Hi @02091945, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
