### ISSUE TITLE
Provide account information,

### ISSUE THREAD

**Issue by Vero7979** [Blockchair/Blockchair.Support#1517]
Seems I don't owe any,
Unable to see balance on wallet

**Comment by daria-blockchair** [comment]
Hi @Vero7979 ,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
