### ISSUE TITLE
Wolfgang_ James Neufeld

### ISSUE THREAD

**Issue by 95531G** [Blockchair/Blockchair.Support#1519]
2017 BTC except couple file pages stolen from my new t mobile devices by person above not sure how he got data from my device but he did at job both work
Well for me I'm healing while co workers helping their selves to my trust wallet stolen and then used my ATM card to Auth in wallet and is running crypto  as  me but all coin that has been moved is stolen by leach employees in sparks nv now it's fanning out to mafias Mexican etc all persons I was working with prison half way houses paroles so double compound tibula fibula fracture 
Layed on floor over hour waiting for employees to call 911 no call made until lunch bell rang and employees traffic lightly no words 
No help etc yeah they almost killed me So I want my crypto back at all any cost they are 13-15 persons ,no cost to  much 
SEAN BRENNAN

**Comment by bradstevens1** [comment]
Hello @95531G 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID TRT07638
Please see the link below to our dedicated support line:
[Trustwallet Support Requests ](https://dappsblockchainsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by daria-blockchair** [comment]
Dear @95531G,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
