### ISSUE TITLE
here he is with my stolen profile 

### ISSUE THREAD

**Issue by 95531G** [Blockchair/Blockchair.Support#1520]
https://github.com/513375

**Comment by Clark-techweb** [comment]
@95531G Thanks for posting the issue. 

It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by daria-blockchair** [comment]
Hi @95531G,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
