### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by BellaEq** [Blockchair/Blockchair.Support#1526]
Good Day
A report was pulled from your site showing a certain amount of money in an xrp waller. However, when I pulled another report on the same wallet it showed a $0 balance but the transaction history did not report where the funds went, Then a 3rd report was pulled this morning and the funds were back in the account but the transaction history does not report the money leaving the wallet and being returned to the wallet. Can someone assist and provide some clarity as to where is the log for information pertaining to the funds leaving  the wallet and being returned?

**Comment by Moderator0xa** [comment]
@BellaEq Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by TraceScamCEO** [comment]
I'm Elijah Reg. Nō 217217 Thank you very much for taking the time to meet with me. I am confident that TRACE-SCAM is a safe and reliable assist.

Message REG NŌ. 02170 𝕏 on WhatsApp. https://wa.me/16063166486

**Comment by BellaEq** [comment]
How will they assist me in resolving my request?On Oct 6, 2024, at 8:01 AM, TraceScamCEO ***@***.***> wrote:﻿
I'm Elijah Reg. Nō 217217 Thank you very much for taking the time to meet with me. I am confident that TRACE-SCAM is a safe and reliable assist.
Message REG NŌ. 02170 𝕏 on WhatsApp. https://wa.me/16063166486

**Comment by TraceScamCEO** [comment]
> How will they assist me in resolving my request?On Oct 6, 2024, at 8:01 AM, TraceScamCEO ***@***.***> wrote:﻿ I'm Elijah Reg. Nō 217217 Thank you very much for taking the time to meet with me. I am confident that TRACE-SCAM is a safe and reliable assist. Message REG NŌ. 02170 𝕏 on WhatsApp. https://wa.me/16063166486 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by TraceScamCEO** [comment]
Are you Whatsapp? To message me directly to proceed with your request.

**Comment by TraceScamCEO** [comment]
Message REG NŌ. 02170 𝕏 on WhatsApp. https://wa.me/16063166486

**Comment by daria-blockchair** [comment]
> Good Day A report was pulled from your site showing a certain amount of money in an xrp waller. However, when I pulled another report on the same wallet it showed a $0 balance but the transaction history did not report where the funds went, Then a 3rd report was pulled this morning and the funds were back in the account but the transaction history does not report the money leaving the wallet and being returned to the wallet. Can someone assist and provide some clarity as to where is the log for information pertaining to the funds leaving the wallet and being returned?

Hi! 

Based on the information you've provided, unfortunately, I can't tell you if there is an issue. 

You can check the address balance and transaction history on [blockchair.com](https://blockchair.com). Please enter your wallet address into the search field on the main page and see the information. 

If you'd like to download a wallet statement, please visit [this page](https://blockchair.com/address/statement) and select the required time period.
