### ISSUE TITLE
Invalid API Token

### ISSUE THREAD

**Issue by LanfordCai** [Blockchair/Blockchair.Support#1527]
I bought an API token but it reported invalid when I tried to use it. I have sent you email 6 days ago but I haven't got any response...

My Order ID is 0146587126, pls take a look

**Comment by Bogorsote** [comment]
Puede ser una estafa cualquiera puede crear token falsos checate el contrato de dirección y verifica la red, si no es correcta se pierden y si hay error alguien lo checara

**Comment by Talhaashraf05** [comment]
Translation of Bogorsote:
It can be a scam, anyone can create fake tokens, check the address contract and verify the network, if it is not correct, they will be lost and if there is an error, someone will check it.

**Comment by daria-blockchair** [comment]
Hi @LanfordCai! I hope that the issue has been resolved. If you still experience any problems with our API service, please contact us at info@blockchair.com
