### ISSUE TITLE
Куда ушли деньги

### ISSUE THREAD

**Issue by Kon709** [Blockchair/Blockchair.Support#1532]
Почему так долго идёт транзакция на Биткойн адрес bc1qjkrstpyqpq6a02yjclz3ehmv060la8ynvk7heu
Или куда ушли 0.00052789 btc

**Comment by LeoNore-ort** [comment]
@Kon709 Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by daria-blockchair** [comment]
Hi @Kon709,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
