### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by mrswart222** [Blockchair/Blockchair.Support#1539]
Pay to address but never received my payment 2

**Comment by LeoNore-ort** [comment]
@mrswart222 Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by daria-blockchair** [comment]
> Pay to address but never received my payment 2

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
