### ISSUE TITLE
Possible display bug

### ISSUE THREAD

**Issue by phillipsjk** [Blockchair/Blockchair.Support#154]
Was arguing somebody on the Internet, and the display for how long ago a blocks happened seems to be wrong/inconsistent.

Two blocks separated by 20 seconds have a "time found" estimate that differs by 2 hours.

https://old.reddit.com/r/btc/comments/a0lxfd/peter_rizun_a_good_cult_leader_can_convince_his/eaizld4/

I am using Chromium

Version 60.0.3112.78 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (32-bit)

**Comment by phillipsjk** [comment]
PEBCAK.

The "block found" is in minutes, not second resolution.

Also, the blocks in error appear to be 10 blocks apart.

**Comment by Har01d** [comment]
Glad that the issue has been resolved. By the way, we have seconds on API level, see `https://api.blockchair.com/bitcoin/blocks` for example.
