### ISSUE TITLE
How to receive my funds 

### ISSUE THREAD

**Issue by Nohamil** [Blockchair/Blockchair.Support#1542]
I'm in need of help retrieving my funds from address ltc1qgw0n6u4f3ddpx575jjq7vxht9qdq7wt7cm973d
And MM4bVEjFvmzuypwJzji9h4yGHMBZpQATY7

**Comment by Aster36-kEth** [comment]
@Nohamil Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by TraceScamCEO** [comment]
I'm Elijah Reg. Nō 217217 Thank you very much for taking the time to meet with me. I am confident that TRACE-SCAM is a safe and reliable assist.

Message REG NŌ. 02170 𝕏 on WhatsApp. https://wa.me/16063166486

**Comment by daria-blockchair** [comment]
> I'm in need of help retrieving my funds from address ltc1qgw0n6u4f3ddpx575jjq7vxht9qdq7wt7cm973d And MM4bVEjFvmzuypwJzji9h4yGHMBZpQATY7

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 
Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
