### ISSUE TITLE
How do I calculate the fee_per_kwu for ltc, bch?

### ISSUE THREAD

**Issue by crazyxia** [Blockchair/Blockchair.Support#155]
hello,i have a question,can you tell me how do I calculate the fee_per_kwu for ltc, bch?i need them,Or will you add this later for other coin?thanks

**Comment by crazyxia** [comment]
im sorry,ltc is supported

**Comment by Har01d** [comment]
Hello, yes, we support `fee_per_kwu` only in Bitcoin and Litecoin, since it’s a part of SegWit. Bitcoin Cash doesn’t have SegWit, so there’s no “weight units”.

**Comment by 1623csK** [comment]
Wellcome...
