### ISSUE TITLE
This person stole my Bitcoin....after many confirmation I sent to him...who can help me

### ISSUE THREAD

**Issue by Khalifa119** [Blockchair/Blockchair.Support#1557]
I sent more than $500+ Bitcoin to him and he never paid me...he lied to me that he didn't receive it and had been ignoring my messages on Whatsapp 😭 this about a month ago now...so I decided to find help from here or anywh
![Screenshot_20241104-063228](https://github.com/user-attachments/assets/f9688eaa-176d-47f0-b66f-04a3e93b9b37)
ere😭😭😭😭😔😔😔
![Screenshot_20241104-063228](https://github.com/user-attachments/assets/9a14474a-e505-4acf-9299-96665e6a661d)
![Screenshot_20241104-063210](https://github.com/user-attachments/assets/0b3942ab-f75c-4ba1-a242-9f02c836a23b)
[Wallet statement 1_1 2024-09-10 - 2024-11-03 (1).pdf](https://github.com/user-attachments/files/17614195/Wallet.statement.1_1.2024-09-10.-.2024-11-03.1.pdf)
![Screenshot_20241104-063228](https://github.com/user-attachments/assets/96e5486c-57d8-4c9f-be4e-118732510d8f)
![Screenshot_20241104-063210](https://github.com/user-attachments/assets/770a87f6-c064-4a1e-89eb-093cc79c35a3)
[Wallet statement 1_1 2024-09-10 - 2024-11-03 (1).pdf](https://github.com/user-attachments/files/17614196/Wallet.statement.1_1.2024-09-10.-.2024-11-03.1.pdf)

**Comment by Teresaevans** [comment]
> I sent more than $500+ Bitcoin to him and he never paid me...he lied to me that he didn't receive it and had been ignoring my messages on Whatsapp 😭 this about a month ago now...so I decided to find help from here or anywh ![Screenshot_20241104-063228](https://private-user-images.githubusercontent.com/187243234/382653165-f9688eaa-176d-47f0-b66f-04a3e93b9b37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTAwMjksIm5iZiI6MTczMDcwOTcyOSwicGF0aCI6Ii8xODcyNDMyMzQvMzgyNjUzMTY1LWY5Njg4ZWFhLTE3NmQtNDdmMC1iNjZmLTA0YTNlOTNiOWIzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGI2MzAyZTg2YTY2ODZiZjZhMzJjM2JiNmU5YjI0ZjcyNjFlNTExYjVjMjkwNTlkMjAzZmNmM2ZiZmQ1N2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xxo2K0nz1JoX2bTwC991RrED0Zw5lCGTOyUv13aM3sY) ere😭😭😭😭😔😔😔 ![Screenshot_20241104-063228](https://private-user-images.githubusercontent.com/187243234/382653231-9a14474a-e505-4acf-9299-96665e6a661d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTAwMjksIm5iZiI6MTczMDcwOTcyOSwicGF0aCI6Ii8xODcyNDMyMzQvMzgyNjUzMjMxLTlhMTQ0NzRhLWU1MDUtNGFjZi05Mjk5LTk2NjY1ZTZhNjYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTMyODA1YjQzNWQ4YWJiYjE0MmYzMTk5MmQ1MjhmZDc1YTk0Yjc5ZDdlZTEyMGNmZjRiYjIzMTg0NTZkNjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rxQAp1mBJay43nPJLjg-D3TSdxbSW0v9Em3TR3H2Uq8) ![Screenshot_20241104-063210](https://private-user-images.githubusercontent.com/187243234/382653236-0b3942ab-f75c-4ba1-a242-9f02c836a23b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTAwMjksIm5iZiI6MTczMDcwOTcyOSwicGF0aCI6Ii8xODcyNDMyMzQvMzgyNjUzMjM2LTBiMzk0MmFiLWY3NWMtNGJhMS1hMjQyLTlmMDJjODM2YTIzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWE5Y2NiYTZjYzI4Mjc0MTA1OThjNGUwYTY1ZGNmYTRjMWMxODBhMTM3OTQ4NzJiNmQxNDJkMTVkMjI5OTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gF2k6F48341DotQdieJ-GMsMHp69JlbuRMwrRN7BxZo) [Wallet statement 1_1 2024-09-10 - 2024-11-03 (1).pdf](https://github.com/user-attachments/files/17614195/Wallet.statement.1_1.2024-09-10.-.2024-11-03.1.pdf) ![Screenshot_20241104-063228](https://private-user-images.githubusercontent.com/187243234/382653273-96e5486c-57d8-4c9f-be4e-118732510d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTAwMjksIm5iZiI6MTczMDcwOTcyOSwicGF0aCI6Ii8xODcyNDMyMzQvMzgyNjUzMjczLTk2ZTU0ODZjLTU3ZDgtNGM5Zi1iZTRlLTExODczMjUxMGQ4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTA5MGRjMDk1MmEyMTliMGM3NmY5ZDA0ZWNhZWJkYTk3Yzk0MWZlYjZjM2I2NDBhZjUzYTlkYjg2NzYwZjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3LrHXnzwTtC61GtjPZBeQZvhiUrZEOyyXKQ6GDLWBzA) ![Screenshot_20241104-063210](https://private-user-images.githubusercontent.com/187243234/382653282-770a87f6-c064-4a1e-89eb-093cc79c35a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTAwMjksIm5iZiI6MTczMDcwOTcyOSwicGF0aCI6Ii8xODcyNDMyMzQvMzgyNjUzMjgyLTc3MGE4N2Y2LWMwNjQtNGExZS04OWViLTA5M2NjNzljMzVhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjJmMjU3NWJlZDM3YjZjNGUxMDY1MDkyZmE0OTU4MjVmNjkwODQ5MzdlODliNzU4OWY0ZDQ0ZjIyZWU1YTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ygo1wGt-kH1F2L5lckibZkGYAkxFc-3mhWtTW2OgqCM) [Wallet statement 1_1 2024-09-10 - 2024-11-03 (1).pdf](https://github.com/user-attachments/files/17614196/Wallet.statement.1_1.2024-09-10.-.2024-11-03.1.pdf)

Hi @Khalifa119 !

I hope your issue has been resolved. If not, I apologize for the delay. To address this, please reach out to the team for specialized support and recovery guidelines .

I've created a support ticket for you (ID: SQR7638). You can find the recovery steps and more help at [Square Dapps Support Ticket Requests](https://thedappsupport.com/).

On the page, click the chat bubble at the bottom right to connect with an agent who can assist you further.

Thanks for your patience, and I hope this helps resolve your issue!

**Comment by daria-blockchair** [comment]
Hi @Khalifa119, 

We are sorry to hear about you being scammed. Unfortunately, we are not able to help get your money back. 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we don't have any personal information about the owners of the addresses.

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains. No one can.

Thank you for understanding.
