### ISSUE TITLE
[Litecoin] CSV

### ISSUE THREAD

**Issue by Sergo20025** [Blockchair/Blockchair.Support#1560]
I can't download a csv extract for accounting monitoring on the blockchain website since 11/8/2024. Empty files are still being downloaded.

**Comment by Enterprize-1701** [comment]
[e8357d1b544afa38baf3ba8be99094c9_en_usd_2024-01-01_2024-11-14_1.short.comma.csv](https://github.com/user-attachments/files/17773442/e8357d1b544afa38baf3ba8be99094c9_en_usd_2024-01-01_2024-11-14_1.short.comma.csv)
[e8357d1b544afa38baf3ba8be99094c9_en_usd_2024-01-01_2024-11-14_1.comma.csv](https://github.com/user-attachments/files/17773443/e8357d1b544afa38baf3ba8be99094c9_en_usd_2024-01-01_2024-11-14_1.comma.csv)

I can generate CSV report for your address for now.
Check It please.

**Comment by Sergo20025** [comment]
Can you provide an online resource where you can get such files in the form of monitoring ?
I will be very grateful to you!

**Comment by Enterprize-1701** [comment]
I generated these files here: [https://blockchair.com/litecoin/address/ltc1qzhs7jy9nnhkf6cu8ra0ms0hchxrem82tekzdq0/statement?format=scsv&from=2024-01-01&to=2024-11-14](https://blockchair.com/litecoin/address/ltc1qzhs7jy9nnhkf6cu8ra0ms0hchxrem82tekzdq0/statement?format=scsv&from=2024-01-01&to=2024-11-14).

What do you mean by "in the form of monitoring"? 
Do you mean metrics for Prometheus, or user monitoring of crypto assets? 
If you want to monitor only your assets, you can try using this: [https://wow.cash/](https://wow.cash/).

**Comment by Sergo20025** [comment]
When I try to download a csv file from a website https://blockchair.com/address/statement then an empty file is downloaded from me, in which there is no information
![photo_2024-11-15_14-54-05](https://github.com/user-attachments/assets/6ed2ee08-02e6-4e92-aed4-70678e329bca)

**Comment by Enterprize-1701** [comment]
> When I try to download a csv file from a website https://blockchair.com/address/statement then an empty file is downloaded from me, in which there is no information ![photo_2024-11-15_14-54-05](https://private-user-images.githubusercontent.com/104981852/386549638-6ed2ee08-02e6-4e92-aed4-70678e329bca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODE1MzIsIm5iZiI6MTczMTY4MTIzMiwicGF0aCI6Ii8xMDQ5ODE4NTIvMzg2NTQ5NjM4LTZlZDJlZTA4LTAyZTYtNGU5Mi1hZWQ0LTcwNjc4ZTMyOWJjYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxNDMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzU5ZDdiNzE5YWVkZGQ5YjBjMDAzZDVjZTEyOTI5MDQ0ODU3YTNjMWQ4ZGViYzcwMDU5MWI5YjRlM2JlN2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CaUjnpaS4XP1BCXuO_B7xflpwEMtWS_IPJ7zt8iaz48)

Check "Start period" and "End period" dates. For example Start period from 2024-01-01.

**Comment by Enterprize-1701** [comment]
And for todays transactions you will be able make report only tomorrow. Only full calendar days in each report.
