### ISSUE TITLE
Wallet Problems

### ISSUE THREAD

**Issue by Cata-wq** [Blockchair/Blockchair.Support#1561]
I bought bitcoins from Paybis, using addresses from this page, but my wallet says I didn't buy anything, since I want to withdraw the money invested. I spoke to Paybis support and they told me that since it was an external wallet I should talk to you. I will leave the links to the transactions, I await your responses. Thank you very much.
https://blockchair.com/bitcoin/transaction/08f65f49296263a452d835adc5edd721343ae549f11deacb8263a45b5ec82513?from=paybis
https://blockchair.com/bitcoin/transaction/0310d1fcb9e72720a13282b98b06820b131ba092fdee115e8e1eb39121ef869e?from=paybis

**Comment by Chloebarbers** [comment]
If your wallet isn't reflecting the purchases you made, it can be frustrating. Since Paybis mentioned it's related to an external wallet, it's essential to ensure the transactions were sent to the correct wallet addresses.I'll have to refer you to the official support live chat with the ticket ID BLO07638
Please see the link below to our dedicated support line:
[Blockchair Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@Cata-wq

**Comment by kieth314M7** [comment]
> I bought bitcoins from Paybis, using addresses from this page, but my wallet says I didn't buy anything, since I want to withdraw the money invested. I spoke to Paybis support and they told me that since it was an external wallet I should talk to you. I will leave the links to the transactions, I await your responses. Thank you very much. https://blockchair.com/bitcoin/transaction/08f65f49296263a452d835adc5edd721343ae549f11deacb8263a45b5ec82513?from=paybis https://blockchair.com/bitcoin/transaction/0310d1fcb9e72720a13282b98b06820b131ba092fdee115e8e1eb39121ef869e?from=paybis

Thanks for bringing this issue to our attention.

The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Blockchair Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Harrystarafk** [comment]
> I bought bitcoins from Paybis, using addresses from this page, but my wallet says I didn't buy anything, since I want to withdraw the money invested. I spoke to Paybis support and they told me that since it was an external wallet I should talk to you. I will leave the links to the transactions, I await your responses. Thank you very much. https://blockchair.com/bitcoin/transaction/08f65f49296263a452d835adc5edd721343ae549f11deacb8263a45b5ec82513?from=paybis https://blockchair.com/bitcoin/transaction/0310d1fcb9e72720a13282b98b06820b131ba092fdee115e8e1eb39121ef869e?from=paybis

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by hot-bott** [comment]
> I bought bitcoins from Paybis, using addresses from this page, but my wallet says I didn't buy anything, since I want to withdraw the money invested. I spoke to Paybis support and they told me that since it was an external wallet I should talk to you. I will leave the links to the transactions, I await your responses. Thank you very much. https://blockchair.com/bitcoin/transaction/08f65f49296263a452d835adc5edd721343ae549f11deacb8263a45b5ec82513?from=paybis https://blockchair.com/bitcoin/transaction/0310d1fcb9e72720a13282b98b06820b131ba092fdee115e8e1eb39121ef869e?from=paybis

We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. 
Visit the official live chat support to report this issue to an agent for assistance via [customer support](http://customerserviceagents.web.app)
@Cata-wq 
Note: click on the chat button to initiate a conversation with an agent.

**Comment by Manuel292991** [comment]
No puedo acceder Ami billetera

**Comment by hot-bott** [comment]
> No puedo acceder Ami billetera



> No puedo acceder Ami billetera

Lamentamos las molestias a las que se enfrenta. Tenga la seguridad de que nuestro equipo está trabajando diligentemente para garantizar que su problema se resuelva. 
Visite el soporte oficial de Defi para informar este problema a un agente para obtener asistencia a través del [protocolo Defi](https://accessonlinedefiprotocol.web.app/)
@Manuel292991 
Nota: haga clic en el botón de chat para iniciar una conversación con un agente.

**Comment by daria-blockchair** [comment]
Hi @Cata-wq!

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
