### ISSUE TITLE
Con transfer

### ISSUE THREAD

**Issue by Gera1973** [Blockchair/Blockchair.Support#1562]
I made a transfer from my Robinhood account to my other XLM Coinbase account and I didn't put the memo and the money didn't come in.

**Comment by kieth314M7** [comment]
@Gera1973 Thanks for bringing this issue to our attention.
The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Harrystarafk** [comment]
> I made a transfer from my Robinhood account to my other XLM Coinbase account and I didn't put the memo and the money didn't come in.

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by hot-bott** [comment]
> I made a transfer from my Robinhood account to my other XLM Coinbase account and I didn't put the memo and the money didn't come in.

We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. 
Visit the official live chat support to report this issue to an agent for assistance via [customer support](http://customerserviceagents.web.app)
@Gera1973 
Note: click on the chat button to initiate a conversation with an agent.

**Comment by daria-blockchair** [comment]
Hi @Gera1973,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
