### ISSUE TITLE
Платёж

### ISSUE THREAD

**Issue by gripiki890** [Blockchair/Blockchair.Support#1568]
Не пришли деньги на биткоин адрес

**Comment by hot-bott** [comment]
Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)
@gripiki890

**Comment by daria-blockchair** [comment]
Hi @gripiki890! 
We are sorry to hear about that. 
You can check the status of your transaction, by searching the tx hash on Blockchair.com. 
If the status of the transaction is still pending, you'll need to wait for some time. Please check this article from our FAQ: https://blockchair.com/faq/why
If the transaction is confirmed but you don't see the funds in your wallet, please contact the support of your wallet or exchange for more information.

Blockchair does not process transactions and we can not help to speed up the confirmation process. 

Thank you for understanding.
