### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Antontulaa** [Blockchair/Blockchair.Support#16]
I lost password Bitcoin wallet ABC version v0.14.6.0-a46e63c. How to recover the password from ABC Bitcoin wallet version v0.14.6.0-a46e63c? Wallet installed on my computer. Help!

**Comment by Har01d** [comment]
Unfortunately, we do not provide support for such cases.

I’d recommend to try to remember the password once again, I don’t think there’s anything else that could be done.
