### ISSUE TITLE
Incorrect Ethereum "transactions_24h" value

### ISSUE THREAD

**Issue by UnholyRaven** [Blockchair/Blockchair.Support#160]
https://api.blockchair.com/stats returns incorrect "transactions_24h" value.
I noticed it by `trx per second` difference between Blockhair and Etherscan.

It currently returns ~924k transactions.
![image](https://user-images.githubusercontent.com/16977284/50400085-18da6c00-0795-11e9-83b9-2a51eae1abaf.png)

If I click on it in the interface, it will open filtered transaction explorer. And it shows only ~600k which looks more realistic.
![image](https://user-images.githubusercontent.com/16977284/50400211-03b20d00-0796-11e9-8b62-e5196aa34a0c.png)

Even etherscan.io shows ~500-600k for the last days.
![image](https://user-images.githubusercontent.com/16977284/50400214-10cefc00-0796-11e9-8c41-0324f0eb1f43.png)

**Comment by Har01d** [comment]
Thank you so much for reporting!

This has been fixed, for some reason all values were reported a bit inflated for Ethereum.
