### ISSUE TITLE
Request: Have addresses for Bitcoin SV displayed with original Bitcoin address format (starting with '1') 

### ISSUE THREAD

**Issue by manufoy** [Blockchair/Blockchair.Support#162]
In use of Bitcoin SV, it's more common to use the bitcoin address format which starts with '1', as opposed to the CashAddr format. I think it would make sense to have Blockchair display the address format which is in use.

**Comment by Har01d** [comment]
This issue duplicate #161.
We’ll look into it a bit deeper, but what I see now is that all other Bitcoin SV explorers except just one are still using CashAddr.
