### ISSUE TITLE
MY TRANSACTION NOT RETURN BACK ON MY ZEBPAY WALLET

### ISSUE THREAD

**Issue by pporpanth** [Blockchair/Blockchair.Support#171]
Sir/Madam

              Zebpay to p4ay.com made transaction successful, and another wallet access that transaction, but has not been return back yet to be on my Zebpay wallet.

              Zebpay wallet mobile No. 9111187818
     
BCH transaction has successfully completed.

Please check below link for complete transaction details on .

https://blockchair.com/bitcoin-cash/transaction/044c86c9cda0e5bbc4f5bd063aedbbe8fad8aa3478370f569a9935a32b38dbe9

Please resolve my transaction issue and return back my Zebpay wallet the earliest please.

With regards
Pramod Porpanth

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/FAQ_PAYMENTS.md

You should contact Zebpay support.
