### ISSUE TITLE
Inconsistency in transaction amount charts

### ISSUE THREAD

**Issue by deeb33** [Blockchair/Blockchair.Support#174]
The median transaction amount chart for BCH in BCH for the last month ranges from about .01 to .156 BCH, while the median transaction amount for BCH in USD ranges from about 7,900 to 40,000 dollars.  I would expect the latter to be something like 3 to 30 dollars if the chart denominated in BCH is correct.

The BTC charts have the same discrepancy.

**Comment by Har01d** [comment]
Sorry we didn’t comment on that earlier, this issue was fixed a month ago :)

Thanks for the report!
