### ISSUE TITLE
Transaction has not been completed.

### ISSUE THREAD

**Issue by bmgs1905** [Blockchair/Blockchair.Support#18]
Hello,

https://blockchair.com/bitcoin-cash/transaction/cba4ca79f3b299e13320d24ee9e588848716443713b6be5093bb255d7e243d1a

Could you check the transaction above, please? It has 32 confirmtions but it has not been completed. Is it possible to accelerate the transaction?

**Comment by Har01d** [comment]
Hello,

The transaction is finalized in the blockchain. If it’s not “completed”, I’d recommend contacting support of the exchange/wallet you use.
