### ISSUE TITLE
Broadcasting transactions not support bitcoin-sv?

### ISSUE THREAD

**Issue by liangjisheng** [Blockchair/Blockchair.Support#184]
https://api.blockchair.com/{chain}/push/transaction (where {chain} can be one of those: bitcoin, bitcoin-cash, ethereum, or litecoin)  this interfacde not support bitcoin-sv? @Har01d

**Comment by Har01d** [comment]
Hi,

It does support BSV, though it’s not mentioned in the documentation.

**Comment by liangjisheng** [comment]
Got it, thanks.
