### ISSUE TITLE
Retrieving Unspent Outputs

### ISSUE THREAD

**Issue by Vimiso** [Blockchair/Blockchair.Support#186]
Take the following request:

https://api.blockchair.com/bitcoin-cash/dashboards/transactions/41e9a118765ecf7a1ba4487c0863e23dba343cc5880381a72f0365ac2546c5fa

I can see there's the `is_spent` attribute for the outputs. Some outputs have duplicate transaction hashes with different `is_spent` values.

**AIM:** I need to retrieve all unspent outputs, for an address, in order to sign a new transaction.

1. Do I retrieve all transactions, for an address, and gather all unspent outputs from those transactions?
2. If so, what if, like in my example, duplicate `transaction_hash` exist with different `is_spent` values and `recipient`, do I just not class that as unspent output all-together?

**EDIT:**

I'm going to use: https://api.blockchair.com/bitcoin-cash/mempool

**Comment by AustEcon** [comment]
I'm having similar issues... https://github.com/Blockchair/Blockchair.Support/issues/188
