### ISSUE TITLE
I sent the BCC money in the wrong pocket

### ISSUE THREAD

**Issue by thanachit99** [Blockchair/Blockchair.Support#19]
https://blockchair.com/bitcoin-cash/address/3N3NoToQQzJokBc7LdKHWYrN1mTtx8yBUR

I sent the BCC money in the wrong pocket, which I sent it in the bag for BTC. Can you help me? By pressing the coin back into the original bag from which I sent a little? I'm really in trouble now, I beg you, that is the last money in my life.

**Comment by Har01d** [comment]
I’d recommend contacting the person or exchange you sent the money to, there’s nothing we can do here.
