### ISSUE TITLE
Enter the address to get more transactions

### ISSUE THREAD

**Issue by 1270734240** [Blockchair/Blockchair.Support#191]
command：{chain}/dashboards/address/{A}
I want to use this command to get all the transactions about the input address,Instead of just 100 transaction data，Please tell me how to do it.

**Comment by Har01d** [comment]
Hi,

It’s possible to iterate the list of transaction hashes using `?offset=N`, e.g. `api.blockchair.com/{chain}/dashboards/address/{A}?offset=100`

The total number of transaction is available via the `data.{A}.address.transaction_count` key.

The default limit is 100.

**Comment by 1270734240** [comment]
Solved, thank you
