### ISSUE TITLE
Show standard Bitcoin addresses instead of cashaddr for Bitcoin SV

### ISSUE THREAD

**Issue by lewis9999** [Blockchair/Blockchair.Support#193]
Bitcoin SV ecosystem has abandoned BCH's cashaddr address format so at this point it doesn't make much sense to use this address format as default for Bitcoin SV.

Take for example main BSV wallet ElectrumSV:
https://twitter.com/ElectrumSV/status/1122058231994572800

Same situation with the most popular mobile BSV wallet Handcash:
https://twitter.com/handcashapp/status/1067432031527653378

And so on.

My suggestion is to display standard Bitcoin addresses by default everywhere but leave "Cash address format" in "General details" as it is now and allow searching by cashaddr as well for now.

Please note that I've found a previously created issue for the same thing:
https://github.com/Blockchair/Blockchair.Support/issues/162

And I probably agree that at that point in time it wasn't really clear about the future of cashaddr so it probably made sense to disregard that request back then.

**Comment by Har01d** [comment]
Hi, thanks for your request!

This indeed duplicates #161 and #162.

Switching to another address format requires our databases to be repopulated, but as of now it’s in our roadmap. No ETA yet though.

**Comment by Polve** [comment]
When they forked, they could simply change the prefix to "bitcoinsv:" and so much mess would have been avoided...
