### ISSUE TITLE
API results different from website for old/new address formats in BSV

### ISSUE THREAD

**Issue by Polve** [Blockchair/Blockchair.Support#196]
This web page correctly shows unspents for address 17GQeFNGFVC44CTL2GA83X2NEcaXxRMSZx/qpzt4wk2pedvrf7a3r04a574p4glerqhhsknnxfcjy:

https://blockchair.com/bitcoin-sv/address/17GQeFNGFVC44CTL2GA83X2NEcaXxRMSZx
https://blockchair.com/bitcoin-sv/address/qpzt4wk2pedvrf7a3r04a574p4glerqhhsknnxfcjy

while the API call gives no results for the legacy format:
https://api.blockchair.com/bitcoin-sv/outputs?q=recipient(17GQeFNGFVC44CTL2GA83X2NEcaXxRMSZx),is_spent(false)

while it is correct for the cash address format:
https://api.blockchair.com/bitcoin-sv/outputs?q=recipient(qpzt4wk2pedvrf7a3r04a574p4glerqhhsknnxfcjy),is_spent(false)

**Comment by Har01d** [comment]
We use CashAddr for Bitcoin SV internally at the moment, our front end simply makes the conversion for convenience. I think we’ll be switching to the legacy format at the next hard fork, an official announcement will come soon.

Duplicates #161, #162, #193.

**Comment by FACHRIFADLY** [comment]
fdevil37@gmail.com
