### ISSUE TITLE
Getting 500 errors on the block explorer

### ISSUE THREAD

**Issue by nnbosko** [Blockchair/Blockchair.Support#20]
XMLHttpRequest cannot load https://api.blockchair.com/bitcoin-cash/blocks?next=481861&u=ff824a6f-1517-4fa6-86c7-9c4fb38f693e. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://blockchair.com' is therefore not allowed access. The response had HTTP status code 500.

**Comment by Har01d** [comment]
Fixed, sorry. Somehow our API server decided that 5 gigabytes is “no space left on device”…
