### ISSUE TITLE
сделка # 243690134

### ISSUE THREAD

**Issue by PsihoZT** [Blockchair/Blockchair.Support#21]
Здравствуйте. Вопрос по сделке # 243690134 Не могли бы вы разъяснить ситуацию с этой сделкой? Я ничего не понимаю в данных которые отображаются на сайте. Хотелось бы узнать на каком этапе сделка. Спасибо заранее за ответ.

**Comment by Har01d** [comment]
Доброе утро, если речь о Bitcoin Cash, то сделка записана в блокчейн.

**Comment by PsihoZT** [comment]
Доброго времени суток. Речь идет о bitcoin cash. В блокчейне нет на него данных почему-то. Уже получается транзакция проходит 13 дней. И ничего не понятно. C электрон кэш кошлька отправила на биткоин приложение на андроиде. Так и называется bitcoin. И нет никакой инструкции куда если,что писать(((. Вот. И поэтому прошу помощи у вас здесь. На ссылку этого сайта переводит электрон кеш, на страницу с номером заявки и кучей не понятных данных.
