### ISSUE TITLE
Bitcoin cash transaction already takes 1 week

### ISSUE THREAD

**Issue by Rudjen** [Blockchair/Blockchair.Support#22]
Hello there Blockchair Support,

I am looking for information on the following:

7 Days ago I have withdrawn approx. 0,5 Bitcoin Cash from Bithumb and send it to be deposited in my wallet at Bitfinex.  According to Blockchair the transaction is still confirming after 7 days.
It shows at this moment 3738 confirmations. 

Why does this exchange / transaction takes so long?
Is there a way to speed up the process or undo the transaction? 

transaction #243651424 
Txid 6a3aa4b1c7165ce6741c302f7a8a3c6e6967328c3ca2fbda4d543322b0012eab

Any info is welcome and kudo's in advance!

Regards,

Rudjen

**Comment by Har01d** [comment]
Hello,

If you still haven’t received the money, I’d recommend contacting Bitfinex.
