### ISSUE TITLE
Can we support omni-test explorer?

### ISSUE THREAD

**Issue by liutao0532** [Blockchair/Blockchair.Support#223]
Can we support (bitcoin)omni-test explorer?
thanks

**Comment by Har01d** [comment]
That’s already supported.

Test omni properties live on the Bitcoin mainnet, see https://blockchair.com/bitcoin/omni, there are 21 testnet properties.

Here’s an example of a test property: https://blockchair.com/bitcoin/omni/property/2147484126 (note the id is a very large number).

I’m not sure if anyone runs Omni on top of Bitcoin testnet?

**Comment by liutao0532** [comment]
> That’s already supported.
> 
> Test omni properties live on the Bitcoin mainnet, see https://blockchair.com/bitcoin/omni, there are 21 testnet properties.
> 
> Here’s an example of a test property: https://blockchair.com/bitcoin/omni/property/2147484126 (note the id is a very large number).
> 
> I’m not sure if anyone runs Omni on top of Bitcoin testnet?

yep,I wanna runs omni  explorer of bitcoin testnet

**Comment by Har01d** [comment]
Yes, indeed there’s an Omni testnet on top of the Bitcoin testnet 🤷‍♂️

I’m not sure if we’ll implement that since nowadays Omni is primarily used for USDT only which is slowly but surely migrating to Ethereum as an ERC-20 token… It seems like no one will use that feature.

**Comment by liutao0532** [comment]
thanks for your reply.
and i have a omni question.
Can you help me?
https://github.com/OmniLayer/omnicore/issues/1014

**Comment by Har01d** [comment]
No, unfortunately we provide support only if the issue is somehow connected to Blockchair services.

**Comment by liutao0532** [comment]
thanks
