### ISSUE TITLE
Size in Block table is labelled as bytes but shows kilobytes

### ISSUE THREAD

**Issue by Xekyo** [Blockchair/Blockchair.Support#229]
In the block table, the size column is labelled with `Size (bytes)`, but the values shown correspond to their size in kilobytes.

![Biggest BSV blocks sorted by size](https://user-images.githubusercontent.com/4060799/68061702-70a20780-fcc3-11e9-8022-40b41ab96832.png)

The same block's individual values show:
![Biggest BSV block size value](https://user-images.githubusercontent.com/4060799/68061720-80b9e700-fcc3-11e9-8f71-60d055e881d9.png)

References:
* https://blockchair.com/bitcoin-sv/blocks?s=size(desc)#
* https://blockchair.com/bitcoin-sv/block/593161

**Comment by Har01d** [comment]
This has been fixed a couple of weeks ago, thanks for noticing!

**Comment by Xekyo** [comment]
Closing since I've verified the issue has been resolved.
