### ISSUE TITLE
Inaccurate nonce on site

### ISSUE THREAD

**Issue by peachbits** [Blockchair/Blockchair.Support#232]
The nonce on this transaction isn't matching other ETH explorers. 

https://blockchair.com/ethereum/transaction/0x3f498636e76e02725db55a2a554724e45fb66a788da81dbe6af6ee3f172b1a41

Blockchair is returning 1120 and these other explorers are returning 460. 

https://blockscout.com/eth/mainnet/tx/0x3f498636e76e02725db55a2a554724e45fb66a788da81dbe6af6ee3f172b1a41/token_transfers
https://eth.btc.com/txinfo/0x3f498636e76e02725db55a2a554724e45fb66a788da81dbe6af6ee3f172b1a41
https://etherscan.io/tx/0x3f498636e76e02725db55a2a554724e45fb66a788da81dbe6af6ee3f172b1a41

This is a standard node call so this should match other explorers

**Comment by Har01d** [comment]
The value is correct, though its representations differ — we show it as an integer value, while etherscan shows it in hex (0x460 = 1120).

**Comment by Har01d** [comment]
As it turned out, it was indeed a bug — we performed hex2dec conversion twice. This is now fixed on both website and API.
