### ISSUE TITLE
Please Add Luxor to guessed pool list

### ISSUE THREAD

**Issue by nitronick600** [Blockchair/Blockchair.Support#235]
Luxor (https://mining.luxor.tech) is a US-based mining pool.  The blocks found by Luxor can be identified by the coinbase data "/LUXOR/"

Here's a sample pull request for another explorer: https://github.com/janoside/btc-rpc-explorer/pull/159

Here's a block which Luxor has found: https://btc.chaintools.io/tx/0ca2ba04ca4f0865a00e38b6291b237ce834275b874b0147de84a6928ee03e90

**Comment by Har01d** [comment]
Better later than never: https://blockchair.com/bitcoin/blocks?q=guessed_miner(LUXOR)#
