### ISSUE TITLE
[Monero] A proposal to change the field value for "Amount"

### ISSUE THREAD

**Issue by TheFuzzStone** [Blockchair/Blockchair.Support#247]
I like your Explorer, I've been using it almost since the first days of its launch and I'm very glad you added Monero.

---

As you know, all transactions in the Monero network are private by default, which means that the third party observer does not know which amount was sent in this or that transaction.

For example, let's take this transaction:  https://blockchair.com/monero/transaction/a22936882e75975bd4a4cb65998c623be8395b496dbb76b0ac7d7a3fcde99636

In your explorer, there's a "**0**" all over the place, which I don't think is quite right, because:

1. You can't send 0 XMR to another person;

2. Claiming that 0 XMR have been sent kind of implies that you know which balance has been sent, which again is wrong, because a third party observer cannot know how much XMR has been sent.

I suggest replacing "**0**" with "**?**", as is here:  https://xmrchain.net/search?value=a22936882e75975bd4a4cb65998c623be8395b496dbb76b0ac7d7a3fcde99636

**Comment by Har01d** [comment]
Thanks, we’ve finally fixed this issue :)
