### ISSUE TITLE
export data is wrong

### ISSUE THREAD

**Issue by franklili3** [Blockchair/Blockchair.Support#25]
When I export data of fee_total_usd and fee_per_kb_usd, the data is wrong. The fee_total_usd is 89363 and  fee_per_kb_usd is 15550 when id is 483659. But in the website, The fee_total_usd is 4,985.12 and  fee_per_kb_usd is 5.92 when id is 483659.

**Comment by Har01d** [comment]
Hello,

We can't reproduce the issue. The export API gives the same data as the website: https://api.blockchair.com/bitcoin/blocks?q=id(483659)&fields=id,fee_total_usd,fee_per_kb_usd&export=csv 

It seems like you used the Bitcoin Cash API instead: https://api.blockchair.com/bitcoin-cash/blocks?q=id(483659)&fields=id,fee_total_usd,fee_per_kb_usd&export=csv

You need to divide usd values by 10000 to get the right result.
