### ISSUE TITLE
Rename "satoshis" to "zatoshis" in Zcash technical details

### ISSUE THREAD

**Issue by rex4539** [Blockchair/Blockchair.Support#254]
On Zcash, there are no satoshis. The units are called zatoshis.

<img width="440" alt="Screen Shot 2020-03-20 at 09 03 06" src="https://user-images.githubusercontent.com/227442/77142754-c23c0a80-6a89-11ea-9e5f-9c79c9d618ed.png">

**Comment by Har01d** [comment]
Thanks, we fixed that yesterday on the Zcash homepage (https://blockchair.com/zcash), and have now also made the change for transactions.
