### ISSUE TITLE
Time Filtering on Bitcoin Transactions/Blocks/etc.

### ISSUE THREAD

**Issue by ayqian22** [Blockchair/Blockchair.Support#256]
Hello, 
On the tables listing Bitcoin transactions/mempool/blocks/etc., the Time filtering component does not seem to work.  In particular, the filter does not allow you to enter values.  For other filtering options such as Block ID, the cursor allows me to click and type in a number.  For the Time filter, the fields do not appear to be edit-able.
Thanks!

**Comment by Har01d** [comment]
Hello,

This has been fixed some time ago.
