### ISSUE TITLE
Scam!

### ISSUE THREAD

**Issue by 1lancebordes** [Blockchair/Blockchair.Support#26]
I think I was scammed! I sent Bitcoin cash to an online wallet about 2 days ago.https://www.bitcash-wallet.info/wallet The crypto still is not showing up in my wallet. 
address: 3F5NaFuBiGunXwc3bDayzHTr6QRrKypYXq 
Can someone help with this?
Thanks, Lance
lbordes@cox.net

**Comment by DesWurstes** [comment]
This is not relevant to BlockChair

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

This is a known scam website which has no connection to Blockchair, and it will be reported to the authorities.
