### ISSUE TITLE
Bug Report Link Broken / False Confirms

### ISSUE THREAD

**Issue by leshacat** [Blockchair/Blockchair.Support#264]
Hi I have two problems.

1) I get false confirms on some transactions, it randomly says 1 confirm but I check other explorers and theres 0 confirms and then I refresh blockchair and it goes back to unconfirmed.

2) When I clicked on "bug report" it was broken and sent me to the address "https://blockchair.com/bitcoin/transaction/https://github.com/Blockchair/https://github.com/Blockchair/https://github.com/Blockchair/Blockchair.Support" which is obviously invalid. I am smart enough to figure it out but others may not be.

Thanks for your hard work and the explorer :D

**Comment by Har01d** [comment]
Hi,

Thanks for reporting!

We are aware of the first one and working on a fix. We’ll fix the broken link as well (the one in the footer is ok, but not in the menu…)

**Comment by Har01d** [comment]
We’ve fixed both issues.

Thank you once again!
