### ISSUE TITLE
Ratio of circulation_approximate / volume_24h_approximate from ethereum stats api

### ISSUE THREAD

**Issue by noslav** [Blockchair/Blockchair.Support#266]
I calculate this ratio -  `volume_24h_approximate /circulation_approximate ` from the ethereum stats API I'm getting a value that is off by one-degree order i.e if 0.4 I get 0.04 which is not what you get from the `Volume / Market Cap` coin gecko mentions in - https://www.coingecko.com/en/coins/ethereum

**Comment by Har01d** [comment]
I think that’s because CoinGecko shows the trading volume, while we show the on-chain transfer volume — these are two different things.
