### ISSUE TITLE
SegWit support

### ISSUE THREAD

**Issue by trace666** [Blockchair/Blockchair.Support#27]
Blockchair.com works very well as it is.
Now, if you had SegWit stats like number of SegWit tx, witness size in KB, total serialized block size in KB, total block weight etc., it would be even better!
Thanks for the good work.

**Comment by Har01d** [comment]
Hello,

Yes, we plan to support SegWit analytics in the near future.

Thank you!

**Comment by Har01d** [comment]
We’re launching beta support for SegWit.

New fields:

Blocks (https://blockchair.com/bitcoin/blocks):
- Stripped size, kB
- Weight, kWU (kilo weight units)
- Fee per kWU, BTC
- Fee per kWU, USD
- Number of transactions containing witness data

Transactions (https://blockchair.com/bitcoin/transactions):
- Does the transaction contain witness data? (boolean)
- Weight, kWU
- Fee per kWU, BTC
- Fee per kWU, USD

Also we’re bringing support for Bech32 addresses, e.g.
https://blockchair.com/search?q=bc1
https://blockchair.com/bitcoin/address/bc1qwqdg6squsna38e46795at95yu9atm8azzmyvckulcc7kytlcckxswvvzej
https://blockchair.com/bitcoin/transaction/4dd51993ef70431c3689dc08be0c272204e8386cb82140323228a4778c0301f0

Still working on the interface to put such lengthy addresses so they’d look nice… 🤷‍♂️

If you encounter any issues, please report them here. Thanks!
