### ISSUE TITLE
Zcash - Shielded amount in Payment Disclosed transactions is off by x10

### ISSUE THREAD

**Issue by jackgavigan** [Blockchair/Blockchair.Support#272]
The amount displayed on the right hand (received) side of a transaction that is payment disclosed is 10x what it should be. 

For example, in [this transaction](https://blockchair.com/zcash/transaction/897ab1f89dba69b04d8099eb6afd91d069b0428c610b40afbe899d83ec93e69e?paymentdisclosure=zpd:706462ff00d63ef4101c84ec956572aa6151152f86c2353940938c3c89ef979714653624c09ee693ec839d89beaf400b618c42b069d091fd6aeb99804db069ba9df8b17a89000000000000000000480572b2573472608f9c00866bb459e0a6b07ec02add07df93e16f5b738ba24bae9b33fc1487eebb4a6f6e3daf9431a595a9d551f9655e0c0578cceb3a6666782e5468697320697320616e206578616d706c65206f66206120736869656c64696e67207472616e73616374696f6e2e7509a59e44efc19e7a2faeb2de1ebb4c0c65889ad03bf5a09bc93f3784d866854eb7ab5c9a5a787678cd0521a0f2e1e9c76049ae5eb302aa08160f8260cafa0c), the amount circled in red should be 4.9896, not 49.896:
<img width="1064" alt="Screenshot 2020-06-29 at 15 43 14" src="https://user-images.githubusercontent.com/1176633/86020204-82d57080-ba1f-11ea-8a44-8bbd9784b752.png">

**Comment by Har01d** [comment]
Thank you for noticing, it’s a front-end bug, API returns the correct value: https://api.blockchair.com/zcash/raw/validate?paymentdisclosure=zpd:706462ff00d63ef4101c84ec956572aa6151152f86c2353940938c3c89ef979714653624c09ee693ec839d89beaf400b618c42b069d091fd6aeb99804db069ba9df8b17a89000000000000000000480572b2573472608f9c00866bb459e0a6b07ec02add07df93e16f5b738ba24bae9b33fc1487eebb4a6f6e3daf9431a595a9d551f9655e0c0578cceb3a6666782e5468697320697320616e206578616d706c65206f66206120736869656c64696e67207472616e73616374696f6e2e7509a59e44efc19e7a2faeb2de1ebb4c0c65889ad03bf5a09bc93f3784d866854eb7ab5c9a5a787678cd0521a0f2e1e9c76049ae5eb302aa08160f8260cafa0c

**Comment by Har01d** [comment]
Fixed, thanks!

**Comment by Margaret830117** [comment]
Thank
