### ISSUE TITLE
Odd Addresses in Bitcoin Address Dump Download

### ISSUE THREAD

**Issue by memiamap** [Blockchair/Blockchair.Support#273]
I have downloaded the Bitcoin Address Dump from https://blockchair.com/dumps.

The TSV file contains the following:

- ~23m P2PKH (`1xxx`) addresses
- ~5.8m P2SH (`3xxx`) addresses
- ~1.3m Bech32 (`bc1xxx`) addresses

However, there are also ~400k addresses that have prefixes that I don't recognise, including:

- d-xxx (example: `d-b697921d996831d1a26ca8d8e92571c1`)
- m-xxx (example: `m-942943e227462513f33c4f32ec6f1e56`)
- s-xxx (example: `s-2ad548f2459c0ed6123400e5d61a479e`)

I raised a question on [bitcoin.stackexchange.com](https://bitcoin.stackexchange.com/questions/96779/unknown-address-format-parsing-bitcoin-addresses-from-blockchair-data), and one of the answers suggested to raise a bug as this may not be information that should be in the database.

**Comment by Har01d** [comment]
In fact, there are no addresses on the Bitcoin blockchain. There are only scripts, some of them are standard and can be converted to a Bitcoin address, some of them can’t — like `nulldata` (`OP_RETURN`) outputs, `nonstandard`, and bare multisig. We use the `d-` prefix for `nulldata`, `m-` for bare multisig, and `s-` for everything else.

This is briefly mentioned in this API documentation section: https://blockchair.com/api/docs#link_300

**Comment by Har01d** [comment]
Here’s an example of such an “address” on the web interface: https://blockchair.com/bitcoin/address/s-ff37b535cbd18ec6e6c13060105398e7

Blockchair is somewhat unique in that matter as all the other explorers don’t allow their users to check non-standard scripts.

**Comment by memiamap** [comment]
@Har01d Thank you for the response and the clarification as to what these addresses are.

You will have to forgive my lack of knowledge, but given what you described and the documentation you references, **do these represent actual wallets that hold funds ?**

If so, how would the address owner instigate payments from them?

I'm presuming that this issue should be closed as the addresses are legitimate in the dataset.

**Comment by Har01d** [comment]
Yes, of course they can hold bitcoins and spend them.

Please refer to https://en.bitcoin.it/wiki/Script — this articles describes how Bitcoin scripting system works. Basically, the mechanism for non-standard script is absolutely the same as for the standard ones.

**Comment by memiamap** [comment]
Thank you once again for responding.

With regards to the `nulldata`, `d-` prefix addresses, am I correct in thinking that these represent coins that are effectively _unspent_ and therefor cannot be spent in the future?

**Comment by Har01d** [comment]
Yes, `nulldata` outputs can never be spent.

**Comment by memiamap** [comment]
Thank you for clarifying the details of this.  I'm going to close the issue as it's basically a non-issue.

**Comment by ihatecsv** [comment]
How are these pseudo addresses calculated from the transaction data?

**Comment by danehwang** [comment]
how to derive the address of nulldata type? I guessed it is `d-{something hash}`, but I can't derive the address.

**Comment by dlscjf151** [comment]
how can I derive the address of nulldata type? I guessed it is d-{something hash}, but I can't derive the address.
