### ISSUE TITLE
Fonts for non-english characters not bolded

### ISSUE THREAD

**Issue by jamesscaur** [Blockchair/Blockchair.Support#274]
<img width="366" alt="blockchair" src="https://user-images.githubusercontent.com/9779954/86505101-2cf22700-bd97-11ea-8add-82476b3732a1.png">

See here - for the Portugese language

**Comment by Margaret830117** [comment]
What is this

**Comment by Har01d** [comment]
Thanks James, we’ve fixed the issue with fonts across the website.
