### ISSUE TITLE
0 confirmations after an hour and a half?? 

### ISSUE THREAD

**Issue by TheCryptoJedi** [Blockchair/Blockchair.Support#28]
https://blockchair.com/bitcoin-cash/address/154DRQnNzGS5FioGEWwV5QhpjhzHfAHqkf

Anyone know any solution

**Comment by TheCryptoJedi** [comment]
still only one confirmation after 5 1/2 hours

**Comment by ErnieHodl** [comment]
Hi I have the same issue but wanted to ask you what the latest status is on your case ?

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
