### ISSUE TITLE
Bitcoin testnet, wrong confirmation count

### ISSUE THREAD

**Issue by SimonHausdorf** [Blockchair/Blockchair.Support#286]
See: https://blockchair.com/bitcoin/testnet/transaction/ac0266c778e6e41adac9b9e33eb47f362ade3e880e722df60ceb860799806699

![image](https://user-images.githubusercontent.com/1446685/89407450-0aae4900-d749-11ea-8a1d-092815fc0522.png)

**Comment by Har01d** [comment]
Thanks for noticing, that has been fixed in one of the latest updates to the API.
