### ISSUE TITLE
Bch sending to btc address 

### ISSUE THREAD

**Issue by khybersani2** [Blockchair/Blockchair.Support#29]
Hi 
My 2.7383 Bch is pending to be send to btc address, please could forward it to my btc address. 
The link is. https://blockchair.com/bitcoin-cash/address/39nLknrnUJ19t47GZMB3SzA84qMpJD7Yw6
Thanks 
Waiting for your prompt reply 
Regards 
Noorul Amin

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
