### ISSUE TITLE
Please provide torrents instead of access keys.

### ISSUE THREAD

**Issue by ytrezq** [Blockchair/Blockchair.Support#293]
Hello,
I tried to reach you several times at info@blockchair.com for getting the price of downloading https://tar.blockchair.com/ethereum__geth-1.9.9__archive__202001/ within less than a month through an access key, but I didn t received a reply.

Instead of having to use such a random process in terms of sucess, why not share the bandwidth of everyone through providing access to torrents files without registration for downloading dumps.

**Comment by Har01d** [comment]
Hi,

What email you were writing from? Generally, we always respond in 24-48 hours.

I don’t think a torrent would be plausible as I highly doubt there will be many seeds.

**Comment by ytrezq** [comment]
@Har01d lael.lael.cellier@gmail.com. A metalink in that case (for merging torrent download and your 10Kb/s http server)?

**Comment by Har01d** [comment]
> lael.lael.cellier@gmail.com

I haven’t been able to find any letters from that address. I’ll ask our team to contact you. Thanks.

**Comment by ytrezq** [comment]
@Har01d sorry lael.cellier@gmail.com. Why do you close this? A metalink without seed is just a plain http download. This would be only a bonus!
