### ISSUE TITLE
landing page "Mempool" stats not updating

### ISSUE THREAD

**Issue by dja29** [Blockchair/Blockchair.Support#3]
At the bottom of https://blockchair.com there are two lines, one for "Bitcoin Mempool" and another for "Bitcoin Cash Mempool". 

At the time of this writing, all values are showing "0".

Tested on:
 - Firefox 54.0 (64-bit) for Linux Mint 18
 - Chrome Version 59.0.3071.115 (Official Build) (64-bit) also on Linux Mint 18

**Comment by dja29** [comment]
Seems to be resolved.

Thanks.

**Comment by Har01d** [comment]
Yes, that issue was due to very high loads. Thank you for your report!

**Comment by Colins1516** [comment]
Someone sent me bitcoin since 3 days ago, but I have received until now, and it has confirmed on blockchain

**Comment by Colins1516** [comment]
Please how can I get it back to my wallet
