### ISSUE TITLE
Bch sending to btc address 

### ISSUE THREAD

**Issue by Alonso102** [Blockchair/Blockchair.Support#30]
https://blockchair.com/bitcoin-cash/address/39wdDaSwppS3gcwsJt2C43fb8dMA5vCyuk

First seen receiving  spending	2017-09-30 22:26	
Last seen receiving  spending	2017-09-30 22:26	
Total received	0.06150000 BCC*	27.37 USDt
Total spent	0.00000000 BCC*	0.00 USDt
Total unspent (balance)	0.06150000 BCC*	27.06 USDtoday
Profit  Loss *		-0.31 USDtoday

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
