### ISSUE TITLE
Search for specific BSV hash returns: TypeError: Cannot read property 'single' of undefined

### ISSUE THREAD

**Issue by emilbes** [Blockchair/Blockchair.Support#317]
I noticed a specific block giving my BSV node a problem, trying to search for the hash on Blockchair gives the error:

> Oh noez! [object Object] TypeError: Cannot read property 'single' of undefined

https://blockchair.com/search?q=0000000000000000004626ff6e3b936941d341c5932ece4357eeccac44e6d56c

Also strangely that block hash is mentioned in a BCH block OP_RETURN statement from 2018: https://blockchair.com/bitcoin-cash/transaction/a83a221f616c6b1e27d6b94fbcf8d52b6aafe30a350d6798656f43414113c85d

> Post memo Weird, my BU node says there's a block 0000000000000000004626ff6e3b936941d341c5932ece4357eeccac44e6d56c that's invalid. I think it's an SV block at 556767.

**Comment by Har01d** [comment]
This has been fixed several days ago.

Thank you for reporting!
