### ISSUE TITLE
No data returned for address balance mass check for some bitcoin-cash addresses

### ISSUE THREAD

**Issue by jermainepaguio** [Blockchair/Blockchair.Support#320]
Seems like there is an inconsistent behavior when pulling data using mass address balance check api and the dashboards address api for bitcoin-cash. 

Target address: qp3wjpa3tjlj042z2wv7hahsldgwhwy0rq9sywjpyy

via Address Balance Mass check API:
https://api.blockchair.com/bitcoin-cash/addresses/balances?addresses=qp3wjpa3tjlj042z2wv7hahsldgwhwy0rq9sywjpyy

Response:
![Screen Shot 2020-11-18 at 13 22 19](https://user-images.githubusercontent.com/61261898/99483201-17c21180-29a1-11eb-96bf-11799aaf3b29.png)

via Addresses dashboard API:
https://api.blockchair.com/bitcoin-cash/dashboards/addresses/qp3wjpa3tjlj042z2wv7hahsldgwhwy0rq9sywjpyy

Response:
![Screen Shot 2020-11-18 at 13 23 03](https://user-images.githubusercontent.com/61261898/99483262-31fbef80-29a1-11eb-89f2-109c5791a363.png)

Data returned is blank for Address balance mass check but balance for target address exists when using normal dashboard address call. Kindly help to check and confirm if there is an inconsistency.

Thanks!

**Comment by Har01d** [comment]
Thanks for reporting!

That was a specific edge case due to some internal logic — that behaviour was only present when requesting data on qp3wjpa3tjlj042z2wv7hahsldgwhwy0rq9sywjpyy — this address is the only output address from the genesis block. Every other address worked fine.

We’ve optimized the logic so now requesting data on genesis block addresses (from any blockchain) yields valid information as well.

**Comment by lozanopo** [comment]
[document(5).pdf](https://github.com/user-attachments/files/18683446/document.5.pdf)

**Comment by lozanopo** [comment]
[document(4).pdf](https://github.com/user-attachments/files/18683449/document.4.pdf)

**Comment by lozanopo** [comment]
[CoinGecko Token API List.pdf](https://github.com/user-attachments/files/18683464/CoinGecko.Token.API.List.pdf)

**Comment by lozanopo** [comment]
[API_DOCUMENTATION_EN.md](https://github.com/user-attachments/files/18683466/API_DOCUMENTATION_EN.md)

**Comment by lozanopo** [comment]
> No description provided.
