### ISSUE TITLE
send a message to a BCH address 

### ISSUE THREAD

**Issue by BabaCrypto** [Blockchair/Blockchair.Support#33]
how can I send a message to a BCH address that I don't know it owner?
I had send by mistake a a BTC to an old output address 
hope they will return my BTC..

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

There's no trivial way to send a message to an address via blockchain.
