### ISSUE TITLE
Два месяца прошло. Объясните кто-нибудь (((

### ISSUE THREAD

**Issue by PsihoZT** [Blockchair/Blockchair.Support#34]
Подскажите кто-нибудь? Два месяца жду уже и ничего не меняется. Может что-то сделать надо? Или все уже. Надежды нет? Транзакция 
https://blockchair.com/bitcoin-cash/transaction/a6796f4c880033544057f530696f64a9bd057c3bcbe2b417b500affd31a08bcb

**Comment by Har01d** [comment]
Доброй ночи,

Пожалуйста, обратитесь к нашему FAQ насчёт этой проблемы: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

Blockchair не предоставляет функционала биткоин-кошелька.
