### ISSUE TITLE
BCC / BTC ADRESS

### ISSUE THREAD

**Issue by seturn555** [Blockchair/Blockchair.Support#35]
Hello, this morning I have make one transaction on changelly.com NXT to BCC. I made a mistake about address of reception. Instead of my address BCC I used my BTC address thus obviously the transaction has never taken place. Is it possible to make a change of address for this transaction?

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
