### ISSUE TITLE
Bug in ERC20 token transaction endpoint 

### ISSUE THREAD

**Issue by YaraHedegeguard** [Blockchair/Blockchair.Support#369]
Hello, 

We are retrieving transactions for ERC20 Token by wallet address using "/ethereum/erc-20/{token}/dashboards/address/{wallet}" but we're not able to correctly parse the response since the returned wallet address for each token has an additional "0x" in its address. 
Could you take a look at that?

Thank you :)

**Comment by Har01d** [comment]
Hello,

It’s not a bug, it’s the intended behaviour. Just ignore the `0x` part.
