### ISSUE TITLE
mistake sent BCC TO BTC

### ISSUE THREAD

**Issue by arieblue212** [Blockchair/Blockchair.Support#37]
I made a mistake transfer from BCH bitcoin cash (vip.bitcoin.co.id) to BTC BITCOIN (my wallet at bittrex.com)

Amount: 1,0005 BCH
TX ID:
Accbf1591f86c3e0fa1551d21fba489e2224a2432311d9cc26165afab154fb59

http://blockdozer.com/insight/tx/Accbf1591f86c3e0fa1551d21fba489e2224a2432311d9cc26165afab154fb59

How can i help to cancel / cancel this transaction?
Along with this I attach the screen shot of the transaction

please help me, I really need that money, because it is my salary for 2 months ... 
![untitled](https://user-images.githubusercontent.com/32460456/31890254-ab848d42-b82c-11e7-90a6-8ff96038fbe2.jpg)

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
