### ISSUE TITLE
Missing Tether transaction

### ISSUE THREAD

**Issue by agisinan** [Blockchair/Blockchair.Support#378]
İ had a Tether transaction 2021/02/18 22:09 date, from binance wallet to coinbase wallet accidently. The amount is missing and i only received 0.00000540 BTC to coinbase wallet. Binance support team tells transaction is success from binance and they can not intervene it when its in blockchain. Coinbase support team tells that Tether is not supported by coinbase and because of this they can not retrieve missing Tether. İm only after to retrieve my Tether amount to my Binance wallet and need help to solve this problem. Thank you !

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair only provides blockchain search and analytics services. We do not process transactions, do not store your funds, and can not help you get your funds back, unfortunately. Thank you for understanding.
