### ISSUE TITLE
Urgent help of Bitcoin cash transfer

### ISSUE THREAD

**Issue by martnart** [Blockchair/Blockchair.Support#38]
Hi, Please i mistakenly sent my bitcoin cash to this address 1G83Dejy7HSrZiuFdeiwjn5Rcv4WeTbins and want it transferred to my bcc address 12Gq1AaWk3p77hGGoWhy36UtYbLxRnaw76

I really need help to transfer it into my wallet.

Thank You
![570308601465446266](https://user-images.githubusercontent.com/33081173/31996864-9a0cb652-b9bc-11e7-8c3d-0640810262b4.png)

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
