### ISSUE TITLE
I've waited more than 19 hours for a doge coin transaction and I m still waiting.

### ISSUE THREAD

**Issue by axt4** [Blockchair/Blockchair.Support#389]
https://blockchair.com/dogecoin/transaction/6e1e539854393b37a7c2063d215c1e5dff8cd2de29d383ca4b23c8d3eefb35bf

**Comment by hasan1910** [comment]
I have same situation

**Comment by Shinso33** [comment]
my problem is the same

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please refer to [FAQ (Q1)](https://blockchair.com/faq) page.
