### ISSUE TITLE
Onaylanmamis transfer

### ISSUE THREAD

**Issue by gamesavas** [Blockchair/Blockchair.Support#395]
Gönderdiğim transfer işlemi 2 gündür onaylanmadi. Bu konu hakkinda madurum bu islem bir an once cozume ulaşsin lutfen
![Screenshot_20210310-142317_Chrome](https://user-images.githubusercontent.com/80398484/110629145-e8841a00-81b4-11eb-9fd3-9d0314aa677d.jpg)

**Comment by firadenqi** [comment]
> Gönderdiğim transfer işlemi 2 gündür onaylanmadi. Bu konu hakkinda madurum bu islem bir an cozume ulutfen
> ![Screenshot_20210310-142317_Chrome](https://user-images.githubusercontent.com/80398484/110629145-e8841a00-81b4-11eb-9fd3-9d0314aa677d.jpg)

**Comment by daria-blockchair** [comment]
Hi! Blockchair only provides blockchain search and analytics services. We do not provide wallet services, we do not process transactions, we do not store your funds. Please refer to our [FAQ (Q1)](https://blockchair.com/faq).
