### ISSUE TITLE
unconfirmed transfer

### ISSUE THREAD

**Issue by volkan34pau** [Blockchair/Blockchair.Support#396]
I sent doge coin from my paribu wallet to my binance wallet 3 days ago but it got stuck in the blockchain network. Can you help me?

Txid : 6e1e539854393b37a7c2063d215c1e5dff8cd2de29d383ca4b23c8d3eefb35bf
#
![Screenshot_2021-03-10-13-44-02-502_com android chrome](https://user-images.githubusercontent.com/80441801/110737428-6b04ec00-823e-11eb-9b22-5a5feb46b0a6.jpg)

**Comment by daria-blockchair** [comment]
Blockchair only provides blockchain search and analytics services. We do not process transactions and do not store your funds. Please refer to our [FAQ (Q1)](https://blockchair.com/faq)
