### ISSUE TITLE
disappearing doge

### ISSUE THREAD

**Issue by Shinso33** [Blockchair/Blockchair.Support#397]
The dogecoin I sent 3 days ago did not provide the pass, it did not return to me either, you are stealing our dogecoin because it is not clear where my dogecoin money went.
![1D42F26E-55DA-428F-91C0-22F6507773DF](https://user-images.githubusercontent.com/80350520/110753548-c2638600-8257-11eb-822d-9bc679ce6a15.png)
![8A0B9B34-DAE8-4719-B34C-1A822AAF9D2C](https://user-images.githubusercontent.com/80350520/110753555-c55e7680-8257-11eb-94f5-807f7b10c8fc.png)
![23F2B0A3-7F39-4E26-B6E1-289B82566857](https://user-images.githubusercontent.com/80350520/110753561-c68fa380-8257-11eb-85b9-2c5cecae5942.png)

**Comment by daria-blockchair** [comment]
Hi, Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
You can check the status of your transaction by searching for its hash on blockchair.com. In case you are not able to find your transaction hash on our platform there might be two reasons for that: 1 - you have an invalid tx hash, 2 - the transaction was dropped out of the mempool. If the transaction was dropped out of the mempool the funds should've remained on the sending address. Please reach out to your wallet or exchange for more information.
