### ISSUE TITLE
BCC Blocks page not reflecting new blocks

### ISSUE THREAD

**Issue by OverlordQ** [Blockchair/Blockchair.Support#4]
https://blockchair.com/bitcoin-cash/blocks shows 478565 as most recent height, whereas the footer shows `Best block: #478566`

**Comment by Har01d** [comment]
Originally we showed the latest block on a separate page, now due to many similar requests we display it on the https://blockchair.com/bitcoin-cash/blocks page. Sorry about the confusion and thanks for the report!
