### ISSUE TITLE
payments were not confirmed after 2 days

### ISSUE THREAD

**Issue by ASEVIL59** [Blockchair/Blockchair.Support#405]
I created 2 payment requests 2 days ago and 1 day ago, but it has not been approved yet.
![Screenshot_20210326_094736_com huawei browser](https://user-images.githubusercontent.com/81406427/112593294-54eb5400-8e18-11eb-98fc-6bcf9283f11f.jpg)
![Screenshot_20210326_094721_com huawei browser](https://user-images.githubusercontent.com/81406427/112593299-56b51780-8e18-11eb-93a5-fb459d59ce22.jpg)

Txid:91e3d925c86e990f02c2fe0c66327602792fadc5c99ea6c0d7047931e00a71eb

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. The transaction [91e3d925c86e990f02c2fe0c66327602792fadc5c99ea6c0d7047931e00a71eb](https://blockchair.com/dogecoin/transaction/91e3d925c86e990f02c2fe0c66327602792fadc5c99ea6c0d7047931e00a71eb) is confirmed. Please contact your wallet or exchange for more information.
