### ISSUE TITLE
payments error

### ISSUE THREAD

**Issue by ayhn0671** [Blockchair/Blockchair.Support#407]
hello i paid during the day but the money has not been transferred to my account
![Ekran Alıntısı1](https://user-images.githubusercontent.com/81022592/113480056-0fbfc580-949b-11eb-96b5-b52db77573bd.PNG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/81022592/113480057-10585c00-949b-11eb-8b74-a3c97bd23b2d.PNG)

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please contact your wallet or exchange for more information.
