### ISSUE TITLE
Bitcoins

### ISSUE THREAD

**Issue by Modusto253** [Blockchair/Blockchair.Support#409]
https://api.blockchair.com/bitcoin/dashboards/xpub/xpub6CUGRUonZSQ4TWtTMmzXdrXDtyPWKikrhko4egpiMZbpiaQL2jkwsB7icqYhZcfDfVxdx4df1890LKnC5fSwqPfgyP3hooxujYzAu3fDVmz?transaction_detail=true

**Comment by mohammadpourzaker** [comment]
https://api.blockchait.com/bitcoin/dashboards/xpub/xpub6CUGRUonZSQ4TWtTMmzXdrXDtyPWKikrhko4egpiMZbpiaQL2jkwsB7icqYhZcfDfVxdx4df1890LKnC5fSwqPfgyP3hooxujYzAu3fDVmz؟transaction_detail=true send/wallt BTC;bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy6

**Comment by Modusto253** [comment]
https://api.blockchair.com/bitvoin/dashboards/xpub/xpub6CUGRUonZSQ4TWtTMmzXdrXDtyPWKikrhko4egpiMZbpiaQL2jkwsB7icqYhZcfDfVxdx4df1890LKnC5fSwqPfgyP3hooxujYzAu3fDVmz?transaction_detail=true send/wallt BT
