### ISSUE TITLE
https://api.blockchair.com/bitcoin/dashboards/xpub/xpub6CUGRUonZSQ4TWtTMmzXdrXDtyPWKikrhko4egpiMZbpiaQL2jkwsB7icqYhZcfDfVxdx4df1890LKnC5fSwqPfgyP3hooxujYzAu3fDVmz؟transaction_detail=true send/wallt BTC;bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy6

### ISSUE THREAD

**Issue by Modusto253** [Blockchair/Blockchair.Support#412]
https://api.blockchair.com/bitcoin/dashboards/xpub/xpub6CUGRUonZSQ4TWtTMmzXdrXDtyPWKikrhko4egpiMZbpiaQL2jkwsB7icqYhZcfDfVxdx4df1890LKnC5fSwqPfgyP3hooxujYzAu3fDVmz؟transaction_detail=true send/wallt BTC;bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy6

_Originally posted by @mohammadpourzaker in https://github.com/Blockchair/Blockchair.Support/issues/409#issuecomment-817130772_

**Comment by mohammadpourzaker** [comment]
https://api.blockchair.com/bitcoin/dashboards/xpub/xpub6CUGRUonZSQ4TWtTMmzXdrXDtyPWKikrhko4egpiMZbpiaQL2jkwsB7icqYhZcfDfVxdx4df1890LKnC5fSwqPfgyP3hooxujYzAu3fDVmz؟transaction_detail=true ارسال / wallt BTC؛  Recipients:
bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy6

**Comment by mohammadpourzaker** [comment]
12dRugNcdxK39288NjcDV4GX7rMsKCGn6B  کد رمزگشایی

**Comment by mohammadpourzaker** [comment]
https://github.com/Blockchair/Blockchair.Support/issues/412#issue-855243416 BTC:0,8967458
bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy6
