### ISSUE TITLE
770

### ISSUE THREAD

**Issue by tap9** [Blockchair/Blockchair.Support#413]
https://poloniex.org/

**Comment by mohammadpourzaker** [comment]
لطفا این کیف پول من و بیت کوین من آزاد کنید من چه غلطی کردم بلاک چین گذاشتم
چه بلایی سر BTC من اومد چکار کردین با پول من شما

در تاریخ سه‌شنبه ۱۳ آوریل ۲۰۲۱،‏ ۱۷:۲۰ tap9 ***@***.***> نوشت:

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Best regards
