### ISSUE TITLE
Success status on Incomplete XRP address and destination tag

### ISSUE THREAD

**Issue by hiimkylepogi** [Blockchair/Blockchair.Support#414]
I'm curious why XRP is needed destination tag but in catex, i found my XRP in withdrawing is only need xrp address. when i withdrawing the funds, the status is successful even no destination tag. how is that happen? 

and what is this status? "tesSuccess"? its just a test?
![xrp3](https://user-images.githubusercontent.com/37624671/114624326-193efe00-9ce3-11eb-94af-4f69474c05b9.png)
![xrp4](https://user-images.githubusercontent.com/37624671/114624328-1a702b00-9ce3-11eb-8eae-cab508a1ed3f.png)
![xrp5](https://user-images.githubusercontent.com/37624671/114624330-1b08c180-9ce3-11eb-864e-8f3d93f7947b.png)

**Comment by Har01d** [comment]
tesSuccess means that the transaction succeeded.
