### ISSUE TITLE
Crypto Funds not received on my coinbase wallet 

### ISSUE THREAD

**Issue by nandishkanes** [Blockchair/Blockchair.Support#416]
I suppose to receive crypto amount of 148.06988900XRP to my coinbase wallet. Until now I don't see anything on my account. It's more than a week I never see my funds yet! I see the transaction was completed on blockchair with Hash ID:
D249606A24AF0827DD4357FF3ADCCD80BE643484679BE53ECF2F77A93C50D87C

I made a ticket#05400267 on coinbase platform and sent tons of emails for the updates but not even getting a single response from coinbase support team till now. I'm frustrated every day by not seeing the funds on my wallet. 

I hope you guys help me on this situation and fix the issue with the transaction. Appreciate your response in this regards. Thank you.

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. The [transaction](https://blockchair.com/ripple/transaction/D249606A24AF0827DD4357FF3ADCCD80BE643484679BE53ECF2F77A93C50D87C) is confirmed. Please contact your receiving wallet for more information. 

Thank you for understanding.
