### ISSUE TITLE
رمز ارز کم شده ولی به مقصد نرسیده

### ISSUE THREAD

**Issue by nasersabeti** [Blockchair/Blockchair.Support#421]
سلام ارز استلار ارسال کردم ممو ثبت نکردم از حسابم کم شده ولی به مقصد نرسیده لطفا کمک کنید

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Best regards
