### ISSUE TITLE
Crypto Funds not received on my wallet

### ISSUE THREAD

**Issue by LG7828** [Blockchair/Blockchair.Support#422]
[2498bb9ac14d23d28d82e6007b047e3e4c6caa2892b8f4d5cd779410f2668506.pdf](https://github.com/Blockchair/Blockchair.Support/files/6348265/2498bb9ac14d23d28d82e6007b047e3e4c6caa2892b8f4d5cd779410f2668506.pdf)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. The transaction [2498bb9ac14d23d28d82e6007b047e3e4c6caa2892b8f4d5cd779410f2668506](https://blockchair.com/bitcoin-cash/transaction/2498bb9ac14d23d28d82e6007b047e3e4c6caa2892b8f4d5cd779410f2668506) is confirmed. Please contact your wallet or exchange for more information.
  
Best regards
