### ISSUE TITLE
Sent stella crypto but it never arrived

### ISSUE THREAD

**Issue by Joybn28** [Blockchair/Blockchair.Support#424]
Stent some crypto to an associate but it never arrived i checked the adress and it all seems correct

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on blockchair.com. If the transaction is not confirmed yet, please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1). If the transaction is confirmed, please contact your receiving wallet or exchange for more information.
  
Best regards
