### ISSUE TITLE
transaction in USDT omni weighs in the status "unconfirmed" for two days

### ISSUE THREAD

**Issue by a-k-github** [Blockchair/Blockchair.Support#425]
the transaction in USD omni weighs in the status "unconfirmed" for two days. Can you explain whether everything is in order and what is the matter? and what is the estimated approval time? Transaction number

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair only displays information regarding transactions that happened in blockchains. We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. For more information please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for further assistance.

Best regards
