### ISSUE TITLE
Speed up Bitcoin transaction

### ISSUE THREAD

**Issue by nanbhan** [Blockchair/Blockchair.Support#427]
TXID transaction: a7031b0f899ce70d7e412cab9ec4bced82f1bf401676401f250d35ff8517489b
Been over a day since this was sent. How long is it going to take and can it be sped up

**Comment by 21selam** [comment]
Txıd işlemi

e29d05ced2a765c742afc5fbf4857b614f84703efc6c102f89e4eda75114c0a2 

Ben buna 220 doge yolladım 23 Nisan 2021 de dogeler gitti gelmedi bu sayfa kimin bu dogelerim neden geri gelmedi

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair just shows transactions from public blockchains (like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for further assistance.
 
Best regards
