### ISSUE TITLE
Wrong recipient 

### ISSUE THREAD

**Issue by wolfpackaaron** [Blockchair/Blockchair.Support#428]
They sent my money to the wrong recipient and wont fix it

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
