### ISSUE TITLE
Request for block IDs of bitcoin

### ISSUE THREAD

**Issue by zsharifian** [Blockchair/Blockchair.Support#429]
To Whom It May Concern:

I am a PhD student working on blockchain systems and need a list of bitcoin block hash and their height and timestamp, from Jan 2020 to end-August 2020.  I would be very grateful if you could help me in this matter.

Best Regards,

**Comment by daria-blockchair** [comment]
Hi @zsharifian, 

Thank you for reaching out! 

You can get this data from our data dumps. For students and academic researchers we generally provide high-speed downloading access for free. Could you please contact us at info@blockahir.com so we can share further details with you?

Looking forward.

Best regards
