### ISSUE TITLE
Forget tage memo xlm

### ISSUE THREAD

**Issue by saeedalone** [Blockchair/Blockchair.Support#431]
Hi.i deposite 738 xlm. And i dont tag memo
Hash:
f2c9a6b4a7fff9eff8715addeb9122d9f22cfa380960429cc13c1f21d5d37dc7
tnx..   memo : 1669390

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please contact your wallet or exchange for more information.

Best regards
