### ISSUE TITLE
Need my transaction confirmed 

### ISSUE THREAD

**Issue by nikki8709** [Blockchair/Blockchair.Support#432]
It's been 2 days and my transaction isn't confirmed https://blockchair.com/bitcoin/transaction/d614e5c6380272402e3cf1542e87dd6f3e16c76fb9bdf11724dc98dd40205e0b

**Comment by spacexcaptain** [comment]
Got the same issue
4e2304c1863fac1720b90bc4ae4b3274cb41e47b1a7950398a0f3d7450013817

**Comment by spacexcaptain** [comment]
https://blockchair.com/dogecoin/transaction/4e2304c1863fac1720b90bc4ae4b3274cb41e47b1a7950398a0f3d7450013817?from=trustwallet

**Comment by nikki8709** [comment]
Mine got confirmed after 3 days

**Comment by spacexcaptain** [comment]
Thx for the feedback bro

**Comment by kuprdimon** [comment]
confirmed and my transaction. pls
https://blockchair.com/ru/dogecoin/transaction/fac395d6ff14dae2c98b902231287886a0ea7fc03e50109c99b57bba428f2482

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and cannot speed up the confirmation process of your transaction. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for further assistance.

Best regards
