### ISSUE TITLE
Funds transferred to wrong recipient 

### ISSUE THREAD

**Issue by wolfpackaaron** [Blockchair/Blockchair.Support#433]
My funds were transferred to the wrong recipient. Can you please undo the transaction, nothing was spent so far and I have no idea who it got transferred to.

**Comment by 21selam** [comment]
220 dogecoin attım beni adres olarak buraya yönlendiriyor 4 gündür mağdurum geri iade edilmedi kime gitti ne oldu bilmiyorum paribu destek ten bilgi aldığım kadarıyla bu site de yada yanlış kişiye yolladım biri yardımcı olsun lütfen

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair just shows transactions from public blockchains (like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and unfortunately, we can not help you get your funds back. 
Irreversibility is one of the fundamental properties of cryptocurrency. If you want to know if there is still a chance to get your funds back, please contact your wallet or exchange. 

Best regards
