### ISSUE TITLE
деньги зависли 

### ISSUE THREAD

**Issue by stalker2184** [Blockchair/Blockchair.Support#434]
хеш   71f14c50fbd7e88a14a05851b61ad357b655c10a67c1e6876c54c7875bf85e66
адрес кошелька     LbWZoH6ezLn8AJc67d6L9Dxnsx5RGxzXH6
Баланс
0.08631642 LTC / 21.31 USD
Последнее получение
5 дней назад

Всего получено
0.47476796 LTC / 115.22 USD
Всего потрачено
0.38845154 LTC / 92.88 USD

Первое / последнее получение
2 месяца назад / 5 дней назад
Первая / последняя трата
2 месяца назад / 9 дней назад

Тип адреса
pubkeyhash

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
