### ISSUE TITLE
pending btc at 10 days

### ISSUE THREAD

**Issue by mohsen588j** [Blockchair/Blockchair.Support#435]
Hello, do not be tired
I transferred bitcoin to my Volt Trust 10 days ago to my Bainance account. Now, after 10 days, an error has not been sent and my balance has not been returned. Please help.

hash id:082aeced083ca292007f1521c6f7d36bb5bdf70463c6dc81d09918485f37355f

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
