### ISSUE TITLE
Перевод завис пожалуйста подтвердите!

### ISSUE THREAD

**Issue by kuprdimon** [Blockchair/Blockchair.Support#437]
хеш -  fac395d6ff14dae2c98b902231287886a0ea7fc03e50109c99b57bba428f2482
адрес кошелька отправки -  DMHrEqbpLfT6TtZcjVDD8Hj4hDDdZxTsFj
Баланс
103.87225434 DOGE
адрес кошелька получения -  D7sTFgnR8RLUecxnQgLwXw2dhPyzqh8wod
Баланс 
102.91225434

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not withhold your funds. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for further assistance.

Best regards
