### ISSUE TITLE
Please confirm the transaction!

### ISSUE THREAD

**Issue by kuprdimon** [Blockchair/Blockchair.Support#438]
hash - fac395d6ff14dae2c98b902231287886a0ea7fc03e50109c99b57bba428f2482
sending wallet address - DMHrEqbpLfT6TtZcjVDD8Hj4hDDdZxTsFj
Balance
103.87225434 DOGE
receiving wallet address - D7sTFgnR8RLUecxnQgLwXw2dhPyzqh8wod
Balance
102.91225434

**Comment by daria-blockchair** [comment]
Hi!

Blockchair just shows transactions from public blockchains (like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, hence we can’t reverse and cancel them, and can't make the confirmation process faster. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for further assistance.
 
Best regards
