### ISSUE TITLE
Dogecoin transaction pending for 3 days.

### ISSUE THREAD

**Issue by timpark901** [Blockchair/Blockchair.Support#439]
I’ve had a transaction on trust wallet that’s been pending for 3 days now and remains unconfirmed on the blockchain. Can I not just cancel this and retrieve my funds? How long could this take realistically? Thanks

**Comment by frigstix** [comment]
I have same problems with doge...

**Comment by kuprdimon** [comment]
And I! Well, below they write that after 3 days it passes, this is from the fact that we set a small commission and our transactions are in the queue, since miners take at first with a larger commission

**Comment by daria-blockchair** [comment]
Hi! 

Blockchair does not process transactions and does not withhold your funds. Miners process transactions based on the transaction fee that is attached to a transaction. The priority is to the transactions with a higher fee. Some wallets support functionality to increase the transaction fee. Please reach out to your wallet or exchange to find out what you can do to make your transaction process faster. Unfortunately, we can not speed up the processing of your transaction.

Best regards
