### ISSUE TITLE
My Bitcoin was possibly Stolen 

### ISSUE THREAD

**Issue by gartek702** [Blockchair/Blockchair.Support#440]
https://blockchair.com/bitcoin/transaction/7048b9fed544eccf86d6ea77f2429b5fddc93b05c25975a8574ac3523b99a529

I uploaded my Bitcoin then gone in a pending stage it’s been days.  Where is my money? Someone please help?
![5CF17813-E132-435E-8DED-502354323C69](https://user-images.githubusercontent.com/83388804/116505731-853b6d80-a870-11eb-890a-65314b660ac4.png)
![D36E4204-A420-472F-871C-32F841D3BA47](https://user-images.githubusercontent.com/83388804/116505734-87053100-a870-11eb-859a-4762e980c2b6.png)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for more information.

Best regards
