### ISSUE TITLE
Bug in a transaction

### ISSUE THREAD

**Issue by frigstix** [Blockchair/Blockchair.Support#441]
The transaction is not transferred for 1.5 days. Writes unconfirmed.

**Comment by frigstix** [comment]
Dogecoin

**Comment by 1234856** [comment]
Je n'ai toujours pas accès à mon compte. Quelqu'un peut me contacter ? Çà fait plus d'un mois que personne ne répond

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not store your money, and cannot help you get it back, unfortunately. We do not process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
