### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by elyassufi** [Blockchair/Blockchair.Support#442]
My deposit from Trust wallet to Binance is 4 days in pending mode
doge coin

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
