### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Eudge** [Blockchair/Blockchair.Support#443]
![Desktop Screenshot 2021 04 30 - 20 48 06 06](https://user-images.githubusercontent.com/83469732/116734147-b72a0c80-a9f5-11eb-9267-caba96776524.png)

When transferring a light coin from a nicehash to a binance, the funds did not come. 8 days have passed

**Comment by 21selam** [comment]
I have transferred 220 dogecoins from paribu for 10 days, the transaction has been confirmed, but here it shows as 0, it has been exactly 10 days, why is it still not reflected or returned, please help me too, please urgent.

https://blockchair.com/dogecoin/transaction/e29d05ced2a765c742afc5fbf4857b614f84703efc6c102f89e4eda75114c0a2

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. The transaction [e29d05ced2a765c742afc5fbf4857b614f84703efc6c102f89e4eda75114c0a2](https://blockchair.com/dogecoin/transaction/e29d05ced2a765c742afc5fbf4857b614f84703efc6c102f89e4eda75114c0a2) is confirmed. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
