### ISSUE TITLE
Transfer split and misplaced

### ISSUE THREAD

**Issue by Baylan13** [Blockchair/Blockchair.Support#447]
I tried transfer from my wallet Bitcon To XMR to a friend's wallet. My transaction was lost I have receipt bit never got the money

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
