### ISSUE TITLE
Doge Coin Pending 

### ISSUE THREAD

**Issue by chirochick** [Blockchair/Blockchair.Support#449]
So I was in pancake swap trying to convert Doge into BNB and it never showed receipt of confirmation. Waited hours nothing. So then I transferred my Doge out of my Trust Wallet into BinanceUS into my dogecoin there bcuz when I tried to do it in pancake swap it showed I had no coins but my wallet showed I did. The transfer said success with this hash that still says unconfirmed a day later. 
19a4e9b5b964f3d7a276d186cdb3291415f919755d497d3ab899eea3c220e3ff
Please help! I even have the pdf receipt showing the amounts but nothing!

**Comment by chirochick** [comment]
Here is the first one through pancake swap that I did but the money never showed up. 

0xebb8b259eab3d32766587829a039da12f76a46bf21e1a1761f96e70ba0071b2f

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
Regarding slow or unconfirmed transactions, please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1). For more information, please contact your wallet or exchange.
 
Thank you for understanding.
 
Best regards
