### ISSUE TITLE
Dogecoin transfer unconfirmed 

### ISSUE THREAD

**Issue by dogenot** [Blockchair/Blockchair.Support#450]
Hi,

I have a transfer of doge from trust wallet to atomic wallet which is still unconfirmed. Please advise. What can I do?

hash:
aa3de7afca091ead174b79ecbd6679e2ee2c9a3faf005a8e620efaa183fd9216

**Comment by spacexcaptain** [comment]
I have the same already 8days and keeping being rejected...

**Comment by alecobama** [comment]
Mine is doing the same thing where r my funds

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. 

Miners process transactions based on the transaction fee that is attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. Some wallets support functionality to increase the transaction fee. Please reach out to your wallet or exchange to find out what you can do to make your transaction process faster. We cannot do anything to process your transaction faster.

Thank you for understanding.
 
Best regards
