### ISSUE TITLE
Dogecoin Deposit Unconfirmed 

### ISSUE THREAD

**Issue by eli221** [Blockchair/Blockchair.Support#453]
Hello. I’m contacting you regarding a Dogecoin deposit that I made via Trust Wallet to Binance more than 8 ago and I haven’t received confirmation yet. I attached the receipt and TXID info. The Block ID is the following:Priority: 3310/4053  Please get back to me ASAP I’m very concerned about the delay of the transaction. Thank you. 
![B17DAB00-F47A-4598-93EC-D36735F97386](https://user-images.githubusercontent.com/83683238/117091749-46069400-ad2a-11eb-88a9-a35501c1102e.png)
![77E66E54-FFCF-421B-B2FC-C1D6366744C4](https://user-images.githubusercontent.com/83683238/117091758-4a32b180-ad2a-11eb-9eb2-1c4e8e91392c.png)

**Comment by mohammadpourzaker** [comment]
از شتاب دهنده برای تایید معامله استفاده نمایید
