### ISSUE TITLE
sendBTC:

### ISSUE THREAD

**Issue by mohammadpourzaker** [Blockchair/Blockchair.Support#454]
sendr:BTC;2f289e0557f38f50604ec6836a08f113e22f513c5d55adc72dac4ab0ccfaca6a
[Bitcoin](www.Bitcoin.com) Recipients:bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy6

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding. 
 
Best regards
