### ISSUE TITLE
doge coin pending

### ISSUE THREAD

**Issue by salehnorouzian** [Blockchair/Blockchair.Support#455]
hi i have transfer doge coin on the other wallet but 10 hours pending in trust wallet i very nervous i hope transfer💔

**Comment by salehnorouzian** [comment]
c94e8b9f5ecdbb14543eae39287060d6600c1ad68231e1ed2b55729e19fb85c6

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
