### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Colethomp-19** [Blockchair/Blockchair.Support#456]
I sent bitcoin to a wallet of mine, but my issue is I forgot what app I've got it on. I was wondering if there is any way of finding out where the wallet is at. I sent aboutb167 dollars to it and meant to do send it to another wallet of mine

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Unfortunately, we don't have the information about the platform on which the address was registered. Nevertheless, if you have your private key, you can import it to another wallet service and get access to your funds.

Thank you for understanding.

Best regards
