### ISSUE TITLE
Transaccion no confirmada Doge 

### ISSUE THREAD

**Issue by rsandoya** [Blockchair/Blockchair.Support#457]
Por favor su ayuda esta transacción tiene más de 18 horas sin confirmar 

cbb4a4377865496f099bbc271a8ad676e04be126e4ac9e9df3660dfeba21869b
![8F20E1B7-DE59-49AF-8128-BFB0F78191B4](https://user-images.githubusercontent.com/83710338/117147474-e97f9500-ad7a-11eb-9eec-49c7a744b69e.png)

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. 

Miners process transactions based on the transaction fee that is attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. Some wallets support functionality to increase the transaction fee. Please reach out to your wallet or exchange to find out what you can do to make your transaction process faster. We cannot do anything to process your transaction faster.

Thank you for understanding.

Best regards
