### ISSUE TITLE
Pending transaction

### ISSUE THREAD

**Issue by ScorSD** [Blockchair/Blockchair.Support#458]
My transaction is stuck due to low commission .. Please cancel my transaction
![Screenshot_20210505-202001_Acrobat for Samsung](https://user-images.githubusercontent.com/83730870/117207245-6bfc6900-adfc-11eb-8288-4b894c71fb0d.jpg)

**Comment by daria-blockchair** [comment]
Hello, 

 
Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. 

Miners process transactions based on the transaction fee that is attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. Some wallets support functionality to increase the transaction fee. Please reach out to your wallet or exchange to find out what you can do to make your transaction process faster. We cannot do anything to process your transaction faster.

Thank you for understanding.

Best regards
