### ISSUE TITLE
Please cancel ASAP I been waiting since 9am. 

### ISSUE THREAD

**Issue by alecobama** [Blockchair/Blockchair.Support#459]
DCG14jyLGjoziQnnPxgsXKbpq7dgo3JrwU

![8B90E00E-1FB8-45D5-B289-8B854C396805](https://user-images.githubusercontent.com/83741955/117235921-a4e50f80-adf5-11eb-8b30-d9c3d68e5cde.png)
![415E1CD2-7A13-4CA6-96D8-5B12AF66BABD](https://user-images.githubusercontent.com/83741955/117235923-a6163c80-adf5-11eb-9a0f-3bb000debd5e.jpeg)

**Comment by daria-blockchair** [comment]
Hello, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, we can't make the confirmation process faster, and we can’t reverse and cancel them. Please contact your wallet or exchange for further assistance.

Thank you for understanding.

Best regards
