### ISSUE TITLE
how many confirmations needs for the payment to be valid?

### ISSUE THREAD

**Issue by bilaljw** [Blockchair/Blockchair.Support#46]
I made this transaction to Bitmain,
BCH transaction ID 

244528434
--

Is this transaction valid?
How long it needs to be valid?

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

Your transaction is valid, the needed number of confirmations depends on the recipient’s policy.
