### ISSUE TITLE
nour

### ISSUE THREAD

**Issue by n1our11** [Blockchair/Blockchair.Support#461]
Pending deal, why wait 3 dayqr5x2pd7sf3fq9k3vrwyeakhmw046v84d5stp4ykuxs and nothing came

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. Please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1) and contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
