### ISSUE TITLE
Pending transactions 

### ISSUE THREAD

**Issue by Temperedkid909** [Blockchair/Blockchair.Support#462]
Please cancel 

hash 

DRvjdw6BG7rWVtxaog3dHocXwGuE2XEoMt

**Comment by esi1679** [comment]
![Screenshot_۲۰۲۱۰۵۰۹-۱۰۴۹۵۴](https://user-images.githubusercontent.com/83898322/117562496-8e201080-b0b4-11eb-9b25-4a62fb582b60.png)
![Screenshot_۲۰۲۱۰۵۰۹-۱۰۴۹۴۷](https://user-images.githubusercontent.com/83898322/117562498-91b39780-b0b4-11eb-8897-bcbacf1743b3.png) please cancle my transaction please

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
