### ISSUE TITLE
PAYMENT

### ISSUE THREAD

**Issue by tasvan** [Blockchair/Blockchair.Support#463]
I sent dogecoin on 06.11.2020 to the following address: D851oKU49jscEw7KpkhiXpn93s6WCdyxur 3477
TXID: aa51e6aecbfb96784896671a6cbc621fc8f10ecb7f949a2c653fa7029f354cb1 This is the process, I can send it back, I am in a very difficult situation.

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. The transaction [aa51e6aecbfb96784896671a6cbc621fc8f10ecb7f949a2c653fa7029f354cb1](https://blockchair.com/dogecoin/transaction/aa51e6aecbfb96784896671a6cbc621fc8f10ecb7f949a2c653fa7029f354cb1) is confirmed. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
