### ISSUE TITLE
Dogecoin not pending

### ISSUE THREAD

**Issue by amroew** [Blockchair/Blockchair.Support#465]
I'm using the app Paribu and transferred 110 dogecoins from my wallet to another wallet. It says successful transaction but i've been waiting and checking for hours and it's not pending on Blockchair.

![Screenshot_20210509-164216_Chrome](https://user-images.githubusercontent.com/83913507/117575580-246f2900-b0eb-11eb-96f8-a8e5bd9ef68c.jpg)

DMLr3ufsuddHfT2Sy8VL9WRLvD7epSXrHt
This is my own hash

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
