### ISSUE TITLE
Stolen Bitcoin

### ISSUE THREAD

**Issue by lijdgoat** [Blockchair/Blockchair.Support#466]
I deposited .006254 Bitcoin to the address 1BTgAY8uztkyRsr32hrP7nAHL6AGS1seXe days ago. I have yet to receive it and this was the last place it was during the transaction. The hash for the transaction is. https://blockchair.com/bitcoin/transaction/2e5b687bb6a37cdb8c4ee30d3fdac57372f3f776cb07de131912e374778c0216
I would like to be able to receive my .006254 either back to the sending address if that is possible

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
