### ISSUE TITLE
Мошенничество с кошельком

### ISSUE THREAD

**Issue by GulnazKhasanova** [Blockchair/Blockchair.Support#468]
9.05.21 отправила 0.05262516 биткоин  на свой кошелек 3GJ2aqzLduPQUtTgV8PiEZMaE2ySG12bqv, но в транзакции номер кошелька 176N4UbM4PszU4kdnB7KpDFg3Pd3xnhwxG  не совпадает с моим. Вот хеш транзакции 1c2e63967b530e4ba4c7ca6304fffa605339207d7da18f72b2cd8bdac1b2d873. Прошу вернуть отправнные 0.05262516 биткоин  

09.05.21 sent 0.05262516 bitcoin to my wallet 3GJ2aqzLduPQUtTgV8PiEZMaE2ySG12bqv, but in the transaction the wallet number 176N4UbM4PszU4kdnB7KpDFg3Pd3xnhwxG does not match mine. Here is the transaction hash 1c2e63967b530e4ba4c7ca6304fffa605339207d7da18f72b2cd8bdac1b2d873. Please return the initial 0.05262516 bitcoin

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
