### ISSUE TITLE
cancle transcration

### ISSUE THREAD

**Issue by esi1679** [Blockchair/Blockchair.Support#469]
![Screenshot_۲۰۲۱۰۵۰۹-۱۰۱۲۳۲](https://user-images.githubusercontent.com/83898322/117664362-f0f9d080-b1b6-11eb-9dea-345a7db00cf4.png)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ (Q2)](https://blockchair.com/faq#q2).

Thank you for understanding. 
 
Best regards
