### ISSUE TITLE
Sent to wrong address

### ISSUE THREAD

**Issue by MDEITRICH** [Blockchair/Blockchair.Support#471]
- [x] My Miniswap Tokens got sent to an unknown address that's not mine. Is it even possible to recover them back? Please help. Thank you![image](https://user-images.githubusercontent.com/72780679/117760643-017c6c00-b1f4-11eb-80c7-5f462adab997.png)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
