### ISSUE TITLE
Never Received my XLM 

### ISSUE THREAD

**Issue by JorgitoFTW** [Blockchair/Blockchair.Support#472]
Hello I transferred my XLM from Trust Wallet to my Coinbase and never received it and I got the right address.

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on blockchair.com. If the transaction is not confirmed yet, please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.
 
Thank you for understanding.
 
Best regards
