### ISSUE TITLE
24 hour and will don't have my funds in my other wallet

### ISSUE THREAD

**Issue by dinka007** [Blockchair/Blockchair.Support#473]
I transferred my XLM from Trust Wallet to my Coinbase and never received it.what info do you need to fix my issue?

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

You can check the status of your transaction by searching its hash on blockchair.com. If the transaction is not confirmed yet, please refer to our [FAQ (Q1)](https://blockchair.com/faq#q1). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.

Best regards
