### ISSUE TITLE
Wrong Address 

### ISSUE THREAD

**Issue by Masi2017** [Blockchair/Blockchair.Support#474]
How Can I get my money Back? Help Please 
![thumbnail](https://user-images.githubusercontent.com/76216218/117839619-63b38c00-b249-11eb-80a4-363adc08aa5c.png)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
Irreversibility is one of the fundamental properties of cryptocurrency. If you want to know if there is still a chance to get your funds back, please contact your wallet or exchange. 

Thank you for understanding.
 
Best regards
