### ISSUE TITLE
долго не подтверждают транзакцию 

### ISSUE THREAD

**Issue by Jeny223** [Blockchair/Blockchair.Support#475]
4 часа уже жду подтверждения. И мою транзакцию уже 3 час держат в середине очереди. df33b830e06c52a16a2c9ba42476ab5a994d333c295a58ca39c1861e02d84019 вот хеш. Решите эту проблему пожалуйста

**Comment by daria-blockchair** [comment]
Hello, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. 

Miners process transactions based on the transaction fee that is attached to a transaction. If your transaction fee is low, it might take some time before the transaction is included in a block. Some wallets support functionality to increase the transaction fee. Please reach out to your wallet or exchange to find out what you can do to make your transaction process faster. We cannot do anything to process your transaction faster.

Thank you for understanding.

Best regards
