### ISSUE TITLE
Error en transacción 

### ISSUE THREAD

**Issue by trustcmrl89** [Blockchair/Blockchair.Support#476]
Hola hace 2 meses realice una transferencia desde mi wallet para adquirir un paquete en una plataforma de trading pero se demoró la transferencia y el enlace desapareció ... No llego a la otra plataforma ni regreso a mi wallet

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
