### ISSUE TITLE
Transfer issue

### ISSUE THREAD

**Issue by petwat757** [Blockchair/Blockchair.Support#478]
I think I have mistakenly sent money to an address on blockchain that is a "holding space" of sorts. When I bought the coin I wanted the address of the sender was "qrx72fhv50u7gwrv43x8rrmfmd4e90x9psrq88fmkz"

That being said I was trying to get rid of my coins and thought that address was my bank so I sent the total amount to it. I see that the amount was received but it's sitting there in an unspent state and I have no idea how to reverse this transaction or what to do next.

I am asking for help or advice from anyone who is able to help.
![Screenshot_20210513-115401_Drive](https://user-images.githubusercontent.com/84143856/118153342-c93b8000-b3e3-11eb-879c-2334266cc2d4.jpg)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. We also don't have the information about the owners of the addresses. Irreversibility is one of the fundamental properties of cryptocurrency. If you want to know if there is still a chance to get your funds back, please contact your wallet or exchange.
 
Thank you for understanding.
 
Best regards
