### ISSUE TITLE
BCH from Coinomi , transfer didn't come to other wallet

### ISSUE THREAD

**Issue by zrin1** [Blockchair/Blockchair.Support#48]
Hello, 

I was sent by mistake some Bitcoin cash from Coinomi to my other wallet (localbtc) but that never come . It passes 72 hours, and it have 1309 confirmations . 
Can  someone help me with that or tell me what to do?

And sorry for my bad english.

Thanks

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

**Comment by zrin1** [comment]
Hello ,

Sorry , but I don't understand where to export and import my private keys?



________________________________
Šalje: Nikita Zhavoronkov <notifications@github.com>
Poslano: 11. studenog 2017. 14:09
Prima: Blockchair/Blockchair.Support
Kopija: zrin1; Author
Predmet: Re: [Blockchair/Blockchair.Support] BCH from Coinomi , transfer didn't come to other wallet (#48)


Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

[https://avatars1.githubusercontent.com/u/22249071?s=400&v=4]<https://github.com/Blockchair/Blockchair.Support/blob/master/README.md>

Blockchair/Blockchair.Support<https://github.com/Blockchair/Blockchair.Support/blob/master/README.md>
github.com
Blockchair.Support - Public repository for issues and feature requests. Submit your favorite bug!
