### ISSUE TITLE
please cancle my transaction

### ISSUE THREAD

**Issue by esi1679** [Blockchair/Blockchair.Support#481]
![Screenshot_۲۰۲۱۰۵۰۹-۱۰۱۲۳۲](https://user-images.githubusercontent.com/83898322/118382179-0bdda200-b608-11eb-8446-3c0a23643a32.png)
please cancle

**Comment by esi1679** [comment]
please cancle my transaction

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. On the screenshot you provided, it is stated that the transaction is confirmed. Irreversibility is one of the fundamental properties of cryptocurrency. If you want to know if there is still a chance to get your funds back, please contact your wallet or exchange. 

Thank you for understanding.

Best regards
