### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by Lakshay024** [Blockchair/Blockchair.Support#482]
Hey,
Can you please cancel this transaction.
Someone stole money from my wallet.
![Screenshot_20210516-161708_Trust 

> 

> 

> `Wallet](https://user-images.githubusercontent.com/27367141/118417644-b2fb2180-b67a-11eb-84c8-4a5a5abdd82b.jpg)
[094ea37d11472d123f8b04bf9f1dd5447f58341128642f83c217e680a26aa997.pdf](https://github.com/Blockchair/Blockchair.Support/files/6490323/094ea37d11472d123f8b04bf9f1dd5447f58341128642f83c217e680a26aa997.pdf)
`

**Comment by 1982-p** [comment]
Witam mi też wyczyścili portfel i używają meila sebastian.noowak@wp.pl a drugi meil to mgrabowski.invest.gmial.com skradli mi ponad 85 tyś zł w historii portfela są wypłaty udukomentowane ale nie wiem jak odzyskać pieniądze czy w ogóle da się coś zrobić chciał bym żeby cofnąć te przelewy

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

Irreversibility is one of the fundamental properties of cryptocurrency. If you want to know if there is still a chance to get your funds back, please contact your wallet or exchange. 

Thank you for understanding.
