### ISSUE TITLE
Pre-BCH fork addresses are showing tripple their "total received" amount.

### ISSUE THREAD

**Issue by adamu** [Blockchair/Blockchair.Support#49]
Any address that had a balance before the BCH fork, shows a `Total received` amount that is 3 times too large.

This is on both the `/search` result page and `/address` page, maybe others too.

For example, an address that received a balance of `1` BTC before the BCH fork will show a `Total received` of `3`.

**Comment by Har01d** [comment]
Hello,

Thanks for reporting! Indeed, for some addresses some of unspent outputs were counted twice or thrice. This has been fixed on both search and address pages for both Bitcoin and Bitcoin Cash.
