### ISSUE TITLE
Моя транзакция висит

### ISSUE THREAD

**Issue by amk9** [Blockchair/Blockchair.Support#490]
Моя транзакция висит более суток ну сколько можно блокчейн

**Comment by amk9** [comment]
9b9afbabf3b0d66bebed72e12dc0b5ee3811ecebc6131f739b73d22570117b5a

**Comment by ella1235** [comment]
У вас прошла транзакция? У меня тожесутки висит

**Comment by daria-blockchair** [comment]
Blockchair только показывает информацию о транзакциях, которые произошли в блокчейнах. Мы не предоставляем услуги кошелька, не храним Ваши деньги. Мы не обрабатываем транзакции и не можем ускорить процесс обработки транзакций. 

Майнеры обрабатывают транзакции на основе комиссии за транзакцию (Transaction fee). Если Ваша комиссия за транзакцию низкая, может пройти больше времени, прежде чем транзакция будет включена в блок. Некоторые кошельки поддерживают функцию увеличения комиссии за транзакцию. Пожалуйста, обратитесь в службу поддержки Вашего кошелька или биржи, чтобы узнать, что Вы можете сделать, чтобы ускорить процесс транзакции. К сожалению, мы ничего не можем сделать, чтобы  Ваша транзакция была обработана быстрее.

Спасибо за понимание.
