### ISSUE TITLE
Почему так долго висят деньги?

### ISSUE THREAD

**Issue by ella1235** [Blockchair/Blockchair.Support#492]
Такое чудо впервые. Пол дня идёт транзакция. Отмените её и верните мне мои деньги

**Comment by ella1235** [comment]
Уже сутки висят

**Comment by daria-blockchair** [comment]
Blockchair только показывает информацию о транзакциях, которые произошли в блокчейнах. Мы не предоставляем услуги кошелька и не храним Ваши деньги. Мы не обрабатываем транзакции и не можем ускорить процесс подтверждения транзакций. Пожалуйста ознакомьтесь с ответом на 1ый вопрос из нашего [FAQ](https://blockchair.com/faq) и свяжитесь со службой поддержки Вашего кошелька или биржи для получения дополнительной информации.
 
Спасибо за понимание.
