### ISSUE TITLE
Отмените транзацию

### ISSUE THREAD

**Issue by ella1235** [Blockchair/Blockchair.Support#493]
Вы мошенники что ли? Отмените по хорошему

**Comment by daria-blockchair** [comment]
Blockchair только показывает информацию о транзакциях, которые произошли в блокчейнах. Мы не предоставляем услуги кошелька, не обрабатываем транзакции и не храним Ваши деньги.  К сожалению, мы не можем помочь вернуть Ваши средства. Пожалуйста свяжитесь со службой поддержки Вашего кошелька или биржи для получения дополнительной информации.
 
Спасибо за понимание.
