### ISSUE TITLE
13 days pending transaction 

### ISSUE THREAD

**Issue by buhnyuy-fomotar** [Blockchair/Blockchair.Support#499]
How do i cancel i btc transfer if its been pending for 13 days

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. Please refer to our [FAQ (Q1)](https://blockchair.com/faq) and contact your wallet or exchange for further assistance. Thank you for understanding.

Best regards
