### ISSUE TITLE
Bitcoin Cash : cryptocurrency for fees and rewards should be in BCH

### ISSUE THREAD

**Issue by k4ms** [Blockchair/Blockchair.Support#5]
While exploring Bitcoin Cash blocks and transactions it appears that every amount/fee/reward is displayed as BTC instead of BCC or BCH. 
Also the USD equivalent is wrong.

**Comment by Har01d** [comment]
The amounts are shown in BCC, but the labels are indeed wrong. We will fix this.

Regarding the USD equivalent — considering very high volatility and difference in price among exchanges, there can be some discrepancies. Currently we update the BCC/USD price once a day.

Thank you for the report!

**Comment by Har01d** [comment]
Fixed, thanks! The ticker symbol is now BCC as recommended by https://www.bitcoincash.org/
The symbol can be changed in the future if the market decides so.

**Comment by k4ms** [comment]
Great job, thanks!
