### ISSUE TITLE
Bug in number of confirmations display

### ISSUE THREAD

**Issue by jgoggan** [Blockchair/Blockchair.Support#50]
Just wanted to report a small bug.  I was watching for confirmations on a transaction and it was up to only 4 or 5 confirmations (was going slow because the fee was lower than intended).  I refreshed and suddenly the count went from 4 or 5 confirmations to "-504002 confirmations".  (Note that the "Included in block" number was 504003.)

Screen grab attached.  Transactions # is 8108f98af9d3d34d576091665b70d9469a6de9fa6c40788f99ed9569cbde623a if you want to see it (but I suspect it'll go away by the time you see this as more confirmations come in).

Note that if I check it in another BCH explorer, it just shows 6 confirmations right now -- looks normal.

Just wanted to let you know.  Thanks.

![blockchair-bug](https://user-images.githubusercontent.com/22042689/32706437-68776424-c7eb-11e7-96bf-0c791c1e3bac.JPG)

**Comment by Har01d** [comment]
Hello,

We were upgrading our node this night, I guess a small outage caused this behaviour.

Thanks!
