### ISSUE TITLE
Trandaction

### ISSUE THREAD

**Issue by frogstomp83** [Blockchair/Blockchair.Support#502]
I deposited my money thru trust wallet, then purchased dogecoin.
It created a Wallet address thru a blockchain.
I accidentally sent it to the block chain address thinking was my putting it back to my checking account but that address doesnt exist in the blockchain.

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information. Thank you for understanding.
 
Best regards
