### ISSUE TITLE
Merhabalar ben blockchair hesabına yanlışlıkla Doge kripto para gönderimi yaptım yanlışlıkla bu paranın tekrar tarafıma gönderilmesini istiyorum lütfen bana yardımcı olur musunuz

### ISSUE THREAD

**Issue by Yahya0123** [Blockchair/Blockchair.Support#503]

**Comment by Yahya0123** [comment]
![image](https://user-images.githubusercontent.com/85297082/120659175-c7b72200-c48e-11eb-92d3-75770a740b1f.jpeg)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
