### ISSUE TITLE
Anonymous Portfolio Tracker

### ISSUE THREAD

**Issue by mariusb** [Blockchair/Blockchair.Support#509]
It seems like the new Anonymous Portfolio Tracker does not support any decimals for any crypto.
Please add support for decimals places to be supported

**Comment by Har01d** [comment]
This has been fixed, thanks for the report. We’re still working on beautifying the portfolio tracker, hang on, it will look even better :)

**Comment by mariusb** [comment]
Thanks, however, the Chrome extension does not get updated when the Anonymous Portfolio Tracker gets updated.  So the web page now works correctly but the extension does not reflect the updated values.

**Comment by P1053094933** [comment]
ในวันที่ ส. 26 มิ.ย. 2021 19:29 น. Marius Bock ***@***.***>
เขียนว่า:

**Comment by mariusb** [comment]
Figure out how to get the Chrome extension to update itself and reflect the correct values
