### ISSUE TITLE
Txid not seen a transaction

### ISSUE THREAD

**Issue by ebukaume** [Blockchair/Blockchair.Support#51]
I made a withdrawal transaction in coinexchange.io and I have not seen my bitcoincash, either I made a mistake of using a bitcoin wallet ID in place of bitcoincash ID or the transaction is hanging in the blockchain. This the withdrawal text ID: 1NMA5j64niSKsqoV2WuyhvWMr5MoHob4tY 
67b37da156a8d1d0e20a09180d5c82c429d79f7b05d761ed13a723780dfbc6b1, that was txid received when withdrawal was marked completed. 
this: https://www.coinexchange.io/withdraw/confirm/1aaab28aa8d342de81962ee514f0bd08, this was the confirmation mail sent to me when I initiated the withdrawal. Please I plead you help track this transaction, thanks.

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
