### ISSUE TITLE
Searching for an address is broken

### ISSUE THREAD

**Issue by magmel48** [Blockchair/Blockchair.Support#512]
After searching completion the result is like the following:

Results for: “xxx”
Found 3 results (2.91 seconds)
Addresses 3

and that's it. There are no results at all with clickable links like it was before (to different blockchains like BCH, BCHA, BSV, etc.).

**Comment by Har01d** [comment]
This has been fixed.

I’d also recommend to change your adblocker as the issue was some adblockers blocking `d-block` CSS class… 🤦

Please check on your side.

**Comment by magmel48** [comment]
great, works ok now, thank you!
