### ISSUE TITLE
The server returned a "501 Not Implemented"

### ISSUE THREAD

**Issue by Andoni-22** [Blockchair/Blockchair.Support#513]
I am trying to acces to my api key, but when y try to login this error ocurred to me:
Oops! An Error Occurred
The server returned a "501 Not Implemented".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

https://blockchair.com/student-pack/auth

**Comment by Har01d** [comment]
This has been fixed, please try again.

**Comment by Har01d** [comment]
Most probably you didn’t save the key. Please reach us out at Info@blockchair.com with your GitHub username mentioning this issue, our sales team will manually send you a key. Thanks.

**Comment by Andoni-22** [comment]
Ok, thanks for your time
