### ISSUE TITLE
Lost my btc 

### ISSUE THREAD

**Issue by Undedfudge** [Blockchair/Blockchair.Support#519]
I sent 1003 usd in btc to the wrong address bc1qxua7cptmpy6er4mspq63dfxz22txqauf3cfdpl

Is it gone forever now? I really messed up & needed that

**Comment by Undedfudge** [comment]
![F8578E9C-D09F-4DD7-AC44-BBACB9DB2CC6](https://user-images.githubusercontent.com/86537613/123527257-956e9e00-d6a3-11eb-9f90-ccdd4743e23e.png)

**Comment by Undedfudge** [comment]
This is the worst week ever, I've lost so much & I'm not looking for pity I just feel very unlucky and thought maybe someone can help with that. My BTC wallet is  3DkouJCYh4N7oTWYcaSxnqyYdF5iF9c5pW

If that person sees this. I gotta sleep now

**Comment by Undedfudge** [comment]
I'll just starve

**Comment by P1053094933** [comment]
คืออะไรคับ

ในวันที่ อา. 27 มิ.ย. 2021 05:26 น. Undedfudge ***@***.***>
เขียนว่า:

**Comment by Undedfudge** [comment]
คุณสามารถช่วยฉันได้ไหม?

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Best regards
