### ISSUE TITLE
XLM transferred from Trust wallet to Binance

### ISSUE THREAD

**Issue by binnybaby90** [Blockchair/Blockchair.Support#520]
I transferred my XLM stellar tokens to Binance account. But I didn’t receive it. Pls help me
![3A2F82AC-87BC-418D-9B81-ADA07522C772](https://user-images.githubusercontent.com/86511072/123530653-f7fc8400-d70d-11eb-9c12-d3cb20742e59.jpeg)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. The transaction [4e1c6366a04619c1793ce8b0e1a29a105ed8c4433d15ebc6a6e32c985e8d80b6](https://blockchair.com/stellar/transaction/4e1c6366a04619c1793ce8b0e1a29a105ed8c4433d15ebc6a6e32c985e8d80b6) is confirmed. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
