### ISSUE TITLE
WRONG ADDRESS

### ISSUE THREAD

**Issue by Zoemama5** [Blockchair/Blockchair.Support#521]
Hello is it possible to get my litecoin back, I sent it to the wrong address and here is the details
ADDRESS: 3KtE8jhgJHCnLqRwAo7L6VMQQ9KxBrroAh
TXID LINK: https://blockchair.com/litecoin/transaction/4940e2026181865cc9a70952cef0e3684fca5cfc32dfd35a6eaff21d494f75d2

![image](https://user-images.githubusercontent.com/60352243/123593678-62eaaf80-d821-11eb-8f49-43f4ae1dd5fd.png)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Best regards
