### ISSUE TITLE
деньги не пришли !

### ISSUE THREAD

**Issue by fsh777** [Blockchair/Blockchair.Support#523]
[TxID](9ce1917e1e4bae8655bcd51dee8b6c175de9f8feee3b0bb9ec712d15c91bfb1f) #

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on blockchair.com. If the transaction is not confirmed yet, please refer to our FAQ, Q: "[Why does it take so long before my transaction is processed?](https://blockchair.com/faq#q0)". If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.
 
Thank you for understanding.
 
Best regards
