### ISSUE TITLE
I have trust wallet trying to figure things out

### ISSUE THREAD

**Issue by anthonyleonard55** [Blockchair/Blockchair.Support#524]
I have trust wallet and I recently had a bunch of crypto like Dodge and  eMax And XRP they recently were all removed and sent out of my account most of them showed that it went back to the block chain but I did not authorize this and I don’t know how to get it back

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
  
Best regards
