### ISSUE TITLE
transaction pending for more than 1 week

### ISSUE THREAD

**Issue by mikemiller1975** [Blockchair/Blockchair.Support#526]
I have a transaction pending for couple of days due to low miner fee, any way I can cancel or speed up it?

**Comment by daria-blockchair** [comment]
Hi!

Blockchair only displays information regarding transactions that happened in blockchains. We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. 

Please refer to our FAQ: "[What can I do to speed up my transaction](https://blockchair.com/faq#q1)?". And contact your wallet or exchange for further assistance.

Thank you for understanding.

Best regards
