### ISSUE TITLE
Is there a way to get the entire UTXO from bitcoin cash?

### ISSUE THREAD

**Issue by floreslorca** [Blockchair/Blockchair.Support#53]
If there is no single query. how can i do this programmatically? If blockchair is inadequate for this. Where can i go?

Thanks.

**Comment by Har01d** [comment]
Hello,

Yes, there’s a query to show all unspent outputs: https://blockchair.com/bitcoin-cash/outputs?q=is_spent(0)#

**Comment by floreslorca** [comment]
Thanks, but how do you do this? Is there a guide for this? Do you use the RPC interface or just query directly on the DB?

**Comment by Har01d** [comment]
You just apply a filter on the “Is spent?” field:

<img width="308" alt="Filter" src="https://user-images.githubusercontent.com/14060856/32751456-0887b89c-c8d7-11e7-879f-e69045e997dc.png">

The interface for that is not super user-friendly right now, but it works :)

**Comment by floreslorca** [comment]
Oh i mean how is blockchair doing it. not through your interface. I assume you have all the utxos on a SQL DB and update them accordingly. did you crawl through all the txs to find all the current utxos?

**Comment by Har01d** [comment]
Yes, the query goes to our database, it's not possible to query a bitcoin node that way.

**Comment by floreslorca** [comment]
thanks im trying to get the # of UTXOS that are below the fee. is there a way to do `COUNT(*)` on this?

**Comment by Har01d** [comment]
You can use the following query: https://api.blockchair.com/bitcoin-cash/outputs?q=is_spent(0),value(..100000000)# (value is set in satoshis).

There's `"total":58706660` in the JSON output. Please note that this is an approximate value. Also please note that our API is not for production use.

**Comment by floreslorca** [comment]
is there a way to just get that "total" without getting the first few blocks. I know you can do that through the gui but not sure how you can through the API

**Comment by Har01d** [comment]
No, currently there's no special API call for this. But it's trivial to extract the needed value from the JSON output of the aforementioned query.
