### ISSUE TITLE
зависла транзакция

### ISSUE THREAD

**Issue by Sveta79** [Blockchair/Blockchair.Support#532]
Отправители
1
384Тч4КY5heftCrjogDT9NWUTViZV4yAc
0,24980996  BTC
8 954,94  долларов США
Получатели
2
1GQcgp8X5qYdQHpifDEfzWiKzzcwS9S6ot
0,03730638  BTC
1337,32  долларов США
3E3h9QQiRRwyeSKpU5HoMWVoZFhmaQCuyV
Изменять
0,21235473  BTC
7 612,28  долларов США

Со слов трейдера эти транзакции зависли на Blockchein.
Что нужно, чтобы переводы поступили мне на эл. кошелек 34HmMhCDVWHwXCp5THLXkQpzLpVZkBVcHf ?

**Comment by daria-blockchair** [comment]
Dear @Sveta79, 

Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. 
If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee. For more information, please refer to our FAQ: "[Why does it take so long before my transaction is processed?](https://blockchair.com/faq#q0)". For further assistance please contact your wallet or exchange.

Thank you for understanding.
 
Best regards
