### ISSUE TITLE
About bitcoin cash

### ISSUE THREAD

**Issue by sabri468** [Blockchair/Blockchair.Support#533]
I wanted to transfer with bitcoin cash, but I accidentally typed my bitcoin wallet code instead of my bitcoin cash wallet code. The cryptocurrency company I use does not support bitcoin cash. My money was left empty. I want my money back please.

Tx: https://explorer.viawallet.com/bch/tx/dbc18240bc1c2c56f9a9074610d4c6f8b14e0a4c373f1eef6e0f0a8c69960116

**Comment by sabri468** [comment]
https://blockchair.com/bitcoin-cash/transaction/dbc18240bc1c2c56f9a9074610d4c6f8b14e0a4c373f1eef6e0f0a8c69960116

**Comment by sabri468** [comment]
please help me.  this money is very important to me

**Comment by daria-blockchair** [comment]
Dear @sabri468, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.
For more information, please refer to our [FAQ](https://blockchair.com/faq#q5): "I sent Bitcoin to a Bitcoin Cash/Bitcoin SV address (or vice versa). Is it possible to retrieve my funds?"
For further assistance please contact your wallet or exchange.

Thank you for understanding.

Kind regards
