### ISSUE TITLE
Transferred LiteCoin from Buyucoin to WazirX mistakenly wrong destination address.

### ISSUE THREAD

**Issue by gaur1982** [Blockchair/Blockchair.Support#538]
Hi,

I transferred 0.18037938 Litecoin from my Buyucoin account to my WazirX account on Wed Jun 30 2021 10:32:46 GMT+0530 (India Standard Time). The transaction hash is "078fab1ef2d4d36f1aeadcf9beece4c00080166a720e0b4eb7b80b88656a116d" and Explorerlink is https://blockchair.com/litecoin/transaction/078fab1ef2d4d36f1aeadcf9beece4c00080166a720e0b4eb7b80b88656a116d. While I made this transaction at that time there is an error on wazirx portal and it copied wrong destination address i.e. "MUQrUTqDch7niLusZ4SxSTAcoawWJK91eT". this destination address is wrong from my side and it doesn't belong to wazirx account. My exact or correct destination address is "MC32rZffUDvz9RAi8dxkQRAqWdYyfcgykW". Is there any way to revert back this transaction or transferred into my correct destination tag?

Buyucoin and Wazirx both can't do anything for me. They both are helpless. You are my last hope.

Thanks,
Gaurav

**Comment by daria-blockchair** [comment]
Dear @gaur1982,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Thank you for understanding.
  
Best regards
