### ISSUE TITLE
Purchase

### ISSUE THREAD

**Issue by Mowjeewowee** [Blockchair/Blockchair.Support#539]
I purchased 55 dollars worth thinking this was the crypto. I purchased this on crypto.com. Is there a way to convert to another crypto?

**Comment by daria-blockchair** [comment]
Dear @Mowjeewowee, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your funds. Please contact your wallet or exchange for further assistance.
 
Thank you for understanding.
  
Best regards
