### ISSUE TITLE
Bitcoin cash transaction stuck in block chain

### ISSUE THREAD

**Issue by ravi6098** [Blockchair/Blockchair.Support#54]
Hello sir,
It's been around 2days since i made bch transaction but still not confirmed, please help me.
My deposit address - 1MRS1zruog2ABH4VTx58rMncYfVVBYi3fB
My Txid - 4bb435e5b4a2484e940f2fc926cea37875353b5415e7769662844fa8cfa5742c

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

Your transaction is confirmed on the blockchain.

**Comment by ravi6098** [comment]
Thanks done
