### ISSUE TITLE
retour de mes bitcoins

### ISSUE THREAD

**Issue by Josianne53** [Blockchair/Blockchair.Support#540]
J'ai envoyé des bitcoins par erreur dans votre site. Comment je peux faire pour les récupérer j'en ai pour 2857$.

J'aimerais que vous me les retourniez à l'adresse suivante : bc1qqz7787cfshyzhek5v6du9c7t9ek40ptnxwg0wa

Ce serait bien gentil à  vous car moi je ne fais pas de trading alors j'aimerais ravoir mes bitcoins svp.

Merci
Josianne53
![blockchair7](https://user-images.githubusercontent.com/67512612/124983633-33e4f280-e006-11eb-80cf-09ea8de03321.png)

**Comment by daria-blockchair** [comment]
Dear @Josianne53, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
For more information please refer to our FAQ: "[Why do I see my money on Blockchair](https://blockchair.com/faq#q4)". 
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Thank you for understanding.

Best regards
