### ISSUE TITLE
Devolver os meus doges 

### ISSUE THREAD

**Issue by Chicao1979** [Blockchair/Blockchair.Support#541]
Bom dia!

Estou a mais de 2 horas esperando minha transação de dogecoin, más até agora não teve ao menos a primeira confirmação.

**Comment by Chicao1979** [comment]
Bom Dia!

Estou a mais de 4horas esperando minha transação de dogecoin, mas até agora não teve ao menos a primeira confirma.

**Comment by Chicao1979** [comment]
Boa tarde

Como posso recuperar meus doges qeu estao aqui, já que não tiveram nenhuma confirmação????

**Comment by daria-blockchair** [comment]
Dear @Chicao1979, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee. For more information please refer to our FAQ: "[Why does it take so long before my transaction is processed?](https://blockchair.com/faq#q0)" and "[What can I do to speed up my transaction?](https://blockchair.com/faq#q1)". For further assistance, please contact the support of your wallet or exchange.

Thank you for understanding.

Best regards
