### ISSUE TITLE
Why can't i get my money back from here, and why is it stuck here in the first place?

### ISSUE THREAD

**Issue by Ahstotal1** [Blockchair/Blockchair.Support#543]
Someone pls help me!!!

**Comment by Josianne53** [comment]
Moi on m'a volé mes bitcoins et je n'ai jamais pu les récupérer

**Comment by mohammadpourzaker** [comment]
چرا من بیت کوین هایم به wallt 
من نمیاد الان هیچ جوابی ب من نمیدهد بیت کوین این لینک ولت من BTC من هست
bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy6

**Comment by daria-blockchair** [comment]
Hi! Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
To learn about why you can see your wallet address and balance on Blockchair, please refer to our FAQ: "[Why do I see my money on Blockchair](https://blockchair.com/faq#q4)"
For more information, please contact your wallet or exchange.
 
Thank you for understanding.
