### ISSUE TITLE
I 

### ISSUE THREAD

**Issue by Kelstar55** [Blockchair/Blockchair.Support#544]
I have had a pending xrp transaction since 7/5/21 why? I can't locate it on bitchair but it is pending in the wallet.

**Comment by daria-blockchair** [comment]
Hi @Kelstar55, 
Blockchair just shows transactions from public blockchains (so like Google is a search engine for the Internet, Blockchair is a search engine for multiple blockchains). We don’t process transactions, so we can’t reverse and cancel them, and can't make the confirmation process faster. 
Please refer to our FAQ:"[Why does it take so long before my transaction is processed?](https://blockchair.com/faq#q0)"

For more information and further assistance, please contact the support of your wallet of exchange.

Thank you for understanding.
