### ISSUE TITLE
لطفا پیگیری کنید چرا بیت کوین من ب کیف پول من نمیاد

### ISSUE THREAD

**Issue by mohammadpourzaker** [Blockchair/Blockchair.Support#545]
Moi on m'a volé mes bitcoins et je n'ai jamais pu les récupérer

_Originally posted by @Josianne53 in https://github.com/Blockchair/Blockchair.Support/issues/543#issuecomment-878219034_
لطفا پیگیری کنید این مشکل بزرگ من را که چرا من بیت کوین هایم ب کیف پولم نمیاد این لینک بیت کوین کیف من هست
bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy6

3MseH3Rik4GyoDnhD4HdfGTu97mGaT6BKp 
لطفا کمک کنید به من

**Comment by daria-blockchair** [comment]
Hi @mohammadpourzaker, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
