### ISSUE TITLE
TRANSACTION  ISSUE

### ISSUE THREAD

**Issue by stanminchel** [Blockchair/Blockchair.Support#56]
Hi, I make transaction in https://changelly.com/transaction/32e8a0580ab8 and my transaction is for exchanging BTC for BCC but I accidently indicate as recipient my BTC wallet address not BCC address and I didnt receive anything in the wallet. Would you help me with this situation what we have to do?
Thank you for your time!
![default -](https://user-images.githubusercontent.com/33673101/32809496-ac27d662-c99f-11e7-9596-1d1ce56b2761.png)

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

**Comment by stanminchel** [comment]
Thank you for your help, would you just clarify in my case I am the recipient and I did export on my BTC wallet address where I have to import now to different BCC wallet or to the same BTC wallet? I use bitcoin.com wallet.
Thank you !!!!

**Comment by Har01d** [comment]
I'm not sure if Bitcoin.com has a Bitcoin Cash wallet, but yes, the idea is to import the keys in any Bitcoin Cash wallet.
