### ISSUE TITLE
BCH address found in /address/ and not found in /addresses/

### ISSUE THREAD

**Issue by DV-13** [Blockchair/Blockchair.Support#566]
https://api.blockchair.com/bitcoin-cash/dashboards/address/1Jxh7ed1kSKGftApo9x7oSeCnk4WCSXdG2
https://api.blockchair.com/bitcoin-cash/dashboards/addresses/1Jxh7ed1kSKGftApo9x7oSeCnk4WCSXdG2

These 2 endpoints should in theory show same data, but multiple addresses endpoint doesn't show any data, while the single address one does.

Result from /address/ endpoint: https://prnt.sc/1h4u06q
Result from /addresses/ endpoint: https://prnt.sc/1h4urax

I'll update the issue if I find more examples.

**Comment by Har01d** [comment]
Yes, this is the intended behaviour outlined in the documentation, only the `address` endpoint supports the old format for keeping backwards compatibility. Please use the cashaddr format for Bitcoin Cash: `https://api.blockchair.com/bitcoin-cash/dashboards/addresses/qrzs9qyjx2fg4wgtwnzg954qye62j8rsluez82wwxd`

**Comment by DV-13** [comment]
Ah, I missed that. Thanks for explanation>
