### ISSUE TITLE
Legacy address stopped working for the ecash/dashboards/address route

### ISSUE THREAD

**Issue by gianchandania** [Blockchair/Blockchair.Support#568]
I have been working on https://api.blockchair.com/ecash/dashboards/address/{address} route for the last few days. This route used to work with the legacy address till yesterday. Today, I tested the same API with legacy address, it is giving me error "Invalid Request" and it is working fine with the ecash format address. Not sure why it was working before if it is supposed to work just with ecash address format. Has anything changed in the last few hours because of which it has stopped supporting the legacy address?

**Comment by Har01d** [comment]
We made a switch several days ago support, and support for the legacy format was turned off. The `address` endpoint still supports the CashAddr format, but this may get turned off too in the future. Please use the `ecash:` format as recommended by eCash developers.

**Comment by gianchandania** [comment]
Thanks for the response
