### ISSUE TITLE
Accidently send 3.7239132 BCH to localbitcoins.com BTC wallet

### ISSUE THREAD

**Issue by sampuk** [Blockchair/Blockchair.Support#57]
Hi,

I have accidently sent 3.7239132 BCH to localbitcoins.com BTC address. Is there a way for me to recover that missing BCH back to my BCH wallet.

Below is the transaction hash:
https://blockchair.com/bitcoin-cash/transaction/c9e702fc2a78eeaaae8df9bf9c6b499156c4b672305f2a90b385515f744eb013

Localbitcoins.com BTC address:
16xb8nQmacYXEYBB8Geh9Mtgfigqwzs7GF

Really need your help to recovery it.

Thank you.

**Comment by sampuk** [comment]
and i know that BCH not go anywhere because that address not exist yet ..

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

**Comment by sampuk** [comment]
i read all FAQ .. but that still not answer my question ..

**Comment by Prof8** [comment]
Sampuk, I have the same problem with a yobit BCH transfer. Please tell me how you were able to get your funds back from the unclaimed wallet. 
Thanks, Prof8

**Comment by sampuk** [comment]
cannot do anything bro .. i also cannot get my BCH back ..

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sampuk** [comment]
cannot do anything bro .. i also cannot get my BCH back ..

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Har01d** [comment]
If the recipient is an exchange, you should contact their support team.
