### ISSUE TITLE
Privacy score is bad maths

### ISSUE THREAD

**Issue by orogvany** [Blockchair/Blockchair.Support#570]
![](https://i.imgur.com/N88qaRd.png)

expected: 51 is !<= 49

actual: 51 is <= 49

**Comment by Har01d** [comment]
This has been fixed, thanks!

**Comment by Mary-debu** [comment]
![6B1883CE-DE7E-47E1-AE43-B2C585AE35C6](https://user-images.githubusercontent.com/82691029/142982276-3c5d2916-1cbe-4983-967a-964f4ebefe4c.jpeg)
![88C83BE9-959A-4675-AAF3-8E7FBC247D06](https://user-images.githubusercontent.com/82691029/142982285-112a11dd-a303-4247-b844-8d00cf5a1558.png)
![CBB4346D-C2E3-4ADE-A412-6D1E1EFFDC28](https://user-images.githubusercontent.com/82691029/142982288-5849fb5e-baa4-423b-84cd-94faf653a690.png)

f9b75dfdf40b44427d2ce53f660eb7cf8ca1962c6083c2b969a172693d8f45a9
