### ISSUE TITLE
Information about the version of clients used by the miners.

### ISSUE THREAD

**Issue by shravan-shandilya** [Blockchair/Blockchair.Support#58]
Is it possible to get information of regarding the version of bitcoin software(typically user-agent string in the 'version' message) .
It would be great to check which version of the consensus rules are used to mine a particular block.However I'm not sure about how this info can be extracted,as this is not part of the blockheader and is purely from the p2p layer.

**Comment by Har01d** [comment]
Hello,

The only way to get this type of information is to analyze the coinbase string and the block version field for each block: https://blockchair.com/bitcoin/blocks#f=id,guessed_miner,miner_votes,coinbase_data,version,version_bits
