### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by calmger** [Blockchair/Blockchair.Support#588]
https://blockchair.com/cardano/transaction/%7BtxId%7D
Oops! An Error Occurred
The server returned a "400 Bad Request".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by Har01d** [comment]
That’s not a valid address, so the server responds with code 400. It would be a good idea to make this page more good-looking though.
