### ISSUE TITLE
How do I transfer funds to another wallet from the wallet that works with bitcoin cache?

### ISSUE THREAD

**Issue by wizardvv** [Blockchair/Blockchair.Support#59]
Проблема такая, положил финансы на свой кошелек 3Mb3v3JiVbW6Z5pRKvfTU3qwMZMPTW7ymr, а он не работает с bitcoin cash. Прошу перевести средства на другой кошелек d7551443-d5cf-4666-9f1b-8ef96f0aca18. Готов оплатить процент за перевод. Прошу помочь с данным переводом. Это все мои средства. Valery Lazarev wizardvv@yandex.ru

**Comment by wizardvv** [comment]
The problem is this, put finances into your purse 3Mb3v3JiVbW6Z5pRKvfTU3qwMZMPTW7ymr, but it does not work with bitcoin cash. Please transfer the funds to another wallet d7551443-d5cf-4666-9f1b-8ef96f0aca18. Willing to pay a percentage of the transfer. Please help with this translation. It's all my money. Valery Lazarev wizardvv@yandex.ru

**Comment by Har01d** [comment]
As our support team already answered by e-mail, Blockchair is not a wallet. Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

If you have private keys for 3Mb3v3JiVbW6Z5pRKvfTU3qwMZMPTW7ymr, it's possible to spend the funds on the Bitcoin Cash blockchain. You just need to export the keys into a Cash-compatible wallet.
