### ISSUE TITLE
how to get a special key for the speed limit of dump?

### ISSUE THREAD

**Issue by Fooooooooooox** [Blockchair/Blockchair.Support#592]
My download speed is limited when I was trying to dump the bitcoin database on https://blockchair.com/dumps. 
It says on the website:  You'd need a special key to download without this limit, if you don't have one, please reach us at <info@blockchair.com>.
I have sent several emails to <info@blockchair.com> , none of which got replied. 
So, how can i get a special key?

**Comment by Har01d** [comment]
Hello,

Generally we respond within 1-2 business day. Most probably your emails haven’t reached our mailbox. Could you please try to use the feedback form here: https://blockchair.com/partnerships
