### ISSUE TITLE
Request to query all transaction data with wallet request

### ISSUE THREAD

**Issue by will-mcdonnell** [Blockchair/Blockchair.Support#597]
Hello Blockchair,

Thanks for building such a robust API. I think for a lot of people's needs, it would be ideal to query all data from each transaction when you enter a wallet address.

For example, when I enter a wallet address, I just see transaction hashes and amounts associated with my wallet and no fees.

But when I send a new request with the transaction hash, I can see all the information (including input and output addresses associated with the transaction. It would be great to feed that info into the wallet address request. Please let me know if there is a way to do this, as it would most certainly benefit many developers.

**Comment by Har01d** [comment]
Hi Will,

The address dashboard reads data from one specific table (outputs), while transaction-related data such as fees is stored in another table (transactions).

There are two possible solutions:
1. Use the `?transaction_details=true` option: it shows a bit more info
2. Use the `https://api.blockchair.com/{:btc_chain}/dashboards/transactions/{:hash1},…,{:hash10}` endpoint that allows to retrieve detailed transaction data for up to 10 transactions at once.
