### ISSUE TITLE
'Learn more' Bad Link

### ISSUE THREAD

**Issue by eljacobsen12** [Blockchair/Blockchair.Support#598]
Missing href for the 'Learn more' hyperlink on [this page](https://blockchair.com/api/plans).

Section: In need of Data Dumps or Full Node Dumps?

**Comment by Har01d** [comment]
Thanks! We’ll fix this in the next update.

**Comment by Josianne53** [comment]
Pourquoi je fais un transfert dans un autre compte bitcoin et c'est dans blockchain ici que ça va?

**Comment by Har01d** [comment]
Fixed, thanks!
