### ISSUE TITLE
Stolen Bitcoins

### ISSUE THREAD

**Issue by Midnight18** [Blockchair/Blockchair.Support#599]
Stolen Bitcoin

**Comment by daria-blockchair** [comment]
Hi @Midnight18,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information. 
Thank you for understanding. 
Best regards
