### ISSUE TITLE
Bitcoin to bitcoin cash Exchange went wrong

### ISSUE THREAD

**Issue by nare4h** [Blockchair/Blockchair.Support#60]
I made an exchange on ShapeShift to exchange my Bitcoins to Bitcoin Cash. These Bitcoin Cash would later be sent to my address. Unfortunately, I did not check twice and had the Bitcoin Cash sent to my Bitcoin address and not Bitcoin Cash address.
Is there a way for me to reclaim these Bitcoin Cash? They are on a Bitcoin Cash address, just not mine. I checked the address and it only holds my Bitcoin Cash, which means it probably does not exist as an address. Is there a way for me to custom creates the address and claims them or how do I get them back?
This is the process of how it went
1.	As BTC in Blockchain.info
2.	Transferred to Bitcoin Cash via ShapeShift
3.	Transferring done, Bitcoin Cash supposed to be sent to my Bitcoin Cash address, to my wallet.btc.com Wallet but after accidentally having written my Bitcoin address and NOT my Bitcoin Cash address, the Bitcoin Cash is now with that address. I can see the cash at the other address but don't know how to get it back.

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
