### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Daiking70** [Blockchair/Blockchair.Support#600]
Hello on 2021-08-08 16:50 I paid BTC 0.00133 to this address but the sum is firm how can I request it do I need help?

**Comment by daria-blockchair** [comment]
Hi @Daiking70 ,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
Thank you for understanding. 
Best regards
