### ISSUE TITLE
Ethereum didn't arrive after exchanging within a blockchain wallet

### ISSUE THREAD

**Issue by Tigran1983** [Blockchair/Blockchair.Support#61]
Hello,
I exchange Bitcoin cash to Ethereum within my wallet 3 days ago, transaction completed, but there is no ethereum arrived to my Ether wallet.
transaction ID is 245123339. Amount to exchange was 1.29 USD.
No arrival of any amount of ether.

Please explain why?

Tigran

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
