### ISSUE TITLE
Inaccurate data about BCH address

### ISSUE THREAD

**Issue by qfavor** [Blockchair/Blockchair.Support#614]
Hello,

When using the API endpoint for checking balances for Bitcoin Cash, I have an address which has been seen previously on the blockchain and which has a balance that is returned as not having one.

API response: https://api.blockchair.com/bitcoin-cash/addresses/balances?addresses=1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

`{"data":[],"context":{"code":200,"source":"A","results":0,"state":702654,"market_price_usd":607.33,"cache":{"live":true,"duration":60,"since":"2021-08-27 09:22:35","until":"2021-08-27 09:23:35","time":null},"api":{"version":"2.0.88","last_major_update":"2021-07-19 00:00:00","next_major_update":null,"documentation":"https:\/\/blockchair.com\/api\/docs","notice":":)"},"server":"BCH3","time":0.2421250343322754,"render_time":0.03126192092895508,"full_time":0.27338695526123047,"request_cost":1.001}}`

Address has balance: https://blockchair.com/bitcoin-cash/address/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

Can you please let me know why this is happening?

Thank you,

**Comment by Har01d** [comment]
The `addresses/balances` endpoint does not support the legacy address format for Bitcoin Cash. Please use CashAddr instead: `https://api.blockchair.com/bitcoin-cash/addresses/balances?addresses=qp3wjpa3tjlj042z2wv7hahsldgwhwy0rq9sywjpyy`
