### ISSUE TITLE
How to check my API Key's remaining calls

### ISSUE THREAD

**Issue by lbphp** [Blockchair/Blockchair.Support#618]
I have puchased an API Key with the Pay-As-You-Go plan.
How can i monitor my calls usage?

**Comment by lbphp** [comment]
Found the link where to check it. Sorry

**Comment by Reki5** [comment]
> I have puchased an API Key with the Pay-As-You-Go plan.
> How can i monitor my calls usage?

**Comment by Reki5** [comment]
Notification
