### ISSUE TITLE
I transferred BTC from my fiat wallet account to HKEx the sender says they sent the receiver saying they haven’t received but my money is gone now. Is it possible to revert my transaction

### ISSUE THREAD

**Issue by rvragavan81** [Blockchair/Blockchair.Support#619]
I transferred BTC from my fiat wallet account to HKEx the sender says they sent the receiver saying they haven’t received but my money is gone now. Is it possible to revert my transaction

**Comment by daria-blockchair** [comment]
Hi @rvragavan81! 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on blockchair.com. If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.

Thank you for understanding.
