### ISSUE TITLE
Zcash wrong number of Shieleded outputs ?

### ISSUE THREAD

**Issue by vamsiikrishna** [Blockchair/Blockchair.Support#620]
https://blockchair.com/zcash/transaction/1e16ee0732744d3a6bedf1f3a3b16d66c46354b78cd915412c0bc7ab8ca2b309

This TX has 2 Shieleded outputs. Currently show as 1 

![image](https://user-images.githubusercontent.com/554887/131668472-ab864d09-3d89-48a2-be83-b2a938cf5f61.png)

**Comment by vamsiikrishna** [comment]
Shieleded outputs seems to be wrong in general, I checked out a couple more txs

TX: 00050f6582dba82305b2d5d25332445293f6cd784c829446704891167806a89f -- this has 6 Shieleded outputs

**Comment by jaysonmald35** [comment]
Help
