### ISSUE TITLE
Transaction refund

### ISSUE THREAD

**Issue by nathanpham723** [Blockchair/Blockchair.Support#623]
Hi, i think i have been scammed. This man had linked me to moonpay in order to get a profit from bitcoin. I would like to hopefully get my money back if that is possible.

Kind Regards ,
Nathan

**Comment by poojason** [comment]
Yes plz help me with my balance litecoin is refund my money ro

**Comment by Panda1228** [comment]
![Screenshot_20210907-173720_Chrome](https://user-images.githubusercontent.com/90288185/132417081-1ee031ec-cf29-4e1e-85f5-a86fb090da75.jpg)
![Screenshot_20210906-233825_Chrome](https://user-images.githubusercontent.com/90288185/132417083-f00232f3-264f-4d9f-8aa5-911b56c46f65.jpg)
![Screenshot_20210906-233653_Chrome](https://user-images.githubusercontent.com/90288185/132417085-3dbeb343-bbf2-479b-97b3-9e08d0d4b5b9.jpg)
![Screenshot_20210906-233552_Chrome](https://user-images.githubusercontent.com/90288185/132417086-8015e56f-dc8b-476d-8fae-8fcba7a28c78.jpg)

**Comment by Panda1228** [comment]
Those are photos of my proof of what they have stolen from me and I think I need a good lawyer and the State Attorney's Office is going after them as well for scamming,, internet theft and get my coins back. I need Github to help me fast get the rest of my Bitcoin and Lithcoin please

**Comment by Panda1228** [comment]
> Hi, i think i have been scammed. This man had linked me to moonpay in order to get a profit from bitcoin. I would like to hopefully get my money back if that is possible.
> 
> Kind Regards ,
> Nathan

I know the feeling, see my comments below.

**Comment by daria-blockchair** [comment]
Dear @nathanpham723, @poojason, @Panda1228, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Please note, Blockchair team will never contact you first and will never ask you to transfer your funds. Please be aware of scammers and do not fall for their schemes.
 
Thank you for understanding.
