### ISSUE TITLE
I like help to retrieve an wrong withdraw

### ISSUE THREAD

**Issue by Intrexium2** [Blockchair/Blockchair.Support#624]
I did a wrong withdraw to the wrong address and need help how to reverse it
![2021-09-07 12_46_42-Transaction history - Wallet - Binance](https://user-images.githubusercontent.com/90254654/132336426-d4fc2ca9-74c1-4e4e-9cf9-bdcbbaa2aa7e.png)
![2021-09-07 12_50_48-Bitcoin _ Transaction _ e29426904cf8e2e0c0952070d9704bbc4862bcb0aa8d662cd399eec2](https://user-images.githubusercontent.com/90254654/132336556-378c2bfd-9735-48af-b0cb-2613f60e3ff3.png)
I do not know where the money went so I need your help

**Comment by Intrexium2** [comment]
e29426904cf8e2e0c0952070d9704bbc4862bcb0aa8d662cd399eec2180f72fa

**Comment by Intrexium2** [comment]
I love to get any reply

**Comment by daria-blockchair** [comment]
Hi @Intrexium2,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
 
Thank you for understanding.
