### ISSUE TITLE
How to I transfer my BCH

### ISSUE THREAD

**Issue by HerbLowe** [Blockchair/Blockchair.Support#625]
It was not supposed to go to blockchair it was supposed to go to my crypto wallet.
Please advise on how I can fix this so I don't have BCH sitting where I cannot access it.
Herb Lowe
![Screenshot_20210907-171318_Chrome](https://user-images.githubusercontent.com/90289649/132422061-da46fc1d-2b78-44e1-9be0-85e0a38fc85b.jpg)

**Comment by daria-blockchair** [comment]
Hi @HerbLowe,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. To learn more about why you can see your address and balance on Blockchair, please refer to our [FAQ](https://blockchair.com/faq#q4). For more information please contact your wallet or exchange.
 
Thank you for understanding.
