### ISSUE TITLE
How can i withdraw my bitcoin and transfer it to my abra wallet?

### ISSUE THREAD

**Issue by Bitmillions** [Blockchair/Blockchair.Support#626]
Please help me to withdraw my bitcoin and transfer it to my abra wallet id?

**Comment by Bitmillions** [comment]
How can i transfer my bitcoin of 3 into my exchangetally.com or abra wallet?

**Comment by daria-blockchair** [comment]
Hi @Bitmillions!

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
