### ISSUE TITLE
Transection problem

### ISSUE THREAD

**Issue by Sumudunimesh67** [Blockchair/Blockchair.Support#628]
I made the purchase, but the payment was made to another wallet belonging to you, with which I previously deposited money
3.5 LTC
Transaction ID
e81e851c3f98b12304a21b6ce4e14b6222517dd567f84710cfe7b8eea0e8b3c0
Address
MS66UvMHg57bmy8h8e2BSwLt81AiYoHUSH 
My Email: sumudunimesh67@gmail.com
Name: sumudu nimesh
I want money back to the address
MVCLUm1tTiKvFYdkw4VrN56vPWzw28ZocH

**Comment by Sumudunimesh67** [comment]
I made the purchase, but the payment was made to another wallet belonging to you, with which I previously deposited money
3.5 LTC
Transaction ID
e81e851c3f98b12304a21b6ce4e14b6222517dd567f84710cfe7b8eea0e8b3c0
Address
MS66UvMHg57bmy8h8e2BSwLt81AiYoHUSH
My Email: sumudunimesh67@gmail.com
Name: sumudu nimesh
I want money back to the address
MVCLUm1tTiKvFYdkw4VrN56vPWzw28ZocH

**Comment by daria-blockchair** [comment]
Hi @Sumudunimesh67,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
To learn more about why you can see your address and balance on blockchair, please refer to our [FAQ](https://blockchair.com/faq#q4). For more information please contact your wallet or exchange.
 
Thank you for understanding.
