### ISSUE TITLE
Fraud Scam.

### ISSUE THREAD

**Issue by patel017** [Blockchair/Blockchair.Support#629]
Transaction ID: b88b142f14fe534e6ca81abca0c97c4a82d3aaf1d5a88f3250822348b7d97561

Wallet address of spammer: LL17p4WdFepgiTV1ou6v1VAkBsinboRjUA

Total 70 LTC - fraud scamster need to tract coin back

The person in fraudster have proof with me and companied to police. Can you recover the LTC and give it back to me or some arrangment if i can prove that i was scammed..

**Comment by patel017** [comment]
Transaction ID: b88b142f14fe534e6ca81abca0c97c4a82d3aaf1d5a88f3250822348b7d97561

Wallet address of spammer: LL17p4WdFepgiTV1ou6v1VAkBsinboRjUA

Total 70 LTC - fraud scamster need to tract coin back

The person in fraudster have proof with me and companied to police. Can you recover the LTC and give it back to me or some arrangment if i can prove that i was scammed..

**Comment by daria-blockchair** [comment]
Dear @patel017, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
 
Thank you for understanding.
