### ISSUE TITLE
Issues with transaction.

### ISSUE THREAD

**Issue by kdstevie23** [Blockchair/Blockchair.Support#630]
Ive recently put some of my bitcoin wallet into this website in exchange for a currency in a different one. the money was taken out of my wallet but then disappeared??? Let me know if we can do anything to get this resolved or get the amount of bitcoin back into my wallet. thanks.

**Comment by kdstevie23** [comment]
d9614a3a6ea13ebc0ab32b280b97413982ee267a97de411c42cedc8ea442b3c6


That is the transaction hash.

**Comment by daria-blockchair** [comment]
Hi @kdstevie23,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Please note, Blockchair team will never contact you first and ask you to transfer your funds.  

Thank you for understanding.
