### ISSUE TITLE
Cant access my bitcoin 

### ISSUE THREAD

**Issue by Tobiasjr805** [Blockchair/Blockchair.Support#632]
I need help relocating my missing funds..I provided the address but can't access my funds

**Comment by daria-blockchair** [comment]
Hi @Tobiasjr805,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
