### ISSUE TITLE
vol de btc 

### ISSUE THREAD

**Issue by master0404** [Blockchair/Blockchair.Support#634]
this btc address was used to steal 0.02 btc to my wallet ( 3ALUab8WPWq54WEGR8c7nUA6w9XsdDDfCa ) https://blockchair.com/bitcoin/transaction/7a0734d32adf3e65547b95761f831505db3cc286f693d9ed5bbdf391de860d7f

Transaction hash
7a0734d32adf3e65547b95761f831505db3cc286f693d9ed5bbdf391de860d7f
Amount transacted
0.02229671BTC
1,074.37USD
Transaction fee
0.00001665BTC
0.80USD
Fee per vbyte
9satoshi
9 hours ago
Sep 16, 2021 2:36 AMUTC    

Thank you for help.

**Comment by daria-blockchair** [comment]
HI @master0404, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. 

Thank you for understanding.
