### ISSUE TITLE
[Minor] News Aggregator API Documentation Missing

### ISSUE THREAD

**Issue by dsmyda** [Blockchair/Blockchair.Support#636]
In your API docs (https://blockchair.com/api/docs), the News aggregator section doesn't actually link to another page unlike the other section headers.

And the "news list infinitable" link redirects to some random transaction score page.

**Comment by daria-blockchair** [comment]
Hi @dsmyda, 

Thank you for reporting this issue. We'll fix it shortly

**Comment by Har01d** [comment]
This has been fixed, thanks!
