### ISSUE TITLE
Прошу вернуть мои биткойны

### ISSUE THREAD

**Issue by Popart46433** [Blockchair/Blockchair.Support#641]
Сделал транзакцию на другой крипто кошелёк, а биткоин так и не пришёл, прошу вернуть его

**Comment by daria-blockchair** [comment]
Dear @Popart46433, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
