### ISSUE TITLE
Filter https://api.blockchair.com/bitcoin/stats output with jq

### ISSUE THREAD

**Issue by PsySc0rpi0n** [Blockchair/Blockchair.Support#643]
Hello.

I was trying to fetch the block height from Blockchair API using curl and pipping it through jq but I'm getting some output I don't know how to exclude.

Is there an easier way to fetch the block height other than this command:
```
$ curl https://api.blockchair.com/bitcoin/stats | jq -r '.data | .blocks'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1795    0  1795    0     0   2506      0 --:--:-- --:--:-- --:--:--  2503
702331
```

I don't need the first three lines. I just need the block height number.

**Comment by DiFronzo** [comment]
You can just simply do the following:

```bash
$ curl -s https://api.blockchair.com/bitcoin/stats | jq '.data.blocks'
702399
```

**Comment by PsySc0rpi0n** [comment]
Thank you. That's it.
Solved
