### ISSUE TITLE
Zcash Block Explorer Not Updating

### ISSUE THREAD

**Issue by steven-ecc** [Blockchair/Blockchair.Support#647]
zcashd Version 4.4.1 reached End-of-Service (EOS) halt earlier today. On September 23rd, we released zcashd version 4.5.0 and on September 29th, released zcashd version 4.5.1. Version 4.5.1 is a required update for all testnet nodes, and is highly recommended for mainnet nodes if you are using the getbalance RPC method. More information can be found in our release blog posts:

[New Release 4.5.0](https://electriccoin.co/blog/new-release-4-5-0/)
[New Release 4.5.1](https://electriccoin.co/blog/new-release-4-5-1/)

Please let me know if you have any questions and thanks for supporting Zcash!

**Comment by Har01d** [comment]
We’ve upgraded to v.4.5.1, thanks!

**Comment by steven-ecc** [comment]
Thanks for the quick turnaround!
