### ISSUE TITLE
CERT_HAS_EXPIRED issue

### ISSUE THREAD

**Issue by bitchin** [Blockchair/Blockchair.Support#648]
we got CERT_HAS_EXPIRED?

**Comment by Har01d** [comment]
You’d need to update your root certificates. The old root certificate for Let’s Encrypt that we use expired on September 30th. So on some older systems like Debian 7 or Windows XP lots of websites are not available. 

https://docs.certifytheweb.com/docs/kb/kb-202109-letsencrypt/
https://borncity.com/win/2021/09/30/sept-30-2021-will-we-see-trouble-with-old-lets-encrypt-certificates/

While we plan to switch to another certificate provider, another solution which can be implemented client-side right now is to ignore the validity of the certificate.
