### ISSUE TITLE
Transection not confirmed by 21 days

### ISSUE THREAD

**Issue by rahman19769** [Blockchair/Blockchair.Support#65]
Dear 
 I have made one transaction from my BTC wallet to BTCH cash wallet but 21 days gone yet to confirmed transaction,detail below  
transaction ID 
244973944

https://blockchair.com/bitcoin-cash/block/505589

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
