### ISSUE TITLE
BTC0 server causes 500 error

### ISSUE THREAD

**Issue by Radiokot** [Blockchair/Blockchair.Support#655]
Hi. We are making large multiaddress Bitcoin requests like this in our wallet:
`https://api.blockchair.com/bitcoin/dashboards/addresses/18ks4kg7kcemJgGnEH62msVRtbvgS6LAkR,1rykmmL2LzUS5QTyete531oKp8TTYKq6T,1FMRau5Gh8L21EQnjssP39JormYRqF5ygp,18qucAqGtwdiLs66GotL8NFjLnGj6Zu1pW,1KcAFUaJJFvyYPq7jorWU71v4mYwyAf3o9,17ngDUvhrxp7bzLWz7mmo4nYao6i1hYDuG,16mjDdzW1BUrzM42PRGRaA2oEY7pEuGSqe,14CKdbowZBCSRVTyDZDBB7t172a11Ea5eT,1NhJUrujQLFtSQYvfiHfRGR7zWAA5xGcqN,1xZxWJi3tonMti6CcM4qeapXKsGr8N3A2,14M5AKMBo1128iwM9F6xrt6PXyR8mapbjr,1DxvcGmh4pGy9KEvaHU4XYKJ7WJ4FRfdE9,14Ga2dL2YwemJgi815YV4Yajk6jjegHCLF,1HGs11YwcFcGzsuDF3cpDqbDnYDSHhokYt,13dbFFGUiSYQTpzbXBpQ9d8qmvLPExDZKF,1DWmdtuTmZ1sg5M3ibSkekjqDbjNy6aExq,1KjX9DoU6REZtoXozForZR6Hvu38kquhmz,12ju8p2C5vHveU4cjaMKNX4C5igN58zqmP,1ATUf3HJ9bHnMvy4A7VGET9VKbyASrpvsP,13uNQokm8fpXrMncyB42H7XdsgQzBzbdo4,1HmFBLcg6aFbBjfvwSpkzNMXgu1Cc7DFAC,1ECQB5tvNKJZm4rzjXJk4Q6Dx14KY4Mb8Q,1CkX54BGbUzSYoqtf5rscZAKPgDEBEMwXj,1A3hXrYkGjvnVoNLeqfBiQPRG9P5Aikbjn,1NktLqTP9bGqJDXzhokrvvmm54iZcV3bTL,12oTSc6ZyRkHhCrAjSu2kQk5H4KunzKHi1,1MBHGHBGRTh5YBwzCjnN8nrdBchcnbQqeU,186UwvoNCzbi6xmXFiMruGfHy6kj1zqPBn,1A1AsZ9yTmGnRmRipTiiPeQbcCxae8687b,1FDWkMuv7xoJuD7PN5Kxi8S8mFZUFJVLXj,1M57c5StiWrihDp2iSx4LQqrjuhp65Rjpw,14kMPUYBKtBB621xsixTVA4hpBH1o1B5KB,16bzteETRCRRB2LCiFuhNPE4GoL5w9TZYx,14LYrpRX4tvE55G23zucWSx1PXwuQq3uWE,12HHg7JfnnvQeoGP4D8KoY74PuA1qgxiV4,1BDxNfpGcQCKaLd6MT5wo46nbfvvbBt2Yb,1M6tkGYA6NSWaoypCF2F2usyL613XxdPgZ,1HW1VhWXtEBzLaRe8W3CBMxvNEfuU7mfHP,19qzKDSzJ59CVWDuv6KzX47nFkn22fdZig,194rKgHxALNT3WFh2BGQhzC42KVbXqWVDn,1LACHQ4wch98ofo6BVsG6hsH6m6g6548Mo,1vu8fm4B6CztQLyXc2SiPoyVNMYT4nkVG,14tZRorvrP56vodkpffjHytic1cocH9hjb,14dsf6Rwt838fAzPCswJN8pufVnNsf7C4E,1EK1foz25d4Y3rYNjMKY2cjLiYjCoFfwNN,1AfUuZ9dytQa8MMsePt7vg5QdrAFnLPRSe,1PjB8ipSjMT51yLEJiCxwxWF1CfXuCzV2v,13YG7veKRbDduGQuBCaBQ29TxnyU7B9zHx,1GXpFYKLdMMwByXFA1DmrEEy5PZCNrv4s5,16tC4nxVfR8JwWcgrr35oox6cbYr4rVtqY,1G3QBDSJpPV9XGXo1SqPPZn4JHG1nF3Jkp/?transaction_details=true&offset=0,0&limit=50,0&key=*******`

For the last few days, when the response comes from `BTC0` server, it is always a 500 Internal server error, sometimes with 60 s. timeout. However, when the request is served by `BTC3` server, it is successful. The same request can return both 500 and success if you replay it multiple times. Examples below:

![image](https://user-images.githubusercontent.com/5675681/136937751-d95dfb23-8055-4c01-a0f1-a5f0c635ca77.png)
![image](https://user-images.githubusercontent.com/5675681/136937773-2023fb0a-9140-4cf1-b563-cc52231cad34.png)

**Comment by Har01d** [comment]
Earlier today we had a partial outage of one of our Bitcoin servers, this is now resolved. Sorry for the inconvenience.

**Comment by Har01d** [comment]
We implemented some optimizations, so response times should be better now. We'll also be deploying new servers to keep up with the constantly increasing load.
