### ISSUE TITLE
Tran section till pending for 21 days

### ISSUE THREAD

**Issue by rahman19769** [Blockchair/Blockchair.Support#66]
Dear
 I had  made an transaction from my BTC wallet but till not fund transfer to payee account or BTC cash wallet details given below 
General Info
--
Id | 244973944
Hash (txid) | eddeabf583dfcbcfb34efb7cd2bcacb6593b09cdcb9d41ba531b365a976907a9
Included in block | 505589 | 2993 confirmations
Time (UTC) | 2017-11-24 14:46 (21 days ago)
Coindays destroyed | 0.74
Input count | 8
Output count | 1
Input total | 0.00640165 BCH* | 10.56 USD
Output total | 0.00637725 BCH* | 10.52 USD
Fee | 0.00002440 BCH* | 0.04 USD
Fee per kB | 0.00001992 BCH* | 0.03 USD

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
