### ISSUE TITLE
SCAM!  SCAM! SCAM!

### ISSUE THREAD

**Issue by 75taylor** [Blockchair/Blockchair.Support#661]
Who do I need to speak to regarding a scammer that stole money from me tonight pretending to be someone they were not??  $1000 to be exact.  I have reported it and doing a police report in the morning.

**Comment by SysopWith10000Reps** [comment]
I was taken for 750 cardano by this wallet addr1qyv8datk4m0c36ev5n38flhm5lv9sw0a20x4zdmvt7hh8y8z47af7rt30k09ycuvu2frxd85hd6qw3y5mj6dc28z8uxqwevzsf   can you help me track them!!

**Comment by daria-blockchair** [comment]
Hi @75taylor, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

We don't have any information about the owners of the addresses. I am sorry you've been scammed but unfortunately, we are not able to help get your funds back.
