### ISSUE TITLE
dolandırıldım lütfen yardım.

### ISSUE THREAD

**Issue by cipsyali** [Blockchair/Blockchair.Support#664]
eb9abba93d040a0249ea36d570104dcf006c8b1df284817da7be2501a15b6a04
tarafından dolandırıldım.

**Comment by cipsyali** [comment]
yardım lutfen

**Comment by daria-blockchair** [comment]
@cipsyali hi, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
