### ISSUE TITLE
Link URLs incorrect for transactions on eCash Block page

### ISSUE THREAD

**Issue by vinarmani** [Blockchair/Blockchair.Support#669]
The link URLs on the page for a given eCash block uses the block hash instead of the transaction hash and, thus, all links are 404 if clicked.

For example, on page 

https://blockchair.com/ecash/block/711240 

the coinbase transaction url is

https://blockchair.com/ecash/transaction/000000000000000012fdb37cf82bd9ef8f0143cdb458c9830898a9b318a35b0e

when it should properly be

https://blockchair.com/ecash/transaction/b37414b57cacc89509102b5eea96b109344de9eeca2fa65187fe19c41b9e86d0

**Comment by vinarmani** [comment]
This appears to now be fixed

**Comment by Har01d** [comment]
Thanks!
