### ISSUE TITLE
transaction 13fXodEjEvGSCAg8p2RWwzR5ekcXK5b7F7 not succeeded

### ISSUE THREAD

**Issue by EdgarPius** [Blockchair/Blockchair.Support#67]
my transaction from https://blockchair.com/bitcoin-cash/address/13fXodEjEvGSCAg8p2RWwzR5ekcXK5b7F7 to https://blockchair.com/bitcoin-cash/address/13hrKJWB5Ch5nVp4mnUyaGqtaswbNcs8hk did not succeed. the bitcoins where removed from my account, but the receiver did not received the payment.

Your order total: 0,01014424 BTC
Amount received: 0,00 BTC
Payment address: 13hrKJWB5Ch5nVp4mnUyaGqtaswbNcs8hk
Amount missing: 0,01014424 BTC

**Comment by ghost** [comment]
from the receiver:

https://www.smartbit.com.au/address/13hrKJWB5Ch5nVp4mnUyaGqtaswbNcs8hk
Als het wel bij U is afgeschreven door de bitcoin provider moet U hun even mailen. het is niet bij ons maar dan nog bij hun, er staat ook niets in het confirmatie proces
Mvg
ANgela
