### ISSUE TITLE
Any chance of returning my fund back into my bitcoin wirex account? 

### ISSUE THREAD

**Issue by matarawiri** [Blockchair/Blockchair.Support#670]
Hi,
I am wondering if you're able to find where my fund gone to. If you are able to put it back into my bitcoin wirex. 

My email is matarawiri82@gmail.com

Regards

Mata Rawiri

<img width="1367" alt="Screen Shot 2021-10-30 at 9 53 27 pm" src="https://user-images.githubusercontent.com/93429965/139530113-fc1538c8-a72a-4d53-ac44-ea72347fac2c.png">

**Comment by daria-blockchair** [comment]
Hi @matarawiri, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and cannot help you get your funds back, unfortunately.
