### ISSUE TITLE
Stella Lumens still in Blockchair

### ISSUE THREAD

**Issue by stukaroa** [Blockchair/Blockchair.Support#671]
Hi there,

I am following up on a transfer I made on 20 August 2021 and still have not received it in my desired wirex wallet.

I have attached all relevant documents and screenshots for your information as proof of transfer made but was not received in desired wallet.

My email address is: susan.tukaroa@gmail.com

Kind Regards,

Susan Tukaroa

![Uploading Blockchair transaction.png…](
[Blockchair Receipt - XLM Transfer - 20.08.2021.pdf](https://github.com/Blockchair/Blockchair.Support/files/7446347/Blockchair.Receipt.-.XLM.Transfer.-.20.08.2021.pdf)
)
![Coin Jar - Stellar Lumens sent address](https://user-images.githubusercontent.com/93430192/139530339-ee1c9174-4fb1-4fc3-b85a-a084061c682b.png)

![Stella Lumens address to Receive in new Wallet](https://user-images.githubusercontent.com/93430192/139530346-32f2d6fb-58ac-4aa4-a5af-bd6269efc13b.jpg)

![XLM Wallet to to receive transaction](https://user-images.githubusercontent.com/93430192/139530348-a3039b8b-68f9-499a-98af-ac336fc7d0b6.jpg)

**Comment by daria-blockchair** [comment]
Hi @stukaroa, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on blockchair.com. If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your receiving wallet or exchange for more information and to find out when the funds will be credited to your account.
