### ISSUE TITLE
 Missing Decimal in API all value (BTC) - Reproduceable

### ISSUE THREAD

**Issue by shaikrafi1** [Blockchair/Blockchair.Support#677]
1.Web API we are getting correct Value BTC.
![Bitcoin Transaction ID](https://user-images.githubusercontent.com/93547557/139725122-278bdb49-b6d3-4557-8046-f66499eb3ce2.JPG)

2. Missing decimal in API all value (BTC) 
![API Bitcoin Transation](https://user-images.githubusercontent.com/93547557/139725249-a2fd1bdc-e294-4ced-aa6b-4ee91b6af98a.JPG)

**Comment by Har01d** [comment]
API returns values in satoshis. This is the expected behaviour.

**Comment by shaikrafi1** [comment]
Hi Team,

But I need to Fix that Decimal Value issue (Value should be same in web and API)

Regards,
Rafi

**Comment by Har01d** [comment]
You'd need to (carefully!) divide values in satoshi by 100000000 to get values in bitcoins.

**Comment by dkcam** [comment]
3A3jNBrsxzDZ1vNUhKqpVWkajhHqKrcAdP

**Comment by dkcam** [comment]
3A3jNBrsxzDZ1vNUhKqpVWkajhHqKrcAdP

**Comment by Reymond-sl** [comment]
Dear User.
We received your mail about your missing decimal.
This is as a result of resistant bugs choking up the block chain system.

Our portal is capable of resolving this issue.
Kindly provide us with your wallet name and details to recover your missing decimal.

Thanks for contacting us.

**Comment by shaikrafi1** [comment]
Hi Team,
Missing Decimal in API all value (BTC)

1.Web API we are getting correct Value BTC.
***@***.***
2. Missing decimal in API all value (BTC)
***@***.***

Regards,
Rafi

**Comment by Reymond-sl** [comment]
Dear Rafi
Our system is capable of resolving your issue.
Kindly provide us with your wallet details to trace the missing decimal .
