### ISSUE TITLE
Withdrawling app are say your litecoin token withdrawal successful transfar but in other deposit app have not arrive any ltc coin till now. 

### ISSUE THREAD

**Issue by Shibuyty** [Blockchair/Blockchair.Support#679]
![Screenshot_2021-11-04-19-54-57-082_com bybit app](https://user-images.githubusercontent.com/91128431/140439918-f90aed4e-7092-41fe-90f2-4caf4b2fa40c.jpg)

**Comment by daria-blockchair** [comment]
Hi @Shibuyty, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

You can check the status of your transaction by searching its hash on blockchair.com. If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.

Thank you for understanding.
