### ISSUE TITLE
Ripple Transactions - Wrong date

### ISSUE THREAD

**Issue by christopherkarger** [Blockchair/Blockchair.Support#687]
I think the date in every ripple transaction is not returning the correct date. Even if i multiply the date with 1000, i get a date from 1991 which is definitely wrong.

A date in the response looks like this  => date: 689613081

Can someone pls tell me how to get the correct date, or is it just a bug in the backend code ?
I am using this endpoint for example:

https://api.blockchair.com/ripple/raw/account/${address}?transactions=true

Br

**Comment by dkcam** [comment]
3A3jNBrsxzDZ1vNUhKqpVWkajhHqKrcAdP

**Comment by Reymond-sl** [comment]
Contact our support group through maskmeta73@gmail.com
Your issue will be resolved

**Comment by Har01d** [comment]
See https://bitcoin.stackexchange.com/questions/23061/ripple-ledger-time-format
