### ISSUE TITLE
cancel a transfer

### ISSUE THREAD

**Issue by mariamar123** [Blockchair/Blockchair.Support#689]
I wanted  to make a transfer from my Binance account into my advcash account. I did a mistake and put the wrong ip address in the binance app and so I lost all my money. There is no trace of it anywhere and the only thing I have is this link from your platform since you were the blockchain involved.

**Comment by Reymond-sl** [comment]
Contact our support group through maskmeta73@gmail.com
Your issue will be resolved

**Comment by mariamar123** [comment]
I contacted them regarding this issue. 
Will they be able to help me get my fund back? 

Thank you

**Comment by daria-blockchair** [comment]
Dear @mariamar123, 

Please be aware of scammers. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains. No one can.
