### ISSUE TITLE
3A3jNBrsxzDZ1vNUhKqpVWkajhHqKrcAdP

### ISSUE THREAD

**Issue by dkcam** [Blockchair/Blockchair.Support#691]
@daria-blockchair

**Comment by daria-blockchair** [comment]
Hi @dkcam, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
