### ISSUE TITLE
"Addresses" table is empty

### ISSUE THREAD

**Issue by Luned** [Blockchair/Blockchair.Support#695]
Hello!

When sending a GET request to the ["Address Balance Mass Check" dashboard endpoint](https://blockchair.com/api/docs#link_390) on Bitcoin Testnet, I am getting a 500 error code with the message " 'addresses' table is empty for some reason". This is only happening for Testnet, the same request on the main net is working as expected. 

My request:
```shell
curl --request GET 'https://api.blockchair.com/bitcoin/testnet/addresses/balances?addresses=mfZbSNd6QyW6qq7Zamioc2PrWeeLKAhm54'
```

The response:

```json
{
    "data": null,
    "context": {
        "code": 500,
        "error": "`addresses` table is empty for some reason",
        "market_price_usd": 64008,
        "cache": {
            "live": true,
            "duration": 10,
            "since": "2021-11-12 11:12:48",
            "until": "2021-11-12 11:12:58",
            "time": null
        },
        "api": {
            "version": "2.0.91",
            "last_major_update": "2021-07-19 00:00:00",
            "next_major_update": null,
            "documentation": "https://blockchair.com/api/docs",
            "notice": ":)"
        },
        "server": "TBTC0",
        "time": null,
        "render_time": 0.27449584007263184,
        "full_time": 0.27449584007263184,
        "request_cost": 1
    }
}
```

Is this an error on Blockchair's side? I have been using this endpoint as-is for several months now and I have never seen this response.
Thank you very much for the help!

**Comment by Har01d** [comment]
This was fixed several days ago. This issue only affected Bitcoin Testnet as we were testing Taproot.
