### ISSUE TITLE
Ripple transactions not returning

### ISSUE THREAD

**Issue by BenSmithNZL** [Blockchair/Blockchair.Support#703]
I'm using the API to get transaction information from XRP transactions, but every single transaction hash I input returns a 404 error: "We do not have information for this transaction". Even the example transaction in the API docs returns this error:

**Input**
`https://api.blockchair.com/ripple/raw/transaction/0847A0062757E3490389069DBB3FBA8626EEEE07C126123660248CE1B32D34E3`
**Output**
{"data":null,"context":{"code":404,"source":"D","results":0,"error":"We don't have info for this transaction","market_price_usd":1.09,"cache":{"live":true,"duration":60,"since":"2021-11-17 00:57:55","until":"2021-11-17 00:58:55","time":null},"api":{"version":"2.0.91","last_major_update":"2021-07-19 00:00:00","next_major_update":null,"documentation":"https:\/\/blockchair.com\/api\/docs","notice":":)"},"time":0.335360050201416,"render_time":0.00898599624633789,"full_time":0.3443460464477539,"request_cost":1}}

Can somebody please advise on what to do here. Many thanks

**Comment by Har01d** [comment]
We don't store full history for Ripple, Stellar, and EOS at this moment, please see:
* https://blockchair.com/api/docs#link_M01
* https://blockchair.com/api/docs#link_510
* https://api.blockchair.com/range

Ripple transactions are stored for approximately 2-3 weeks.
