### ISSUE TITLE
Pricing terms confusion

### ISSUE THREAD

**Issue by tmr-prestolabs** [Blockchair/Blockchair.Support#705]
I think you should add more clarification about the difference/similarity between terms "request cost formula" and "call".

https://blockchair.com/api/plans, this page shows the amount of money I have to pay per number of calls.

However, the API documentation shows smth called "Request cost formula", which can be larger than one.

Then, let's say if `Request cost formula == 3`, does it mean I'm making 3 calls or 1 call?

**Comment by tmr-prestolabs** [comment]
and would be cool to have an email or some other easier means of communicationwith you guys for asking about such questions

**Comment by Har01d** [comment]
Hello,

You can always reach us at <info@blockchair.com>. We also provide Enterprise subscribers with direct Telegram chats with our support team.

> Then, let's say if Request cost formula == 3, does it mean I'm making 3 calls or 1 call?

Yes, that's 3 "calls".
