### ISSUE TITLE
14bvC3cw5bmfS1zFxMEkUu6y3t9TrzUE1G  

### ISSUE THREAD

**Issue by Breed96** [Blockchair/Blockchair.Support#707]
Didn't receive enough time to copy my mnemonic phrase down and than got logged out the wallet and now they want the phrase just to get back in the wallet any help would be greatly appreciated

**Comment by daria-blockchair** [comment]
Hi @Breed96, 
Blockchair is a block explorer which only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Unfortunately, we are not able to assist you with this issue.
