### ISSUE TITLE
Scammed from my crypto

### ISSUE THREAD

**Issue by Lgroucho** [Blockchair/Blockchair.Support#708]
Hey I'm a dumb new user for crypto and was scammed into sending money into someone else "withdrawl" . I've reached out to crypto and was told to try to contact you guys with this txID. I dont know of this is even the support contact but it's all I could find. Please if anyone can assist in helping get back my families holiday money.

 Provide them with the txID: a03459649f9cf59bcf8389d99147e48ebe220ae36dad3b64d394b3eced0ec34a

**Comment by ncmmam** [comment]
I'm in the same boat. Feel so stupid! Have you had any help yet??

**Comment by dogegotshibsback100** [comment]
So have I been Scammed out of my Dogecoins, Shiba Inu coins and USDC funds. I posted on here about the fraudulent activities going on that Crypto.com App. Your money nor your assets are not safely secured on that app for people to keep getting scammed out of their investment. No help at all. I've been trying to get my coins back and their support team are garbage in doing so. They say the same thing everytime I contact them. I told them I will expose them of this activity going on that app. Do you know who to contact? If you find out something please? let me know. Thanks

**Comment by daria-blockchair** [comment]
Hello @Lgroucho @ncmmam @dogegotshibsback100, 

We are very sorry about you've been scammed. But unfortunately, we are not able to help get your funds back. 

Blockchair is a block explorer, which just shows publically available information stored in blockchains. We do not process transactions and do not store the funds of the users. We don't have any information about the owners of the addresses. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains.

Thank you for understanding.
