### ISSUE TITLE
I BEEN SCAMMED!

### ISSUE THREAD

**Issue by dogegotshibsback100** [Blockchair/Blockchair.Support#710]
Hello, 
      I Have been trying to reach out to someone in the support department I have Crypto.com since September 24 2021. All of my Dogecoins, Shiba Inu coins and my USDC funds were fraudulently withdrawn from my Crypto.com accounts. You have to do something about this going on. It's not right. I refuse to repurchase those coins for the prices have gone up and the value of the coins are to high for me to buy what I bought back in February(Doge) and June (Shiba Inu) plus the funds that were in my USDC account. PLEASE? Whoever that is in charge of all these consumers complaints have compassion in your heart to investigate each and every case (do not ignore)on this post and consider returning all the coins that the people and I were victims of fraudulent activities on the Crypto.com App. 
           Thank you kindly,

Here are the addresses that were used to transfer my coins and money.

![image](https://user-images.githubusercontent.com/95295639/144074219-b5a7f81e-3371-4338-9f53-9d1b83f35cb9.jpeg)

![image](https://user-images.githubusercontent.com/95295639/144074415-55bd7798-41a0-4b76-9efc-e3d24f5f8578.jpeg)

**Comment by daria-blockchair** [comment]
Hi @dogegotshibsback100, 

We are very sorry to hear that you've been scammed. Unfortunately, we are unable to help you get your funds back. 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
