### ISSUE TITLE
About money transcription

### ISSUE THREAD

**Issue by Serikhan** [Blockchair/Blockchair.Support#712]
Hello my money from emcd account did not go to my wallet my link [bc1qvtj2nscvnplparhzvggjyjd74kg8nx6eyklm49]() 
bc1qvtj2nscvnplparhzvggjyjd74kg8nx6eyklm49

**Comment by daria-blockchair** [comment]
Hi @Serikhan,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money.

You can check the status of your transaction by searching its hash on blockchair.com. If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.
