### ISSUE TITLE
By mistake, I send from my Coinbase BCH Wallet to Localbitcoins BTC Wallet

### ISSUE THREAD

**Issue by KervinVergara** [Blockchair/Blockchair.Support#72]
How can I recover my lost money? By mistake, I send BCH from my Coinbase BCH Wallet to LocalBitcoins BTC Wallet, and the money never up, but in the Blockchair appear that the transaction is completed. Can you help me please?

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
