### ISSUE TITLE
Lost earnings

### ISSUE THREAD

**Issue by CaveWoman71** [Blockchair/Blockchair.Support#727]
Yesterday around 21.30 h I've sent 6 $ to my Bitcoin Wallet, like I usually do using "pay", but it never got to my Wallet, although it's gone from my account here
I've waited till now and still didn't get it but I see it there in my balance ...
Can you help me please ??

![Screenshot_20211212_220943_com android chrome](https://user-images.githubusercontent.com/96044093/145771745-139c7feb-9d26-46d4-bf5a-387fcde9e54a.jpg)

**Comment by daria-blockchair** [comment]
Hi @CaveWoman7!

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
