### ISSUE TITLE
My assets are being stolen?

### ISSUE THREAD

**Issue by MagnoliaSlimMarket** [Blockchair/Blockchair.Support#728]
Help Me Please...
I cannot find any of my Assets.

**Comment by daria-blockchair** [comment]
Hi @MagnoliaSlimMarket. 

Blockchair is a blockchain search and analytics engine. We don't provide wallet services, we don't process transactions, and we don't store the funds of the users. 
You can check the balance of your address by entering your wallet address into the search bar on blockchair.com. For more information about your account, please contact your wallet or exchange. Thank you for understanding.
