### ISSUE TITLE
PROBLEM SEND ACCIDENTALY

### ISSUE THREAD

**Issue by simonemiccolo90** [Blockchair/Blockchair.Support#73]
i have send accidentallyBitcoin Cash (BCH) to a  Bitcoin (BTC) address portfolio outside of coinbase

i have send at my account coinpot.co

how do please? i need a private key what is? 
where I find the private key and how I do import and export?

ok pls ty very much for help me okok byebye.!!!

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
