### ISSUE TITLE
ZEC not deposit

### ISSUE THREAD

**Issue by bongcrypto** [Blockchair/Blockchair.Support#735]
I have deposited ZEC, but not done till now. Do the need full 

My Transaction hash 

1 - 4e1f4f063d303065ec04428d8008352968a434ab54b912adb035abcf08d731ae

2 - eaab32ae7d397091c43800d99def842c94166d4363ab56d796e4543bbc9e8616

Thanks

**Comment by bongcrypto** [comment]
Please confirm my transaction

**Comment by daria-blockchair** [comment]
Hi @bongcrypto!

Blockchair is a blockchain search and analytics engine. We do not provide wallet services and we do not process transactions. 

The transactions [4e1f4f063d303065ec04428d8008352968a434ab54b912adb035abcf08d731ae](https://blockchair.com/zcash/transaction/4e1f4f063d303065ec04428d8008352968a434ab54b912adb035abcf08d731ae) and [eaab32ae7d397091c43800d99def842c94166d4363ab56d796e4543bbc9e8616](https://blockchair.com/zcash/transaction/eaab32ae7d397091c43800d99def842c94166d4363ab56d796e4543bbc9e8616) are confirmed. 

For more information please contact your receiving wallet or exchange.
