### ISSUE TITLE
SLP Token Bug

### ISSUE THREAD

**Issue by giviz** [Blockchair/Blockchair.Support#736]
[https://blockchair.com/bitcoin-cash/transaction/f0aeba0ff51ec2c75975f256219e8bfcbe1c079d1c2e5d09041b659981ccec48](url)

Transaction is valid.
Input = 9,223,372,036.854776382 FYOOK
Output 1 = 2
Output 2 = 9,223,372,036.854776382

so already there, it's broken as Input == Output2 and there is still Output1 of 2.

But

[https://simpleledger.info/tx/f0aeba0ff51ec2c75975f256219e8bfcbe1c079d1c2e5d09041b659981ccec48](url)

Input = 18,446,744,067.709551616
Output 1 = 2
Output 2 = 18,446,744,065.709551616

So here it's valid, Input == Output1 + Output 2

But

As you can see, your values are also wrong, they have somewhat been devided by 2 ?

Tx OP_Return is : OP_RETURN 5262419 1 1145980243 452e82ded440deda889a1bbe566f5384bcd4fda65f8f1e8f0a4057c5ea41f28f 0000000077359400 fffffffe2329b000

So outputs are 0000000077359400 and fffffffe2329b000
0000000077359400 (hex) = 2000000000 (dec)
fffffffe2329b000 (hex) = 18446744065709551616 (dec)

So simpleledger.info values are correct, the tx is valid, and you have a bug :)

**Comment by giviz** [comment]
[https://blockchair.com/bitcoin-cash/transaction/7fcc663c5ce228eee3349acc0731c98e6089f83eb1eafa0784a7074915bf6049](url)

That tx should not mention the second output of 12,323.6789 UIOP2 because it's not valid, because there is no matching BCH output on vout = 2 on that tx.

The tx is still valid, but that SLP output has to be ignored.

Reference : [https://simpleledger.info/#tx/7fcc663c5ce228eee3349acc0731c98e6089f83eb1eafa0784a7074915bf6049](url)

**Comment by Har01d** [comment]
This was fixed in one of the previous updates. Thanks!
