### ISSUE TITLE
request

### ISSUE THREAD

**Issue by mozzo2014** [Blockchair/Blockchair.Support#75]
Hello admin
A few hours ago, I sent 1.2198 BCC to 1BDMe2gAt7VKmBsLZDFJJ9xscbjRu2KNfA but now I not receive coins in my account. Please check my transactions for me.
thanks

**Comment by mozzo2014** [comment]
Hello admin
A few hours ago, I sent 1.2198 BCC to 1BDMe2gAt7VKmBsLZDFJJ9xscbjRu2KNfA but now I not receive coins in my account. Please check my transactions for me. my link is :https://blockchair.com/bitcoin-cash/address/1BDMe2gAt7VKmBsLZDFJJ9xscbjRu2KNfA
thanks

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
