### ISSUE TITLE
Bitcoin testnet transaction push returning 500

### ISSUE THREAD

**Issue by Luned** [Blockchair/Blockchair.Support#765]
Hello!

Recently, I have noticed that the endpoint for pushing a transaction hex has been returning error 500. As far as I could tell, this is only happening on Bitcoin Testnet, the exact same code on our side works perfectly for Bitcoin Mainnet. 

Furthermore, just to be sure, I have tested the same transaction hexes that failed on other APIs for transaction broadcasting, and they were broadcast successfully. 

This is the return that I am getting from the endpoint:
```json
{
  "data":null,
    "context": {
      "code":500,
      "source":"R",
      "error":"Something went wrong",
      "market_price_usd":41596,
      "cache":{
        "live":true,
        "duration":20,
        "since":"2022-01-19 09:28:49",
        "until":"2022-01-19 09:29:09",
        "time":null
      },
      "api":{
        "version":"2.0.95-ie",
        "last_major_update":"2021-07-19 00:00:00",
        "next_major_update":null,
        "documentation":"https:\/\/blockchair.com\/api\/docs",
        "notice":"Some explorers and APIs may lag behind! Due to a global Internet shutdown in Kazakhstan we're moving to our reserve infrastructure. Some Ethereum transactions and ERC-20 transfers may be missing, eCash explorer is temporarily unavailable. Situation updates will be available at https:\/\/status.blockchair.com"
      },
      "server":"TBTC0",
      "time":0.21892189979553223,
      "render_time":0.0017881393432617188,
      "full_time":0.22071003913879395,
      "request_cost":1
  }
}
```

Please let me know if this is an issue on my side, or anything that Blockchair can fix soon, since it is causing problems with the platform that I currently develop.

Thank you very much for your help!
Joana

**Comment by Har01d** [comment]
Hi,

I think this has been fixed, we were reconfiguring some of our servers. Could you please confirm it’s working for you now?

**Comment by Luned** [comment]
Hi, Har01d!

It is working perfectly now, thank you very much.

Cheers,
Joana
