### ISSUE TITLE
Real-time updated version of bitcoin days destroyed / BTC price chart

### ISSUE THREAD

**Issue by sukitrebek** [Blockchair/Blockchair.Support#77]
Is it possible to see a real-time updated version of this chart?

https://pbs.twimg.com/media/C1uuo7wXUAI5r35.jpg

**Comment by Har01d** [comment]
Hello, there’s a similar chart showing CDD for the last 3 months on our homepage:

<img width="351" alt="CDD" src="https://user-images.githubusercontent.com/14060856/34327262-ada60d92-e8d0-11e7-9307-304711804032.png">

We’ll be bringing more flexible charts in the future. Thank you!
