### ISSUE TITLE
Money gone 

### ISSUE THREAD

**Issue by butticekelly** [Blockchair/Blockchair.Support#772]
You stole it

**Comment by DONI9090** [comment]
Ушли деньги с Coinex куда ушли непонятно

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. We also don't have any information about the owners of the addresses.
Please contact your wallet or exchange for more information.
Thank you for understanding.
