### ISSUE TITLE
My money was stolen 

### ISSUE THREAD

**Issue by Cristy1987** [Blockchair/Blockchair.Support#773]
On January 24th someone cleared my account, a transaction was made with all my money, about $170! I don't understand how this could have happened since I didn't make any transactions! Now I ask if I leave all the data of the transaction here can I have some help to recover my money?
Transaction hash
5c447c521a11fb1bee0b978348a833d82a2c035a181b87d5b05ddb08be036934
Recipients
bc1qvyys4wpj8m9542kycxavverhly68xcuyt5wlt4

**Comment by daria-blockchair** [comment]
Hi @Cristy1987,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Unfortunately, we cannot help you get your money back.
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
Thank you for understanding.
