### ISSUE TITLE
Transaction without my confirmation

### ISSUE THREAD

**Issue by Piri750** [Blockchair/Blockchair.Support#774]
This adress stolen my BTC. Moderate privacy, they can track my BTC adress. Please do something.
![Screenshot_20220203-114455](https://user-images.githubusercontent.com/98954097/152337344-65c1df2e-97d2-43bb-963c-1085cd53ea84.png)
![Screenshot_20220203-114639](https://user-images.githubusercontent.com/98954097/152337385-eeff9d4f-b978-4345-baeb-a57963139ee0.png)
![Screenshot_20220203-114650](https://user-images.githubusercontent.com/98954097/152337409-ca2e39a7-a4dd-4559-80ce-479b05e306d3.png)
![Screenshot_20220203-114511](https://user-images.githubusercontent.com/98954097/152337496-fff8b80b-91ba-4e4a-853b-f737b5e7f1dd.png)

**Comment by daria-blockchair** [comment]
Hi @Piri750,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
Thank you for understanding.
