### ISSUE TITLE
Sent Bitcoin cash from GDAX to bittrex 

### ISSUE THREAD

**Issue by Hell000000** [Blockchair/Blockchair.Support#78]
I've 379 confirmations 
I sent this 4 days ago and it's still not in bittrex. It says complete on coin base 
please help me out

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md and contact the Bittrex support.
