### ISSUE TITLE
721824 no ile bloklanan usdt yi gönderen iade

### ISSUE THREAD

**Issue by suleyman1969** [Blockchair/Blockchair.Support#780]
721824 no ile bloklanan usdt yi gönderen adresime iade edebilir misiniz iade adresimi veriyorum.   
TXcAW4Eq4A3fXtKJpzKCrVRjzUQTG53CgX

**Comment by daria-blockchair** [comment]
Hi @suleyman1969,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.
Please contact your wallet or exchange for more information.
Thank you for understanding.
