### ISSUE TITLE
Error 430 on all IP addresses and devices

### ISSUE THREAD

**Issue by mehdiirh** [Blockchair/Blockchair.Support#782]
Hello
I want to use blockchair API for personal purposes, to check my wallet balance and get notified when ever a transaction is made. I used to check my BTC address every 2 minutes which will not exceed API limits, but from 2 days ago, everytime I get error with response 430

Error meaaage:
"Your IP address is temporary blacklisted due to exceeding usage of API resources. Please apply for an API key by contacting us at [info@blockchair.com](mailto:info@blockchair.com)"

I tried to change my IP ( restarted my router, used a public VPN, used Personal VPN, ... ), changed device and **even sent request from a whole different network and device which never was used to send request to blockchair website**, but everytime I get 430 response.

So my guess is the problem is from your side, can you do a quick check on your endpoints ?

**Comment by daria-blockchair** [comment]
Hello, 
We provide free access to our API service with a limit of 1,000 daily requests for several days. After a few days of testing, we recommend applying an API key. You are welcome to purchase one of our API keys from [this page](https://blockchair.com/api/plans). We offer different subscription plans starting from $10 and you can choose a plan that best suits your need.

**Comment by greatwolf** [comment]
I'm running into the same issue. This is my very first time trying out the blockchair api and it's already giving this error even though I've never made any prior request to begin with! What gives?

**Comment by Loug3141** [comment]
> I'm running into the same issue. This is my very first time trying out the blockchair api and it's already giving this error even though I've never made any prior request to begin with! What gives?

I came here for the same reason. I literally made 1 call and the second one gave me this message. ???

**Comment by daria-blockchair** [comment]
Hi @greatwolf, @Loug3141, 

Unfortunately, our Dashboard endpoints are not available without an API key. So you may receive the same error if you haven't exceeded the trial period limit but tried dashboard endpoints.

You are welcome to purchase one of our API keys from [this page](https://blockchair.com/api/plans).
If you are a student, you can obtain an API key for free through the GitHub Student Developer Pack or on our [website](https://blockchair.com/student-pack).

**Comment by Loug3141** [comment]
I had an account for 5 minutes. Is that the trial period?

Em qui., 29 de jun. de 2023 às 17:27, daria-blockchair <
***@***.***> escreveu:

**Comment by daria-blockchair** [comment]
Hi @Loug3141, 

We offer free access for several days with a limit of 1,000 calls/day. A trial period does not include dashboard endpoints, so if you try dashboard endpoints without an API key, you'll receive a 435 error. 

Please apply an API key and your IP address will be unblocked automatically. If you experience any issues with our service even when you apply the key, please email us at info@blockchair.com and we will be glad to assist.

**Comment by Loug3141** [comment]
I guess I'll just not use your api since you guys can't admit when there is a bug in your system. No thanks.
