### ISSUE TITLE
ارسال اشتباه مقدار 500.000.000شیبااینو

### ISSUE THREAD

**Issue by Ebr4him80** [Blockchair/Blockchair.Support#787]
سلام من  به اشتباه ازکیف پول تراست ولت خودم مقدار ۵۰۰.۰۰۰.۰۰۰شیبا ارسال کردم به ادرس خود قرارداد اصلی شیبا اینو
لطفا کمک کنید بازگردانم
مقدار500.000.000شیبا اینو ارسال کردم به ادرس قرارداد

0x04a0bc5e2a45300b71d9294c32aa1a7728fbdb61458e8d17b027df938abf7aa8

**Comment by daria-blockchair** [comment]
Hi @Ebr4him80,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
Thank you for understanding.
