### ISSUE TITLE
Sent money to the wrong address

### ISSUE THREAD

**Issue by KDB321** [Blockchair/Blockchair.Support#788]
Hi, please help to recover my money sent to the wrong address
Here's the TXiD: 68977d33016bf4f72da75747077cda0ebd37c1b66295124a509eee56a22a25ba
Recipient address:
3LgdqgcZf6Mp5gvCLTM3cudczeLwVt8Cjo
Please help my problem. Thank you and best regards

**Comment by KDB321** [comment]
![Screenshot_2022-02-14-14-38-15-98](https://user-images.githubusercontent.com/99641458/153824719-6b150ba4-12ba-4f0b-9a3e-bd17e056adce.jpg)
![IMG_20220214_151036](https://user-images.githubusercontent.com/99641458/153824876-e670d790-839c-4dc0-b742-ccf7a6711a37.jpg)
![Uploading Screenshot_2022-02-14-14-46-19-78.jpg…]()
![Uploading Screenshot_2022-02-14-14-52-48-67.jpg…]()

**Comment by KDB321** [comment]
Please help me to return my money to my account . Big big Thanks in advance

**Comment by daria-blockchair** [comment]
Hi @KDB321 ,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
Thank you for understanding.
