### ISSUE TITLE
Deposited to wrong address

### ISSUE THREAD

**Issue by parveen1980** [Blockchair/Blockchair.Support#79]
Hello 4 days back I did the transaction where address is same for bch and btc.instead selecting btc I chose bch n it's has credited to my account yet. Surprisingly address is same as my btc account.kindly help, it's a huge amount.

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
