### ISSUE TITLE
Scam report

### ISSUE THREAD

**Issue by Yousef5763** [Blockchair/Blockchair.Support#791]
943ad1685c3fdcb2932fe7a2028c226d218681de85ca66aef96b18ca937cf4ec
This address received 56 DOJcoin from me and did not pay me any interest

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
