### ISSUE TITLE
XLM sent to me with no Memo

### ISSUE THREAD

**Issue by phillgood1979** [Blockchair/Blockchair.Support#794]
Can someone please help me retrieve my Lumens, it's on the Blockchain but someone forgot to put in the Memo when they sent it, I have screenshots of my transaction and there transaction to prove I'm the owner.

Thanking you in advance.

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
