### ISSUE TITLE
Transaction flow is inverted for Cardano

### ISSUE THREAD

**Issue by muriloito** [Blockchair/Blockchair.Support#795]
Hi Guys, 

Cardano address page is showing transaction flow inverted, for exemple, when the address is on outputs, transaction is classified as "sent".

example page:
https://blockchair.com/cardano/address/addr1qxwq0mqwns9wjrvnjh4de0gkqu2p6sddr83ydp54ddap4f848ns0yp7rtep4v9wcjm4kzwcey5ajxuedwggju3hwzglsf9vtgp

![image](https://user-images.githubusercontent.com/2486889/155019104-f12f4d98-2628-4370-8482-6f1be42bf54f.png)

**Comment by Har01d** [comment]
This was fixed several months ago, thanks!
