### ISSUE TITLE
Scam investor

### ISSUE THREAD

**Issue by Kaiafas93** [Blockchair/Blockchair.Support#796]
I invest $555 for my first time she told me 1 time deposite then told me to invest one more time $2000 i this is a spam. Can anyone help me please?

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by daria-blockchair** [comment]
Hi,
We are sorry for you being scammed. Unfortunately, we are not able to get your money back.
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information. If you suspect fraud you can contact local authorities.
Thank you for understanding.
