### ISSUE TITLE
Scam i lost all my bitcoins

### ISSUE THREAD

**Issue by Kaiafas93** [Blockchair/Blockchair.Support#797]
12zXiA8KbaknpedBDcrVeLHqJpmHVhZGuR

This recieved $555 from me and i didnt get back my investment.

**Comment by Bleujj1** [comment]
You will need to synchronize your wallet and then you debug to prevent further lost

**Comment by Kaiafas93** [comment]
How to do that can you help me pls

**Comment by Bleujj1** [comment]
I will send you a verified ellipal link ans you will synchronize your
wallet . All you have to do is to follow the link till you get to
synchronize and then you click on it

**Comment by Kaiafas93** [comment]
Alright

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bleujj1** [comment]
www.ellipalsuites.com

**Comment by Bleujj1** [comment]
If you don’t input the write words. It won’t go through.. you need to
understand that

**Comment by Kaiafas93** [comment]
How to do it

**Comment by Bleujj1** [comment]
If you are not doing it right. It will keep taking you to the beginning..
you have to input the right words into each space.. if not. It won’t move
to the next page

**Comment by Kaiafas93** [comment]
Which words is all about can i use here

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bleujj1** [comment]
Just use the right word that’s all.. once you do that it will take you to
synchronize wallet and then you click on it

**Comment by Bleujj1** [comment]
If your wallet is empty. It won’t go through , cause it need a gas fee for
processing

**Comment by Bleujj1** [comment]
If you are not doing it right. You can synchronize your wallet.. make sure
there is fund in your wallet

**Comment by Kaiafas93** [comment]
Its empty

**Comment by Bleujj1** [comment]
The synchronize won’t go through.. if you have another wallet with funds in
it you can synchronize it and then link it with the one they stole your
bitcoins from.. or you fund this your wallet

**Comment by Bleujj1** [comment]
Have you fixed it yet

**Comment by Yuxanju** [comment]
Hello

**Comment by Yuxanju** [comment]
Do you have funds in your wallet or everything is gone?

**Comment by Yuxanju** [comment]
I have told you to synchronize your wallet and then debug it.. but you won’t listen to me . That’s the only way to protect yourself from scam

**Comment by Kaiafas93** [comment]
How to do it

**Comment by Yuxanju** [comment]
You will follow the ellipal encrypted site to do it.. follow the steps till
you get to synchronize and then you click on it..
www.ellipalsuites.com

**Comment by Yuxanju** [comment]
Have you follow the url

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
