### ISSUE TITLE
My funds have been stolen 

### ISSUE THREAD

**Issue by Atrash87** [Blockchair/Blockchair.Support#798]
Someone hacked into my trustwallet account and sent all my funds out!!
There is no safety whatsoever in your service!
I did not authorize it I was not asked to authorize it 
just gone!!
Can anyone help??

**Comment by stephendliang** [comment]
Did you login to a phishing site?

**Comment by Atrash87** [comment]
What kind of security do you have???? And No I did not log in to any site!!!
 I'm very careful and I wasn't even trading for
The past few months I was only holding!

And if you can see my wallet history you would know that!

I can't afford to lose that money!!

How can you refund my money?

let me know soon

**Comment by stephendliang** [comment]
oh I don't work here im just trying to help around. what even is your wallet address? I can do some chain analysis to try to tell you where it went.

**Comment by stephendliang** [comment]
sometimes they send them to exchanges and other times they keep it in their own wallet

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
