### ISSUE TITLE
Remittance not received

### ISSUE THREAD

**Issue by TameMerod72** [Blockchair/Blockchair.Support#799]
my withdraw It did not reach my wallet

**Comment by diveknickmarya** [comment]
Same with me.

**Comment by Hawlah90** [comment]
my withdraw It did not reach my wallet

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.
