### ISSUE TITLE
transfer invalid

### ISSUE THREAD

**Issue by 6zmysl** [Blockchair/Blockchair.Support#80]
Hi, I sent money by bitcoin cash to this adress :  18Vcfa3UTy121ti2RGibQEeHkQLC3WCmoh   12 hours ago and somebody didn't receive the money. What is this?  Money transfer should be maximum 30 minutes,like always .

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

**Comment by 6zmysl** [comment]
WHat???????????????  WHere I have to write it ??????????????  I clicked on this stupid link and what???????????
I wrote it everywhere and always the same -Please refer to our FAQ regarding this issue https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
So what is fucken this??????????

**Comment by Har01d** [comment]
As stated in the FAQ, Blockchair doesn’t provide payment services, we just display blockchain data as is. Have a nice day.
