### ISSUE TITLE
Transfer missing , recipient didn't receive BTC

### ISSUE THREAD

**Issue by diveknickmarya** [Blockchair/Blockchair.Support#800]
Hi there. 

I send BTC to one of my friends and still he hasnt got it. 

How long does it takes for the transfer to be completed. 
My understanding was that the transfer is instant. But I found out some posts that I can take up to few hours as well depending on the network traffic. 
I need help with this issue of transfer times and network traffic please. 

Thanks.

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.

Thank you for understanding.
