### ISSUE TITLE
1GYYiJzKvtYh8WiVKLGs89au8jixPVWRX9 He tricked me into paying $300 in return for receiving interest of $8000, and when I sent the money, he blocked me from all social media and disappeared. 

### ISSUE THREAD

**Issue by islamomari** [Blockchair/Blockchair.Support#801]
I was tricked by a woman named Linda Donna who works as a crypto consultant and she tricked me into thinking she was going to run money on trading sites for the benefit but she betrayed me and went

**Comment by stephendliang** [comment]
Please send me the twitter or instagram handle or any screenshots. I will attempt to find them for you or at least reveal some information.

**Comment by islamomari** [comment]
> من فضلك أرسل لي حساب twitter أو instagram أو أي لقطات شاشة. سأحاول العثور عليها لك أو على الأقل الكشف عن بعض المعلومات.

**Comment by islamomari** [comment]
> > من فضلك أرسل لي حساب twitter أو instagram أو أي لقطات شاشة. الكشف عن بعض المعلومات.

https://vk.com/sd021 لديها حساب على الموقع الروسي المعروفالمعروف vk I also have pictures of her and screenshots of how I sent her money

**Comment by islamomari** [comment]
She had four Instagram accounts. The first and the second she used to cheat and the third and fourth were her two people. When I found out about them through my search for her, I found them and when I texted her she deleted them immediately so as not to leave any evidence behind. I found out that her real name is Dimina Svetlana, a Russian girl from the Kaliningrad region

**Comment by islamomari** [comment]
> من فضلك أرسل لي حساب twitter أو instagram أو أي لقطات شاشة. سأحاول العثور عليها لك أو على الأقل الكشف عن بعض المعلومات.

ظهرت انها فتاة اسمها ديومينا سفيتلانا روسية من منطقة تدعى كلينيغراد . تحصلت ايضا على حساب زوجها لكن تكمن الفائدة في ارجاع الاموال .لم يعد بإمكاني تسديد فواتير دراستي

**Comment by islamomari** [comment]
> من فضلك أرسل لي حساب twitter أو instagram أو أي لقطات شاشة. سأحاول العثور عليها لك أو على الأقل الكشف عن بعض المعلومات.

https://instagram.com/sdemina?utm_medium=copy_link
This is her Instagram account, it was the first time a public account, and after I sent it to her, I made it private. Help me get my money back

**Comment by daria-blockchair** [comment]
Hi, 
We are very sorry for you being scammed. Please be aware of scammers and do not fall for their schemes. 
Unfortunately, we cannot help you get your funds back. Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. 
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. If you suspect fraud you can contact local authorities.
