### ISSUE TITLE
Bitcoin transfer 

### ISSUE THREAD

**Issue by Stewy5353** [Blockchair/Blockchair.Support#806]
Hi. 
I transferred some BTC and it hasn't shown up in recipients acc but I have noticed it sitting in Blockchair

**Comment by csabifenyvesi** [comment]
39o7xTVFfo5H5hH86ufRxNva7dXFp6222LSzeretném visszatéríteni ezt a tranzakciót, mert nem fejeződött be.

**Comment by csabifenyvesi** [comment]
39o7xTVFfo5H5hH86ufRxNva7dXFp6222L

Szeretném visszatéríteni ezt a tranzakciót, mert nem fejeződött be.

**Comment by Koita95200** [comment]
J'ai transféré un certain BTC et il n'est pas apparu dans les bénéficiaires mais je l'ai remarqué assis dans Blockchair comment faire pour récupérer mes bitcoin s'il vous plait

**Comment by Koita95200** [comment]
Depuis que j'ai acheté je n'arrive pas à utiliser mon bitcoin

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
