### ISSUE TITLE
Simon77

### ISSUE THREAD

**Issue by Simon700908** [Blockchair/Blockchair.Support#807]
要寄到幣托bitcoincash:pqfgvu2cc85wun4hg6gv4xh48jwwqxfvxck9wqz07t
這才是我的
33Ny9F5HVzV3QeW8upc8yGb3WTmxw9ePZH

**Comment by Simon700908** [comment]
Simon77 請寄到幣托 bch
Bch位址qretzvrkdctp5grwj0avcyquk8zdzt5zwgxsq3f6jc

**Comment by Simon700908** [comment]
bitcoincash:pqfgvu2cc85wun4hg6gv4xh48jwwqxfvxck9wqz07t
我之前寄錯位址 上面才是正確的 0.97美 可以寄到這嗎？

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
 
Thank you for understanding.
