### ISSUE TITLE
Transaction issue 

### ISSUE THREAD

**Issue by Aoikame1412** [Blockchair/Blockchair.Support#811]
df23d5db9a768e9ffee506c99985e78110875e3825eadee946bd9c873873c81a

I want to refund this transaction because it's not complete.

**Comment by Wrathchyld** [comment]
Help me

**Comment by csabifenyvesi** [comment]
39o7xTVFfo5H5hH86ufRxNva7dXFp6222L

**Comment by csabifenyvesi** [comment]
39o7xTVFfo5H5hH86ufRxNva7dXFp6222L Szeretném visszatéríteni ezt a tranzakciót, mert nem fejeződött be.

**Comment by Wrathchyld** [comment]
Blockchair transfer should be verified

**Comment by Aoikame1412** [comment]
df23d5db9a768e9ffee506c99985e78110875e3825eadee946bd9c873873c81a　refund

**Comment by csabifenyvesi** [comment]
Hogy kell vissza igényelni?

**Comment by csabifenyvesi** [comment]
e3662edc66207516876af577591ffcdba43888f26821a6d64effd2cfb2685549

Hogy lehet vissza igényelni?

**Comment by csabifenyvesi** [comment]
![Screenshot_20220316-150731_Chrome](https://user-images.githubusercontent.com/82440288/158608625-f3951e1c-66ff-49b5-a6f0-d2e8a0443455.jpg)

**Comment by csabifenyvesi** [comment]
Így jelenik meg innen szeretném vissza igényelni a pénzt
