### ISSUE TITLE
Why has this nft. Gone out my wallet 

### ISSUE THREAD

**Issue by sanniesbitsandbobs** [Blockchair/Blockchair.Support#812]
0x79326199049a38743ce65452ccf5363a492f9cdda5dd6d11b0ddef1b8538f3a5  My expensive nft has gone to an abandoned wallet and no one will help me to receive it I can’t even contact the owner as they have not accessed the wallet in 9 months

**Comment by daria-blockchair** [comment]
Hello, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your assets, and cannot help you get it back, unfortunately. Please contact your wallet for more information.
Thank you for understanding.
