### ISSUE TITLE
df23d5db9a768e9ffee506c99985e78110875e3825eadee946bd9c873873c81a　refund

### ISSUE THREAD

**Issue by Wrathchyld** [Blockchair/Blockchair.Support#816]
df23d5db9a768e9ffee506c999
[1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa_en_usd_2009-01-03_2022-01-22_1.pdf](https://github.com/Blockchair/Blockchair.Support/files/8319676/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa_en_usd_2009-01-03_2022-01-22_1.pdf)
[Etherscan.io--Ox.zip](https://github.com/Blockchair/Blockchair.Support/files/8319683/Etherscan.io--Ox.zip)
85e78110875e3825eadee946bd9c873873c81a　refund

_Originally posted by @Aoikame1412 in https://github.com/Blockchair/Blockchair.Support/issues/811#issuecomment-1066327632_

**Comment by Wrathchyld** [comment]
What do I do ?

**Comment by daria-blockchair** [comment]
Hello, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
Thank you for understanding.
