### ISSUE TITLE
Transaction NEVER finished/btc CASH not accepted

### ISSUE THREAD

**Issue by immask1** [Blockchair/Blockchair.Support#82]
Re: BTC Cash transaction never sent/
GitHub Staff to you
10:25AMShow Details
Hi Michele,

I'm sorry, but you've reached Support for GitHub. It sounds like you may have been looking for support for a specific project that is hosted on GitHub.

https://github.com/Blockchair/Blockchair.Support

We didn't build that project, so we're not able to support it. There are a few places we suggest you look when you need help with a project hosted on GitHub:

its SUPPORT or README file, which may include contact information or an official website
its Issues tab, where you can report bugs
the owner's GitHub profile, which may include contact information
Of course, do let us know if you have any questions about GitHub itself!

Thanks,
GitHub Staff

Hello, my name is Michele Kaltsas and I'm writing to request from you a resolve of a transaction of Bitcoin CASH that was to be approved by you and sent to the address below. In tracing why the casino never received my deposit, I found that it went through you and I was told by the casino that they do not accept Bitcoin cash, only Bitcoin. After pressing the TRANSACTION DEAILS from coinbase's email saying my transaction was a sucess, I found that it went through block chair and it was approved but never spent. Can you please help me resolve this issue by sending back the money that was approved by you to my Coinbase account? It's just sitting in your world now... Below is the wallet address of the casino where the money was supposed to go to. I ask kindly, can you please help me with this. Sincerely, Michele Kaltsas
immask1@aol.com
774-641-5254
Wallet Address below cannot receive btc cash:
1Nv1J2c5EGWS7NTPsDJc4NBYjCzqDLdetM

**Comment by immask1** [comment]
Is there a "person" who can help me with this? A support person I can call or email? Please someone help me????

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
