### ISSUE TITLE
3Gyuy5zKPAtQDJfExMdCL6fYWt2YsVoeqHn  Me engaño esta persona que se llama daniel garcia que esta en una empresa se hace llamar FOREX BINARY OPTION INVESTMENT

### ISSUE THREAD

**Issue by alixette** [Blockchair/Blockchair.Support#822]
AYUDA INVERTI 11,500 Y NO ME DEJA D EPEDIR MAS
ME ESTA EXTROCIONANDO ME PORDRIAN AYUDAR NO ME QUIERE MANDAR MI INVERSION

**Comment by fatemehramezanli** [comment]
> AYUDA INVERTI 11,500 Y NO ME DEJA D EPEDIR MAS
> ME ESTA EXTROCIONANDO ME PORDRIAN AYUDAR NO ME QUIERE MANDAR MI INVERSION

**Comment by alixette** [comment]
hola buen dia me podrias ayudar con mi situacion Fatemehramezanli
