### ISSUE TITLE
No Crypto Processor list display on blockchain Awesome's view more page.

### ISSUE THREAD

**Issue by jkpatel1463** [Blockchair/Blockchair.Support#829]
Issues URL: https://blockchair.com/awesome/crypto-processors

Description:  [Blockchair Awesome](https://blockchair.com/awesome) shows list of all crypto processor, but when i clike on "Discover Crypto processors " next to Crypto processors, I was recirect to below link

https://blockchair.com/awesome/crypto-processors
 It do not shows anything in it. Screenshot is attached in this issues. 
 
 https://ibb.co/98Fn5d8
 
 I have cleared cache. Still same result
 
 Browser: Google Chrome Version 99.0.4844.83 (Official Build) (x86_64)
 Os: mac OS Big Sure Version 11.6
 
 Hope, You could produce issues using above information.

**Comment by daria-blockchair** [comment]
Hi @jkpatel1463! Thank you for reporting this issue. Currently, we are in the final stage of developing the improved version of our Awesome list. And we'll make sure to avoid such issues in the new version.
