### ISSUE TITLE
Remittance not received. 

### ISSUE THREAD

**Issue by kangdorr** [Blockchair/Blockchair.Support#831]
I only received less than 1% of the amount I sent and didn't receive the rest.

Please check this issue and let me know that progress.

**Comment by kangdorr** [comment]
Bitcoin sent to the wrong address.


![img122](https://user-images.githubusercontent.com/102481579/160293708-b615a717-3837-482f-b087-3e3ab15a739e.png)

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
