### ISSUE TITLE
Sent Bitcoin  my wallet to unown addres

### ISSUE THREAD

**Issue by Rzaoly** [Blockchair/Blockchair.Support#835]
مقداری بیت کوین به کیف پول من واریز شد ولی خود به خود از کیف پول به آدرس دیگری ارسال شده است .لطفاً برگشت دهید

**Comment by Angelo196** [comment]
It my wallet

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
