### ISSUE TITLE
Funds. 

### ISSUE THREAD

**Issue by Rsolaizatwentyone** [Blockchair/Blockchair.Support#837]
My funds have been held for 9 months. Since June 23rd. Shows there was 2 recipients but only one has spent partial. The rest is still unspent. How long until I receive it.

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
