### ISSUE TITLE
Is somebody there  ????????????????

### ISSUE THREAD

**Issue by 6zmysl** [Blockchair/Blockchair.Support#84]
HI,I want to cancel my 2 transfers. I want to have money back! I sent it a few days ago and nobody received it. Now transfers are closed and I have inf.that I need to send money back to my wallet. Can You do this? These are adressess : First : 18Vcfa3UTy121ti2RGibQEeHkQLC3WCmoh 0.05391972 BCH and second 1N7CMi66uTgriNasJadrcnsuwgUMNymamQ 0.00562311 BCH . I must to have it ASAP !!!!!!!!!!!!

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
