### ISSUE TITLE
hashrate-distribution chart retrurns 404

### ISSUE THREAD

**Issue by jakobsn** [Blockchair/Blockchair.Support#840]
Hi,

There seems to be something wrong with the hashrate distribution chart: 
https://blockchair.com/bitcoin/charts/hashrate-distribution.

My browser sends this request to the API, returning 404: 
https://blockchair.com/_api/charts/data?constructors[]=%7B%22selectedChain%22:%22bitcoin%22,%22selectedTable%22:%22blocks%22,%22selectedAggregationField%22:%22count()_blocks%22,%22selectedAggregationFieldValue%22:%7B%22count()_blocks%22:%22count()%22%7D,%22selectedFilterFields%22:[%7B%22field%22:%22time%22,%22table%22:%22blocks%22,%22value%22:%22time--blocks%22,%22unit%22:null,%22qsac%22:%7B%22q%22:%22%E2%8C%98%22,%22s%22:true,%22a%22:%22%E2%8C%98%22,%22c%22:false%7D%7D],%22selectedFilterFieldsOrder%22:[%22time%22],%22selectedFilterFieldsValues%22:%7B%22time%22:%22time(~P2W)%22%7D%7D&globals=%7B%22selectedGlobalGroupField%22:%22guessed_miner%22,%22selectedGlobalGroupTime%22:null,%22selectedGlobalGroupTimeCustom%22:null,%22selectedChartType%22:%22pie%22%7D

The query string is:
constructors[]={"selectedChain":"bitcoin","selectedTable":"blocks","selectedAggregationField":"count()_blocks","selectedAggregationFieldValue":{"count()_blocks":"count()"},"selectedFilterFields":[{"field":"time","table":"blocks","value":"time--blocks","unit":null,"qsac":{"q":"⌘","s":true,"a":"⌘","c":false}}],"selectedFilterFieldsOrder":["time"],"selectedFilterFieldsValues":{"time":"time(~P2W)"}}
globals={"selectedGlobalGroupField":"guessed_miner","selectedGlobalGroupTime":null,"selectedGlobalGroupTimeCustom":null,"selectedChartType":"pie"}

The response contains an empty string in a "message" field and a 404 error.

<img width="2556" alt="Screenshot 2022-04-04 at 09 33 50" src="https://user-images.githubusercontent.com/9268039/161495759-933cf5a6-3047-4e28-84c6-87d98a7c8b62.png">

**Comment by Har01d** [comment]
This has been fixed a while ago, thanks.
