### ISSUE TITLE
scam

### ISSUE THREAD

**Issue by shirmel40** [Blockchair/Blockchair.Support#841]
i need my money back

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by JohnnyMatos** [comment]
Hi my name is Jhonny this was my last transaction there was where they scammed me, 

this was my last transaction

687261d22025adf25d9288ac6b6fcfd97890c30b16b8104bb346f9d377e0eb04  

I need your help pleace

**Comment by shirmel40** [comment]
y is this sent to me

**Comment by JohnnyMatos** [comment]
What should I do to get your answer?

**Comment by JohnnyMatos** [comment]
I was scammed and I wanted to know if I can get my money back I need to
know please I will leave you the transfer number and the wallet to which I
made the transfer.

Wallet: bc1q9tga977qyvmdlaxhf3t06clnmg59t6p0sq5gct

Transfer number:
d4b78544657e46e2448e11421aeb2857b2c31f3ae036b55458f5eae9b7180e9d

What should I do to get your answer?
