### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by lesibalebel** [Blockchair/Blockchair.Support#842]
Hi can i plz reverse  the bitcoin i sent 1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY i made a mistake plz plz i cnt c my wallet i dnt undastand how to trade i thot this was like luno plz help

**Comment by normagene36** [comment]
d4ed2292b4db530129e3341d48502d2b4d91e073f87a0a66513cdb4199b7a055

**Comment by normagene36** [comment]
Crypto

**Comment by lesibalebel** [comment]
I dnt understand plz help

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains.
 
Thank you for understanding.
