### ISSUE TITLE
Dogecoini cüzdan adresini yaZmadan çekim yaptm 

### ISSUE THREAD

**Issue by avdoyla** [Blockchair/Blockchair.Support#843]
Acil acil
 Yardımcı olabilecek kimse varmı????

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
