### ISSUE TITLE
Blockchar

### ISSUE THREAD

**Issue by pangsirirat422** [Blockchair/Blockchair.Support#844]

**Comment by normagene36** [comment]
00cd3b4cfdc7c61060e13ddbf2685c24a666beeb38950d9968f8346a9b46562e  gh_2.5.0_linux_armv6.deb
0d0b9360536628ba9b4a1fd6bb12632d3900466fbc701884cc0ea15be12f03f8  gh_2.5.0_linux_arm64.deb
21259205f06c86c4d49cce957c44ddaf5f7d9a4f1553421feedfc672dbd4c1d7  gh_2.5.0_windows_amd64.zip
30acc72047b0172daccbed494c1f95f235a1ff694f516a227028c42283c917da  gh_2.5.0_linux_amd64.deb
34731614d5304549241b0f5966e087dfdee2945a8d4be4af5389a60d85108f1c  gh_2.5.0_linux_386.tar.gz
3d0ec2d5566ef805c2eb63ba6cb5e5be56648509b3fb11f188256cbbde897278  gh_2.5.0_linux_armv6.rpm
4390bc476cc79c33346be3e0098cfbb3afe2257006fcd38765ef83569df11a0f  gh_2.5.0_linux_amd64.tar.gz
44e44829a5361957217bfd7c2c8c6dc88fc5f56a72f2e4df772e0ea551a493bd  gh_2.5.0_linux_armv6.tar.gz
45cf80192438846315014494346d534a881baebcb85822dacf6da7d73cc866a3  gh_2.5.0_linux_arm64.tar.gz
54d0a049de817236611e9f3652ecf0b2341fe0024671dd50359aea0f3acbb686  gh_2.5.0_macOS_amd64.tar.gz
84521202fc9589e007a30c43f9b318b484b85be15edaad979d7872f0f761efa1  gh_2.5.0_linux_386.deb
9568ac5576d65281b4d2422a2baeddbb19671d16c823183d527ce7452cf5880e  gh_2.5.0_linux_amd64.rpm
ce6955f494a47f37d1ef6fc8e636cd727a083cc1f88fb136812c2fec5c2d8dd9  gh_2.5.0_linux_arm64.rpm
df4d9097fdafe235952fa7f01a91e9dbc7d408d72eea4497cdc1ada8989b9247  gh_2.5.0_windows_386.zip
e4c978e67da4c969a6071f4ce8ddad3d0a272093e239fbe9ea1ba7dbea6ae977  gh_2.5.0_linux_386.rpm

**Comment by pangsirirat422** [comment]
> 00cd3b4cfdc7c61060e13ddbf2685c24a666beeb38950d9968f8346a9b46562e gh_2.5.0_linux_armv6.deb 0d0b9360536628ba9b4a1fd6bb12632d3900466fbc701884cc0ea15be12f03f8 gh_2.5.0_linux_arm64.deb 21259205f06c86c4d49cce957c44ddaf5f7d9a4f1553421feedfc672dbd4c1d7 gh_2.5.0_windows_amd64.zip 30acc72047b0172daccbed494c1f95f235a1ff694f516a227028c42283c917da gh_2.5.0_linux_amd64.deb 34731614d5304549241b0f5966e087dfdee2945a8d4be4af5389a60d85108f1c gh_2.5.0_linux_386.tar.gz 3d0ec2d5566ef805c2eb63ba6cb5e5be56648509b3fb11f188256cbbde897278 gh_2.5.0_linux_armv6.rpm 4390bc476cc79c33346be3e0098cfbb3afe2257006fcd38765ef83569df11a0f gh_2.5.0_linux_amd64.tar.gz 44e44829a5361957217bfd7c2c8c6dc88fc5f56a72f2e4df772e0ea551a493bd gh_2.5.0_linux_armv6.tar.gz 45cf80192438846315014494346d534a881baebcb85822dacf6da7d73cc866a3 gh_2.5.0_linux_arm64.tar.gz 54d0a049de817236611e9f3652ecf0b2341fe0024671dd50359aea0f3acbb686 gh_2.5.0_macOS_amd64.tar.gz 84521202fc9589e007a30c43f9b318b484b85be15edaad979d7872f0f761efa1 gh_2.5.0_linux_386.deb 9568ac5576d65281b4d2422a2baeddbb19671d16c823183d527ce7452cf5880e gh_2.5.0_linux_amd64.rpm ce6955f494a47f37d1ef6fc8e636cd727a083cc1f88fb136812c2fec5c2d8dd9 gh_2.5.0_linux_arm64.rpm df4d9097fdafe235952fa7f01a91e9dbc7d408d72eea4497cdc1ada8989b9247 gh_2.5.0_windows_386.zip e4c978e67da4c969a6071f4ce8ddad3d0a272093e239fbe9ea1ba7dbea6ae977 gh_2.5.0_linux_386.rpm

**Comment by pangsirirat422** [comment]
> > 00cd3b4cfdc7c61060e13ddbf2685c24a666beeb38950d9968f8346a9b46562e gh_2.5.0_linux_armv6.deb 0d0b9360536628ba9b4a1fd6bb12632d3900466fbc701884cc0ea15be12f03f8 gh_2.5.0_linux_arm64.deb 21259205f06c86c4d49cce957c44ddaf5f7d9a4f1553421feedfc672dbd4c1d7 gh_2.5.0_windows_amd64.zip 30acc72047b0172daccbed494c1f95f235a1ff694f516a227028c42283c917da gh_2.5.0_linux_amd64.deb 34731614d5304549241b0f5966e087dfdee2945a8d4be4af5389a60d85108f1c gh_2.5.0_linux_386.tar.gz 3d0ec2d5566ef805c2eb63ba6cb5e5be56648509b3fb11f188256cbbde897278 gh_2.5.0_linux_armv6.rpm 4390bc476cc79c33346be3e0098cfbb3afe2257006fcd38765ef83569df11a0f gh_2.5.0_linux_amd64.tar.gz 44e44829a5361957217bfd7c2c8c6dc88fc5f56a72f2e4df772e0ea551a493bd gh_2.5.0_linux_armv6.tar.gz 45cf80192438846315014494346d534a881baebcb85822dacf6da7d73cc866a3 gh_2.5.0_linux_arm64.tar.gz 54d0a049de817236611e9f3652ecf0b2341fe0024671dd50359aea0f3acbb686 gh_2.5.0_macOS_amd64.tar.gz 84521202fc9589e007a30c43f9b318b484b85be15edaad979d7872f0f761efa1 gh_2.5.0_linux_386.deb 9568ac5576d65281b4d2422a2baeddbb19671d16c823183d527ce7452cf5880e gh_2.5.0_linux_amd64.rpm ce6955f494a47f37d1ef6fc8e636cd727a083cc1f88fb136812c2fec5c2d8dd9 gh_2.5.0_linux_arm64.rpm df4d9097fdafe235952fa7f01a91e9dbc7d408d72eea4497cdc1ada8989b9247 gh_2.5.0_windows_386.zip e4c978e67da4c969a6071f4ce8ddad3d0a272093e239fbe9ea1ba7dbea6ae977 gh_2.5.0_linux_386.rpm
