### ISSUE TITLE
Weird priority fraction

### ISSUE THREAD

**Issue by DesWurstes** [Blockchair/Blockchair.Support#85]
Was this intended:

![screen shot 2018-01-07 at 13 27 59](https://user-images.githubusercontent.com/23437045/34648660-ba254c70-f3ae-11e7-9d8c-656ed2441154.png)
https://blockchair.com/bitcoin/transaction/3857e01084275a0259efee900b30ecd985a81b7e8a30ed53a5853ff9a73d670e

**Comment by Har01d** [comment]
Fixed, thanks for the report!
