### ISSUE TITLE
BITCOIN REFUND OR STATUS

### ISSUE THREAD

**Issue by JJOpwanda** [Blockchair/Blockchair.Support#850]
I was making bitcoin payments to NovatechFx for 500$ on the 14th of this month. I used my Novatech account to generate an invoice whose payment ID was CPGD4LCMRP60UFL3X6DRKB2RL8 for  0.01220000 BTC to be sent to the address 3EecJYQ7zTvtvV8nC2Ht1sW4P3ucWaKFLz. I however sent 0.01016272 BTC instead, the transaction ID of which is 969f804ce964bd13d9a8ae44d82b1eaacc6afe379aaa1e194aefcb1b39433f56. I never received confirmation for this less than the required payment. I was never advised to pay the additional funds and after time out I was never advised to get a refund. NovatechFx has advised me that coinpayments should have sent me an email informing me that my payment was less. The wallet I used to send the funds i.e [http://localbitcoins.com] has confirmed to me that the funds arrived at the recipient's address mentioned above. From blockchain explorer, the funds were confirmed and are marked as unspent.   kindly, advise me on how to proceed with seeking a refund of the same in order to make another order.

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. For more information please contact the service to which you've sent your funds.
 
Thank you for understanding.
