### ISSUE TITLE
API response is incorrect.

### ISSUE THREAD

**Issue by morihisasagawa** [Blockchair/Blockchair.Support#851]
Balance is different between explorer and API.

This is explorer.
https://blockchair.com/bitcoin-cash/address/qr5c447dm9v2pq3d9zxvs33g5vuytsd54uxm2qdh25

This is API.
https://explorer.api.bitcoin.com/bch/v1/addr/qr5c447dm9v2pq3d9zxvs33g5vuytsd54uxm2qdh25
{
	"addrStr": "qr5c447dm9v2pq3d9zxvs33g5vuytsd54uxm2qdh25",
	"balance": 38225.99669876,
	"balanceSat": 3822599669876,
	"totalReceived": 75391.5294768,
	"totalReceivedSat": 7539152947680,
	"totalSent": 37165.53277804,
	"totalSentSat": 3716553277804,
	"unconfirmedBalance": 0,
	"unconfirmedBalanceSat": 0,
	"unconfirmedTxApperances": 0,
	"txApperances": 26,
	"transactions": [
		"15a5582a9e704d1bcf1a07a91c1a71634e3cdb32629615ea2429f4cb6db43266",
		"c9c00a986c78f01c364ced51b6cf9f0ca502ebb0a6ee242fcd15899a8e4056f5",
		"c9c00a986c78f01c364ced51b6cf9f0ca502ebb0a6ee242fcd15899a8e4056f5",
		"c9c00a986c78f01c364ced51b6cf9f0ca502ebb0a6ee242fcd15899a8e4056f5",
		"3c62448b16a853b6ce61cdf2f4546ef7ef13d97b5bddd1a3cd69e7cde25c2a8a",
		"3c62448b16a853b6ce61cdf2f4546ef7ef13d97b5bddd1a3cd69e7cde25c2a8a",
		"3c62448b16a853b6ce61cdf2f4546ef7ef13d97b5bddd1a3cd69e7cde25c2a8a",
		"3c62448b16a853b6ce61cdf2f4546ef7ef13d97b5bddd1a3cd69e7cde25c2a8a",
		"a3fe88b8cf240aad95674e7860136b5dd2c73aea70b698bb1d8f4b9c204115c2",
		"a3fe88b8cf240aad95674e7860136b5dd2c73aea70b698bb1d8f4b9c204115c2",
		"a3fe88b8cf240aad95674e7860136b5dd2c73aea70b698bb1d8f4b9c204115c2",
		"a3fe88b8cf240aad95674e7860136b5dd2c73aea70b698bb1d8f4b9c204115c2"
	]
}

There are duplicate transactions in the API.

qqkw0rkrpntl95lfpvhm7r58run0lmc3ru5c5f6rle is in the same state.

**Comment by Har01d** [comment]
`api.bitcoin.com` is not a part of Blockchair, please contact the corresponding support.
