### ISSUE TITLE
Sent lite coin to the wrong address 

### ISSUE THREAD

**Issue by Jhed666** [Blockchair/Blockchair.Support#853]
Need help I sent LTC to wrong address but the address shows up as red in my transactions but it’s confirmed is there anyway to get it back

**Comment by Jareesh355** [comment]
Hello can you help me

**Comment by daria-blockchair** [comment]
Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains.
