### ISSUE TITLE
Blockchair Support Site

### ISSUE THREAD

**Issue by moradutf** [Blockchair/Blockchair.Support#858]

**Comment by mslisemc** [comment]
- i gad money stolen twice off of wirex in 24 hours**

**Comment by mslisemc** [comment]
right off of my account

**Comment by Jareesh355** [comment]
I can’t get the bitcoins from the block chair . please help me j don’t know what to do

**Comment by mslisemc** [comment]
someone has stolen mine and i cant get mine or stop them from using my wallet and continuing making money off of my deposit
-

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information and to discuss the security of your account.
 
Thank you for understanding.
