### ISSUE TITLE
account create

### ISSUE THREAD

**Issue by popmem** [Blockchair/Blockchair.Support#86]
while signing as new user on first attempt my username was rejected as being used. 2nd username was accepted. email verification came seconds later addressing me by the 1st (taken) user name. let me log in as the username that had been identified as taken.

**Comment by Har01d** [comment]
Hello,

Are you sure you are using Blockchair.com? Currently there’s no ability to open an account on our platform.

**Comment by popmem** [comment]
Yes from the black chair / about page I selected issues and requests. He
referred me to a sign-up page not create account. I did this because I have
a transfer that did not go through when transferring Bitcoin cash to my
Bitcoin account I have since been sent over to fax sheet that I either
don't understand or having a problem with my pass phrases. It was just
signing up not creating an account is where the problem occurred

**Comment by Har01d** [comment]
You can’t directly transfer Bitcoin Cash to Bitcoin without using an exchange. Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md 
Blockchair is neither a wallet, nor an exchange, so there’s nothing we can help with.
