### ISSUE TITLE
Wrong Blockchain Address

### ISSUE THREAD

**Issue by Thaboss1522** [Blockchair/Blockchair.Support#872]
I need to track my BTc I sent to an address on this site to get it back. I don't know what to do exactly. Please help?

**Comment by Jareesh355** [comment]
> I need to track my BTc I sent to an address on this site to get it back. I don't know what to do exactly. Please help?

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q4) contact your wallet or exchange for more information.
 
Thank you for understanding.
