### ISSUE TITLE
pending transaction

### ISSUE THREAD

**Issue by 09122019** [Blockchair/Blockchair.Support#877]
my transaction of bch transaction id is aa756173412f0365c8651eda35cb5314043f3fb0093df44e02305de307f93ce7 and transaction address is https://blockchair.com/bitcoin-cash/address/qpfzxjfhurdxzdds2v99pr8gnzwtu26c7yhx736yyv 
want to track it i have not recived payment yet

**Comment by westbrookcrook** [comment]
My transaction is also stuck please help hash: d1509ebde097bc663c31f2e9fc975317f5f48301da52050c61519ec6ec900e4d

Transaction address: https://blockchair.com/bitcoin-cash/transaction/d1509ebde097bc663c31f2e9fc975317f5f48301da52050c61519ec6ec900e4d?from=crypto.com

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.
 
Thank you for understanding.
