### ISSUE TITLE
wrong wallet address n still no receive wallet in blockchain

### ISSUE THREAD

**Issue by firmANfire** [Blockchair/Blockchair.Support#88]
please help me admin...my bch wrong addres...what can i do to resolve my problem...to give me back my bch...tx succes but in blockchain still no receive becouse that is wrong wallet address

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

**Comment by firmANfire** [comment]
can you explain how to get admin bch blockchain ??because that fund still unconfirmation since 4 month ago??


________________________________

**Comment by Har01d** [comment]
Unfortunately, we do not have enough support resources to resolve such cases. You can try to ask for help on our Telegram chat (https://telegram.me/Blockchair) or on any public Bitcoin forum.

**Comment by firmANfire** [comment]
ok thanks for help


________________________________
