### ISSUE TITLE
This functionality available with JavaScript enabled only

### ISSUE THREAD

**Issue by gannesh1996** [Blockchair/Blockchair.Support#881]
I want to search for some transactions based on filters, so I go to blockchair.com/bitcoin/transactions as usual.  Ever since a month or so, I get the error 'This functionality available with JavaScript enabled only', while JavaScript is running as normal and updated to the latest version.

![image](https://user-images.githubusercontent.com/16748886/169630762-c7235881-3603-4e0d-9741-04823ffc2f77.png)

**Comment by daria-blockchair** [comment]
Hi! You are on a No JS version of the site. Please go to the website settings and unclick the "Turn off JavaScript" option
![JS:NoJS](https://user-images.githubusercontent.com/80337128/170248653-fb50adb1-c171-4342-b009-6fe3db9da966.png)
