### ISSUE TITLE
Не приходят битки через микшер 1BGfZwXs8Bny23jg5z3SWtGNQHsQUkuRLX

### ISSUE THREAD

**Issue by LichKing1111** [Blockchair/Blockchair.Support#886]
Не приходят битки уже третий день, хотя транзакция прошла успешно вот хэш
febac77a6a05c3c9d443f28fd6c30752a50625c2c67e7a6ba3e506ce3b7bfb8a

**Comment by daria-blockchair** [comment]
Hi, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. Please contact your wallet or exchange for more information.
Thank you for understanding.
