### ISSUE TITLE
Dash explorer doesn't work in german language when coming via coinwallet

### ISSUE THREAD

**Issue by spl1zzer** [Blockchair/Blockchair.Support#899]
Gives no error:
`https://blockchair.com/de/dash/transaction/e4fb92b5f2dd4dabfb0d1bcb8f7e80ce2b5a59cb7c0483271af83ea17e6ea706`

Gives no error:
`https:// blockchair.com/dash/transaction/e4fb92b5f2dd4dabfb0d1bcb8f7e80ce2b5a59cb7c0483271af83ea17e6ea706?from=coinwallet`

### Gives an error:
`https://blockchair.com/de/dash/transaction/e4fb92b5f2dd4dabfb0d1bcb8f7e80ce2b5a59cb7c0483271af83ea17e6ea706?from=coinwallet`

**Comment by daria-blockchair** [comment]
Hi @spl1zzer! 
It's working fine on my side. Could you please specify a browser from which it doesn't work?
<img width="1102" alt="Dash_DE" src="https://user-images.githubusercontent.com/80337128/174592951-4b49f305-0911-4357-ac1c-0942d4c177e8.png">

**Comment by Har01d** [comment]
We haven't been able to confirm any issue. Please reopen with details if it persists for you.
