### ISSUE TITLE
API query limit parameter

### ISSUE THREAD

**Issue by iYalovoy** [Blockchair/Blockchair.Support#90]
Cool project!
Is there any way to set limit api query size? By default it is 10. Can't find where it can be changed?

**Comment by iYalovoy** [comment]
Seems it always returns first 10 results only? Any ways around it?

**Comment by Har01d** [comment]
Hello,

Please refer to the API documentation here: https://github.com/Blockchair/Blockchair.Support/blob/master/API.md

You can either use JSON pagination or export data in CSV/TSV.
