### ISSUE TITLE
error login with github student pack

### ISSUE THREAD

**Issue by warifp** [Blockchair/Blockchair.Support#906]
response:

<code>[{"data":null,"context":{"code":400,"error":"No one-time password specified. Please contact us at info@blockchair.com.","cache":{"live":true,"duration":120,"since":"2022-06-07 00:35:19","until":"2022-06-07 00:37:19","time":null},"api":{"version":"2.0.95-ie","last_major_update":"2021-07-19 00:00:00","next_major_update":null,"documentation":"https:\/\/blockchair.com\/api\/docs","notice":":)"},"servers":"API4","time":null,"render_time":0.0034470558166503906,"full_time":0.0034470558166503906,"request_cost":1}}]<code>

**Comment by Har01d** [comment]
This has been fixed several days ago, please try to activate your key once again.

**Comment by warifp** [comment]
Still error
