### ISSUE TITLE
#203711 Sent Bitcoin Cash 12/29/2017 12:43 AM

### ISSUE THREAD

**Issue by AJ3TM** [Blockchair/Blockchair.Support#91]
Hi,

Can someone please help me recover my funds sent to this address wallet?

Wallet address:
3FLvhPSTcnpujNBFZkKHVswK44UCrXqLMW

#203711 Sent Bitcoin Cash 12/29/2017 12:43 AM 

Thanks,

**Comment by AJ3TM** [comment]
Hello,

any updates on my ticket?

Thanks

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
