### ISSUE TITLE
Can't copy to clipboard transaction hash

### ISSUE THREAD

**Issue by nikashitsa** [Blockchair/Blockchair.Support#912]
I noticed that I can't copy to clipboard transaction hash (e.g. https://blockchair.com/cardano/transaction/2cbe24fb96db3dfc6fe4111c9d2477755d0b5dd466cc6e098a8d70b400753404)
Tried on iPhone (Safari), Android (Chrome) and macOS Chrome with opened Chrome Console.
It works sometimes on iPhone, but not always as it should be. On Android it doesn't work at all for me.

![Screenshot 2022-06-16 at 14 05 50](https://user-images.githubusercontent.com/1029908/174066150-1aa53ce7-e8ff-4832-b839-0600e005dbb3.png)

Please have a look 😊

**Comment by nikashitsa** [comment]
Check clickable zone.

**Comment by Har01d** [comment]
This has been fixed, thank you! We didn't test this properly for Android.
