### ISSUE TITLE
Проблема с зачисление. 

### ISSUE THREAD

**Issue by Rusiyoo12** [Blockchair/Blockchair.Support#913]
Добрый день проблемы с зачисление. На кошелёк который отправлял не поступили деньги. Блок 740 013

**Comment by Black13666** [comment]
Мне тоже не приходят

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
