### ISSUE TITLE
Big BUG : network fee change

### ISSUE THREAD

**Issue by nonomaxxis** [Blockchair/Blockchair.Support#916]
Hi, 
why network fee change after transfer confirm?

![photo_2022-06-27_14-33-45](https://user-images.githubusercontent.com/6130447/175928387-34f7de68-e9c1-4335-8eee-b878a2385a21.jpg)
![photo_2022-06-27_14-33-51](https://user-images.githubusercontent.com/6130447/175928397-a5f37b33-ebeb-4ad9-89db-144060f55097.jpg)

**Comment by abooozarfox** [comment]
![Uploading Screenshot_۲۰۲۲۰۶۲۸-۰۲۰۰۳۵_Trust Wallet.jpg…]()

**Comment by Har01d** [comment]
This is not connected to Blockchair, please contact your wallet support team.
