### ISSUE TITLE
Bitcoin Cash average block size chart has broken link

### ISSUE THREAD

**Issue by neldredge** [Blockchair/Blockchair.Support#917]
At https://blockchair.com/bitcoin-cash/charts, the "Average block size (MB)" link goes to https://blockchair.com/bitcoin-cash/charts/average-blocks-size which is 404.  However https://blockchair.com/bitcoin-cash/charts/average-block-size (with "block" instead of "blocks") works.

Other currencies don't seem affected, e.g. for Bitcoin the link goes to https://blockchair.com/bitcoin/charts/average-block-size (no s) which works.

In general, there seem to be some inconsistencies in the URL naming scheme between currencies.  For instance, for Bitcoin, the median block size link is https://blockchair.com/bitcoin/charts/median-block-size (no s), but for Bitcoin Cash it is https://blockchair.com/bitcoin-cash/charts/median-blocks-size (with an s).  So maybe you will want to check for such issues more broadly.

**Comment by Har01d** [comment]
This has been fixed, thanks! `https://blockchair.com/bitcoin-cash/charts/average-block-size` now works.
