### ISSUE TITLE
Transaction not yet confirm

### ISSUE THREAD

**Issue by pdkhuong** [Blockchair/Blockchair.Support#93]
Hi there,
My transaction begin from 2017-12-20 17:03 (a month ago). But it still not yet confirm

https://blockchair.com/bitcoin-cash/transaction/0d8df0aeb489049c27278411cfcad920e92e423366be9a52fc4a57b53cdca36f

**Comment by Har01d** [comment]
Hello,

Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

The transaction is confirmed on the blockchain.

**Comment by pdkhuong** [comment]
Thanks for your replied!
