### ISSUE TITLE
API request blacklist .. on web query is impossible. .... bug or misc lolz 

### ISSUE THREAD

**Issue by mikejnpc** [Blockchair/Blockchair.Support#934]
So unless you count web queries and a few per hour, ...i clicked on api .. on the wallet data to the left ... 
its a bug... or someone internally think its funny... from the notice msg there.... :)    
ill take a API account as opposed to the  21479 you requested from me .... for my 30 clicks today.  
nice bug wonder if you make money doing that fellas.,.... so glitch bug or *wink* 

if you deem it applicable... cheers 

context	
code	430
error	"Your IP address is temporary blacklisted due to exceeding usage of API resources. Please apply for an API key by contacting us at info@blockchair.com"
market_price_usd	21479
cache	
live	true
duration	60
since	"2022-07-09 12:33:54"
until	"2022-07-09 12:34:54"
time	null
api	
version	"2.0.95-ie"
last_major_update	"2021-07-19 00:00:00"
next_major_update	null
documentation	"https://blockchair.com/api/docs"
notice	":)"
servers	"API4"
time	null
render_time	0.0012850761413574219
full_time	0.0012850761413574219
request_cost	1

**Comment by Har01d** [comment]
If you want to avoid getting "too many requests" type errors, please purchase an API plan.

**Comment by mikejnpc** [comment]
Well simply using the site and clicking on api should not blacklist my up
and ask for 26k... or did you miss that point?
