### ISSUE TITLE
38Dfa5ZYqt1inHLp4XGRCLKdSYazFAdTN7

### ISSUE THREAD

**Issue by 3b33c678-3838-40ad-be84-7c576e3b5813** [Blockchair/Blockchair.Support#94]
warum ist meine geld blockirt

**Comment by Har01d** [comment]
Hello,

Unfortunately, we don’t provide support in German.

**Comment by 3b33c678-3838-40ad-be84-7c576e3b5813** [comment]
Hello

why is my money blocked?


Von meinem iPhone gesendet

Am 24.01.2018 um 00:13 schrieb Nikita Zhavoronkov <notifications@github.com<mailto:notifications@github.com>>:


Hello,

Unfortunately, we don’t provide support in German.

**Comment by Har01d** [comment]
Please refer to our FAQ regarding this issue: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md

**Comment by 3b33c678-3838-40ad-be84-7c576e3b5813** [comment]
Können sie mir sagen wo meine geld ist ich verstehe nicht ehrlich das ist nicht korrekt meine geld blockieren und meine Konto ist jetzt Lehr

Outlook für iOS<https://aka.ms/o0ukef> beziehen
________________________________

**Comment by PrinceKK300188-zz** [comment]
Hahaha
