### ISSUE TITLE
Необработанная транзакция 

### ISSUE THREAD

**Issue by Azamat1975** [Blockchair/Blockchair.Support#947]
Всем добрый день. Я новичок.  У меня Необработанная транзакция в сети лайткоина. Можно ли как то решить вопрос, или надо ждать когда само по себе решится?

**Comment by daria-blockchair** [comment]
Hi! Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information. 
Blockchair does not process transactions and we do not store your funds. 
Thank you for understanding.
