### ISSUE TITLE
FRAUD REPORT

### ISSUE THREAD

**Issue by Cj1377** [Blockchair/Blockchair.Support#949]
https://blockchair.com/bitcoin/address/1L3q356E9j5RMc5QiiK4kc3HjXq9dLYNie

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
