### ISSUE TITLE
Нет Поступлений на счёт

### ISSUE THREAD

**Issue by HopeAngels** [Blockchair/Blockchair.Support#954]
Во первых ждал подтверждения обменника на протяжении полутора часов, так к тому же зачислений на счет так и не было

**Comment by Nodiwiwgwb** [comment]
И у меня тоже самое я только жду уже 1 неделю

**Comment by Belovensti** [comment]
При обмене статус «посланный» денег нет с 5 августа. Транзакции были 5 и 7го

**Comment by Belovensti** [comment]
![15F7C257-B7E3-4EF4-8BF0-33E12FFC5BE0](https://user-images.githubusercontent.com/111205811/184530982-e1f4ab69-748f-4652-8a9e-23587d35523f.png)

**Comment by Belovensti** [comment]
Денег на кошельке нет

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
