### ISSUE TITLE
Code 500 - Error: addresses table is being repopulated

### ISSUE THREAD

**Issue by highree** [Blockchair/Blockchair.Support#956]
Hi I see this error since couple of days when calling (demo link): 

https://api.blockchair.com/bitcoin/addresses/balances?addresses=34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo,1DoesntExist

**Comment by DeanDonkov** [comment]
Any updates?

**Comment by DeanDonkov** [comment]
@daria-blockchair

**Comment by Vero7979** [comment]
20160201_status_updates_d2f

**Comment by Vero7979** [comment]
Thank you for all you do!
