### ISSUE TITLE
Easily search coinbase_data on selection of part of the string

### ISSUE THREAD

**Issue by erikhuisman** [Blockchair/Blockchair.Support#96]
By providing a small context menu when selecting a part of the coinbase so users can easily search for blocks from the same (unidentified) miner. 

For example: 
https://blockchair.com/bitcoin-cash/block/514209
When selecting "coingeek" in the coinbase yield a small search button near the selection directing to:  
https://blockchair.com/bitcoin-cash/blocks?q=coinbase_data(~coingeek)

Like this implementation: 
http://idorecall.github.io/selection-menu/

**Comment by Har01d** [comment]
Hello,

Nice idea, thanks! We’ll see if we can implement that. Right now you can just copy-paste the selected text into the universal search box in the header of any page.
