### ISSUE TITLE
Cara melihat dompet litecoin

### ISSUE THREAD

**Issue by Yuliana90** [Blockchair/Blockchair.Support#960]
Saya mengirim litecoin,dan tidak tau cara melihat dompet litecoin saya. Apakah litecoin saya dapat dipindahkan ? 
![Screenshot_2022-08-16-14-36-52-01](https://user-images.githubusercontent.com/111341559/184824256-2b50efad-818b-458b-8dd1-77f713f60f63.png)

Mohon bantuannya dan email ke yuliana199088@yahoo.com

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
