### ISSUE TITLE
Заблокировали заявку на перевод 

### ISSUE THREAD

**Issue by Bikini39** [Blockchair/Blockchair.Support#964]
35cpdxTezBwu1Fkpr2uHpvg1ssoWexs85b
Транзакция 
Перевода так и не было заявка в блоке

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q3) and contact your wallet or exchange for more information.
 
Thank you for understanding.
