### ISSUE TITLE
Как отменить транзакцию?

### ISSUE THREAD

**Issue by Avalasslava** [Blockchair/Blockchair.Support#965]
Как отменить транзакцию?

**Comment by daria-blockchair** [comment]
Hi, 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services.

Thank you for understanding.
