### ISSUE TITLE
NEED HELP ABOUT THIS FRUSTRACTING ISSUES

### ISSUE THREAD

**Issue by zozoman2000** [Blockchair/Blockchair.Support#966]
Hi. For a few months I have only been losing money and apparently Crypto.com and Defi wallet can't do anything because the problems are not on their platform!!! But what they forget I am one of their customers who loses money by making transactions and does not know exactly where his pennies go. I listed some transactions that I submitted to them. After investigation, they said that the sums of money are on Blockchair account so, to get in touch with Blockchair. Also, when I follow the link they gave me, I see that my money is on your Blockchair site and all transactions have the same transaction key at the reception! I wonder what is really going on with your site which is introduced into my transactions which do has nothing to do with you. I only do my transactions from my Bank to my Crypto or Defi wallet account, so why is my money ending up with you??? I need my money ASAP! Could you please help me find it?
thank you.
Charles Kassalo.

**Comment by inmortalbobz** [comment]
OK, advice from me keep your wallet safe, I don't know exactly what you mean

**Comment by daria-blockchair** [comment]
Blockchair.com is a blockchain explorer which displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. 
Blockchair.com only provides blockchain search and analytics services, so there is nothing we can do to help you with your payments.

Blockchain is a public distributed database of which anyone can make a copy. Your cryptocurrency transactions and address balance are also stored in such a database. However, your money and assets are not stored on Blockchair.com.
At Blockchair.com we provide insight into data that is stored in blockchains. We offer ways to find, sort, and filter blockchain data, so you can easily check your address balance and transaction history. We do not provide wallet services and do not process transactions.

For more information and further assistance, please contact your crypto wallet.

Thank you for understanding.
