### ISSUE TITLE
On API.md add a brief description after each item

### ISSUE THREAD

**Issue by jidanni** [Blockchair/Blockchair.Support#97]
On API.md add a brief description after each item:
> https://api.blockchair.com/bitcoin/mempool/transactions?{query}

Mention: Shows this and that about ...
> https://api.blockchair.com/bitcoin/mempool/outputs?{query}

Mention: Shows some... about ...
>https://api.blockchair.com/bitcoin/dashboards/address/{address}

Mention: Shows all the $$ in the address, in US and native units.

**Comment by Har01d** [comment]
Yes, we’ll have a more detailed documentation, right now you can reverse-engineer the front-end (e.g. for `https://api.blockchair.com/bitcoin/mempool/transactions?{query}` that would be `https://blockchair.com/bitcoin/mempool/transactions?{query}` page

**Comment by Har01d** [comment]
Hello, we’ve finally published detailed documentation for our API: https://github.com/Blockchair/Blockchair.Support/blob/master/API.md
