### ISSUE TITLE
Scammed by a Crypto Scammer

### ISSUE THREAD

**Issue by tsnells2** [Blockchair/Blockchair.Support#978]
I was defrauded out of bitcoin by a crypto scammer. This person presented themselves as a forex day trader. Well they aren't. Please help. 

This is their wallet address: bc1q8vlglrc54wvv2cuuw98wq0a7kl3tcha72lj7rk

Here's the transaction hash#: 2f1b0a96c2518efa99b5a8d9aa3c923b0523feb2ce4e1e0e7d84d7452cd01e1f

Please help in getting my bitcoin back. 

My email is tsnells2@yahoo.com
Phone: 484-241-8634

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
