### ISSUE TITLE
Scammed 

### ISSUE THREAD

**Issue by Jekinson10** [Blockchair/Blockchair.Support#979]
I was been scammed right now...Someone send bitcoin to me and i didn't know how it left someone transferred it away from my Wallet...Can you help me get my bitcoin back please..🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
