### ISSUE TITLE
Document the output format

### ISSUE THREAD

**Issue by jidanni** [Blockchair/Blockchair.Support#98]
Document the output format,
```
         "pl_usd" : 0,
         "plu_usd" : -285.97254,
         "rate" : "1657.4",
```
etc.
pl, plu, etc.: New users can't guess the exact meanings. Also mention if those rates were then, or now.

**Comment by Har01d** [comment]
Currently the only way is to reverse-engineer `https://blockchair.com/bitcoin/address/{address}` page. `rate` is the current price of a coin, `pl_usd` and `plu_usd` is something unreliable we don’t currently use.

**Comment by Har01d** [comment]
Hello!

We’ve published the documentation for our new API, it is available here: https://github.com/Blockchair/Blockchair.Support/blob/master/API.md
