### ISSUE TITLE
Pagamento doge non arrivato 

### ISSUE THREAD

**Issue by Daiking70** [Blockchair/Blockchair.Support#980]
Ciao ho inviato 30 Doge Coin a un indirizzo che non sono mai arrivati ecco la transazione.

https://blockchair.com/it/dogecoin/transaction/1f0e1e465ccf582d64185a6e449fac8d90252160801e6afc1d2b3d5fa1b19a72

Come risolvo ?

**Comment by Daiking70** [comment]
Hash: SHA512

Ciao,

Il tuo pagamento di 30.00000000 DOGE a Wakedoge.io Dogecoin Cloud Mining è scaduto senza che noi ricevessimo i fondi richiesti. La transazione con ID CPGI7SOVDL8HZNX6FFPMUYASZD è stata annullata.

Se hai bisogno di aiuto o assistenza, non esitare a contattarci all'indirizzo https://www.coinpayments.net/help-support

CoinPayments.net

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.

Thank you for understanding.
