### ISSUE TITLE
Refund on transaction fraudulently made 

### ISSUE THREAD

**Issue by KakemboIsmail256** [Blockchair/Blockchair.Support#988]
e74e1798cfc5b7656b8559c5d7da7c82f1e6d68b43bf4d072a401a501fbd4e6d this hash and this hash 64263b83d9bbed446f37117519d4b2ae4c9887c7a8a7bf50f5de3942ef6e4271 need to be reversed to the sender address because they were made without my consent through chipper cash

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
