### ISSUE TITLE
Is there a way to push a raw transaction through the API?

### ISSUE THREAD

**Issue by festus1973** [Blockchair/Blockchair.Support#99]
Does the API provide a way to push a raw transaction (expressed as hex) to the Bitcoin network?

**Comment by Har01d** [comment]
Hello,

This is a popular request, so we have that in our pipeline. Thank you!

**Comment by festus1973** [comment]
Hi, just checking in to see if there's a way to push raw transactions to the Bitcoin network via the Blockchair API?

**Comment by Har01d** [comment]
We added an ability to broadcast raw transactions (for Bitcoin, Bitcoin Cash, Litecoin, and Ethereum) to our API a week ago, now we’re finishing testing this, should be available in production this or the next week.

**Comment by Har01d** [comment]
It’s finally here: https://github.com/Blockchair/Blockchair.Support/blob/master/API_DOCUMENTATION_EN.md#broadcasting-transactions
and not only for the Bitcoin network, but for all others we support (Bitcoin Cash, Ethereum, and Litecoin).

**Comment by festus1973** [comment]
Oh, that's great news! And I assume SegWit-style transactions are supported as well? I'm only asking because some other APIs (e.g. Insight) tend to choke on them. In any case, thanks for the update. I'm looking forward to running some transactions through the API.

**Comment by Har01d** [comment]
Yes, it should be possible to broadcast SegWit transactions. Please let us know if you run into any issues.
