### ISSUE TITLE
Where can one find the OrderId to test the buy function?

### ISSUE THREAD

**Issue by pcgandhinj466** [Blockchair/Blockchair.Support#990]
Where can one find the OrderId to test the buy function?

__Originally posted by @MakerGit22 in https://github.com/rarible/example/issues/10__

**Comment by mortalkhon** [comment]
With me

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet or exchange services, we do not process transactions, and we do not store your money. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
