### ISSUE TITLE
Can't figure which wallet my coins are

### ISSUE THREAD

**Issue by Wrathchyld** [Blockchair/Blockchair.Support#991]
b6e6a69262d67b55a95b4b364c34a635e6e1968a98429eb9002afe529e42a374

**Comment by daria-blockchair** [comment]
Dear @Wrathchyld,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. We also don't have the information about the platform on which the address was registered. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
